### ISSUE TITLE
patch submission code diff is incorrect right after submission, but correct after a page reload

### ISSUE THREAD

**Issue by gosnat** [codecombat/codecombat#1015]
When I submit a patch in the System tab (haven't check the Components tab yet), here's what I see:

I write some code:
![image](https://cloud.githubusercontent.com/assets/6819822/3000488/77ad28bc-dd24-11e3-9c33-64dfe74042b2.png)

I get ready to submit a patch, and everything looks good in the diff:
![image](https://cloud.githubusercontent.com/assets/6819822/3000494/8bc3d544-dd24-11e3-8f5a-bb83c0a50dca.png)

After I submit the patch, I click on any other system, and then back to the one I just submitted a patch for (without actually reloading the page).  I see my patch waiting for approval, but when I check the diff I see that random pieces have been duplicated:
![image](https://cloud.githubusercontent.com/assets/6819822/3000497/b2a83074-dd24-11e3-8d85-42ceb6cf9e9c.png)

I reload the page, and now the diff looks correct
![image](https://cloud.githubusercontent.com/assets/6819822/3000508/df472a40-dd24-11e3-9026-343e70bae41b.png)

I don't have a screenshot of it, but for the submission that made me notice this, the bad diff showed really garbled code that wasn't even syntactically correct.

**Comment by sderickson** [comment]
Can no longer reproduce. Closing unless it shows up again.
