### ISSUE TITLE
Clojurescript support for Greed

### ISSUE THREAD

**Issue by MaikKlein** [codecombat/codecombat#1053]
How can I use Clojure in Greed? 

I changed the current editor to Clojure but how do I access "this"? The "this-as" macro doesn't parse and I can't define it myself.

Could you translate me the following js code snippet to Clojure as an example?
```
if (base.built.length === 0)
    base.build('peasant');
```

**Comment by nwinter** [comment]
Had to disable Clojure with the new interpreter for now.
