### ISSUE TITLE
Proposal: Standardized db errors

### ISSUE THREAD

**Issue by rubenvereecken** [codecombat/codecombat#1066]
Depending on whether you have a user cookie going on at CodeCombat, GETting http://codecombat.com/db/article will net you a 401 "Must have an identity to do anything with the db. Do you have cookies enabled?" or a 403 "Forbidden". This suffices for testing purposes and a machine might know enough knowing it's a 401 or 403, but that's all it can know.

I'd like to propose returning JSON error objects instead. Right now no code relies on the actual response messages in case of error so it can be done gradually, but there'd need to be a standard.

The usual way to approach this is to have an optional 'error' property in the JSON response body but the downside is that for homogeneity this would require all response bodies to have the actual data as a property, instead of being the actual data, as follows:

```
{
  error: {
    message: "No database identity.",
    type: "auth" // Introduce types, codes, whatever
  }
}
```

The nice part is we can work slowly work towards this without changing any existing success response bodies. So nothing relies on whatever we'd change. 

This would, however, call for some careful but small standard to be established, because as soon as some calls start to rely on this changes would become quite expensive.

Some existing APIs:
- Facebook Graph API - Response body has 'error' property ([example](http://graph.facebook.com/someguy))
- GitHub API v3 - Response body is actual error message, so response doesn't have an error property ([example](https://api.github.com/orgs/codecombat/dude))
- Twitter API 1.1 - Response body has 'errors' property ([example](https://api.twitter.com/1.1/statuses/mentions_timeline.json))
- LinkedIn API (XML body but same structure) - Root is 'error' ([example](http://api.linkedin.com/v1/people-search?keywords=Hacker))

**Comment by sderickson** [comment]
This has been done. Not all endpoints return these objects, but any new or refactored ones do.
