### ISSUE TITLE
"You rock!" screen comes up when you lose

### ISSUE THREAD

**Issue by stuartpb** [codecombat/codecombat#1133]
I'm trying to refine my Humans Gold Rush code against my own Ogres code (since it's currently ranked \#6), and at the end of the simulation (when Ogres win), the "You Win!" screen popped up. At first, I thought this was because, as I wrote the Ogres code, "I" did actually win.

However, I also see it when watching replays of games against other users where I lost, so I'm not sure what's happening.

**Comment by nwinter** [comment]
I'm going to go ahead and close this, since it's only an issue for old-style ladder levels, and I don't want to mess around in the script state restoration bug stuff for those.
