### ISSUE TITLE
Install mockgoose for server tests

### ISSUE THREAD

**Issue by sderickson** [codecombat/codecombat#1144]
Right now to run the tests, you need the local mongodb running. We should instead use mockgoose, which wraps around mongoose and makes it so you don't need to have a separate mongodb instance running. However, presumably this wouldn't work right out of the box because the test runner and the test server are different processes which won't share mockgoose's data. So all the suites which depend on both calling test runner models directly and server endpoints remotely need to be reworked, probably by adding an endpoint to the server to clear mockgoose. There may be other things to fix. Also, the travis config would need to have its mongodb related commands removed.

**Comment by nwinter** [comment]
We gave up on Mockgoose.
