### ISSUE TITLE
Integrate with Mozilla OpenBadges

### ISSUE THREAD

**Issue by bkimminich** [codecombat/codecombat#1175]
How about issuing a badge for each completed level which can be sent to a player's Mozilla OpenBadges backpack? You already have awesome images for each level which would do well as a badge image.

see http://www.openbadges.org/

**Comment by nwinter** [comment]
I've checked out the Open Badges thing, but it's a bit confusing, and I don't think it's adding enough value for CodeCombat players, so I'm going to close this–not going to implement. If someone is super interested, they can do all the integration work themselves and we'll accept the pull request.
