### ISSUE TITLE
JavaScript inheritance problem: [...] is not a function

### ISSUE THREAD

**Issue by phlopsi** [codecombat/codecombat#1189]
I was playing Gold Rush when I noticed the following problem.

Here's my sample code:

    function Path() {}
    
    Path.prototype = Object.create(Array.prototype);
    
    var path = new Path();
    path.push(1);
    path.push(2);
    path.push(3);
    this.say(path.length);

What I expect:
Tharin saying "3"

What I get:
> Line 6, time 0.0: tmp13[tmp14] is not a function

Can you guys fix this please? =/

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
