### ISSUE TITLE
Linux-Installer Script

### ISSUE THREAD

**Issue by djsmith85** [codecombat/codecombat#1241]
I've tried several methods of getting a dev-environment setup and until just now I failed miserably. Yes I am definitley new to this but setting up the dev-environment shouldn't stop anyone from making a contribution. I finally got the Linux-installer to work. I installed it on Lubuntu just because I had it laying around and it belongs to the Ubuntu family. 

Fix: During the installation of npm I had several errors. I researched a bit and found out that the packets "make" and "build-essential" have to be installed so that npm install can work its magic. Could you please add that to the wiki. Maybe a plain Ubuntu has these already preinstalled.

In codecombat/scripts/devSetup/configuration.py there is a line that states your private repository url. Does this have to be changed by the user prior to running setup.py?

Windows and vagrant install also failed on me. I'm sure it's some kind of configuration issue. II'll have another look at it and will report my findings.

**Comment by nwinter** [comment]
Anyone want to add make and build-essentials to the dev setup script (or has it been already), and/or add a Docker or Vagrant-based method?

**Comment by schmatz** [comment]
I believe emhs added it to the build script a few days ago for Ubuntu (make
is included with build-essential)
