### ISSUE TITLE
Question: Treema doesn't haven children Treemas

### ISSUE THREAD

**Issue by rubenvereecken** [codecombat/codecombat#1259]
I got a patch ready that fetches LatestReferenceVersion models on demand as part of the Treema extension. It effectively fixed 'Unknown' references in the level editor, except for the `treema-shortened` preview when a node is collapsed. Though I'm sure I'll get that one to work too.

The patches however still don't show properly. The Treema doesn't have children Treemas, as can be seen in this image:

![](http://puu.sh/9XLtd/bb864c32c1.png)

I looked around how others did it but couldn't find the difference. I'm sure Scott could help me out really quickly?

Here's a working node for reference, with the shortened version still as 'Unknown'.

![](http://puu.sh/9XLFK/e3aaceb95a.png)

**Comment by nwinter** [comment]
Moved to https://github.com/codecombat/treema/issues/48
