### ISSUE TITLE
Need the ability to make Guides accept different languages

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#1283]
Need to be able to make the Guide accept different programming languages.

**Comment by nwinter** [comment]
We should be able to use the new template context i18n stuff to pull this off, like we do in Component property documentation code examples, which have either one main entry, or an entry for each code language, and all the spoken language stuff comes in through template context variables.

**Comment by nwinter** [comment]
You can now do this by adding several languages' blocks, since the guides and intros now filter out the not-chosen language:
  
    Some guide text in the guide! Code like this!
 
    ```python
    self.example()
    ```
    ```javascript
    this.example();
    ```
    ```clojure
    (.example this)
    ```

    Yay **Markdown**!
   
It will only show the one for the user's target language.
