### ISSUE TITLE
Possibly incorrect CoffeeScript compilation error when using callbacks within functions and fat arrows

### ISSUE THREAD

**Issue by lawrencejohnston** [codecombat/codecombat#1291]
Given the following CoffeeScript in my hero's chooseAction in Dungeon Arena:
```
noFun = @getEnemies().some((e) => (@distance e) > 3) # No error

fun = =>
    @getEnemies().some((e) => (@distance e) > 3) # Error
```

This is the error message I receive:
>Missing `this.` keyword; should be `this.this$1`.
>There is no function `this$1`, but `this` has a method `this$1`.

I'm still learning CoffeeScript but I believe this should work because I'm using fat arrows to capture @. Either way the error message is pretty unintelligible.

I do understand that CoffeeScript support is still in beta, this is being filed in the hopes of bringing it closer to coming out of beta.

**Comment by nwinter** [comment]
Fixed with @basicer's new Esper interpreter.
