### ISSUE TITLE
CoffeeScript debugger says variable is undefined when it isn't.

### ISSUE THREAD

**Issue by lawrencejohnston** [codecombat/codecombat#1292]
Given the following CoffeeScript in my hero's chooseAction in Dungeon Arena:
```
noFun = @getEnemies().some((e) => (@distance e) > 3)

@say noFun
```

If I advance the clock to a point where I've built a hero and he's saying "true" and hover over `noFun` it shows it as `undefined` even though it must be defined because he's saying true.

I do understand that CoffeeScript support is still in beta, this is being filed in the hopes of bringing it closer to coming out of beta.

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter (well, whenever we re-enable the debugger).
