### ISSUE TITLE
CoffeeScript compiler fails on multiple for...in loops nested in a function

### ISSUE THREAD

**Issue by lawrencejohnston** [codecombat/codecombat#1293]
Code in hero's chooseAction in Dungeon Area:
```
fun = -> 
    for x in [1, 2, 3]
        for y in [1, 2, 3]
            null
```

Fails with:
> Missing `this.` keyword; should be `this.accum$1`.
> There is no function `accum$1`, but `this` has a method `accum$1`.

**Comment by nwinter** [comment]
Fixed with @basicer's new Esper interpreter.
