### ISSUE TITLE
Python string slice syntax gives `message._pySlice is not a function` error

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#1305]
It appears that the python parser has issues with indexes for strings (and I would assume arrays as well).  Using negative numbers and using slices doesn't seem to work.

Negative indexes:

``` python
message = 'Company Halt!'
if message[-1] != "!":
     order()
```

The order function should not run, but it does.  When I change it to:

``` python
message = 'Company Halt!'
if message[len(message)-1] != "!":
     order()
```

The order function is not run.  

Slices:
`message[:2]`
`message[4:9]`
`message[2:9:3]`

None of these seem to work.

So apparently python's extra ways of dealing with string indexing doesn't work.

**Comment by nwinter** [comment]
The first two test cases work now. However, the slice stuff gives `message._pySlice is not a function`, so that's not in yet. @basicer do we have an issue for that part yet somewhere else, and is in Filbert or Aether/Esper?
