### ISSUE TITLE
CoffeeScript error reporting often reports errors at the top of chooseAction even when they're elsewhere

### ISSUE THREAD

**Issue by lawrencejohnston** [codecombat/codecombat#1310]
The CoffeeScript error location detection doesn't work in a lot of cases. Very often an error is reported as being at line 1 position 1 even when it's elsewhere in the file.

As an example place the following in your Dungeon Arena->base->chooseAction:
```
unusedvar = 'some value'
fun = ->
    a = 'a'
        b = 'b'
```

The reported error is:
> Syntax error on line 1, column 1: unexpected '=' (\u003D)

The actual problem is on line 4 (the extra indent).

**Comment by nwinter** [comment]
We have several CoffeeScript error range problem issues in Aether, but I just tested and this one is fixed, anyway.
