### ISSUE TITLE
Dungeon Arena: Cannot assign to read only property 'myVar' of Yugargen

### ISSUE THREAD

**Issue by hfarrow** [codecombat/codecombat#1364]
In the following example script, I have an object defined as `this.myObject = {myVar=false};`. `this.myObject.update()` attempts to change the value of `myVar` which throws the error "*Cannot assign to read only property 'myVar' of Yugargen*"

This does not seem like intended behaviour. `myVar` should not be protected. Here is the script in it's entirety:

```javascript
if(!this.initialized)
{
    this.initialized = true;

    this.myObject = {myVar:false};

    // The line below will cause the same error if we remove myVar:false from above.
    //this.myObject.myVar = false;

    this.myObject.update = function()
    {
        // Cannot assign to read only property 'myVar' of Yugargen
        this.myVar = true;
    };
}

this.myObject.update();
```

One partial work around for this issue is below. With the addition of `this.myObject.init()` to initialize `myVar` to false. This almost works, except that at time=00.2 (first run of script)  `msg`  it equal to "*undefined:undefined:undefined:*". I would have expected it to equal "*undefined:false:true*". On the next run of the script, it correctly prints "true:true:".

```javascript
var msg = "";
if(!this.initialized)
{
    this.initialized = true;

    this.myObject = {};

    this.myObject.init = function()
    {
        this.myVar = false;
    };

    this.myObject.update = function()
    {
        this.myVar = true;
    };
    
    msg += this.myObject.myVar + ":";
    this.myObject.init();
}


msg += this.myObject.myVar + ":";
this.myObject.update();
msg += this.myObject.myVar + ":";
this.say(msg);
```

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
