### ISSUE TITLE
Kmeans++ : Always the same seed

### ISSUE THREAD

**Issue by Vettax** [codecombat/codecombat#1399]
Hi,
I discuss with @Darredevil about the K means.
We solved few problems in my code and in the level.
But now I'm not able to get various seed to test the 4 different predictions.
With the previous code level, It worked, I mean, I was able to get the different seeds, and my code was successful only with seed 1.
Now I get only seed 1. So ok, my code now works all the time, but it's not the normal behavior.
I tried to change the seed, or by reloading the level (F5 in Chrome), or by changing a little bit the code. 10 times each, and always the same seed.
@nwinter, any idea ?

Vettax
PS : to be precise, With f5 under Chrome, I always get the same debug and same generated random seed :
Manannan Mac Lir's Ray| Generated random seed -172894491305 of type playerCode from sessionIDs ["53cd7fab2bb1f44d0507a06f"] app.js:59
|Manannan Mac Lir's Ray| Using seed 4198011591 from seedBucket 1

If I change the code, the generated random seed number is different, but it always end in the same seed bucket:
|Manannan Mac Lir's Ray| Generated random seed -172950288191 of type playerCode from sessionIDs ["53cd7fab2bb1f44d0507a06f"] app.js:59
|Manannan Mac Lir's Ray| Using seed 4198011591 from seedBucket 1

a link to my session:
http://codecombat.com/play/level/k-means-cluster-wars?session=53cd7fab2bb1f44d0507a06f

**Comment by nwinter** [comment]
Moved this to the in-level Tasks list.
