### ISSUE TITLE
position of input cursor is always not right in Debian in any browser

### ISSUE THREAD

**Issue by andyhunter** [codecombat/codecombat#1411]
When editing the source code(js code),anything I typed always appears at several letters ahead the twinkling cursor.
The cursor will always be some distance away from the real inserting position.

Im using Debian 7.5,tried both Chrome and Iceweasel,always the same problem.And no other website I visited has this problem.(e.g. github)
But switching to Windows solves it.

I really want to use codecombat in Dedian.
I do want some help!Thanks!

**Comment by wmh** [comment]
I need to download Monaco font to fix this issue.
