### ISSUE TITLE
Automatic type conversion hook for CoCo API arguments

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1451]
We need a hook to provide per-language automatic type conversions when passing data **into** CoCo APIs.

Related thread: https://github.com/codecombat/codecombat/issues/1053
Hook for automatic type conversion **out** of CoCo APIs: https://github.com/codecombat/aether/commit/368916f357ecd11af2cc9bb3b83d2397e7648473

**Comment by nwinter** [comment]
@basicer do we still need this?
