### ISSUE TITLE
Criss-Cross: array.splice() inside a function has no effect

### ISSUE THREAD

**Issue by MHeasell** [codecombat/codecombat#1459]
In Criss-Cross, calling array.splice() to insert an element from inside a function has no effect. See this example.

    function spliceWrap(item, a) {
        a.splice(0, 0, item);
    }

    var arr = ["a", "b", "c"];

    spliceWrap("x", arr);
    //arr.splice(0, 0, "x");

    this.debug(arr);

    return null;

The output of the debug statement is currently ["a", "b", "c"]. Commenting the spliceWrap line and uncommenting the splice line yields ["x", "a", "b", "c"].

**Comment by nwinter** [comment]
Fixed with @basicer's new Esper interpreter.
