### ISSUE TITLE
Unable to call player methods from plan()

### ISSUE THREAD

**Issue by Darredevil** [codecombat/codecombat#1466]
While working on the 'Minimax Tic-Tac-Toe' level I ran into a problem with plan() :  i was unable to call any of the other player-side functions, the ones the player has to write code for them, from plan(). Had to switch to chooseAction for them to work.
Too see this live go to http://codecombat.com/editor/level/minimax-tic-tac-toe and edit the chooseAction() into plan()

**Comment by nwinter** [comment]
We aren't doing multiple method implementation levels any more, so this is no longer relevant.
