### ISSUE TITLE
Criss Cross Leaderboard Ogres Im twice on it

### ISSUE THREAD

**Issue by chess9876543210** [codecombat/codecombat#1473]
CodeCombat
DEUTSCH (DEUTSCHLAND)
Spielen
Community
Account
Banner2

Turnier endet in a month
Win bids, construct paths, outwit opponents, grab gems, and upgrade your career in our Criss-Cross tournament! Check out the details on our blog.

Spiele als Humans
Spiele als Ogres
Zuschauen
Rangliste
Meine Matches
Simuliere
#17 of 67

-2,000
0
2,000
4,000
6,000
HumansLeaderboard
Punktzahl   Name  
1   6607    Nick    Fight!
2   6456    qwe Fight!
3   6210    c11ris  Fight!
4   6008    nino48  Fight!
5   5780    zbanana Fight!
6   5605    Valiant Fight!
7   5552    Wizard Dude Fight!
8   5506    nemoyatpeace    Fight!
9   5418    Jex Fight!
10  5244    Jerigan Fight!
11  5188    piThrower   Fight!
12  5174    dcm Fight!
13  5166    Tilorian    Fight!
14  5143    MyWizardlyName  Fight!
15  4931    Forsaken    Fight!
16  4834    paulgator   Fight!
17  4789    chess   Fight!
18  4617    jChuck  Fight!
19  4603    JavaCaster1 Fight!
20  4597    Driphter    Fight!
#28 of 53

-2,000
0
2,000
4,000
6,000
OgresLeaderboard
Punktzahl   Name  
1   6380    Nick    Fight!
2   6370    CryZe   Fight!
3   6363    nino48  Fight!
4   6352    Tehvudgaw   Fight!
5   6254    Interimo    Fight!
6   5783    MyWizardlyName  Fight!
7   5607    nemoyatpeace    Fight!
8   5568    Driphter    Fight!
9   5344    Valiant Fight!
10  5336    lifeline    Fight!
...
24  4279    jChuck  Fight!
25  4233    Diruna  Fight!
26  4108    chess   Fight!   NOTE: here is one
27  4051    odoacre Fight!
28  4018    chess   Fight!   NOTE: here, too
29  3974    Kefir   Fight!
30  3896    lichens Fight!
31  3837    skeltoac    Fight!
32  3790    Plak87  Fight!
More
spielende Freunde
Verbinde und spiele gegen deine Freunde!
FacebookGoogle+
HomeHelfenRechtlichesÜberKontaktEditorBlogForum
Twitter
Mobile AnalyticsPowered by Firebase

the German ladder menu over here

**Comment by nwinter** [comment]
@chess9876543210 have you seen this again since? Do you remember what browser it was in? I found one bug that could have caused this yesterday, but I don't know for sure whether I got it.

**Comment by nwinter** [comment]
> Uhm... there's seems to be a bug in the leaderboard... I'm both 26th and 27th on multiplayer-treasure-grove (Ogres)

Of course I get another bug report of this the day after I close it. Looks like the logic around being 26th-28th is wrong.
