### ISSUE TITLE
Scroll bars covering text in Level Editor

### ISSUE THREAD

**Issue by Darredevil** [codecombat/codecombat#1479]
While making some guides in the Level Editor I noticed that parts of the text are covered by the scroll bars: 
![test1](https://cloud.githubusercontent.com/assets/6786777/4022251/4e830408-2b25-11e4-99af-68f3034fe1aa.png)

The above picture is what you see when you are writing it, the actual text after you toggle the preview is:
![test2](https://cloud.githubusercontent.com/assets/6786777/4022255/724d116c-2b25-11e4-9fed-c5204a231f97.png)

**Comment by duybkict** [comment]
@nwinter I just checkout Level Editor and see that this issue was fixed. Should this issue be closed?

**Comment by sderickson** [comment]
This may be specific to Windows/Chrome. What operating system did you use to check?

**Comment by duybkict** [comment]
I checked on Windows/Firefox and Windows/Chrome, both are fine

**Comment by sderickson** [comment]
Sounds good to me! Thanks for checking it out.

**Comment by Darredevil** [comment]
Hello,

I see I have been CC-ed as the author of this ancient bug.
If i remember correctly it was on Ubuntu Chrome (possibly with a small
screen, for 22''+ there wasn't a problem i think).

Alex

2016-05-05 21:18 GMT+03:00 Duy Trần <notifications@github.com>:

**Comment by duybkict** [comment]
hmm, now the width of the textview stretch to fit the screen and the height is auto resized base on the input text, so I think it would cover all cases
