### ISSUE TITLE
"Break the Prison" default python code reverting to JS, hear() function

### ISSUE THREAD

**Issue by buddyatkins** [codecombat/codecombat#1495]
In the level "Break the Prison" when using python the default code for the hear() function reverts to JS. The other two functions, isFriend() and choseAction(), are both pythonic. 

When viewing the level editor there is proper python code for the hear() function, it is just not being called up.

Screenshot of error:
![2014-08-28_12h08_02](https://cloud.githubusercontent.com/assets/8581710/4078620/825707e2-2ecd-11e4-8e8f-466c56335309.png)

Screenshot of other function appearing properly:
![2014-08-28_12h06_43](https://cloud.githubusercontent.com/assets/8581710/4078606/658e6772-2ecd-11e4-9629-54c053d029fb.png)

**Comment by nwinter** [comment]
I think the read-only stuff is working. We are basically never using read-only code in any levels any more, so I'm going to close this instead of thinking that someday we'll implement read-only Python code.
