### ISSUE TITLE
Add data-i18n="[title]translation_key" throughout site

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#1502]
I just realized that it's really easy to translate attributes like `title`, `placeholder`, etc. using i18next:

```jade
a(data-i18n="[title]common.submit_patch")
input(data-i18n="[placeholder]editor.enter_level_name", placeholder="Type in a level name")
button(data-i18n="[title]editor.randomize_terrain;editor.randomize", title="Randomize Terrain") Randomize
```

We should go through the site and add i18n tags for all the title and placeholder attributes found throughout the templates so they can be translated.

**Comment by nwinter** [comment]
@Imperadeiro98 are there any remaining places in the site you know about that don't already have their own specific issues here?

**Comment by Imperadeiro98** [comment]
Not that I know. As I find new places without i18n, I add them myself or open an issue, so I think this issue can be closed.
