### ISSUE TITLE
Brawlwood Tutorial level shows NaN for the Ogre gold value

### ISSUE THREAD

**Issue by johnbatty** [codecombat/codecombat#1507]
Appears to be some bug in Ogre gold calculation.

![brailwood_tutorial](https://cloud.githubusercontent.com/assets/1869270/4122579/06f177de-32c6-11e4-8895-c1f4b769a69e.png)

**Comment by nwinter** [comment]
Looks like this is fixed; just shows no entry, since they have no gold.
