### ISSUE TITLE
In Brawlwood Tutorial, archer attack() function fails to move towards enemy

### ISSUE THREAD

**Issue by johnbatty** [codecombat/codecombat#1508]
The tutorial says "Have your archers use their attack spell on any ogre enemies they see".
So I changed my code to this...

    var enemy = this.getNearestEnemy();

    if(enemy) {
        // An enemy unit is visible to the archer.
        this.say('I see ' +enemy.id);
        this.attack(enemy);
    } 
    else {
        // No enemies in sight
        // IMPORTANT: hover over the map for coordinates, shift+click to insert
        this.move({x:40, y:65}); // absolute, not relative
    }

The archers all say that they see the enemy, and the enemy is out of range so they should (according to the function description) move towards it.  However, they just stand still and don't fire any arrows :-(

Unfortunately this makes it very difficult to progress through the tutorial!

![brailwood_tutorial](https://cloud.githubusercontent.com/assets/1869270/4122851/ad6a8f9a-32c8-11e4-8532-27fa1380c6dc.png)

**Comment by nwinter** [comment]
I've updated the sample code to point out that the archers don't chase in this one if out of range.
