### ISSUE TITLE
Sky Span: Game overloads when beating Lanner

### ISSUE THREAD

**Issue by buddyatkins** [codecombat/codecombat#1513]
Lanner's Strategy: Create nothing but Anya's and have them sit behind the human commander spamming the field with razor disks. Unless players instruct minions to ignore attacking the commander and go after the heroes behind the commander the attackers will be overwhelmed with razor disks before they get a chance to kill the commander.

The problem: When I adjusted for this strategy and took out the Anya's  the game would "take too long or hit an infinite loop". Even when I simplified my code down to just a few lines it still would error out. Not sure what is causing the error. It tends to happen right around the time the first Anya would die and the send Anya would spawn. And only happens when the ogre's have a mass of people around the human spawn.

The ogre code that causes the error (I had an even simpler version but it doesnt seem to matter):

```python
buildOrder = ['munchkin', 'munchkin', 'munchkin', 'thrower']
buildType = buildOrder[len(self.built) % len(buildOrder)]
if len(self.built) <100:
    if self.buildables[buildType].goldCost <= self.gold:
        self.build(buildType)

enemies = self.getEnemies()

minions = self.getFriends()
for minion in minions:

    # self.command(minion, 'move', {"x": 64, "y": 30})

    if enemies[1]:   
        self.command(minion, 'attack', enemies[1])
    else:
        self.command(minion, 'attack', enemies[0])
 
#When the move command is used instead of attack to keep minions from swarming human spawn it does not freeze
```

**Comment by nwinter** [comment]
I've got better `NaN` handling in place now, so at least it errors out. Will keep an eye out for scattershot or razor discs continuing to be problems in new hero levels.
