### ISSUE TITLE
Criss-Cross: cannot modify user object passed into function

### ISSUE THREAD

**Issue by MHeasell** [codecombat/codecombat#1533]
Playing criss-cross, I cannot reassign (or modify in-place) the properties of an object passed in as a parameter from within the function body.

Example:

    function replaceArr(thing) {
        thing.arr = ["xyz"];
    }

    function pushArr(thing) {
        thing.arr.push("foo");
    }

    var foo = { arr: [] };
    //replaceArr(foo);
    //pushArr(foo);

    return null;

If I uncomment the replaceArr call, I get:

`Line 2, time 0.6: Cannot assign to read only property 'arr' of Anya`

If I uncomment the pushArr call, no error occurs but `foo.arr` is not modified.

I guess this is another symptom of the API protection issues with Aether similar to #1459.

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
