### ISSUE TITLE
programming.Programmable deleteClones is slow

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1565]
It's particularly bad in Sky Span and Brawlwood.

Chrome beta now easily lets you profile the execution of a web worker thread:

![screenshot 2014-09-16 12 21 01](https://cloud.githubusercontent.com/assets/2965172/4293568/649720de-3dd7-11e4-975d-7b62b3c6029b.png)

**Comment by popey456963** [comment]
I definitely like that feature with Chrome, however, what happens to be the difference between total and self?  For the one highlighted, self is 206ms which is very reasonable.

**Comment by Imperadeiro98** [comment]
But if you look down the tree, you see there are more deleteClones, which, in fact, take a long time.

**Comment by nwinter** [comment]
Fixed with @basicer's new Esper interpreter, since we no longer need to delete clones.
