### ISSUE TITLE
Un-textured wizards

### ISSUE THREAD

**Issue by chess9876543210** [codecombat/codecombat#1568]
As I spectated a match, on load of the site the invisible wizards (the two of the coders and the one of me/the spectator) were all on the left bottom, names overlaped and just past loading they were on their normal position.
This could be longer as on other devices because low RAM for the internet explorer.

**Comment by nwinter** [comment]
This probably isn't important enough to fix now, because we aren't doing much with old-style ladder levels (the ones with the wizards).
