### ISSUE TITLE
Thangs sharing code need to be in specific index order in thang list

### ISSUE THREAD

**Issue by gosnat** [codecombat/codecombat#1569]
If thangs are sharing code (so one "master" thang owns the method, and the other thangs refer back to the master thang), the master thang must have a lower index in the thang list in order for it to work.  

This is a problem because every time you edit the master thang, it moves to the last index in the list, requiring you to do empty edits to the other thangs to move them down the list.

**Comment by nwinter** [comment]
We don't intend to keep supporting Thangs sharing code any more.
