### ISSUE TITLE
Add simple loop statement support for remaining languages

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1570]
We need to add support for the remaining programming languages.  JavaScript and Python were initially supported.

Initial commits:
https://github.com/codecombat/aether/commit/b599f79f9c3b6d87ad44764d1442209b292545f4
https://github.com/codecombat/codecombat/commit/3209e4f838b3b669b055eaf3237b6e8a22bf5fc6

Steps:
1. In [Aether](https://github.com/codecombat/aether), implement ```replaceLoops()``` for the given programming language
2. in [CodeCombat](https://github.com/codecombat/codecombat), add Ace keyword syntax highlighting

Note that CoffeeScript already has a loop keyword, but still needs an Aether ```replaceLoops()``` that tracks the correct start range index.

Note that Clojure already has a loop form, and not a good equivalent of while (true).  Therefore, we should hold off adding support to Clojure until we know what would be appropriate for that language.

**Comment by nwinter** [comment]
Lua is done, now, too: https://github.com/basicer/aether/commit/3fe72f8e5f348eef4fac2e01f66f69a81b2a0113#diff-097340f7eba6ced75ce0bc69979054b2R23

**Comment by vickychijwani** [comment]
Just a note, Clojure does have a `while (true) { ... }` equivalent, try this on the [parser demo](http://vickychijwani.github.io/closer.js/):

```clojure
(while true
  (alert "sdf"))
```

**Comment by merlinpatt** [comment]
To make CoffeeScript easier to deal with, would it be possible to convert it behind the scenes to JavaScript and then run that? Or is that too time intensive?

**Comment by nwinter** [comment]
Sure, we just use CoffeeScript's parser, we don't even have to worry about code generation (Aether does that). Adding simple loop for CoffeeScript isn't going to be that difficult, just need someone to sit down, do it, and test it out.

**Comment by nwinter** [comment]
We aren't going to do simple loops going forward, so we don't need to get it working for CoffeeScript.
