### ISSUE TITLE
First single player mission (Python) hints for JS

### ISSUE THREAD

**Issue by amueller** [codecombat/codecombat#1591]
The hints and help given by the other character are for JS, not Python (not sure this is the case for all missions)

**Comment by GrampaPaul** [comment]
I found this problem in Forest in 3 places thus far:  Nine Gems, Back-To-Back, Maniac Munchkins.
First one, I reported in Forums.  Second one, I made a new topic.  Third one I was referred to Github and this is where I finally found this Issue topic #1591.
Some big learning experience for me.  👍
