### ISSUE TITLE
Switching Languages and Reloading Code at the same time

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#1604]
When I use the game menu to change the language I get some weird things.
1. My default language is python but I decide to change to javascript for this level:
   A. This is my code:
   ![image](https://cloud.githubusercontent.com/assets/6550021/4415291/42a37740-4528-11e4-97b7-d90238ea1f56.png)
   B. I go to the game menu, switch languages, and hit close: 
   ![image](https://cloud.githubusercontent.com/assets/6550021/4415299/6cb961e8-4528-11e4-8c44-14b964bbda20.png)
   C. The page reloads, my code stays the same (just adds some errors):  
   ![image](https://cloud.githubusercontent.com/assets/6550021/4415302/82a31a4e-4528-11e4-9b53-66b9db87b0de.png)
   D. Now I go back to the menu and Reload code and I have nice javascript code and am running in javascript.

Option 2, I decide now that I've solved with javascript that I want to change to python.
 A. I switch language to python and hit the reload all button:  
![image](https://cloud.githubusercontent.com/assets/6550021/4415943/985ab416-4535-11e4-92b1-b18626f12a1d.png)
 B. Screen reloads set as python, but code is javascript default code:
![image](https://cloud.githubusercontent.com/assets/6550021/4415952/c27eedf2-4535-11e4-80dc-4837d5c7b53a.png)

It seems that the reload is checked without checking the language first.

**Comment by javatlacati** [comment]
When changing the character and language from lua to phyton got an error on the comments at line 1 saying:

`-- Use "if" and "else if" to handle any situation.`

when changed comments to `#` noticed that code was unchanged so here's the full code for your test:

    -- Use "if" and "else if" to handle any situation.
    -- Put it all together to defeat enemies and pick up coins!
    -- Make sure you bought great armor from the item shop! 400 health recommended.

    loop
    local flag = self:findFlag()
    local enemy = self:findNearestEnemy()
    local item = self:findNearestItem()
    if flag then
        -- What happens when I find a flag?
        local fx=flag.pos.x
        local fy=flag.pos.y
        self:moveXY(fx, fy)
        self:pickUpFlag(flag)
    elseif enemy then
        -- What happens when I find an enemy?
        if self:isReady("cleave") then
            self:shield()
            self:shield()
            
            self:cleave(enemy)
        else
            self:attack(enemy)
        end
    elseif item then
        -- What happens when I find an item?
        --    local fx=flag.pos.x
        --    local fy=flag.pos.y
         --   self:moveXY(fx, fy)
         self:moveXY(item.pos.x, item.pos.y)
        end
    end

So... please reopen issue! :sob:

**Comment by nwinter** [comment]
Hmm, we don't reload the code for you if you switch languages and have written the solution, only if you just have the default code. We figure players might be sad if their solutions just vanish on language change instead of being able to translate to the new one. And you could hit the reload button in the upper right if you intentionally wanted to get rid of it. What do you think, @javatlacati?

**Comment by javatlacati** [comment]
I agree it's painful to get your solution lost forever.
So.. for language change I propose: #3020 
I suggest to add with the say command a entry for comment syntax that depens upon the language.

The main problem I faced was that for the first levels I didn't want to loose my solution by reload and didn't knew the syntax of a new language.

**Comment by javatlacati** [comment]
![bug lua cc1](https://cloud.githubusercontent.com/assets/1063901/9834774/bdae627a-598f-11e5-9bc2-fbc9fc0e93ae.png)
As you can see you open and it runs automatically, then go to the in gae¿me menu, change language and no errors appears, then the message that you were killed and failed missions is shown.
