### ISSUE TITLE
Automatic Google login dismisses login dialog

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1614]
If you're signed into Google, the CodeCombat login automatically logs you in and closes the dialog.  Poor user experience

This is a problem for a few reasons:
1. Why did the user have to open this dialog if we're going to just dismiss it?
2. How does a user know they have to go to google.com and sign out, before they can login with a different account?
3. It makes testing user creation and sign in more difficult.

You should be able to login with a different account, without having to navigate to another site first.

Suggested changes:
1. Don't auto-dismiss the login dialog (and maybe don't automatically login with Google)
2. Auto login with Google on the homepage once, but definitely not if a user has selected logout during the current session.

**Comment by differentmatt** [comment]
@nwinter How has this issue been resolved?

**Comment by nwinter** [comment]
I dunno, someone said that it was fixed, but since it wasn't pointed at this issue, I don't remember who.

**Comment by differentmatt** [comment]
This no longer reproduces on Mac Chrome 42.0.2311.135 (64-bit)
