### ISSUE TITLE
Google API script error in Chrome on play/ladder page

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1633]
Red 'JS console' script error popup occurs in Chrome on OSX and Windows8.1.  Does not repro on Firefox.

![playladdergapiscripterror](https://cloud.githubusercontent.com/assets/2965172/4495847/9fffeeaa-4a5f-11e4-9438-9cff27c29c83.png)

**Comment by popey456963** [comment]
Tested on the latest version of Chrome on both OSX and Windows 8.1, there are know no errors.
