### ISSUE TITLE
Brunch build hangs on Windows

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1641]
This is caused by the fix to #1615, and indirectly https://github.com/brunch/sass-brunch/issues/40.

Mac/Linux requires sass-brunch 1.7.2 or earlier.  Windows requires sass-brunch 1.8.0 or later.

We need a combination that works for both, and digging into the tool dependencies will likely yield that.  E.g. is the real problem in ruby sass or libsass?

The workaround on Windows is to manually install sass-brunch 1.8.0 or later, and then build via brunch.

**Comment by nwinter** [comment]
We are using our custom `sass-brunch` version now that should work in both places.
