### ISSUE TITLE
Doesn't work in Opera (need unsupported message)

### ISSUE THREAD

**Issue by ClockworkMachine** [codecombat/codecombat#1727]
Hello!

I've just started to play the Dungeon campaign in CodeCombat. I tried to restart "Gems in the deep" because I made by accident some kind of mistake and I were not avaible to achieve bonus for code without mistakes. Unfortunately something gone wrong and now I can't play any level from Forest and Dungeon campaign. I receive message "Infinite Loop detected". I don't know what I did wrong because I played that level only few seconds. None of three options works. Thank you in advance for help. My CodeCombat nickname: Acererak.

**Comment by nwinter** [comment]
It works in Opera now. Even the sound will work next time we update SoundJS.
