### ISSUE TITLE
Zatanna not clearing out old snippets

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#1737]
If I change code languages in CodeCombat, [it should call](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/SpellView.coffee#L273) `@zatanna.addSnippets`, which [looks like it is supposed to deregister old snippets](https://github.com/differentmatt/zatanna/blob/master/src/zatanna.coffee#L91-L104), but they just all get in there:

![screenshot 2014-11-10 09 16 41](https://cloud.githubusercontent.com/assets/99704/4980145/5fb9a05e-68fd-11e4-87c7-c2b51efaea66.png)

I didn't dig too deeply. To repro: open hero chooser, change language from JavaScript to Python, hit next, close inventory modal without hitting play, then see the extra snippets. (I've seen it happen with hitting play, but it's less reliable a repro.)

**Comment by amankr** [comment]
I think this commit 80fb1247724c94a310246b9ddeb393d00482b841 fixed the issue
