### ISSUE TITLE
Logged in to random account

### ISSUE THREAD

**Issue by nholtappels** [codecombat/codecombat#1749]
Upon visiting codecombat.com I found myself logged into a stranger's account. There is no way someone else logged into their account from my computer, unless I got hacked, so I strongly suspect that this is the consequence of a bug in codecombat. I'd be happy to help with troubleshooting this.

**Comment by nwinter** [comment]
My best guess now is that the GitHub login was what was so buggy about this. It has been disabled for a while and no one has reportedly seen the issue, so I'll close this in favor of just fixing it so we can turn it back on with #1764.
