### ISSUE TITLE
Actions sometimes activated again all at once improperly

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#1757]
This has the result that all the dead units get up in order to die again. I would have said it's probably something to do with world streaming chunks improperly setting `actionActivated` to `true`, but now just looking at when it happened, it doesn't reproduce when scrubbing past the same point on the same run again, so maybe it is something to do with real-time playback instead?

**Comment by nwinter** [comment]
This happens when spritesheets are rerendered after resizing everything to a smaller spritesheet: https://github.com/codecombat/codecombat/blob/master/app/lib/surface/LayerAdapter.coffee#L294 – maybe we need to maintain old animation frames when rerendering? At least rerender less often.

**Comment by nwinter** [comment]
@sderickson how hard to maintain old animation frames when rerendering?

**Comment by sderickson** [comment]
Maybe a few hours to figure out?

**Comment by nwinter** [comment]
Fixed in c56ec2c, at least for SegmentedSprites!
