### ISSUE TITLE
Hero class not displayed in store

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1775]
Need to know hero class so I can map class restricted items to heros.  Which heros can wear that sweet wizard hat?

![screen shot 2014-11-21 at 9 19 15 pm](https://cloud.githubusercontent.com/assets/2965172/5153006/468b52ec-71c4-11e4-8933-6313603ee79b.png)

**Comment by nwinter** [comment]
Fixed by #2326
