### ISSUE TITLE
If the target position is not reachable, the hero will stuck in map and can't cancel current action.

### ISSUE THREAD

**Issue by iAladdin** [codecombat/codecombat#1783]
Some times a map random generated, and there is some coins or enemy placed around collision, but I still can find them by findnearestItem or findnearestenemy, so the hero always try to move and I can't cancel the action.

**Comment by popey456963** [comment]
At the moment of speaking, the move command will cancel after a certain amount of time if said location is unreachable.  The hero will say that he cannot reach the location.
