### ISSUE TITLE
Email Stats Show Win and Loss to Same Person

### ISSUE THREAD

**Issue by chess9876543210** [codecombat/codecombat#1786]
I got the Email from Multiplayer  info Email about my stats and it Said Lost to (playername) won against (same name). this might be caused by the fact you win and lose weather the Enemy placed Flags or not. So i think it would be the Most Easy if the code Senats the Email ignores a player already shown in Loss category, because everything else would effect the flag System or the replay Match while user is online possibility.

**Comment by nwinter** [comment]
I think this will be fixed by fixing #1830, so I'll close in favor of that one. I don't want to make the emails hide the problem.
