### ISSUE TITLE
move and moveXY are choppy (yielding too much)

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#1787]
moveXY currently runs in a choppy fashion if I attempt to break the moves into pieces.  I want to be able to check things again after 3 meters so I make sure I'm only moving 3 at a time, but it seems that now my hero accelerates and decelerates every time, thus causing very choppy movement.  Would be nice to have the old move concept back so that he will just move smoothly.

**Comment by nwinter** [comment]
Finally got this one!
