### ISSUE TITLE
Comments to code for infinite loops

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#1788]
I have code that won't load because of an assumed infinite loop.  I can hit the "comment out my code" and it works fine, except that the inserted line of code is now an error because it is javascript rather than my current language.

![image](https://cloud.githubusercontent.com/assets/6550021/5159809/f9959a6e-73ae-11e4-91b1-33673645f5b4.png)

![image](https://cloud.githubusercontent.com/assets/6550021/5159810/03c67e36-73af-11e4-8e1c-a1e9edbfbb18.png)

**Comment by nwinter** [comment]
Need to update [this code](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/TomeView.coffee#L80-L86) to use the right return syntax per language. Probably want to move the comment logic into SpellView, where we know which language the spell is in and have the [comment regex](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/SpellView.coffee#L782-L782) ready and all that.

**Comment by Nuke928** [comment]
How would this be accomplished in Clojure?

--- Ursprüngliche Nachricht ---

Von: "Nick Winter" <notifications@github.com>
Gesendet: 10. Januar 2015 18:03
An: "codecombat/codecombat" <codecombat@noreply.github.com>
Cc: "Gian S." <gian.sass@outlook.de>
Betreff: Re: [codecombat] Comments to code for infinite loops (#1788)

Need to update [this code](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/TomeView.coffee#L80-L86) to use the right return syntax per language. Probably want to move the comment logic into SpellView, where we know which language the spell is in and have the [comment regex](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/SpellView.coffee#L782-L782) ready and all that.

---

**Comment by nwinter** [comment]
There's no return, but you could add some one-line Clojure at the beginning that would cause it to error out, which would stop the infinite loop, like `(.dieEarly this "now")` (or something less dumb).

**Comment by divyanshu013** [comment]
You may close this issue @nwinter, I think the last commit fixed it.
