### ISSUE TITLE
Simulation stops with "The task was malformed, reason: Two players share the same team"

### ISSUE THREAD

**Issue by ebirkenes** [codecombat/codecombat#1833]
When running simulations it just stops after a while. I get this error in the console: 

|Helios's Woodhouse|   Loaded 1576 of 1800 (+1086ms) Angel.coffee:47
|Helios's Woodhouse|   Loaded 1672 of 1800 (+1103ms) Angel.coffee:47
|Helios's Woodhouse| The world ended in won on frame 1698 Angel.coffee:47
Uncaught Error: The task was malformed, reason: Two players share the same team
|Helios's Woodhouse| Headless simulation completed in 15571ms. Angel.coffee:47
Posted 1 error to errorception.com 

Then it just stops running simulations.
I didn't think to check if it's always the same level, but in this case it was Multiplayer Treasure Grove.
This is in Chrome on Linux if that matters.

**Comment by nwinter** [comment]
I don't think we are getting malformed double-team errors any more, but if anyone sees one, let me know.

I've added some logic to abort the simulation if we see those NaN velocities, so at least it should finish pretty quickly, although it'd be better if we could recover, or at least figure out what piece of game engine code got the NaNs into the velocities in the fires place.
