### ISSUE TITLE
Can't fork thang "burl"

### ISSUE THREAD

**Issue by chess9876543210** [codecombat/codecombat#1844]
If I try to fork "burl" it says "Error saving Burl2: 401: Unauthorized"
and another message in red: "Error: Uncaught Syntax Error: Unexpected Token M
Check the console for more"
console says:"WebSocket connection to 'ws://codecombat.com:9485/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
jquery.js:8623 POST http://codecombat.com/db/thang.type 401 (Unauthorized)
CocoModel.coffee:149 going to log an error message
CocoModel.coffee:150 Error saving burl2 undefined
burl:1 Uncaught SyntaxError: Unexpected token M"
if it fails to save/fork because im unauthorized, there's no problem

**Comment by popey456963** [comment]
I will close this, because the issue has been fixed - @chess9876543210 , you should still be able to reply to @nwinter 's question.
