### ISSUE TITLE
Highlighting locked default code doesn't work for multiple ranges

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1852]
The ranges are correct.  The actual locking is correct.  The locked-code divs under ace_marker-layer have the correct position dimensions.

However, the dashed highlighting is stacked from the top:
![screen shot 2014-12-05 at 2 08 26 pm](https://cloud.githubusercontent.com/assets/2965172/5323757/479ef070-7c88-11e4-823e-a12486fd2f07.png)

**Comment by nwinter** [comment]
We are moving away from locking default code, especially complicated bits like multiple ranges.
