### ISSUE TITLE
403 when purchasing as anonymous

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1882]
Tried to purchase an item that was more gems than I had.

Need to go through login process and then continue purchase path.

![screen shot 2014-12-08 at 8 48 29 am](https://cloud.githubusercontent.com/assets/2965172/5342960/147095d8-7eb7-11e4-9af3-6ccf4115853f.png)

**Comment by nwinter** [comment]
Should be fixed with my fixes to #2293, if not before.
