### ISSUE TITLE
Ladder matches against specific opponents aren't opening up properly

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#1892]
From [the forum](http://discourse.codecombat.com/t/cant-fight-some-players-on-demand/1632), "Can’t fight some players on demand":

> When I click explicitly to test against some player in ladder often the load hangs (in the middle of green bar).

> I have a hunch that it has something to do with language, I use JS and seem to be able to test against other JS players, but not Python.

[Another post](http://discourse.codecombat.com/t/suddenly-losing-every-match/1640) and #1830 talk about not being able to load opponent code properly in 'Defeat the ogres' matches.

**Comment by nwinter** [comment]
There's also this bug report a user emailed to us, talking about the ladder update match results emails:

> Clicking on the "See Match" buttons takes me to that level but doesn't load my code -- it looks like the code has been reset to default, even when I go back "home" and look at "My Matches".

**Comment by sotonin** [comment]
I have noticed that randomly sometimes a specific player won't load. the loading bar just gets stuck. sometimes its a player i've been tweaking my script to battle a few times then it just happens. I haven't gone back and tried again later (usually don't remember there name) it might automatically resolve itself.
