### ISSUE TITLE
Problems with flags 

### ISSUE THREAD

**Issue by thedoctorde** [codecombat/codecombat#1901]
I don't see any availiable flag to place on the map in levels: Coinucopia and next for Coinucopia.
Some days ago there were flags in Coinucopia level, but now they dissapiared!

screenshot: http://take.ms/9jcFz

google chrome last version, windows 8.1

**Comment by nwinter** [comment]
Just added some more scripts, and had added more comments and docs. Have done several things now to guide the player towards pressing submit in Coinucopia, even a second time, to get to the flags.
