### ISSUE TITLE
Not counting correct lines of code

### ISSUE THREAD

**Issue by DrDinosaur** [codecombat/codecombat#1915]
Bonus for using under six lines of code. I use five, but it doesn't count. I think this is because of the comment on top I can't remove. See screenshot.

http://gyazo.com/30ddc1448dcbde32c4efda31f77f3bbb

**Comment by popey456963** [comment]
This is a very difficult issue to solve, counting statements is hard for the user, and counting lines can be easily gamed in some languages (JavaScript you can use a minimiser to get a single line for every challenge).

**Comment by popey456963** [comment]
#2612 is Linked

**Comment by nwinter** [comment]
Let's just discuss in 1808.
