### ISSUE TITLE
Exp and gems text don't fit the victory window

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#1917]
![default](https://cloud.githubusercontent.com/assets/1132840/5409356/463d47f0-81fa-11e4-9c1e-c496b64e783f.PNG)
ru locale. When numbers are greater then 99 text starts floating. With numbers <100 i have some glitches too, but it is not so noticeable.

**Comment by popey456963** [comment]
I think this issue should be closed.  The solution provided by nwinter fixes this issue.

**Comment by nixel2007** [comment]
But it hasn't fixed yet. I saw this bug yesterday on production. 

Отправлено с моего HTC

----- Reply message -----
От: "Popey Gilbert" <notifications@github.com>
Кому: "codecombat/codecombat" <codecombat@noreply.github.com>
Копия: "nixel2007" <nixel2007@gmail.com>
Тема: [codecombat] Exp and gems text don't fit the victory window (#1917)
Дата: вс, янв. 11, 2015 13:50

I think this issue should be closed.  The solution provided by nwinter fixes this issue.

&mdash;

**Comment by nwinter** [comment]
The code that I linked only shows how to reduce the font size per-language for the home page slogan text; a similar approach still needs to be taken here.

**Comment by rishiloyola** [comment]
i made necessary changes . and i checked it, for text greater then 100 . while solving this bug i found other bug for sign up button . look in picture it is over flowing . can i fix this ?
![screenshot from 2015-01-31 17 11 16](https://cloud.githubusercontent.com/assets/10094679/5987983/630c586a-a970-11e4-8538-b1b0b43fa2da.png)

**Comment by nixel2007** [comment]
@rishiloya exp part looks great! 
For the "reg to save" button - will it solve the problem if button will stretch to the right edge of the gems field?

**Comment by popey456963** [comment]
@rishiloyola - You can of course fix the submit button!  But may I suggest making two separate pull requests?

**Comment by rishiloyola** [comment]
ok sure , but i am thinking to increase in height of button and separate sentence in to two parts rather then increase in a width .

**Comment by popey456963** [comment]
Although you should speak to someone else, I'm not sure we'll want to increase the height of the button specifically - maybe decrease the margins so it does go to two lines?

**Comment by rishiloyola** [comment]
yeah , i saw that pic , i also want to do something like that .

**Comment by nwinter** [comment]
If we can figure out how to get those buttons to wrap onto two lines, that'll be cool; it might be a bit tricky with the CSS, though. One solution would be to 1) reduce the font size a bit for "ru" and 2) make an alternate translations that wasn't so long.

**Comment by nixel2007** [comment]
2) I think, it's really hard to make them smaller. Also, I really don't think that current variant of translation is long - it's 5 or 6 letters longer than en-variant

**Comment by rishiloyola** [comment]
i think so if we break this sentence in two part , and slightly reduce fond along with increase height of button . then it will fit . let me try this idea . i will upload a pic after testing  it locally .

**Comment by rishiloyola** [comment]
I changed the button height but can anyone help me about how can i separate this sentence into two line .

**Comment by divyanshu013** [comment]
This issue is solved, probably due to an updated translation.
![solved](https://cloud.githubusercontent.com/assets/6682655/6432733/1a51788e-c082-11e4-8a5c-7e27fc744b45.png)
