### ISSUE TITLE
Unlock hero button text too long in Russian

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#1918]
I've just completed the Arcane Ally level and gained access to Miss Hushbaum (the first magic char). But when i choose a Touch of the Death level (next to Arcane Ally) and clicked on this hero, i have only the restricted_title on big button and no possibility to buy/unlock it. Reloading the page helps.
No screenshot =/

**Comment by nwinter** [comment]
I think I've found the bug with Hushbaum not showing up right away; the achievement unlocking her was ill-configured.

**Comment by nwinter** [comment]
Here's an example of how to reduce per-language font sizes when text doesn't fit:

https://github.com/codecombat/codecombat/blob/master/app/styles/home.sass#L86-L89

We could do this here for French, or for all non-English languages to be safer, or we could come up with a better way of finding the right font size for a given button and text string.

**Comment by nixel2007** [comment]
I think splitting to word and price could help for most cases for this button

**Comment by nixel2007** [comment]
No splitting to 2 words, I guess :)

**Comment by divyanshu013** [comment]
@nixel2007 I thought it would look better this way :smiley:

**Comment by nixel2007** [comment]
Ehm... Guys...
Select hero
![2](https://cloud.githubusercontent.com/assets/1132840/6388872/6a042d8e-bdaf-11e4-8ca7-6e63e5440e53.PNG)

Unlock hero
![default](https://cloud.githubusercontent.com/assets/1132840/6388868/60c74878-bdaf-11e4-8141-21851d05a24e.PNG)

**Comment by nixel2007** [comment]
And i can't find "reopen" button for this issue Oo

**Comment by divyanshu013** [comment]
I'll have a look @nixel2007. Thanks for pointing out.

**Comment by nixel2007** [comment]
Closed via 01c2cfce7c5dc5e8d00103d93eaa18c7cc6e6b21
