### ISSUE TITLE
Omarn's potion throw needs work

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#1934]
I just purchased Omarn and am using him on Seige of Stonehold.  I had previously beaten the level using Amara.  In the code I was using the throw command.  Upon switching to Omarn I still have the throw command.  As in this screenshot, I am in the process of throwing a charge at an ogre, you can see the charge in the air and the list of throw as a function.

![image](https://cloud.githubusercontent.com/assets/6550021/5427501/542535ee-83da-11e4-8c27-3bb615fa22e2.png)

Here is what I have equipped:
![image](https://cloud.githubusercontent.com/assets/6550021/5427509/c646572a-83da-11e4-891d-ac900a38635d.png)

**Comment by nwinter** [comment]
It now has a weak stun effect with it, so that may scale up and be worth using even as the damage falls off against stronger foes. And it looks like a potion.
