### ISSUE TITLE
Nearest Friend in Stonehold is a Peasant

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#1935]
So I was attempting to have Omarn run to the nearest friend.  Unfortunately at the beginning of the level, apparently the peasants are the nearest friend, so I run to the peasant to start with, then continue to push that peasant off the edge of the map.  I do survive, but note my final location of x=-301.  I don't think it is a big deal that there is nothing blocking the side of the map.  My concern is why the nearest friend is a peasant when I have to run past the archers in order to get to the peasant.  Wondering if maybe the peasants spawn earlier than the archers and before the first frame is calculated.

I fixed the problem by simply telling my looking at all archers and soldiers instead of all friends.

Heading past archers to get to "nearest" friend, the peasant.
![image](https://cloud.githubusercontent.com/assets/6550021/5427654/39000778-83e2-11e4-82ae-60c66a2c996d.png)

End of the quest, hiding well off the screen since I've been pushing the peasant for a couple minutes.
![image](https://cloud.githubusercontent.com/assets/6550021/5427597/921603c8-83e0-11e4-9b9a-848833aa7add.png)

**Comment by nwinter** [comment]
Just tested this and it appears to be working now; nearest friend is one of the archers at first.
