### ISSUE TITLE
Aether erroring out when trying to play particular ladder opponents

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#1943]
See [this thread](http://discourse.codecombat.com/t/game-locked-cant-get-in/1917). Looks like Aether is trying to add globals for a language which doesn't exist. Player is playing in JS, opponent is playing in Python. I wonder if somehow the module loader is not loading the Python stuff?

**Comment by sotonin** [comment]
This is the only time this particular one has happened.
