### ISSUE TITLE
Runtime Lag

### ISSUE THREAD

**Issue by Rytrik** [codecombat/codecombat#1945]
I'm working on the CodeCombat level "The Dunes" in Python. I'm noticing that when I have my code structured in a certain way, there's runtime lag. 

If I have it set up this way, it's fine.
~~~~~~~~~~~~~~
loop:
    enemy = self.findNearestEnemy()
    item = self.findNearestItem()
    if item:
        # Collect coins.
          if item:
            pos = item.pos
            itemX = pos.x
            itemY = pos.y
            self.moveXY(itemX, itemY)    
    if enemy:
        if enemy.type is 'sand-yak' or enemy.type is 'burl':
            # Don't fight Sand Yaks or Burls! Just keep collecting coins.
            pass
        # But if the enemy is a 'thrower' or an 'ogre', fight them.
        if enemy.type is 'thrower' or enemy.type is 'ogre' and self.distanceTo(enemy) < 20:

~~~~~~~~~~~~~~~~~~~~

If I move my 'if item' near to the end of my code, with an else, then the loop appears to prioritise the 'enemy' portion of the code, and slows down on going to the 'item' part of the code. There is a significant delay, as it seems to constantly be working in the 'enemy' portion, and rarely going to the 'item' portion.

However, if I structure the code as I have it set up, above, it runs smoothly, and will prioritise the coins first, and rarely jump to the enemy (only if no coins are left). Which is fine.

Just curious as to why this might be the case :)

Thanks!

**Comment by nwinter** [comment]
I've fixed a bunch of perceived runtime lag with the plan() yielding dropped frame fix. I'm not sure this is what was causing your problem–the code is a bit strange–but I can't reproduce it now, so I assume it is fixed.
