### ISSUE TITLE
Add user info to server db error message

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1953]
We need the user ID to the error message, if available.
https://github.com/codecombat/codecombat/blob/master/server/routes/db.coffee#L45

**Comment by amankr** [comment]
I have added user ID and email of the user to the console. Do we need to display anything else ?
![ex](https://cloud.githubusercontent.com/assets/2175623/6225522/82035838-b6b1-11e4-9bd1-d8186a647f9a.jpg)

**Comment by nwinter** [comment]
That's pretty good; if you have it hooked up to show when there is an error, please submit a pull request.
