### ISSUE TITLE
Don't disable spaces for comments

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1954]
We currently disallow spaces in some beginner levels so the syntax is easier to get right.  We should still allow spaces in comments.

https://github.com/codecombat/codecombat/blob/master/app/lib/LevelOptions.coffee#L3

Original issue: https://github.com/codecombat/aether/issues/129

**Comment by nwinter** [comment]
This was implemented [here](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/SpellView.coffee#L217-L223) but may still be buggy based on feedback from [this thread](http://discourse.codecombat.com/t/kounter-kithwise-space-bar-randomly-stops-working-in-code-editor/2293). More testing / steps to repro are needed.

**Comment by AdnanZahid** [comment]
This returns 404 error: https://github.com/codecombat/codecombat/blob/master/app/lib/LevelOptions.coffee

Also, spaces are working in the code. They are not disabled. I'm new here, am I getting it wrong?

**Comment by nwinter** [comment]
Ah, right; we recently migrated the hard-coded level options to database properties editable from the campaign editor. But mainly we need to go into levels like Dungeons of Kithgard and make sure that spaces work in single-line comments but don't work in normal code, in all programming languages.

**Comment by rishiloyola** [comment]
how can i directly play these stage to test it ?

**Comment by nwinter** [comment]
That's the first level.

**Comment by rishiloyola** [comment]
ohh i checked that it is working fine .

**Comment by nwinter** [comment]
Okay; will close unless someone else sees an issue.
