### ISSUE TITLE
Add achievements for multiplayer levels

### ISSUE THREAD

**Issue by Lynxbob** [codecombat/codecombat#1957]
So on the first multiplayer level for the campaign, I get this bug where the flag is silver even though I've already beaten the level.
![codecombatbug](https://cloud.githubusercontent.com/assets/10163103/5497397/2a7cef5e-86df-11e4-83b8-0c48a78ed536.png)
This is the level.
Proof that ive beaten it:
![codecombatbug2](https://cloud.githubusercontent.com/assets/10163103/5497422/591f50fe-86df-11e4-8ecd-01f3c023a47b.png)
This bug occurred after I beat the level and played it again.

**Comment by nwinter** [comment]
This is possibly happening because the multiplayer levels don't have any achievements. After we do that, we'll check whether this is still showing as "started" instead of "complete".

**Comment by anter69** [comment]
More ideas for rewards/achievements here:
http://discourse.codecombat.com/t/rewards-for-multiplayer-levels/5324

**Comment by nwinter** [comment]
We now have a mechanism for adding achievements for these–you will get more gems/exp for a solution which defeats progressively harder levels of prepopulated AI strategies, which sidesteps a lot of the multiplayer ladder-based balancing issues. We're tracking retrofitting existing levels with achievements in another place, so will close this one.

**Comment by anter69** [comment]
I suggest that all players (no matter when they submitted their code) should be matched (at least 2-5 times) against all AI levels to have a chance for getting the achievements.

e.g. I'm in the top 20 on dueling grounds on both sides, but I don't even have the "beat the simple AI" achievement...
