### ISSUE TITLE
Achievements - Are we only processing level.sessions achievements?

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1969]
Don't show achievements for level.sessions:
https://github.com/codecombat/codecombat/blob/master/app/views/core/RootView.coffee#L39

Only POST achievements for level.sessions:
https://github.com/codecombat/codecombat/blob/master/server/achievements/earned_achievement_handler.coffee#L47

**Comment by sderickson** [comment]
Awarding these achievements (which happen via middleware) were disabled during HoC because of memory leak issues: a9265bce42a070fe77be50a92c3f4083eeafc8e8

Re-enabling started here: 9272ceb23ec839647a9806ce77ba2c016a84984a
