### ISSUE TITLE
Achievements - pollAchievements treats EarnedAchievement as Achievement

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#1970]
Server returns EarnedAchievement:
https://github.com/codecombat/codecombat/blob/master/server/users/user_handler.coffee#L316
Client treats as Achievement:
https://github.com/codecombat/codecombat/blob/master/app/models/CocoModel.coffee#L363

**Comment by sderickson** [comment]
Fixed in d69c5941b337854d9b9617ee5b473201b32257f4
