### ISSUE TITLE
Make sure spell palette popover docs aren't off the screen

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#1974]
Probably we need to adjust the popover parent element to not be the body but some shorter child so that it puts it higher up:

![docs-off-screen](https://cloud.githubusercontent.com/assets/99704/5518844/712a3e52-88ec-11e4-8136-7987d1c74639.png)

**Comment by rishiloyola** [comment]
![screenshot from 2015-01-08 22 45 28](https://cloud.githubusercontent.com/assets/10094679/5666780/25d9e72c-9788-11e4-8be6-74413e86e335.png)
i made changes and put it just beside the compiler . so that it will not go off the screen . whats your suggestion ?

**Comment by nwinter** [comment]
This is looking better! Can you submit a pull request so I can try it on some different screen sizes?

**Comment by rishiloyola** [comment]
but sometimes it looks like this. 
![screenshot from 2015-01-09 00 40 49](https://cloud.githubusercontent.com/assets/10094679/5668774/29df28ea-9798-11e4-9548-43618175f1de.png)
so what do you think about this. i think so let fix position by adding some conditions so that it will always pop over at perticular position .

**Comment by rishiloyola** [comment]
let fix position just beside the compiler . as shown in earliar screen shot.

**Comment by nosheep** [comment]
Hi,
I got the same, how to fix it ?
![2015-01-11-121509_1280x800_scrot](https://cloud.githubusercontent.com/assets/10477497/5695039/a2e48330-998b-11e4-880d-36ff6f3c2130.png)

**Comment by popey456963** [comment]
@nosheep IIRC changing your zoom level (ctrl + -/=) you can get your commands back.

**Comment by nosheep** [comment]
@popey456963 Oh, thanks, it work perfectly!

**Comment by rishiloyola** [comment]
@nwinter  what is your idea to fix specific  position  for all popover ?

**Comment by nwinter** [comment]
This is much better now with #2094. Some day we might be able to do even better, since the positioning is still a little weird due to the way Bootstrap does it.

**Comment by differentmatt** [comment]
Another instance, likely due to blue script dialog.  This happened when I hovered over the spell palette area a yellow arrow was pointing at on Defense of Plainswood.
![buildxypopupoffscreen](https://cloud.githubusercontent.com/assets/2965172/6010748/22fc18ac-aaea-11e4-9b3b-4f5195a10d66.png)

**Comment by rishiloyola** [comment]
we can do one thing , we can fix its position beside the compiler . so it will never shift from its position .

**Comment by divyanshu013** [comment]
I agree with rishiloyola. Sometimes the popovers block the view to the code. If one can see the code while studying the spell info it would be easier to relate to.

**Comment by nwinter** [comment]
The only case where it displays off screen still is when you were hovering over it during a blue script, and then the script goes away, and you don't move your mouse. (Once you move it again, it goes to the right position.) Probably not important enough to worry about.
