### ISSUE TITLE
Thornbush Level: Coffee--Syntax Error

### ISSUE THREAD

**Issue by mkassorla** [codecombat/codecombat#1975]
When playing the Thornbush level on Coffee, there is a syntax error that reads:

Syntax error on line 1, column 1: unexpected '@' (/u0040) 1: plan = () ->^
:^2:3:#Patrol the village entrances. 4: #Build a "fire-trap" when you see an ogre.

It is impossible to fix that syntax error if you are a player (as I am).

Sincerely,

Michelle

**Comment by nwinter** [comment]
Going to move this issue over to the Aether repository: https://github.com/codecombat/aether/issues/162
