### ISSUE TITLE
Some seeds allow you to win automatically on Village Guard

### ISSUE THREAD

**Issue by gsaines** [codecombat/codecombat#1986]
I just loaded village guard with no prior code and the sample code beat the level because findNearestEnemy will still detect enemies on the right side and some seeds don't manage to kill a peasant if you don't cover both sides.

This is also affected by the boots I was wearing: the Leather Boots grant +2 m/s speed, which allows my hero to move quickly enough to defend against the munchkin rush. But we can definitely expect that players could have purchased leather boots by this point in the game.

**Comment by nwinter** [comment]
Migrated to Level Editor task list.
