### ISSUE TITLE
Medical Attention - Failed when no humans die?

### ISSUE THREAD

**Issue by tjchan001** [codecombat/codecombat#1987]
Still looks like there are red health bars for everyone so I don't think it should stop and say failed.  Looking at it, the the human at the heal point looks almost knocked down..so she probably died and got healed after the fact...so I think this may be a bug.

![codecombatbugmedical](https://cloud.githubusercontent.com/assets/4033083/5544977/a271e38a-8ada-11e4-8287-417ea2a57c09.PNG)

**Comment by nwinter** [comment]
Migrated to Level Editor task list for this level.
