### ISSUE TITLE
Stuck in level "Dread Door" when using CoffeeScript

### ISSUE THREAD

**Issue by Nuke928** [codecombat/codecombat#1993]
It says the code has an infinite loop
```coffeescript
# Attack the door!
# It will take many hits, so use a loop.


loop
    @attack "Door"

```
Here a screenshot: ![Screenshot](http://puu.sh/dK7Pk/32ab7bb24c.png)

**Comment by nwinter** [comment]
We need to fix #1570, and then this will start working. Closing in favor of that issue.
