### ISSUE TITLE
Haste is always on!

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2034]
So, I just started playing with Haste and love that I can always be hasted!  In talking with @nwinter I realize that the issue is the fact that haste is affecting the passage of time toward the cooldown allowing me to haste in 5 seconds instead of 10 seconds.  If we just changed all the specific cooldowns to 15 seconds that would amount to 10 real seconds as the first 5 seconds would be hasted and count as 10 seconds, leaving another 5 seconds of cooldown after the haste has expired.

Of course, this only works if the haste is cast on self.  If haste is cast on someone else then this wouldn't be good.

I was going to change the specific cooldown in the thang, but I guess maybe it needs to be done on the code side, will see if I can figure out a way to do it there.

OK, so in action.Acts I see this line:
```
    @actionHeats[@action] = action.specificCooldown if action.specificCooldown
```
I was thinking of adding something like this:
```    
    @actionHeats[@action] = action.specificCooldown*1.5 if @getActionName() == 'haste' and @target == @
```

I'm not sure if I have the syntax correct or if it will work anyway.  The thinking is checking if the action is 'haste' and the target is self.  Would this work?

**Comment by nemoyatpeace** [comment]
So I was thinking about this a little more.  As it stands, even if haste were to have a 10 second cooldown, with the way that cooldowns are affected by haste as well, you could conceivably keep the enemy slowed for 75% of the time while you are hasted for 50% of the time:

t=0 haste on, slow on
t=5 haste off, slow recast
t=10 haste on, slow off
t=12.5 slow recast
t=15 haste off
t=17.5 slow off
t=20 repeat cycle

So the enemy is slowed for 15 out of 20 seconds.  Maybe the speed up shouldn't affect spell cooldowns at all?  Or maybe haste and slow should have the same cooldown or be on different items so you can't have both of them or...

**Comment by nwinter** [comment]
I've changed it so that any sort of haste/slow doesn't affect specificCooldowns, just general cooldowns. So you'll still attack and move faster or slower, but your spells and bashes and things will follow the regular intervals.
