### ISSUE TITLE
Typo in comment for level "Mirage Maker"

### ISSUE THREAD

**Issue by tjchan001** [codecombat/codecombat#2035]
// While your health is full, yell insults at the smaller ogres to draw their ire.

I think you meant "fire".

**Comment by nwinter** [comment]
Actually, "ire" is correct here. But I'll change it to "to provoke them" to prevent confusion. Thanks!

**Comment by tjchan001** [comment]
Looked up the word "ire".  I stand corrected.  Thanks for teaching me a new word.
