### ISSUE TITLE
canCast auto correct loses if

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2042]
When I type `if canc` I canCast is highlighted so I hit enter to activate the auto complete and it is replaced with `self.canCast('drain-life',target)`

Would be nice if it was replaced with `if self.canCast('drain-life',target)`.

**Comment by nwinter** [comment]
@differentmatt what would cause the autocomplete to replace the `if` there?

**Comment by nemoyatpeace** [comment]
By the way, if I do `if self.c` and hit the auto correct it replaces perfectly.

**Comment by nixel2007** [comment]
Neh, noticed it either at coffeescript and the 'else' keyword. I thought parser search the (), and if it can't find it, it replaces whole string. But it doesn't correlate with 'if self.c' situation.

**Comment by nemoyatpeace** [comment]
Rather than replacing whole line, would make more sense for it to replace backwards to a space.

**Comment by nixel2007** [comment]
Or (, "&", "||" and other special symbols.

**Comment by differentmatt** [comment]
Looks like a bug in our [autocomplete](https://github.com/differentmatt/zatanna).  I'll look into it.

**Comment by differentmatt** [comment]
Caused by an autocomplete insertion bug: https://github.com/differentmatt/zatanna/commit/7d659853bfdf653cad0f45f2ea1ecdec99e6eea6

Should be fixed after next production deploy.
