### ISSUE TITLE
Programmer should have access to spell damage and range without having to place them in the palette

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2052]
Working on refactoring the spells for this.  I'll keep a list as I update things.

Finished:
shockWave
confuse
drainLife
earthskin
fear
fling
force-bolt
grow
haste
heal
magicMissile
poisonCloud
raiseDead
regen
root
shrink
timewarp
windstorm

**Comment by nemoyatpeace** [comment]
These spells are not implemented yet and will be refactored when implemented:

disintegrate
dispel
fireball
flame Armor
goldstorm
invisibility
lightning bolt
summon Burl
summon Undead
swap
teleport

**Comment by Imperadeiro98** [comment]
@nemoyatpeace, you can add "- [ ]" before each spell so that they appear with a checkbox.

**Comment by nemoyatpeace** [comment]
Now working on the thangs with spells on them:
All books are complete, need to mess with these wands:

Enchanted Stick
Simple Wand
Twisted Pine Wand
Oak Wand
Mahogany Staff
Balsa Staff
Banded Redwood Wand
Oak Sphere Staff
Steel Wand
Lightning Twig
Obsidian Staff
Crystal Wand
Sulphur Staff
Golden Wand
Vine Staff

**Comment by nwinter** [comment]
Ah yeah, those wands/staffs don't exist yet. Now that the Thangs are done, the next step is to go back to all the Components:

1. Add the new names to the top-level `default` object with the default values.
2. Delete the old names from the config schema `default` and `properties`.
3. Delete the old name handling from the spell initialization in the code.
4. Submit a patch.

Then when all those are ready, I'll merge them all and I'll do the last step, which is to delete the now-unrecognized properties from all the item Thangs.

**Comment by nemoyatpeace** [comment]
OK, so refactoring components again here is my todo list:

x confuse
x drainLife
x earthskin
x fear
x fling
x force-bolt
x grow
x haste
x heal
x magicMissile
x poisonCloud
x raiseDead
x regen
x root
x shockWave
x shrink
x timewarp
x windstorm

Complete, ready for you now nick

**Comment by nwinter** [comment]
Phew, done! (Time will tell if we missed any.) Nice work as always, @nemoyatpeace!
