### ISSUE TITLE
Google is deprecating OpenID 2.0 in favor of G+/OAuth 2.0/OpenID Connect

### ISSUE THREAD

**Issue by schmatz** [codecombat/codecombat#2067]
A user recently reported when signing up they saw a warning about this and were directed to [this link](https://developers.google.com/accounts/docs/OpenID#shutdown-timetable). 

Sometime before February we should get this fixed (when auto-approval is turned off.) Luckily, we can keep using the login data we already have, but just have to change our Google sign-in process slightly.

**Comment by nwinter** [comment]
@sderickson can you take a look at this one?

**Comment by sderickson** [comment]
@nwinter Yep

**Comment by nwinter** [comment]
Also need this for Discourse: https://meta.discourse.org/t/configuring-google-oauth2-login-for-discourse/15858

**Comment by sderickson** [comment]
I believe it was mainly complaining about how we were loading emails. If there are more complaints, reopen, because I wasn't able to reproduce this bug exactly.
