### ISSUE TITLE
Not Found page renders twice, looks bad

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2068]
I think that the "Not Found" page is bad formated.
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/5653645/096ae5ca-96b4-11e4-9284-d6c3c0b57b0e.png)
In the first place it is not translated.
Second, the upper menu looks weird.

**Comment by Imperadeiro98** [comment]
Now it is kind of fixed, but doesn't look good. It opens up the page described above, and then updates it with i18n and, sometimes, switches the image.

**Comment by tahmidshahriar** [comment]
I was able to fix this but am not sure if this is how you want it. I found that this works fine if you take the "not found" page out of core and go to it similar to how you go to any other page (such as legal or admin). 

I am not sure why showNotFoundView and notFoundView functions are being used and NotFoundView being put in core, but I was wondering if they are important and if it will cause a problem if they are removed (like being used somewhere else other than the router or something or have causes some other problem)?

Changes I made:
https://github.com/codecombat/codecombat/compare/master...tahmidshahriar:master

Would love it if you can take a look! :)
