### ISSUE TITLE
Cannot read property 'formals' of null with self-defined Python functions

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2073]
From [this thread](http://discourse.codecombat.com/t/cannot-read-property-formals-of-null/2243):

```python
loop:
    enemies = self.findEnemies()
    enemy = self.findNearest(enemies)
    if is_soldier(enemy):
        # Assess the threat and take appropriate action
```

> The if line is giving the error Cannot read property 'formals' of null when is_soldier(enemy) is evaluated and enemy is None (or null to be precise).

> I'm performing the null check inside is_soldier() but it's never reached because the program crashes before reaching the check.

> FWIW, here is my definition of is_soldier(). It shouldn't matter how it's defined since I believe passing null as an argument is causing the error.

```python
def is_soldier(enemy):
    if enemy and not is_sandyak(enemy):
        return True
    return False
```

@differentmatt I'm sure we have some issues for Python function definitions somewhere, but I don't think I'd seen this one before. Know what's up?

**Comment by differentmatt** [comment]
This looks like a bug in the function parameter processing code.  I fixed a different error I got with this sample code, but was unable to get the same null formals error.
https://github.com/differentmatt/filbert/commit/e1d22465c6bbaf2273e397d9c7138560c129dc94

@dideler Can you past your full code example here?

**Comment by dideler** [comment]
@differentmatt here's the full code.

```python
# Stay alive for two minutes.
# If you win, it gets harder (and more rewarding).
# If you lose, you must wait a day before you can resubmit.
# Remember, each submission gets a new random seed.
loop:
    enemies = self.findEnemies()
    enemy = self.findNearest(enemies)
    if is_soldier(enemy):
        if self.distanceTo(enemy) > 10:
            self.moveXY(46, 78)  # Move to safety
        if not heavy_attack(enemy):
            self.attack(enemy)
    else:
        self.moveXY(46, 78)  # Move to safety
 
def heavy_attack(enemy):
    if self.isReady("cleave") and self.distanceTo(enemy) <= 10:
        self.cleave(enemy)
        return True
    return False
 
def is_soldier(enemy):
    if enemy and not is_sandyak(enemy):
        return True
    return False
    
def is_munchkin(enemy):
    return enemy.type == "munchkin"

def is_scout(enemy):
    return enemy.type == "scout"

def is_ogre(enemy):
    return enemy.type == "ogre"

def is_sandyak(enemy):
    return enemy.type == "sand-yak"
```

**Comment by differentmatt** [comment]
Invalid Python.  You need to define your functions before using them.

I've opened a separate Python parser issue to throw a more reasonable error.

**Comment by dideler** [comment]
Good catch, but I think that's a different issue. Unlike in Python, defining your functions before using them does work in filbert (I've been doing it in a couple of levels so far). So this error might be caused by something else?

For example, if I define `talk()` at the end and call it as the first statement, then the code runs fine and the first thing my character does is say "yo" before getting stuck at `is_soldier(enemy)`.
```python
talk()

loop:
    ...

...

def talk():
    self.say("yo")
```

**Comment by differentmatt** [comment]
You can do it in most cases because we're running JavaScript under the hood.  But, the correct solution is not to make this invalid Python work in all cases.

See https://github.com/differentmatt/filbert/issues/55 for more details.
