### ISSUE TITLE
Io -> Lua. Lang change not working, buggy and Inconsistent

### ISSUE THREAD

**Issue by AtomicCreeper** [codecombat/codecombat#2077]
I cannot figure this out. 
I cannot change from Io to Lua.
Io by the way is not working.

It's inconsistent no matter what I do.
    It's also pretty hard to explain.
    Io wasn't changing back to Lua even after browser and code reload
    So I'm confused to as what to do

**Comment by arghyapolley** [comment]
write your full code

**Comment by nwinter** [comment]
Not supporting Io any more.
