### ISSUE TITLE
Dedicated Simulation Software

### ISSUE THREAD

**Issue by Popey456963** [codecombat/codecombat#2078]
Is there a piece of software (that is not in the web-browser), that I can run in order to simulate the matches?
Similar to [this](http://codecombat.com/play/ladder/cavern-survival#simulate).

**Comment by nwinter** [comment]
Yes: https://github.com/codecombat/codecombat/blob/master/headless_client.coffee

But last I remember, it was giving a small number of worrisome ties, so we need to sit down and debug it very carefully to make sure it's giving the same results as the browser simulator before we start firing it up. (Higher priority is to figure out the other simulation bugs like #1830 and #1892.)

**Comment by nwinter** [comment]
The headless client should be working again now.
