### ISSUE TITLE
API protection issue: enemy.health not updating

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2079]
From [the forum](http://discourse.codecombat.com/t/possible-bug-on-sarven-brawl/2239). For code like this on Sarven Brawl:

```python
loop:
    drop = self.findNearest(self.findItems())
    enemy = self.findNearest(self.findEnemies())

    if enemy:
        while enemy.health > 0:        
            self.say(enemy.health)        
            self.say(enemy.type)
            self.attack(enemy)
    else:
        self.moveXY(drop.pos.x, drop.pos.y)
```

Or code like this on Backwoods Brawl:

```python
loop:
    enemies = self.findEnemies()
    numEnemies = len(enemies)
    if numEnemies != 0:
        enemy = self.findNearest(enemies)
        while enemy.health > 0:
            if self.isReady("cleave"):
                self.cleave(enemy)
            elif self.isReady("bash"):
                self.bash(enemy)
            else:
                self.attack(enemy)
```

We get infinite loops on the `while enemy.health > 0` part. Weird, because this pattern appears to work in Sarven Shepherd, where we introduce it. My first guess is that the `enemy` variable is not being updated from its API clone.

Working code pattern in Sarven Shepherd:

```python
loop:
    enemies = self.findEnemies()
    enemyIndex = 0
    while enemyIndex < len(enemies):
        enemy = enemies[enemyIndex]
        if enemy.type != 'sand-yak':
            while enemy.health > 0:
                self.attack(enemy)
        enemyIndex += 1
```

**Comment by cristoslc** [comment]
Having the same issue in Keeping Time (desert level) with the following code:
```
e = self.findNearest(self.findEnemies())
while e.health > 0:
    self.attack(e)
```
In fact, this seems to be happening in just about ANY level where I use `while` in Python. This is seriously degrading the experience coding in Python (which I joined CodeCombat to learn). In fact, I spent over an hour trying to figure out if I was missing some kind of loop terminator.

Original forum report: http://discourse.codecombat.com/t/python-while-loop-runs-infinitely/2407

![000f82d8e3_690x375](https://cloud.githubusercontent.com/assets/1724064/5839964/2a86e306-a160-11e4-9ccf-32b4f60d7282.png)

**Comment by cristoslc** [comment]
Interestingly, the following code (including a `while` loop) appeared to work fine in [Preferential Treatment] (http://codecombat.com/play/level/preferential-treatment )

```
self.say("Imma count to 3, then BAM!")
while self.now() < 2:
    self.say(self.now())

e = self.findNearest(self.findEnemies())
self.cleave(e)
# First, loop through all enemies...
enemies = self.findEnemies()
throwers = []
for e in enemies:
    if e.type == "thrower":
        throwers.append(e)
# ... but only attack 'thrower' type enemies.
# And don't forget to use your special abilities!
for t in throwers:
    while t.health > 0: #   <=== Here's the working 'while' loop
        self.attack(t)
# Then loop through all the enemies again...
enemies = self.findEnemies()
enemyIndex = 0
# ... and take out everyone who's still standing.
for e in enemies:
    if self.isReady("cleave"): self.cleave(e)
    self.attack(e)
```

**Comment by nickhill** [comment]
I think you are on the right track with the enemy variable not being updated.
I have identical results with 

while enemy.health > 0:  

as with using
 
loop:
  if (enemy.health <= 0 ):

i.e. enemy.health == enemy.maxHealth and does not change
    break

**Comment by differentmatt** [comment]
Fixed by https://github.com/codecombat/aether/commit/687abedc45697a8354614b4f1a1db3dd6657aaf0

Wasn't an API protection issue after all.  We were corrupting Python objects returned from API calls, which is why `enemy = enemies[enemyIndex]` worked but `enemy = self.findNearest(enemies)` didn't.
