### ISSUE TITLE
Campaign editor login doesn't work

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2082]
From [this comment](https://github.com/codecombat/codecombat/pull/2066#issuecomment-69360578). If you log in from the campaign editor, the [JS that handles the login form submit](https://github.com/codecombat/codecombat/blob/master/app/views/core/AuthModal.coffee#L18-L18) doesn't fire for some reason, so it actually submits the form (which doesn't do anything except reload the page and happily put your credentials in the URL).

**Comment by jieunko** [comment]
under codecombat/editor
we have just 3 editor THANG, Level, Article editor..
What is that campaign???

**Comment by popey456963** [comment]
Maybe the campaign isn't an editor?

**Comment by GeetikaBatra** [comment]
@popey, If you login from a form apart from the main page example  http://codecombat.com/editor/campaign/forest .Login on this page,have a closer look on the URL,your Id and password will be concatenated.

**Comment by popey456963** [comment]
@GeetikaBatra Ah, I understand that part!  I don't understand @jieunko 's question.

**Comment by jieunko** [comment]
Oh I meant that there's no description about http://codecombat.com/editor/campaign
in http://codecombat.com/editor page 
so I was wondering what that campaign page's about?

**Comment by nwinter** [comment]
It's a new editor that only admins really use right now, so we haven't documented it anywhere. It's how we lay the levels out in order and adjust the pacing and stuff like that.

**Comment by katemamba** [comment]
Okay so i figured out the cause, the problem seems to be resolved if a certain delay is added in accessing the file auth.jade(/app/templates/core/), this file is loaded instantly, even before the post method is called, hence leading to fetch url in next window along with params.
So a simple solution is to add delay at start in fetching file, correct me if i am in wrong direction @nwinter [For a sample test to this add a manual delay to auth.jade]

**Comment by AnirudhGP** [comment]
Hi this is my first bug here! I have built the dev environment. Can i fix this ?

**Comment by nwinter** [comment]
I think @divyanshu013 was working on it, although I might be misremembering. He had gotten pretty close, possibly something with two AuthModals being opened because the parent CampaignEditorView and the child CampaignView, both being RootViews, were both listening to the login button click event.

**Comment by divyanshu013** [comment]
@amankr I added the overiding method for signup clicks. Its working great now :+1:
