### ISSUE TITLE
startTime issue in Waves

### ISSUE THREAD

**Issue by stephenstgo** [codecombat/codecombat#2086]
I am having an issue trying to set a startTime for Waves where no matter what value you put for startTime, if it is active and present, the level will not load and cause an error page to come up. As soon as startTime is gone then the level will load.

**Comment by nwinter** [comment]
Can you check the JS console to see if it's spitting out any error messages about not being able to spawn the wave, maybe due to a misconfigured wave or not matching the Builds/Spawns dependent ThangTypes?

**Comment by stephenstgo** [comment]
Yeah I fixed it. That's exactly what it was. Thanks for the message back
tho, appreciate it.

Can you check the JS console to see if it's spitting out any error messages
about not being able to spawn the wave, maybe due to a misconfigured wave
or not matching the Builds/Spawns dependent ThangTypes?

—
Reply to this email directly or view it on GitHub
<https://github.com/codecombat/codecombat/issues/2086#issuecomment-69522695>
.
