### ISSUE TITLE
codecombat占系统系统内存大

### ISSUE THREAD

**Issue by jequal** [codecombat/codecombat#2088]
1.国内打开codecombat网站非常慢，登录游戏后进入关卡载入游戏后，占用系统内存很大，如图所示：
![image](https://cloud.githubusercontent.com/assets/8425946/5701000/cddd3a28-9a80-11e4-8f2f-ccad973f0fa2.png)

**Comment by nwinter** [comment]
600-700MB 系统内存都是需要的，不能减少。

对国内网站慢性来说：由于GFW的问题，我们需要把服务器放在中国才行，可是现在没时间。
