### ISSUE TITLE
Running Ubuntu Installer

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#2093]
NPM installs incorrectly, I get the following error message:

http://pastebin.com/Y3yvKjPu

**Comment by schmatz** [comment]
Please post the relevant contents of `/home/alexander/coco/npm-debug.log`.

**Comment by popey456963** [comment]
Okay, turns out uploading something so large is rather a problem, I am not a pro user on pastebin and finding a suitable host has been hard.  [Here](http://sebsauvage.net/paste/?d109c60ffdc6066e#WP5r/UEbb3HP6/4zU5fBUEpPn/hHvVKfQ/K2TQsn8IY=) is a link to the npm-debug.log.  Loading times for the page are quite long.

**Comment by schmatz** [comment]
Hmm.... what version of Ubuntu are you running, and do you have g++/make installed?

**Comment by popey456963** [comment]
I'm using VMWare, running a 64 bit Ubuntu 14.04.1 LTS.  I have neither make or g++ installed, are these required?

**Comment by schmatz** [comment]
Yes they are; I believe build-essential should have been installed as part of the setup process; did you run the scripts? I think if you install those, it should work.

**Comment by popey456963** [comment]
I shall install g++ and make, (100mb!) and then run the program again.

**Comment by popey456963** [comment]
http://i.imgur.com/QDVY400.png - MongoDB dosen't seem to be playing ball.

**Comment by schmatz** [comment]
The dev setup scripts are in the scripts folder I believe. Also, you need to import the public database dump, which you can do by:
1. Downloading the dump [here](http://54.91.159.37/dump.tar.gz)
2. Untarring it
3. While your mongo is running, run the "mongorestore" command in the directory where the untarred folder is (the dump folder must be in the directory where you run the command.)

Then, you should have the levels.

**Comment by popey456963** [comment]
Turns out that although I had already dumped the database, I believe the coffee file compiler had crashed, simply restarting that fixed the problem.

**Comment by rishiloyola** [comment]
the same problem was also with me , ..and i also have ubuntu 14.04 lts,but i done  the following things and that worked . 
as mentioned here : https://www.youtube.com/watch?v=usN85KSiWUM&feature=youtu.be
then sync it  and.
downloaded data base dump.

**Comment by schmatz** [comment]
Hi @rishiloyola, which problem did you also have? The node-gyp one, or the coffeescript compiler crash?

**Comment by rishiloyola** [comment]
i think so node-gyp, but some how i fixed it . right now i did not have screen shot otherwise i will post it .

**Comment by schmatz** [comment]
Build-essential was added for Ubuntu a few days ago, so this might have been resolved. Reopen if that's not the case.

**Comment by arghyapolley** [comment]
Why you are trying it in ubuntu? can use windows
