### ISSUE TITLE
Certain Aether warning messages show up before constructs explained in-game

### ISSUE THREAD

**Issue by schmatz** [codecombat/codecombat#2098]
I recently had a user comment that they were shown an error message on Cavern Survival to the effect of "You should check if there is an enemy (from a call to findNearestEnemy) with an if to make sure there is someone to attack". However, this user hadn't covered the if statement, and as a result, couldn't interpret the error message. 

Is there a method of preventing certain warning messages based on campaign progress?

**Comment by nwinter** [comment]
We should probably just move the Cavern Survival unlock until after the if-statements are introduced.
