### ISSUE TITLE
User not aware of what submitting is in Cavern Survival

### ISSUE THREAD

**Issue by schmatz** [codecombat/codecombat#2099]
The user didn't know what submission meant in Cavern Survival. Is there information about this displayed to the user before they enter multiplayer levels? If so, can we make it more prominent?

**Comment by nwinter** [comment]
And if we moved Cavern Survival until after the real-time playback submit button is introduced, that would help out here. I'll just make some tasks in Cavern Survival level itself to do this and #2098.
