### ISSUE TITLE
The Gauntlet: Under 6 Statements Issues

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#2104]
http://i.imgur.com/CdRfp4N.png
4/5 lines long, bonus not working.
http://i.imgur.com/Qg1Rbw1.png

**Comment by nwinter** [comment]
This is 6:

1. `loop`
2. `self.moveRight()`
3. `self.findNearestEnemy()`
4. `self.attack(...)`
5. `self.findNearestEnemy()`
6. `self.attack(...)`

**Comment by popey456963** [comment]
Fixed, thanks.

**Comment by rcardenes** [comment]
There seems to be a regression for this bug. I've played The Gauntlet right now and with this code:

    loop:
        self.moveRight()
        enemy = self.findNearestEnemy()
        while enemy.health > 0:
            self.attack(enemy)

I don't get the < 6 bonus

**Comment by nwinter** [comment]
That's 'cause the `enemy.health`, `0`, and `>` are all statements, too. I know, I know, statement counter is bad; we will work on it with the next version of our transpiler, which should make things much easier to count intuitively.
