### ISSUE TITLE
Getting current stage for repeatable levels

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2107]
I know there is a command that I can go to the console to see the current stage I'm running, but it would be awesome if somewhere on the screen it showed what stage you were on for the level.  Maybe as a part of this:
![image](https://cloud.githubusercontent.com/assets/6550021/5770889/cf79a926-9d6d-11e4-8a24-c081c4ed614f.png)
Could add a number after it:
`Backwoods Treasure (6)`

**Comment by nwinter** [comment]
Oh right, I totally built this, just like you said, a few days ago.

**Comment by nemoyatpeace** [comment]
Looks awesome.

Would also be cool if there was a way to replay lower difficulties, for example to test different strategies or heroes or to learn other languages.  Or maybe just to finally have success after constant failure!

**Comment by nwinter** [comment]
Would you expect to keep the gems from your highest-achieved difficulty or to earn gems again for the lower ones?

**Comment by nemoyatpeace** [comment]
I would assume just keeping the gems from the highest level reached.  Basically would be cool to have the ability to swap between the different difficulties for testing tactics, not meant to earn extra gems.  Ideally submitting and failing a previous level would not set the 24 hour clock, only when submitting the highest level reached.

Of course, I do think it would be cool to get a few extra gems for repeating any level in a second language, maybe earn 10% of level gems for each new level that it is done in.  I know we aren't ready for this one yet.

**Comment by popey456963** [comment]
@nemoyatpeace I think 10% of gems would be a good value.  It would be nice if you could get best armour + weapons without subscribing.  Pay 2 win is such a saddening business model.

Obviously I do realise that there is a reason pay 2 win is so popular.

Note - English spelling used.
