### ISSUE TITLE
Lost rewards on repeatable levels

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2108]
I mentioned this in hipchat, but often when I beat a repeatable level it locks up on "Saving Progress".  The difficulty gets bumped up, but the rewards are not granted.  Is it possible to shift the code for increasing difficulty til after the gems are granted?

Is there a way to recalculate how many gems we should have earned and update how many gems earned?

**Comment by szocske42** [comment]
Me too! For people paying for gems, this is costing them real money...
I also suspect the difficulty is bumped even if you lose the level, I've been unsuccessful at the desert brawl for days now, and today a flying dragon swooped :-)

I've got a screenshot of a lockup, and this was on the console afterwards:

|Thanatos's Lana| cosmicBackgroundMunchkinRadiation used power 27 of 30 spawning ogre-munchkin-m at 14.300980577245355
Angel.coffee:47 |Thanatos's Lana| cosmicBackgroundMunchkinRadiation used power 28 of 30 spawning ogre-munchkin-m at 47.22371340962127
Angel.coffee:47 |Thanatos's Lana| cosmicBackgroundMunchkinRadiation used power 29 of 30 spawning ogre-munchkin-f at 19.526212620548904
Angel.coffee:47 |Thanatos's Lana| cosmicBackgroundMunchkinRadiation used power 30 of 30 spawning ogre-munchkin-f at 52.89002433186397
Angel.coffee:47 |Thanatos's Lana| And it was so: (69.774ms per frame, 900 frames)
Simulation   : 62797ms 
Serialization: 19ms
Delivery     : 69ms
world.coffee:546 First changed frame is 1 with hash 1974568708.639473 compared to 3005833486.780201
1222 console messages are not shown.

![image](https://cloud.githubusercontent.com/assets/8174856/5787006/cd1681a4-9dbd-11e4-8f20-ba907bb8b9bf.png)

$ uname -a
Linux ThinkPad 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ aptitude show google-chrome-beta
Package: google-chrome-beta              
New: yes
State: installed
Automatically installed: no
Version: 40.0.2214.69-1
Priority: optional
Section: web
Maintainer: Chrome Linux Team <chromium-dev@chromium.org>
Architecture: amd64
Uncompressed Size: 188 M

But the same thing happened on a 64bit Windows 7 with a fairly old chrome stable a few days ago too, so it probably does not matter.

**Comment by nwinter** [comment]
More bug reports of this [on the forum](http://discourse.codecombat.com/t/backwoods-brawl-locked-up-after-level-completion/2359/6).

**Comment by nwinter** [comment]
I'm having a really hard time reproducing this bug.

**Comment by nemoyatpeace** [comment]
Not sure how to replicate either.  Is there a way you can look at an account and see if it has the correct number of gems for the levels beaten and items purchased?

**Comment by nwinter** [comment]
If the achievement showed up gray instead of counting up when you see the victory screen, it probably didn't fire. It will correctly give you all the gems if you beat it on the next difficulty and it works, though. But if it never fires for you on a particular level, you haven't gotten your gems yet.

**Comment by nemoyatpeace** [comment]
Like it will give the gems for the current difficulty as well as the previous difficulty that weren't awarded?

**Comment by nwinter** [comment]
Right. The achievements are set up to say, oh look, you beat it on difficulty 4, and last time we gave you gems for this achievement, it was for difficulty 2, so now you need additional gems for 3 and 4. Or if you beat it on difficulty 3 and it had never been awarded, it'll give you 1, 2, and 3.

**Comment by nemoyatpeace** [comment]
So the only people that are out gems are those people that haven't been able to beat it again after it locked up.  That is good.

Now I just need to beat Sarven Brawl 2!

**Comment by nwinter** [comment]
Has anyone been seeing this bug lately on any of the replayabls, like Sarven Treasure, Sarven Siege, Kithgard Brawl, etc.?

**Comment by nemoyatpeace** [comment]
I haven't seen it for a while, not since the first couple repeatables came out.
