### ISSUE TITLE
Leaderboard <bad match data>

### ISSUE THREAD

**Issue by chess9876543210** [codecombat/codecombat#2109]
![image](https://cloud.githubusercontent.com/assets/8473563/5776630/ba176d4e-9d8a-11e4-992e-c9995b246006.png)
i just uploaded a code and this appeared as 2nd new entry
ps: multiplayer treasure grove

**Comment by popey456963** [comment]
This happens to me quite often, for me it is fixed by simply refreshing the page.

**Comment by sotonin** [comment]
I get bad match data pretty often. no clue who it is though (mine or somebody else)

**Comment by TheYuriLin** [comment]
C++ logic

**Comment by popey456963** [comment]
Is there a way to get this to work retroactively?
