### ISSUE TITLE
Level sessions saved with incorrect date format

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2123]
Should be a date object instead of a string:
https://github.com/codecombat/codecombat/blob/master/app/schemas/models/level_session.coffee#L52

Example problematic levels: thumb-biter, gems-or-death

**Comment by nwinter** [comment]
Did we change anything with this in the past few weeks? I think this is busting a few other things. @sderickson happen to know what's up?

**Comment by differentmatt** [comment]
@sderickson Did you intend to start saving level session 'changed' as an ISO string here? https://github.com/codecombat/codecombat/commit/d8e89f31b1e87a665d7ff8ccb24240ce8ee7c49b

This change also has a comment about converting all Date and objects and timestamps to ISO strings.  Is there a work item somewhere tracking that?

This is breaking things like analytics queries, so I'm going to change it back unless I hear otherwise.
