### ISSUE TITLE
Long player names overflow poorly on user dropdown

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2125]
From [the forum](http://discourse.codecombat.com/t/adding-a-tool-to-search-for-specific-tasks-in-level-editor/2367):

> when the profile name is pretty big,the name is being shown over "profile".

![aaahhh](https://cloud.githubusercontent.com/assets/99704/5831547/983f77e0-a0e9-11e4-96a8-d3e6dd4fedb5.png)

Probably just need some CSS to truncate that text to one line.

**Comment by katemamba** [comment]
Do we need to truncate the name to one line, or adjust the background so as to clearly classify name from options
![screenshot from 2015-01-21 14-08-08 cropped](https://cloud.githubusercontent.com/assets/7155772/5833364/b50e4768-a178-11e4-84ad-163a4885da48.png)
![screenshot from 2015-01-21 14-08-45 cropped](https://cloud.githubusercontent.com/assets/7155772/5833365/b62d2632-a178-11e4-9a1c-cd1da64a21e3.png)
 picture1 will be a nice option, but i am not sure as to truncating the name to one line will be the same or not

**Comment by nwinter** [comment]
Oh yeah, we could just make it taller, duh. That would be good.

**Comment by navya-nizamkari** [comment]
If the name scrolls on mouseover,would it be a usability problem?

**Comment by nwinter** [comment]
Scrolls on mouseover? Not sure what that would look like; I'd have to see it.
