### ISSUE TITLE
Cavern Survival Endlessly trying to attack door

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2127]
In cavern survival it seems that things have changed so that you are no longer able to pass between the rooms, if you try you are teleported back to the middle of your room.  Unfortunately, you can still try to attack the doors.  If you attack the door closest to you, then try to attack the other door, you are teleported to the middle of your room, only to run back toward the door attempting to attack it again, this loop continues until someone dies.  Would be good if either you can't attack the doors, or if when you teleport to the middle your action is reset to idle.  

As it is if someone has the basic attack nearest enemy strategy, they will attack their door first, then most likely the other door will be the closest thing, so they will attempt to attack it, entering into the endless loop of running to it.

**Comment by nwinter** [comment]
How about now? Looks like I messed up the geometry on the mid rect when coding my out-of-bounds checker, but someone submitted a patch for me, which I just accepted.

**Comment by popey456963** [comment]
Should this be closed now?
