### ISSUE TITLE
Match results in multiplayer are not always attributed to the correct game

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2134]
After some investigation of why I was losing matches that looked like clear wins I think I know what is going on. For my user (Africanized Swallow)

[This match](https://codecombat.com/play/level/multiplayer-treasure-grove?team=ogres&opponent=54884b90e6b7cda906c7561d) is reported as a loss but is a clear win, but [another match](https://codecombat.com/play/level/multiplayer-treasure-grove?team=ogres&opponent=547baad303f4e24905a9aa1e) that ran at more or less exactly the same time is reported as a win but is a clear loss.

How significant this is depends on which opponents score is being used to update the player's score.

**Comment by nemoyatpeace** [comment]
I thought maybe I'd come across a similar thing here:
![image](https://cloud.githubusercontent.com/assets/6550021/5956476/42561724-a7e9-11e4-981b-9a6dc3fc934b.png)

But I checked all the other matches that are at the same time as this match and all came out as wins.  The two matches that are losses the other player had a red X the whole match until he died.

I've also noticed that occasionally a match is listed twice in a row.  This only seems to happen when it is a loss.  Thus this error is magnified.  These are currently my only losses in the last 200 matches.  Earlier it was a different pair of losses that when I looked at them they came back as wins.

**Comment by nwinter** [comment]
I've double-checked the code for any sort of mistakes that could lead to simultaneous-simulation-time mixups like this (we used to have some, so you would have just found the last big simulation inconsistency problem), but I think this kind of error is now pretty unlikely compared to problems with random seeds and flag histories and possibly bad simulator clients, which are the things I'm working on in #1830. Let's keep track of further inconsistencies after my latest round of fixes in that issue.
