### ISSUE TITLE
Spritesheet size errors when adding AoE marks

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2143]
Kevin's working on the [Sacred Statue level](http://codecombat.com/play/level/sacred-statue), but it is trying to add AoE marks to show the statue's healing circle radius. When trying to add this AoE effect:

```aoe-["90.67",75,"30.00","rgba(171, 171, 171, 0.1)"]```

the LayerAdapter gives this error from the `addCustomGraphic` method:

`Uncaught frame dimensions exceed max spritesheet dimensions`

It shouldn't be that big, though; we do AoE marks that big in other places, like the CastsWindstorm Component. @sderickson know what's going on with the ground layer spritesheet size there?

**Comment by sotonin** [comment]
I think we can maybe close this. I got the aura working on the statue aura. turns out i didnt need that big at all. around 17 was enough. it must have been trying to go past the amount of floor tiles i had on the level.

**Comment by sderickson** [comment]
The first and third arguments are strings when they should be numbers. Might that be causing the issue?

**Comment by sotonin** [comment]
Naw. looks like nick just posted them as strings. They were numbers in mine. But regardless. i think this one is invalid now. I think i was just making it too large for the place i was trying to put it.
