### ISSUE TITLE
Random Number on Page Not Found

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#2144]
[Here](https://github.com/codecombat/codecombat/blob/04e06242686a8cafcf6382a5e024aa64c70874a3/app/templates/core/not-found.jade#L7) a random number between one and three (possibly) is generated.  What does this do, and is it necessary?
`- var num = Math.floor(Math.random() * 3) + 1;`

**Comment by nwinter** [comment]
It's used [in the next line](https://github.com/codecombat/codecombat/blob/04e06242686a8cafcf6382a5e024aa64c70874a3/app/templates/core/not-found.jade#L9) to pick one of three random not-found images.
