### ISSUE TITLE
Control+p cause the print dialog to open (IE11)

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2146]
On IE11, pressing ctrl+p to pause the script opens the print dialog.  
Looking at some SO Q&A it looks like this chord may not be trappable on newer versions of IE.

**Comment by divyanshu013** [comment]
I couldn't find a way to disable Ctrl + P for IE, it doesn't allow to override default settings. What we can do is to disable the Ctrl key entirely but that's not what we're looking for: http://stackoverflow.com/questions/1130353/disable-internet-explorer-shortcut-keys

**Comment by nwinter** [comment]
Agree, I don't think we can fix this, unfortunately.
