### ISSUE TITLE
video tutorial not loading when connected over https

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2147]
The video tutorial on the help screen of level one is not loading when connected over https. the error in the JS console is
```
Mixed Content: The page at 'https://codecombat.com/play/level/dungeons-of-kithgard' was loaded over HTTPS, but requested an insecure resource 'http://player.vimeo.com/video/114729724?api=1&badge=0&byline=0&portrait=0&title=0'. This request has been blocked; the content must be served over HTTPS.
```
Confirmed in windows chrome and IE11

**Comment by differentmatt** [comment]
Is this still a problem?

This change forces all videos to load over https: https://github.com/codecombat/codecombat/commit/92f070eccaae62dce2ac597e452933e83dd75247

**Comment by yaur** [comment]
No.  Tested in IE and chrome.

**Comment by differentmatt** [comment]
Great, thanks for checking!
