### ISSUE TITLE
Full screen doesn't work in IE11

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2152]
When switching to full screen mode in IE11 I get a black screen instead of full screen. This is with an i7-4700HQ that is otherwise idle so is not a CPU issue.
No obvious problems in JS console.

**Comment by divyanshu013** [comment]
It's working fine with me on IE.

**Comment by differentmatt** [comment]
Works on IE11 Win7.

If this is still problem, please include the platform and a screenshot.  Thanks!
