### ISSUE TITLE
Fixed aspect ratio play interface doesn't work well on tall, narrow screens

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2153]
On my machine the contact div takes up the bottom 165 pixels which translates into 15-20% of the total vertical space. Given that there are already issues with how little code is visible in the code editor, this div should either be much smaller. Ideally I would like to be able to dismiss it completely.

**Comment by popey456963** [comment]
Could you provide us with an image?

**Comment by yaur** [comment]
http://i.imgur.com/27AnZGV.png

**Comment by nwinter** [comment]
Ah, the problem isn't that the contact div is taking space, it's just that the interface is at a fixed aspect ratio and can't scale to fill the height (just the width), so there's nothing else going on down there at the bottom. I have some art I want to put in there, but it would be quite a trick to get a fully vertically and horizontally scaling interface.

**Comment by nwinter** [comment]
Let's discuss this in #1777.
