### ISSUE TITLE
Forest background image doesn't load in IE11

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2154]
After completing dungeon and switching to the forest the background image does not load.  You get a blue screen with the normal widgets.  Happens with both HTTP and HTTPS.  Reloading the page fixes this, but deleting the cache and switching via the in game UI consistently causes this issue.
```

**Comment by differentmatt** [comment]
Is this still a problem?
Can you include the OS version and a screenshot?

I didn't see any problems going between dungeon and forest on IE11 Win7.

**Comment by differentmatt** [comment]
Please reopen if you still see this.
