### ISSUE TITLE
Local developer environment god mode button

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2164]
We need to add a button to the local dev environment, maybe on the account page next to the admin toggle, that will automatically do some of the things mentioned in [this forum post](http://discourse.codecombat.com/t/dev-env-localhost-how-to-sandbox-into-god-mode/2299):

1. Turn the user into a premium user so she can play the premium levels.
2. Give the user a ton of gems.
3. Give the user a ton of experience points.
4. Stop locking levels.
5. Stop locking items.

It will probably be a button which makes a request to the server to modify the User object for 1-3, and some client-side logic to respect the `godMode` flag for 1, 4 and 5, plus a bit of server-side logic to respect it for 1, also.

**Comment by h3yduck** [comment]
Did you mean a button like this?
![image](https://cloud.githubusercontent.com/assets/8607511/6113514/39240168-b098-11e4-86cb-8184e6dbeee9.png)
Wouldn't it be better to use a toggle like with admin?

**Comment by nwinter** [comment]
Yeah, just like that. It will take actions that we don't want to bother reversing (like adding gems), so we can just leave it as a button. But it doesn't matter too much, so if we wanted to make it as a checkbox that didn't fully undo itself, that'd be fine.

**Comment by differentmatt** [comment]
This should also make you an admin.  Then we could make users in a local dev env **not** admins by default, which is better for testing.

**Comment by laituan245** [comment]
I have one quick question. What is the point of giving the user a lot of gems (# 2) if you stop locking all the items (# 5)?
