### ISSUE TITLE
Simulator gets stuck if a Thang fails to load

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2174]
My current fuzzing setup fails 5% of the calls to `/db/thang.type/...` The frequently results in the simulator getting stuck at "Setting up simulation". A behavior I see somewhat regularly on the live site.  It would be nice if we could recover gracefully from Thangs failing to load.

**Comment by nwinter** [comment]
@yaur I haven't implemented request retries, but do you still see occasional ThangType load failures causing to "Setting up simulation" hangs? Recently it seems that simulations have been much more stable.

**Comment by nwinter** [comment]
Closing unless this still seems to be a frequent problem with ThangType requests failing.
