### ISSUE TITLE
cavern survival ladder page crashes IE11

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2175]
navigating to http://codecombat.com/play/ladder/cavern-survival sometimes crashes IE11 with an access violation.  This happens 100% of the time when running against a local server.

**Comment by popey456963** [comment]
Is it giving you an error code, like "Forbidden 403"?  Or are you getting the loading bar that says you don't have permission to access this?

**Comment by yaur** [comment]
Its a hard crash. see:
http://i.imgur.com/dgnXcc1.png

**Comment by differentmatt** [comment]
Is this still a problem?

Which OS version?
In a private browsing window?

I don't get a crash on IE11 Win7, using a local server or against production.

**Comment by differentmatt** [comment]
Please reopen if you still see this.
