### ISSUE TITLE
Couldn't fetch new game while simulating

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2180]
error in JS console:

There was an error fetching two games! {"readyState":4,"responseText":"Couldn't select a random session! MongoError: exception: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.","status":500,"statusText":"Internal Server Error"}

**Comment by schmatz** [comment]
I'm aware of this issue and will fix it this weekend.

**Comment by schmatz** [comment]
Previously, the average document size had to be under 6.4kB to succeed (the average over all level.sessions is 2.946kB). I increased it so that now it's 160kB. Kids these days, with their gigantic level sessions... :stuck_out_tongue:

**Comment by yaur** [comment]
I am still seeing this error while simulating

**Comment by nwinter** [comment]
Hmm, not sure if the fix was uploaded yet. I've just deployed to make sure that the latest server code is in production; still seeing same error now?
