### ISSUE TITLE
Level Editor Tab-out

### ISSUE THREAD

**Issue by purenickery** [codecombat/codecombat#2192]
If you tab out of the level editor and return later, sometimes the level turns all black and has scrolling issues

**Comment by popey456963** [comment]
What operating system are you using, browser, version of browser, rough time until it goes black?

**Comment by divyanshu013** [comment]
I'm unable to reproduce this bug. @purenickery could you provide some more information?

**Comment by nwinter** [comment]
Closing until we can reproduce; I'm guessing this might be related to running out of graphics memory or something like this.
