### ISSUE TITLE
Issues with victory conditions for high scores.

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2204]
As I play through the levels looking for high scores I will add the issues I'm finding.

Some levels seem to have a lowest possible speed that can't be broken.  Need to figure a better way to test level finished for these, I beat them while hasted, and still tied with players using Tharin.

Sarven Gaps
Backwoods Ambush
ThunderHooves - Haste helped this time, but I still stood in the oasis for probably 4 seconds before the level finished.
Great Yak Stampede - Not sure how to fix the time on this one.  Seems that time is always the same if you succeed.  Love that there is option for high damage dealt.

Other issues:
Sarven Road - Don't have to kill the scouts, can just haste to the end of the level.

I'll add more issues as I find them.

**Comment by nwinter** [comment]
Fixed Backwoods Ambush and Great Yak Stampede. On Sarven Gaps, Sarven Road, and Thunderhooves, we just need to make the referee smarter about knowing when the goals have been achieved instead of waiting so long to check completion and then assuming that if you're still alive and at the right spot, you've done it.

**Comment by nemoyatpeace** [comment]
Is it possible to have a Most Gold Collected stat?  Mad Maxer Sells out would be cool that way.  (When hasted I can collect more coins than just the 3 gold)

**Comment by nwinter** [comment]
I juts need to finish Thunderhooves now. Also just added gold-collected to Mad Maxer Sells Out.

**Comment by nemoyatpeace** [comment]
You'll need to clear out the old scores for Sarven Road as well.  I currently hold the best time and damage taken at 4.9 seconds and 0 damage.  I just cast haste and ran.  Was planning to kill at the end, but the level just ended.
