### ISSUE TITLE
 footer remains hidden behind the taskbar (windows chrome)

### ISSUE THREAD

**Issue by focks** [codecombat/codecombat#2205]
![hidden](https://cloud.githubusercontent.com/assets/10615264/6007686/ea88eb94-aad0-11e4-847c-8644c3f568b3.PNG)

the footer which is visible below is not visible in the above case (when the footer is at the bottom)
it seems as if there are no  content after that ...since it is not in the game "scrowling bar" can  be included in this case  to avoid confusion

![hid](https://cloud.githubusercontent.com/assets/10615264/6007708/19c24f90-aad1-11e4-8d77-20678cf3c5c0.PNG)

**Comment by nwinter** [comment]
I don't know that there's much we can do here; we aren't going to know what you might have on the screen occluding part of your browser window.
