### ISSUE TITLE
Level failed to reach 'start level' possibly due to Aether error

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2210]
![levelloadfailure1](https://cloud.githubusercontent.com/assets/2965172/6010479/92d7712e-aae7-11e4-881d-8b6fd3119c86.png)
![levelloadfailure2](https://cloud.githubusercontent.com/assets/2965172/6010480/92e5731e-aae7-11e4-8d36-acee0ff00c5b.png)

**Comment by makertech81** [comment]
I loaded up fine but got errors on console.
![screen shot 2015-02-09 at 6 35 08 pm](https://cloud.githubusercontent.com/assets/5672443/6118337/86ef2052-b08a-11e4-914b-9b4fdf83fb6c.png)
![screen shot 2015-02-09 at 6 35 13 pm](https://cloud.githubusercontent.com/assets/5672443/6118338/87c7b6e2-b08a-11e4-9b2f-fa06fe4ab1de.png)
![screen shot 2015-02-09 at 6 34 48 pm](https://cloud.githubusercontent.com/assets/5672443/6118339/8944ea1c-b08a-11e4-91cf-c04c4aaa9934.png)

**Comment by makertech81** [comment]
I am going to go through each bug in console.

**Comment by differentmatt** [comment]
Thanks for the info.  Please let me know if you see a level fail to load with a aether.js error in the JS console.

**Comment by nwinter** [comment]
I think I fixed this with a8dc353.
