### ISSUE TITLE
Add goals dropdown to real-time playback view

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2221]
This is useful when there's real-time interaction (e.g. flags).  Otherwise you have to remember what you're trying to do.

**Comment by nwinter** [comment]
We probably just have to 1) stop [hiding it in the sass](https://github.com/codecombat/codecombat/blob/master/app/styles/play/level.sass#L39-L41) and 2) adjust its positioning to make sense in the full-screen layout.

**Comment by nwinter** [comment]
Actually, we can't easily fix this, because the goals aren't updated in real time, only at the end–they would be misleading if we showed them during the level. And given that it's only hard to remember what to do on a few levels (like Coinucopia), I think we can ignore it.
