### ISSUE TITLE
Spell palette gets truncated

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2224]
Need to make it scroll, scale, or drilldown to fit everything.

![spellpalettechopped](https://cloud.githubusercontent.com/assets/2965172/6011096/27e9502a-aaed-11e4-886a-f6a400a20e93.png)

**Comment by makertech81** [comment]
I have been having the same problem
I am going to look into it

**Comment by makertech81** [comment]
Someone close this, because the bug was already fixed.
TJ

**Comment by nwinter** [comment]
I haven't done anything to fix this yet; it's just worse the smaller your screen and the more properties you have access to.

**Comment by amankr** [comment]
I wonder why is this commented. 
https://github.com/codecombat/codecombat/blob/master/app/styles/play/level/tome/spell_palette.sass#L12

**Comment by nwinter** [comment]
Let's discuss this in #1777.
