### ISSUE TITLE
Sarven Savior - Need to explain len() in guide

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2225]
Or in an earlier level if we use it there.

**Comment by nwinter** [comment]
You can [open it in the level editor](http://codecombat.com/editor/level/sarven-savior) and add a description of how to access array lengths in the guide, in a Specific Article called "Overview".

**Comment by Khoffee** [comment]
Added this to the map overview:
 "Hint: You can use arrayName.len() to return the length of your array."
