### ISSUE TITLE
Autocomplete is using "this" while in python

### ISSUE THREAD

**Issue by Catsync** [codecombat/codecombat#2233]
Currently, if I type "pow" and tab to autocomplete a powerUp() statement, it's inserting this.powerUp() instead of self.powerUp(). Same with "attTAB" for attack()

I played javascript for a while (earlier levels), then switched to python, so maybe something is leftover from that.

**Comment by differentmatt** [comment]
I checked the combat.PowersUp component setting in the level editor, and the snippets look correct.  

Yes, this sounds like a an autocomplete bug in the language switching resulting in stale snippets.

Relevant code: https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/SpellView.coffee#L394
