### ISSUE TITLE
Buy gems window

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2238]
I think it should have a close button!

![sem titulo](https://cloud.githubusercontent.com/assets/6980488/6046350/3273aa2e-ac99-11e4-9625-cd37b31ceca0.png)

**Comment by nwinter** [comment]
1. Add the markup, like [in the other modals](https://github.com/codecombat/codecombat/blob/master/app/templates/play/modal/play-heroes-modal.jade#L13-L14), to the [buy gems modal template](https://github.com/codecombat/codecombat/blob/master/app/templates/play/modal/buy-gems-modal.jade).

2. Do similarly for [the styles](https://github.com/codecombat/codecombat/blob/master/app/styles/play/modal/play-heroes-modal.sass#L52-L68).

3. Add the [hide event handler](https://github.com/codecombat/codecombat/blob/master/app/views/play/modal/PlayHeroesModal.coffee#L22-L22).

**Comment by Imperadeiro98** [comment]
Fixed on #2263.
