### ISSUE TITLE
incorrect layout for the items in the down right hand corner

### ISSUE THREAD

**Issue by ZX-WT** [codecombat/codecombat#2250]
![2015-02-06 22 31 36](https://cloud.githubusercontent.com/assets/10883749/6081018/0cab676e-ae51-11e4-9c1e-120f7995f29a.png)
Here's what I am using
OS:ubuntu 14.04
Browser: Firefox 35.0.1
I did not try it with Chrome but it was shown correctly for another computer using Chrome in Windows 7

**Comment by Popey456963** [comment]
I don't think this is a bug, look at the space for the items, self.shield() is taking up more than half.  It would be cool to maybe lose the images on smaller displays however.

**Comment by nwinter** [comment]
There should always be at least two columns, so there's definitely a bug here with the small screen size.

Let's discuss this in #1777.
