### ISSUE TITLE
100.3% of translation

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2253]
![default](https://cloud.githubusercontent.com/assets/1132840/6085054/9029b276-ae47-11e4-9dff-2ed28230865c.PNG)

Chrome 40.0.2214.111 m (64-bit), win 8.1 x64
[offtopic]MORE THEN 9000!!!![/offtopic]

**Comment by Imperadeiro98** [comment]
@nwinter, could you propagate i18n? This bug happened because I removed some strings from en.coffee.
