### ISSUE TITLE
Sarven Brawl stuck at loop?

### ISSUE THREAD

**Issue by nickhill** [codecombat/codecombat#2260]
Hi - 
Sarven Brawl hangs with 'loop:' highlighted ( I think that means the currently running step? ).

I simplified the code to the following to try to isolate the problem:

loop:
    e = self.findNearest(self.findEnemies())
    if ((e is not None ) and ( e.type != 'sand-yak' )):
        while e.health > 0:
            self.attack(e)

This works as expected for the first 5 or 8 enemies but fails after
a bit. A bunch of throwers show up and they are easily visible
though they tend to cluster around yaks. I had my warrior move
a bit if no enemies could be seen (instead of staying put), same
result as long as I didn't move very far. Move very far and the 
situation resolves itself, but it can happen in other arrangements - 
your warrior will just sit around and get shot to 0 health.

See screenshot attached - clearly at least 2 of the throwers should be visible
and I'm not even clear that a yak can occlude another enemy to the point where 
it can shoot you but you can't see it?

![sarven_brawl_fail](https://cloud.githubusercontent.com/assets/1440805/6095989/b3658bfc-af2d-11e4-9ff5-271f1d425e9d.png)

**Comment by makertech81** [comment]
I have played this level and was able to see it.  Can you play it again and send a screen shot of the whole game screen? I think its a bug.
TJ

**Comment by makertech81** [comment]
UPDATE: It should not be stuck at loop.  Are you sure its stuck?

**Comment by sotonin** [comment]
Not a bug. just bad coding. In the code in the screenshot if the nearest enemy is a sand yak it will just stand there doing nothing. That's what is happening in the screenshot the yak is closer than the throwers so you are just standing there while they kill you. You need to loop over all the enemies and not just use findNearest to actually locate the true closest non yak enemy to target.
