### ISSUE TITLE
forgetful gemsmith no bonus ( under 9 statments) - clojure

### ISSUE THREAD

**Issue by junior83** [codecombat/codecombat#2268]
Hi, i have code 

(.moveRight this)
(.moveUp this)
(.moveRight this)
(.moveRight this)
(.moveDown this)
(.moveDown this)
(.moveUp this)
(.moveRight this)

but I don't get uder 9 statments bonus

**Comment by nwinter** [comment]
Sorry about that–this is the same issue as #1808. Let's follow that one.
