### ISSUE TITLE
Campaign i18n error

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2269]
When I try to i18n the campaign names, I get a "403 Forbidden" error.

Note: I'm seeing this same behavior with thangs.

**Comment by nwinter** [comment]
This might be related to #1866 or f7403a6, but it may be a new thing. @sderickson can you check it out? I don't think it's all the way there with the permissions yet, even though you added the `PatchablePlugin`.

**Comment by Imperadeiro98** [comment]
This is now fixed.
