### ISSUE TITLE
CodeCombat not working

### ISSUE THREAD

**Issue by makertech81** [codecombat/codecombat#2272]
CodeComabt just wont work on any browser! Nothing!

**Comment by yaur** [comment]
Are you setting up a dev environment? the live site looks ok from where I'm at.
Hipchat is generally the best place to go for help getting the dev environment set up.

**Comment by makertech81** [comment]
I am in HipChat and @nwinter was helping me.  I already have a dev environment, but I am not using dev environment right now.

**Comment by popey456963** [comment]
Less dramatic.

**Comment by nwinter** [comment]
@makertech81 Is it still busted today? I just can't figure out why it's not working for you all of a sudden.
