### ISSUE TITLE
Title is T?

### ISSUE THREAD

**Issue by makertech81** [codecombat/codecombat#2273]
The title is t on http://52.1.55.176:3000/play. Is it supposed to be like that?

**Comment by makertech81** [comment]
![screen shot 2015-02-09 at 6 29 03 pm](https://cloud.githubusercontent.com/assets/5672443/6118251/b8fbee8c-b089-11e4-9a79-ea14b4056528.png)

**Comment by nwinter** [comment]
Yeah, it's in development mode until it's on codecombat.com, so it'll try to show the view class titles instead of the normal title blurb–but it is a production build, so they get minified.
