### ISSUE TITLE
Autocomplete that is triggered while playing,doesn't disappear on pressing the back button.

### ISSUE THREAD

**Issue by navya-nizamkari** [codecombat/codecombat#2289]
After the autocomplete is suggested,when the back button on browser is pressed, the screen is loaded along with the autocomplete which doesn't go away until you choose one of those options.
![screenshot from 2015-02-11 18 43 16](https://cloud.githubusercontent.com/assets/7747651/6147576/21362ddc-b21f-11e4-8d56-91ef4cbacd8e.png)

**Comment by matifol** [comment]
I'm having trouble re-producing the error. What browser and system are you on?

**Comment by navya-nizamkari** [comment]
I used firefox on ubuntu 14.04

**Comment by rmarren1** [comment]
I have the same issue with firefox 35.0.1 on ubuntu 14.04

**Comment by nwinter** [comment]
Not seeing it; anyone still having issues with this?
