### ISSUE TITLE
Tim Berners-Lee quote/tip too long

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2303]
This was on IE11 Win7.
Introduced by https://github.com/codecombat/codecombat/pull/2264
![screen shot 2015-02-12 at 11 38 35 am](https://cloud.githubusercontent.com/assets/2965172/6175456/ca789678-b2ab-11e4-82d7-296d07e64d38.png)

**Comment by matifol** [comment]
Should we just exclude it, or what?
