### ISSUE TITLE
Fix new patch review interface to Achievement Editor

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2304]
We have a patch acceptance interface in the Article Editor, like this:

![screenshot 2015-02-12 13 24 56](https://cloud.githubusercontent.com/assets/99704/6177327/9619b920-b2ba-11e4-87f2-eef684747f22.png)

The code for that starts [here](https://github.com/codecombat/codecombat/blob/master/app/views/editor/article/ArticleEditView.coffee#L67-L68) and [here](https://github.com/codecombat/codecombat/blob/master/app/templates/editor/article/edit.jade#L26-L27).

We need a similar thing for the Achievement Editor, which has no way yet of accepting all its pending i18n patches:

![screenshot 2015-02-12 13 26 36](https://cloud.githubusercontent.com/assets/99704/6177355/d052dffe-b2ba-11e4-9d0a-268a680dec14.png)

**Comment by aniketisin** [comment]
Hi I am new here, i would like to work on this bug, can someone guide me a bit through it

**Comment by rmarren1** [comment]
I'm a newbie trying to tackle this issue, making some progress but wondering if someone can push me in the right direction.

I have the patches view added: 
![selection_002](https://cloud.githubusercontent.com/assets/10272301/6200800/6efdccf8-b456-11e4-9347-1fbc3a965670.png)

However, it is not being populated with patch data correctly.

The articles patch view makes a database call like '/db/article/524c8cb26ee802556d00000e/?status=pending' to populate the patches list.

However, when the same call is made for achievements it looks like this '/db/achievement/undefined/?status=pending'

The call that returns undefined is '@achievement.get('original')' ('@article.get('original')' returns '524c8cb26ee802556d00000e')

This is where I am stuck, I cannot trace the calls further than this. I am finding no 'get' method in article.coffee or achievement.coffee.

Any tips would be appreciated! Also, let me know if this is the right place to be posting this kind of question.

**Comment by aniketisin** [comment]
I am also having the same problem, as described by rmarren1, i found the get method in CocoModel.coffee, it returns the attribute from the model (i think so). When i opened my database dump/achievements.metadata.json i was not able to find any key value pair for 'original', whereas there was one such pair in articles.metadata.json. Can this be a database issue ?

**Comment by nwinter** [comment]
Looks like [the PatchesCollection only knows how to fetch patches for versioned models](https://github.com/codecombat/codecombat/blob/master/app/collections/PatchesCollection.coffee#L9-L9) (the ones that have the `original` property). Maybe something like this will work for using `_id` instead, for non-versioned documents where the `original` value just would be the same as `_id` (since the single Achievement document *is* the original):

```coffeescript
    identifier = if forModel.schema().properties.original then 'original' else '_id'
    @url = "#{forModel.urlRoot}/#{forModel.get(identifier)}/patches?status=#{@status}"
```

**Comment by aniketisin** [comment]
there is no object at  http://localhost:3000/db/achievement/<achievement-id>/patches
instead we get the json at  http://localhost:3000/db/achievement/<achievement-id>/?status='status'
the json objects at article and that achievement are handled very differently, hence i suppose we need to write a different viewer to do so, can you guide me through it?

**Comment by nwinter** [comment]
Nah, http://localhost:3000/db/achievement/signed-up?status=pending is the right format and the right URL; I just asked about /patches to see if there was anything there. If you have patches from the ?status=pending URL, they should show up in the viewer, no?

**Comment by rmarren1** [comment]
I have the menu working, and all get requests are going through
![selection_001](https://cloud.githubusercontent.com/assets/10272301/6219807/5564ddde-b5fc-11e4-89be-45e347e16d99.png)

However, I am not actually seeing any patches. Is something wrong, or are there just no patches in the database? I don't want to make a pull request until I'm sure it works.

**Comment by nwinter** [comment]
There are no patches in the local DB unless you make some. You can submit a PR and I can test with the live DB to see if they are showing up, or you can log into a non-admin account and try to submit some patches to the achievement to test it. (For example, if you go to http://localhost:3000/i18n/achievement/signed-up and submit an en-US change from a non-admin account, it will create a patch.)

**Comment by nwinter** [comment]
@sderickson we now have the interface in there, but 1) the patches don't update the model, and 2) the patches don't save when accepted:

![screenshot 2015-02-16 17 40 12](https://cloud.githubusercontent.com/assets/99704/6222087/e8a6fedc-b602-11e4-95f7-ac8e3c98bae3.png)

What do we normally do to make patches actually update the models, and what can we do to make them save on these non-versioned Achievements? (Also, the patches don't update the models on Articles, so it's probably the same problem.)

**Comment by rmarren1** [comment]
Don't know if this helps, but the after I make a patch just access the database, the patches show up.

e.g. http://localhost:3000/db/achievement/5499ec66a88ecca974d501e6 shows
![selection_003](https://cloud.githubusercontent.com/assets/10272301/6222230/070b1d70-b61e-11e4-8f6f-e303093b4159.png)

But when I try to access the patches directly at:
 http://localhost:3000/db/achievement/5499ec66a88ecca974d501e6/patches

There is just a [ ].
