### ISSUE TITLE
Red error box when developing and running game - randomseed type error

### ISSUE THREAD

**Issue by cakey** [codecombat/codecombat#2309]
Basically makes the game unusable for me. Also seemed to prevent saving and I lost some work, unless that is a separate bug.

I was playing Gold Rush as humans, on Chrome 40, Yosemite.

Here's the stack trace:

Error saving LevelSession: 422 Unprocessable Entity [{"message":"invalid type: string (expected integer)","code":0,"dataPath":"/matches/0/randomSeed","schemaPath":"/properties/matches/items/properties/randomSeed/type","subErrors":null,"stack":"Error: invalid type: string (expected integer)\n at new ValidationError (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:1188:12)\n at ValidatorContext.createError (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:176:9)\n at ValidatorContext.validateType (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:559:14)\n at ValidatorContext.validateBasic (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:529:19)\n at ValidatorContext.validateAll (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:410:19)\n at ValidatorContext.validateObjectProperties (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:786:21)\n at ValidatorContext.validateObject (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:737:11)\n at ValidatorContext.validateAll (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:414:11)\n at ValidatorContext.validateArrayItems (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:723:21)\n at ValidatorContext.validateArray (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:656:11)\n at ValidatorContext.validateAll (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:413:11)\n at ValidatorContext.validateObjectProperties (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:786:21)\n at ValidatorContext.validateObject (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:737:11)\n at ValidatorContext.validateAll (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:414:11)\n at Object.api.validateMultiple (/home/ubuntu/codecombat/node_modules/tv4/tv4.js:1308:12)\n at LevelSessionHandler.module.exports.Handler.validateDocumentInput (/home/ubuntu/codecombat/server/commons/Handler.coffee:482:15)\n at LevelSessionHandler.module.exports.Handler.saveChangesToDocument (/home/ubuntu/codecombat/server/commons/Handler.coffee:521:19)\n at /home/ubuntu/codecombat/server/commons/Handler.coffee:349:10\n at LevelSessionHandler.module.exports.Handler.doWaterfallChecks (/home/ubuntu/codecombat/server/commons/Handler.coffee:497:12)\n at /home/ubuntu/codecombat/server/commons/Handler.coffee:346:8\n at Promise. (/home/ubuntu/codecombat/server/commons/Handler.coffee:491:9)\n at Promise. (/home/ubuntu/codecombat/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)\n at Promise.EventEmitter.emit (events.js:95:17)\n at Promise.emit (/home/ubuntu/codecombat/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)\n at Promise.fulfill (/home/ubuntu/codecombat/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)\n at Promise.resolve (/home/ubuntu/codecombat/node_modules/mongoose/lib/promise.js:114:23)\n at Promise. (/home/ubuntu/codecombat/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)\n at Promise.EventEmitter.emit (events.js:95:17)\n at Promise.emit (/home/ubuntu/codecombat/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)\n at Promise.fulfill (/home/ubuntu/codecombat/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)\n at /home/ubuntu/codecombat/node_modules/mongoose/lib/query.js:1400:13\n at model.Document.init (/home/ubuntu/codecombat/node_modules/mongoose/lib/document.js:250:11)\n at completeOne (/home/ubuntu/codecombat/node_modules/mongoose/lib/query.js:1398:10)\n at Object.cb (/home/ubuntu/codecombat/node_modules/mongoose/lib/query.js:1155:11)\n at Object. (/home/ubuntu/codecombat/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)\n at Object._onImmediate (/home/ubuntu/codecombat/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)\n at processImmediate [as _immediateCallback] (timers.js:330:15)\n"},{"message":"invalid type: string (expected integer)","code":0,"dataPath":"/matches/1/rand

**Comment by cakey** [comment]
I was using coffeescript

**Comment by cakey** [comment]
I believe my username is Daskuva

**Comment by nwinter** [comment]
I see the problem; I've fixed it with a more permissive schema. Sorry about that! I'm deploying the fix now, so should be live in 20-60 minutes depending on caching.

**Comment by cakey** [comment]
Great job! Could you possibly link me to the commit? I'm curious about the fix!

**Comment by nwinter** [comment]
Just [this](https://github.com/codecombat/codecombat/commit/a8dc353f86a0bdf6951d48a26fbb9714f006bbe6#diff-f460cba2d34c2a08a6a264bbfbfe0164R289). I don't really care about the data type that gets stored in here, as it's only for visual debugging purposes anyway.
