### ISSUE TITLE
Standard Hero Diversity

### ISSUE THREAD

**Issue by robmuh** [codecombat/codecombat#2318]
I have one class that contains all 7-10 year old black kids. These guys are great and really love programming asking when they will work up to code combat. I'd also really like to encourage programming in demographics that statistically are underrepresented. I'd love to see a standard hero in the standard free hello list that looks like them. I love Hattori and he is a favorite from students of all races and I realize these days people are ok and understand better, mostly I just think it would be cool the same way I think Hattori is cool.

**Comment by nwinter** [comment]
You're totally right about this. All the next seven heroes coming up (the most powerful ones) are non-white, including two black heroes. (It would be better if we'd realized this sooner to include more diverse heroes early on, but we weren't thinking.) Will close this when they are in the game.

**Comment by nwinter** [comment]
They are coming:

![new_heroes](https://cloud.githubusercontent.com/assets/99704/7093323/052594b8-df6d-11e4-9800-83ed7d86dd03.png)
