### ISSUE TITLE
FR localisation - (417) parent_button : Not enough space for text

### ISSUE THREAD

**Issue by ZeAntwan** [codecombat/codecombat#2324]
The translated text for the "Ask your parent" ("Demande à tes parents") button,  refered as parent_button an line 417, is too long to fit in the box dedicated to it. 

Here is what it looks like.
![capture](https://cloud.githubusercontent.com/assets/11023019/6213308/ab02fafe-b5ee-11e4-8694-e39ebafcf333.PNG)

It seems to be okay when the text-size is reduced to 21px : 
![capture](https://cloud.githubusercontent.com/assets/11023019/6213326/d21f39ea-b5ee-11e4-8570-6e96b5b07797.PNG)

**Comment by nwinter** [comment]
Here's an example of how to reduce per-language font sizes when text doesn't fit:

https://github.com/codecombat/codecombat/blob/master/app/styles/home.sass#L86-L89

We could do this here for French, or for all non-English languages to be safer, or we could come up with a better way of finding the right font size for a given button and text string.
