### ISSUE TITLE
scattershot optional target not optional

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2342]
No script error when passed a target object.

![screen shot 2015-02-17 at 3 00 30 pm](https://cloud.githubusercontent.com/assets/2965172/6239204/5da90ece-b6b6-11e4-942f-6198aff349c0.png)

**Comment by Zerrien** [comment]
Made a patch request that fixes shooting at a {x:, y:} position as well as allows the player to simply scattershot() 10 meters ahead of them.

**Comment by nwinter** [comment]
Thanks @Zerrien!
