### ISSUE TITLE
scattershot not in autocomplete suggestions

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2343]
Saw in level Medical Attention.

**Comment by amankr** [comment]
I have verified that while adding ZatannaSnippet , the doc for scattershot has no field named snippet. Thats why its not added into autocomplete suggestions. 
https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/SpellView.coffee#L412
I am stuck with adding snippet field into docs for scattershot.

**Comment by nwinter** [comment]
You could submit a patch to Scattershot to add the snippets. Here's a bit of an example: https://github.com/codecombat/codecombat/issues/1237

**Comment by amankr** [comment]
I have submitted the patch for adding scattershot snippets for all supported languages.
