### ISSUE TITLE
Can't beat Dread Door in IE9

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2355]
Heard this from a user; haven't tried to reproduce myself.

**Comment by nwinter** [comment]
Anyone have easy access to an IE9 machine and can report whether this level worked or what the problem was?

**Comment by divyanshu013** [comment]
It's working (except in CoffeeScript), although a bit slow. Might have been a memory issue Nick.

**Comment by differentmatt** [comment]
Works on Win7 IE9 in Python and CoffeeScript.
