### ISSUE TITLE
Russian "shield" translation typo

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2364]
Someone emailed me to say:

> There is an orthographical mistake in russian version of CodeCombat; in description of shields we can see this word: поглащает. But according to rules of the russian language, it would be correct to write поглощает.

I am not really sure which strings he's talking about, might be in the item descriptions for some (all?) shields? @nixel2007 if you have a moment, would you mind checking it out?

**Comment by nixel2007** [comment]
Mistake at http://codecombat.com/i18n/component/shields
I've submitted a patch with fix.

**Comment by nwinter** [comment]
Great, thanks!
