### ISSUE TITLE
Fix text search

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2367]
@schmatz tells me that in order to get text search working again in MongoDB 3.0 release candidate, we need:

1. Remove the dependency on mongoose-text-search (which can be found by grepping "textSearch")
2. Ensure the correct index(es) are placed
3. Rewrite the calls to textSearch to just be find calls [like this](https://stackoverflow.com/questions/24714166/full-text-search-with-weight-in-mongoose)

**Comment by Catsync** [comment]
I'm seeing errors when trying to attach components to thangs in the editor.

It triggers queries like:
`http://direct.codecombat.com/db/level.component?term=Referee&project=name,system,original,version,dependencies,configSchema,description`

Which get either empty responses, or:

 `Database error, MongoError: no such command: text` 

I'm guessing that's from this issue? If so, +1 :+1:  for prioritizing this fix :)

**Comment by nwinter** [comment]
Working on this now.

**Comment by Imperadeiro98** [comment]
Also, the tests related to this should be updated (they are not passing).
