### ISSUE TITLE
JumpTo behaves inconsistent

### ISSUE THREAD

**Issue by J-F-B-M** [codecombat/codecombat#2372]
JumpTo jumps different distances, based if it is immediatly followed by another Jump-command.
If no command follows a jump-command, the hero will not make the full jump, even though the maximum jump-length is not reached, and the way is unobstructed.

In the following pictures you can see a proper full jump for reference, on the left a failed shorter jump, and on the right a correct shorter jump, followed by a failed jump.

Code (Coffeescript) is (for left):
```
@jumpTo {x:8, y:125}
@jumpTo {x:8, y:125}
```

and for right:
```
@jumpTo {x:8, y:125}
@jumpTo {x:8, y:125}
@jumpTo {x:46, y:122}
```

The following picture is taken in *Deadly Dungeon Rescue*
![jumpto_is_inconsistent](https://cloud.githubusercontent.com/assets/1939512/6316825/4dc80258-ba35-11e4-9c69-41a38aa9aedb.png)

**Comment by J-F-B-M** [comment]
Possibly related to this:

Glacian mentioned jumpTo needs to be executed in a loop? This seems rather unintuitive
http://discourse.codecombat.com/t/how-to-use-jumpto/2079/7?u=j_f_b_m

**Comment by nwinter** [comment]
Found the problem–when you got to the end of the `plan()` method code, it would automatically brake. Now it will only do it if your hero is on the ground, so you can't stop in mid-air when your code is done.
