### ISSUE TITLE
Multiplayer Greed - can't get nearest object to item

### ISSUE THREAD

**Issue by J-F-B-M** [codecombat/codecombat#2381]
Move from the [forum](http://discourse.codecombat.com/t/i-have-some-trouble-with-the-findnearest-function-called-from-an-item/2823/3?u=j_f_b_m)
    Apparently item.getNearest()/item.findNearest() are not working, and it is unclear which to use anyway. Both methods seem to work for the base-building though.

**Comment by nwinter** [comment]
Should be solved now that Greed isn't really supported and the new APIs are more consistent.
