### ISSUE TITLE
Layout problem in german subscribe

### ISSUE THREAD

**Issue by angryelven-jdd** [codecombat/codecombat#2409]
I commited the german translation for #2405, subscription window, yesterday.
Unfortunately, after it was merged, I noticed that the text is too long and breaks the layout.
Since I am new to the project, I am not sure if I should shorten the text,
or if I can simply change the window properties. I started installing the whole project locally to
check for these things offline first. 

Thanks,
nin

**Comment by nwinter** [comment]
Can you post a screenshot of the busted text? If there's no shorter translation that would fit, we can apply some language-specific styling to lower the text size, as we did in #2408.

**Comment by angryelven-jdd** [comment]
I can shorten the headline and the 3500 Bonusedelsteine, But The Problem would remain because the second entry is hard to make any shorter and still be nice to read.

![german_subscription_](https://cloud.githubusercontent.com/assets/11194369/6422187/ff2cb7ba-bed5-11e4-8913-e6c73da5db2b.png)

I watched #2408 and think that would also be a good idea.
If I am allowed to, I could change these layout things and check them in in the future. I will of course try to make it all fit and still sound nice. I was going to install the codecombat for checking on my machine, but the npm takes up all the ressources on my computer when using windows. Hard to imagine... I got time on sunday and will fix my linux. So if you do not mind and I could test locally, I would also change the layout and commit that in future. 


Thanks,
nin

**Comment by angryelven-jdd** [comment]
I just noticed that there is still the $ sign in the price field. Another contributer translated that.
Should it stay dollar or would it be the same in euro? Then I would change it along with other things.

**Comment by nwinter** [comment]
You would want to change it to $ USD, because we don't know what the Euro price would be; Stripe figures that out dynamically.

Sure, I'd be happy to review a pull request changing the layout. Thank you!

**Comment by angryelven-jdd** [comment]
Okay, seems I do not need to change that for #2409. Thanks for the fix.

**Comment by divyanshu013** [comment]
You're welcome @angryelven-jdd !
