### ISSUE TITLE
Use simple loops in all levels' Lua sample code

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2422]
We used to have to have code like this for Lua, since we had no simple `loop` keyword, and so we had to help the player avoid infinite loops:

```lua
while true do
    -- whatever the sample code is

    self:say("Remove this line once your loop is finite.")
end
```

Now we can rewrite that to:

```lua
loop
    -- whatever the sample code is
end
```

(The simple loop will automatically yield for one frame if no action is taken, so you can't get an infinite loop by not doing `move`, `attack`, `say`, or some other blocking action.)

We need to update the Lua sample code in pretty much all levels to use the new `loop` keyword instead, and to get rid of the placeholder `say` lines. The first few levels have no loops, and some of the last ones in the desert actually are teaching `while true do` loops, and some levels have just comments for sample code, but everything else will need updating.

To update the Lua sample code:

1. Open the level editor
2. Double-click the Hero Placeholder
3. Click programming.Programmable on the left
4. Open `programmableMethods` -> `plan` -> `languages` -> `lua`
5. Update the Lua sample code.
6. Submit a patch
7. Post (or update) your comment here saying which ones you've done.

![screenshot 2015-02-27 14 22 41](https://cloud.githubusercontent.com/assets/99704/6422328/25cfc26c-be8c-11e4-9a7b-7a7f9351a0d1.png)

I've definitely missed some that actually just have comments for sample code, but this is the list I know about so far:

- [x] [Haunted Kithmaze](http://codecombat.com/editor/level/haunted-kithmaze)
- [x] [Riddling Kithmaze](http://codecombat.com/editor/level/riddling-kithmaze)
- [x] [Descending Further](http://codecombat.com/editor/level/descending-further)
- [x] [The Second Kithmaze](http://codecombat.com/editor/level/the-second-kithmaze)
- [x] [Dread Door](http://codecombat.com/editor/level/dread-door)
- [x] [Cupboards of Kithgard](http://codecombat.com/editor/level/cupboards-of-kithgard)
- [x] [Hack and Dash](http://codecombat.com/editor/level/hack-and-dash)
- [x] [Breakout](http://codecombat.com/editor/level/breakout)
- [x] [Dueling Grounds](http://codecombat.com/editor/level/dueling-grounds)
- [x] [Kithgard Gates](http://codecombat.com/editor/level/kithgard-gates)
- [x] [Kithgard Brawl](http://codecombat.com/editor/level/kithgard-brawl)
- [x] [Patrol Buster](http://codecombat.com/editor/level/patrol-buster)
- [x] [Endangered Burl](http://codecombat.com/editor/level/endangered-burl)
- [x] [Village Guard](http://codecombat.com/editor/level/village-guard)
- [x] [Thornbush Farm](http://codecombat.com/editor/level/thornbush-farm)
- [x] [Back to Back](http://codecombat.com/editor/level/back-to-back)
- [x] [Ogre Encampment](http://codecombat.com/editor/level/ogre-encampment)
- [x] [Woodland Cleaver](http://codecombat.com/editor/level/woodland-cleaver)
- [x] [Shield Rush](http://codecombat.com/editor/level/shield-rush)
- [x] [Peasant Protection](http://codecombat.com/editor/level/peasant-protection)
- [x] [The Agrippa Defense](http://codecombat.com/editor/level/the-agrippa-defense)
- [x] [Munchkin Harvest](http://codecombat.com/editor/level/munchkin-harvest)
- [x] [Arcane Ally](http://codecombat.com/editor/level/arcane-ally)
- [x] [Munchkin Swarm](http://codecombat.com/editor/level/munchkin-swarm)
- [x] [Backwoods Brawl](http://codecombat.com/editor/level/backwoods-brawl)
- [x] [Swift Dagger](http://codecombat.com/editor/level/swift-dagger)
- [x] [Touch of Death](http://codecombat.com/editor/level/touch-of-death)
- [x] [Shrapnel](http://codecombat.com/editor/level/shrapnel)
- [x] [Bonemender](http://codecombat.com/editor/level/bonemender)
- [x] [Coinucopia](http://codecombat.com/editor/level/coinucopia)
- [x] [Hold the Forest Pass](http://codecombat.com/editor/level/hold-the-forest-pass)
- [x] [Copper Meadows](http://codecombat.com/editor/level/copper-meadows)
- [x] [Drop the Flag](http://codecombat.com/editor/level/drop-the-flag)
- [x] [Backwoods Treasure](http://codecombat.com/editor/level/backwoods-treasure)
- [x] [Deadly Pursuit](http://codecombat.com/editor/level/deadly-pursuit)
- [x] [Rich Forager](http://codecombat.com/editor/level/rich-forager)
- [x] [Hold for Reinforcements](http://codecombat.com/editor/level/hold-for-reinforcements)
- [x] [Storming the Farmhouse](http://codecombat.com/editor/level/storming-the-farmhouse)
- [x] [Unfair Support](http://codecombat.com/editor/level/unfair-support)
- [x] [Tactical Timing](http://codecombat.com/editor/level/tactical-timing)
- [x] [Doom Glade](http://codecombat.com/editor/level/doom-glade)
- [x] [Defend the Garrison](http://codecombat.com/editor/level/defend-the-garrison)
- [x] [Multiplayer Treasure Grove](http://codecombat.com/editor/level/multiplayer-treasure-grove)
- [x] [Cavern Survival](http://codecombat.com/editor/level/cavern-survival)
- [x] [The Dunes](http://codecombat.com/editor/level/the-dunes)
- [x] [The Mighty Sand Yak](http://codecombat.com/editor/level/the-mighty-sand-yak)
- [x] [Oasis](http://codecombat.com/editor/level/oasis)
- [x] [Sarven Road](http://codecombat.com/editor/level/sarven-road)
- [x] [Sarven Gaps](http://codecombat.com/editor/level/sarven-gaps)
- [x] [Thunderhooves](http://codecombat.com/editor/level/thunderhooves)
- [x] [Wild Horses](http://codecombat.com/editor/level/wild-horses)
- [x] [The Great Yak Stampede](http://codecombat.com/editor/level/the-great-yak-stampede)
- [x] [Medical Attention](http://codecombat.com/editor/level/medical-attention)
- [x] [Minesweeper](http://codecombat.com/editor/level/minesweeper)
- [x] [Sarven Sentry](http://codecombat.com/editor/level/sarven-sentry)
- [x] [Keeping Time](http://codecombat.com/editor/level/keeping-time)
- [x] [Hoarding Gold](http://codecombat.com/editor/level/hoarding-gold)
- [x] [Decoy Drill](http://codecombat.com/editor/level/decoy-drill)
- [x] [Yakstraction](http://codecombat.com/editor/level/yakstraction)
- [x] [Sarven Brawl](http://codecombat.com/editor/level/sarven-brawl)
- [x] [Desert Combat](http://codecombat.com/editor/level/desert-combat)
- [x] [Sarven Rescue](http://codecombat.com/editor/level/sarven-rescue)
- [x] [Sacred Statue](http://codecombat.com/editor/level/sacred-statue)
- [x] [Dust](http://codecombat.com/editor/level/dust)
- [x] [Mirage Maker](http://codecombat.com/editor/level/mirage-maker)
- [x] [Sarven Savior](http://codecombat.com/editor/level/sarven-savior)
- [x] [Odd Sandstorm](http://codecombat.com/editor/level/odd-sandstorm)
- [x] [Lurkers](http://codecombat.com/editor/level/lurkers)
- [x] [Preferential Treatment](http://codecombat.com/editor/level/preferential-treatment)
- [x] [Sarven Shepherd](http://codecombat.com/editor/level/sarven-shepherd)
- [x] [Shine Getter](http://codecombat.com/editor/level/shine-getter)
- [x] [Sarven Treasure](http://codecombat.com/editor/level/sarven-treasure)
- [x] [Mad Maxer](http://codecombat.com/editor/level/mad-maxer)
- [x] [Mad Maxer Strikes Back](http://codecombat.com/editor/level/mad-maxer-strikes-back)
- [x] [Mad Maxer Sells Out](http://codecombat.com/editor/level/mad-maxer-sells-out)
- [x] [Mad Maxer Gets Greedy](http://codecombat.com/editor/level/mad-maxer-gets-greedy)
- [x] [Mad Maxer: Redemption](http://codecombat.com/editor/level/mad-maxer-redemption)
- [x] [Sarven Siege](http://codecombat.com/editor/level/sarven-siege)
- [x] [Clash of Clones](http://codecombat.com/editor/level/clash-of-clones)
- [x] [Harrowland](http://codecombat.com/editor/level/harrowland)

**Comment by h3yduck** [comment]
Submitted patch for:
Haunted Kithmaze
Riddling Kithmaze
Hack and Dash
Patrol Buster
Endangered Burl

The Second Kithmaze - it has comment only
Breakout - no default source code
Dueling Grounds - it has comment only
Kithgard Gates - no loop in default source code
Kithgard Brawl - it has comment only

**Comment by Khoffee** [comment]
Submitted patch for:
- Touch of Death
- Shrapnel
- Bonemender
- Coinucopia
- Hold the Forest Pass

**Comment by Sleeper097** [comment]
Submitted patch for:
     - Back to Back
     - Ogre Encampment

**Comment by tvdang** [comment]
submitted patch for 
-back to back
-Rich forager

**Comment by divyanshu013** [comment]
Submitted patch for:
1. Village Guard
2. The Agrippa Defense

Shield rush has comments only

**Comment by laituan245** [comment]
Submitted patch for:
+ Deadly Pursuit
+ Hold for Reinforcements
+ Oasis
+ Sarven Gaps
+ Wild Horses

Backwoods Treasure - it has comment only
Minesweeper - it has comment only
Dust - no loop in default source code

**Comment by nwinter** [comment]
Awesome, great work so far y'all! A bunch of the remaining levels might be because they're paid levels, and I guess maybe the level editor doesn't let you open those. But there are still some free ones left that either need doing or need a heads up that they don't need simple loops in them.

**Comment by laituan245** [comment]
Submitted patch for:
+ Thornbush Farm
+ Munchkin Swarm
+ Mad Maxer Strikes Back
+ Mad Maxer Sells Out
+ Mad Maxer Gets Greedy
+ Mad Maxer: Redemption

Clash of Clones - it has comment only
Backwoods Brawl - it has comment only

**Comment by laituan245** [comment]
Tactical Timing - it has comment only
Doom Glade - no default Lua source code
Defend the Garrison - it has comment only
Yakstraction - it has comment only
Sarven Brawl - it has comment only
Sarven Rescue - it has comment only
Preferential Treatment - no loop in default source code

**Comment by divyanshu013** [comment]
The Dunes -> Patch submitted
Copper Meadows -> Patch submitted
Swift Dagger -> Patch submitted

Harrowland -> Comments only
Preferential Treatment -> Comments only
Mirage Maker -> Comments only
Sacred Statue -> Comments only
Yakstraction -> Comments only
Hoarding Gold -> No Lua source
Keeping Time -> Comments only
Cavern Survival -> No Lua source
Multiplayer Treasure Grove -> Comments only
Defend the Garrison -> Comments only
Doom Glade -> No Lua source
Tactical Timing -> Comments only
Arcane Ally -> Comments only
Munchkin Harvest -> Comments only
Shield Rush -> Comments only

Lurker -> Uses a while loop
Odd Sandstorm -> Uses a while loop
Desert Combat -> Uses a while loop

Sarven Seige -> Unable to access

**Comment by divyanshu013** [comment]
That should cover all @nwinter

**Comment by nwinter** [comment]
Wonderful! Good hustle, team. Hopefully we can soon apply the same simple loop logic for CoffeeScript and do the same thing for those levels.
