### ISSUE TITLE
Enemies struck with the lightning bolt spell become invincible zombies

### ISSUE THREAD

**Issue by JoshuaSpears** [codecombat/codecombat#2423]
The lightning bolt spell that comes with the lightning twig weapon instantly reduces any enemy to 0 HP.  I did this to a 2900 HP Tharin on dueling grounds and reduced him to 0 HP in one shot.  It does the same to any enemy in the single player missions.  An enemy reduced to 0 in this way does not die, instead it plays the death animation, then continues to move and attack while laying on the ground, and cannot be killed.

**Comment by nwinter** [comment]
Oh my! That's quite nice. Although that is exactly what lightning bolts do in real life, our game should have Game Balance. ;) I'll fix it.

**Comment by nwinter** [comment]
Fixed it.
