### ISSUE TITLE
ReferenceError: seed is not defined when a level is loading 

### ISSUE THREAD

**Issue by AnirudhGP** [codecombat/codecombat#2424]
When I run codecombat on localhost and I select the first level for Python and click Play I get this error in the loading screen: 
    Error: ReferenceError: seed is not defined
    Check the JS console for more.
The loading screen freezes and I can't load the level.

**Comment by nwinter** [comment]
1. Go to http://localhost:3000/editor/level/dungeons-of-kithgard
2. Click Systems -> Existence
3. Paste your code here.

Also, does your rand.coffee initializer match this one exactly with how it references `@seed` and not `seed` throughout the constructor? https://github.com/codecombat/codecombat/blob/master/app/lib/world/rand.coffee#L1-L11

**Comment by nwinter** [comment]
Closing for now; I'm pretty sure this has to do with an old version of the code being loaded for localhost.
