### ISSUE TITLE
Improve Account Page

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#2426]
At the moment the [account page](http://codecombat.com/account) is looking quite bland when compared with how sleek the rest of the interface is.  
![](http://i.imgur.com/aZ5QImV.png)

**Comment by MonkStrom** [comment]
A couple of classmates and I want to try working on this issue. We're having some trouble finding the relevant files. Could someone tell us where we should be looking?

**Comment by nwinter** [comment]
Awesome! Here they are:

* [main-account-view.jade](https://github.com/codecombat/codecombat/blob/master/app/templates/account/main-account-view.jade)
* [main-account-view.sass](https://github.com/codecombat/codecombat/blob/master/app/styles/account/main-account-view.sass)
* [MainAccountView.coffee](https://github.com/codecombat/codecombat/blob/master/app/views/account/MainAccountView.coffee)

**Comment by chenq7** [comment]
I'm not sure how the account page should be changed. Do you think something like this would look fine?
![template](https://cloud.githubusercontent.com/assets/14229728/11570451/4d10ddd8-99c5-11e5-925a-cdbb2654479b.png)

**Comment by nwinter** [comment]
Hmm, I don't think mirroring part of the profile page on the account page is the right answer, because you already have to click an /account breadcrumb from one of the subpages to get there, so you were possibly just looking at the profile page, and it'd be redundant. This page should serve mostly as navigation. Maybe tiles more like /contribute would work better here?

**Comment by chenq7** [comment]
We made an account page similar to the on the contribute page, what are your thoughts on this? The boxes are there to show how much relative space we can use. We can add a background image to each box if provided and we can also add a description to each box (if needed).  
![accountpage2](https://cloud.githubusercontent.com/assets/14229728/11615324/6b1c4af2-9c2b-11e5-866f-d44fb4fafe9b.png)

**Comment by nwinter** [comment]
Sure, beats what we have now. I don't think we will have art for this for a while (the artist is busy drawing a ton of other stuff), and these are pretty self-explanatory, so I don't think we need a description.

**Comment by chenq7** [comment]
We were able to make the "log out" button but we are having trouble finding the file or code to make the button work. Can you give us any tips for making the button "log out" the user?

**Comment by nwinter** [comment]
Add an event subscription to [the view code](https://github.com/codecombat/codecombat/blob/master/app/views/account/MainAccountView.coffee) that calls the view's `@logoutAccount()` method, sort of [like this](https://github.com/codecombat/codecombat/blob/master/app/views/core/RootView.coffee#L25-L25):

```coffeescript
  events:
    'click .our-logout-button-class-name': -> @logoutAccount()
```

**Comment by MonkStrom** [comment]
Hey @nwinter, just realized we never really thanked you for all the help. I like we shouldn't have needed to ask for some stuff like finding files if we just looked a little harder. Again, thank you for guiding us.
