### ISSUE TITLE
Text-fit with focus on 1st campaign

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2427]
Mouse over 1st campaign -> text doesn't fit to browser window. 
Yeah, ru-translation is a bit wide (he-he).

![default](https://cloud.githubusercontent.com/assets/1132840/6426795/6dee214c-bf7c-11e4-9086-efd43d9e8595.png)

**Comment by divyanshu013** [comment]
@nixel2007 have you committed the changes? I'll have a look, currently I don't see any translation for it:
![ru issue](https://cloud.githubusercontent.com/assets/6682655/6431098/c250407a-c04a-11e4-9ead-a238e40691d8.png)

**Comment by nixel2007** [comment]
@divyanshu013 yeah, it's in production. stupid question - did you select russian language at main page?

**Comment by nixel2007** [comment]
@nwinter how is it possible?
chrome x64, win 8 x64

**Comment by nixel2007** [comment]
hm... could subscriber status affect to translation of campaigns?

**Comment by divyanshu013** [comment]
I don't know @nixel2007.

**Comment by nwinter** [comment]
There's nothing funky going on with the Russian i18n on this page as far as I know; it should just be working and too-long, so we need to slightly lower the font size for body[lang='ru'] on that element.
