### ISSUE TITLE
Line sync for translation

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2428]
What we have now: en.coffee as original text and a plenty of translation files for different languages.
When someone adds a new line to en - it's ok, next propagination and line will be synced in all files.
But when someone _change_ line it en - nothing happens.
The latest example - removing HoC-related text from the "teachers" tab - a lot of strings was changed. And now diplomats need to re-read all of strings in both en and i.e. ru files or blocks to sync the translation.
So... Is it real to make some script that will seek the history of en.coffee on git/github and add comments to lines or comment the whole line?

**Comment by nwinter** [comment]
That's a good idea. I didn't want to switch to new translation keys and lose the old translations for minor changes like this, where the old translated string is better than no string, but adding comments automatically indicating a change could be good. I don't know how easy it would be to pull off, though.

**Comment by nixel2007** [comment]
if the script will add comments to lines, we need to update the copy-i18n-tags.coffee - AFAIK it removes all comments from lines

**Comment by popey456963** [comment]
Being stupid here, couldn't the editor say that this line has been changed in en, and a program with Regex or something finds that, and adds a note to the end of said line to all other files?  Like:

1. Editor changes en.coffee
`slogan: "Learn to Code by killing ogres" //change`
1. During propagation, regex finds all versions of said comment
`[/]{2}change`
1. When it finds said change, it removes it
`line = line - change //if only it was this simple` and `lineno = x`
1. It then goes to every single file in the directory `for file in dir: `
1. And appends the line `text[lineno] = text[lineno] + "//change"`
1. Now, we keep the old translation, and tell the diplomats to change the new one.

|Lang |Before (en)|After (sp)|
|--------|---------------|-------------|
|EN|`Line //change`|`ChangedLine`|
|SP|`línea`|`línea //change`|

The downside is obviously that they have to trek back to en.coffee and see what the original words are, but that isn't very difficult.

**Comment by nixel2007** [comment]
and need to exlude deleting of that //change from non-en files - let diplomats delete this manualy when they correct the translation.
this is a good idea, but we face the "human factor" - you need to manualy add //change to en file. but i think it's a good price for this

**Comment by nwinter** [comment]
I just used this and it works well, except I had to modify it to not add `# {change}` to lines that hadn't been translated yet. Maybe I'm misunderstanding, but it seems like [this](https://github.com/codecombat/codecombat/commit/e6cf298ed3fa216256caba4417ef41f0aa8352b1#diff-78766be23221abb773927bbd42a4cc7dR49) should have done it. Instead, I have to run the i18n propagation twice, and then it works.

Can you take a look and maybe mod it so that I only have to run it once, and it won't add the {change} tag to untranslated lines?

**Comment by nixel2007** [comment]
Sure, I'll check it. Funny, I specially add support of inserting changes in translated like, don't know why :D

Also is it normal that some translations in vi.coffee were dropped?
