### ISSUE TITLE
Arguments at MoveUp/Down/etc method

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2434]
On some level i discovered that you can do
this.moveDown(2)
to make two down moves. but there is no info for that function argument in the methods' tips.

**Comment by Khoffee** [comment]
Which levels were you able to do that?

**Comment by nixel2007** [comment]
I'll try to find that level tomorrow.

**Comment by nixel2007** [comment]
I remember, that on level was big Blue fireball, that want to hit you, and you need to 

loop
Right(2)
Down(2)
It's a kithgard campaign with js language.

**Comment by nwinter** [comment]
You can do that in any level with the simple boots, but we don't want the players to have to worry about that kind of complexity at first, so it's only introduced in the premium levels (which do explain it). I want the docs to be as simple as possible before then, so I don't want to talk about arguments in those docs.
