### ISSUE TITLE
SSL gem install sass issue (Ruby Related)

### ISSUE THREAD

**Issue by nonlin** [codecombat/codecombat#2436]
There seems to be a security issue on the final step that requires you to install sass to run the environment. 

Could not find a valid gem 'sass' (>= 0), here is why: Unable to download data from https://rubygems.org/ - SSL_connect_returned=1 errono=0 state=SSLv3
read server certificate B: certificate verify failed (https://api.rubygems.org/latest_specs.4.8.gz)

There seems to be multiple solutions and does not occur to everyone. What personally worked for me was to use 

 gem sources -a http://rubygems.org/

HIt y for yes and then follow with gem install sass.

**Comment by nwinter** [comment]
No more sass gem dependency :)
