### ISSUE TITLE
Some characters do not load to be edited for issue #2422

### ISSUE THREAD

**Issue by tvdang** [codecombat/codecombat#2439]
I was trying to add the changed loop statements in conjunction to issue #2422  but some characters either do not have anything to be edited yet or does not load yet.Not sure if it's only my computer or not.

**Comment by nwinter** [comment]
Can you list which ones? It might be that they haven't been created, or perhaps it's that they are premium subscriber only and can't be opened in the level editor (although it should give you a nice "forbidden" message if so, so maybe we need to hook one up if that didn't happen).
