### ISSUE TITLE
Duplicated players in the multiplayer scoreboards

### ISSUE THREAD

**Issue by JoshuaSpears** [codecombat/codecombat#2443]
Somehow Dueling Grounds is now running 2 copies of my code for the same team (humans), with 2 different scores.  It seems I'm both the 4rd and 5th place player for my team.

One of them is an older version of my code that's using a different hero.

![dueling grounds scoreboard](https://cloud.githubusercontent.com/assets/5615355/6429239/1c85ce7e-bf7a-11e4-8d55-97caaaab6ee8.png)

**Comment by nwinter** [comment]
No idea what could have caused that second session to be created, but I've gotten rid of it, so you should be good to go. I'll wait until we can see some sort of pattern to the duplicate session creation to investigate that issue. Did you happen to open Dueling Grounds in the level editor or anything like that?

**Comment by JoshuaSpears** [comment]
No, I just updated my code and the hero I was using.  Nothing out of the ordinary.
