### ISSUE TITLE
Two Goals for Cavern Survival

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#2445]
![](http://i.imgur.com/DySv1O6.png)

**Comment by nixel2007** [comment]
<offtopic>double goal - double reward! :D</offtopic>

**Comment by popey456963** [comment]
@nixel2007 If only!

**Comment by divyanshu013** [comment]
Strange, I see it only once Popey.
![cavern survival](https://cloud.githubusercontent.com/assets/6682655/6431078/f2efd084-c049-11e4-83d7-c18dfc3b7444.png)

**Comment by popey456963** [comment]
Yeah, only one for me now.  Haven't seen a patch, must just have been a bug.  Strange that I saw it on both direct + normal.
