### ISSUE TITLE
Non-Highlighted Code + Weird OnClick Positioning

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#2447]
* Running Chrome Version 40.0.2214.115 m
* Window 7 - 64 Bit
* Using Book III and I am clicking on the items.
* Please ignore the code, I was changing from coffee to python because it was bugging.
![](http://i.imgur.com/rbeXvZq.jpg)

**Comment by popey456963** [comment]
Note, this occurs on all zoom levels, and on different resolutions.

**Comment by nwinter** [comment]
Hmm, can't reproduce; let me know if you see it again, and if you do, check the JS console for any fun error messages in there. Thanks!
