### ISSUE TITLE
Repeated Ladder Games

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#2448]
Although I believe this issue was raised earlier, and closed, it appears to have resurfaced.  (If the other issue wasn't closed, sorry, close this one, I just can't find it).

Of the 93 games I've currently played on the human cavern-survival ladder, I've won 64 and lost 29.  Out of these 29 lost games, I've lost 24 to Lativa - the second best player on the ladder (while I am but 103).

![](http://i.imgur.com/qTOocob.png)

Note on the image how Lativa is found 24 times.

I doubt this is meant to happen, playing a quarter of my games against one person seems to give one of the people a huge advantage (24 free wins) whilst the other person a huge disadvantage (24 definite loses).

**Comment by nwinter** [comment]
See [this thread](http://discourse.codecombat.com/t/simulation-improvements/3285). We need to get away from uneven `-submitDate` queries and get a better random distribution. @schmatz suggested:

> We can build similar in-memory data structures to support such operations in our app servers. We could preload the IDs of sessions to simulate into some array and randomly pick among them and refresh at some regular interval.
