### ISSUE TITLE
One more text fit bug in "Victory" window

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2452]
Beige "Register to save progress" button with victory_sign_up i18n-key.
In ru-traslation it is: "Зарегистрируйтесь, чтобы сохранить прогресс"

![1a51788e-c082-11e4-8a5c-7e27fc744b45](https://cloud.githubusercontent.com/assets/1132840/6436807/935bc75e-c0c6-11e4-9144-06406cf6f71c.png)

**Comment by nixel2007** [comment]
Now, if you plus this 2 buttons it says - register to continue :D

**Comment by nixel2007** [comment]
@divyanshu013 please link a screenshot we talked today

**Comment by divyanshu013** [comment]
If we should do it this way or not, what do you say Nick?
![ru victory](https://cloud.githubusercontent.com/assets/6682655/6441729/b360bbe6-c110-11e4-9002-0e336c42840a.png)

**Comment by nixel2007** [comment]
[offtopic] i think we could add new lable named "text-fit bug cause of ru-translation :D[/offtopic]

**Comment by nwinter** [comment]
I can't find another issue for it now, but also there's [this one](https://github.com/codecombat/codecombat/issues/2452):

![](http://virtual-host-discourse.global.ssl.fastly.net/uploads/codecombat/_optimized/a27/ba0/b306de915a_690x421.jpg)

**Comment by nixel2007** [comment]
@nwinter also looks similar to this https://github.com/codecombat/codecombat/issues/1917
