### ISSUE TITLE
i18n editor strings a pain when they don't fit in the input box

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2455]
Heard this from a Diplomat:

> Strings simply don't fit into lines. they too short and narrow to see all information at once. Part of time to read original text on left and check translated text on right is simply playing with mouse pointer or arrows.

So I guess we need to make the input fields bigger somehow, or rework the layout there a little bit. Maybe instead of having one horizontal row per translation, we have the source text above and the translation line directly below? This would give much more width and also probably be easier for Diplomats' visual attention switching.

**Comment by popey456963** [comment]
We could use text area instead, which allows the user to resize things.  Not sure how it would fair with the CSS however.  Example:
```html
<textarea rows="2" cols="25">
Default text goes here
</textarea>
```

**Comment by nixel2007** [comment]
Suggestion - we can rearrange strings. 
Now we have 
En string 1 - non-En string 1
En string 2 - non-En string 2

1st:
We can change view to 
En string 1
non-En string 1

En string 2
non-En string 2

2st - make resizable text-areas, but it's not necessary to if we'll make the 1st thing.
