### ISSUE TITLE
Glasses higher than wooden lose the findNearestEnemy() method

### ISSUE THREAD

**Issue by tchalvak** [codecombat/codecombat#2456]
Which is used in a lot of levels, and immediately causes default code examples to fail due to the lack of this convenience method.

It also requires much more verbose code instead of just one method call (2 nested method calls instead of 1).

**Comment by popey456963** [comment]
Would a good solution be just to keep the normal findNearestEnemy() function?

**Comment by tchalvak** [comment]
I expect so.  I believe the same problem exists with the self.findNearestItem() method, as well.  That comes up even less often in the early levels, does happen periodically.

**Comment by popey456963** [comment]
I think it's the only time we show how to send the result of a function to another function.  I'll go speak to other people about this.

**Comment by nwinter** [comment]
Hmm. I do want to encourage the progression from less-flexible to more-flexible methods, and keep the total number of API methods down. I think that if we had a way of just rewriting the default code to use `this.findNearest(this.findEnemies())` wherever it had `this.findNearestEnemy` if you were using the higher-level glasses, that would solve most of the problem and still let me encourage players to learn how to transition to using the more powerful APIs.

**Comment by nwinter** [comment]
I changed it to rewrite the default code if you are using the more-advanced glasses, so I think most of the frustration is gone. I do still want to encourage players to transition to the composed function method of doing it.

**Comment by popey456963** [comment]
Does this do the opposite as well?  More-advanced glasses to the basic functions?
