### ISSUE TITLE
IE9 - CreateJS Float32Array script error

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2457]
Unclear if this is causing functional problems, but it has in other areas for us in the past.
http://caniuse.com/#feat=typedarrays

![ie9createjsfloat32array](https://cloud.githubusercontent.com/assets/2965172/6446907/23f0942e-c0c3-11e4-928d-1bf49807bd0e.png)

**Comment by nwinter** [comment]
IE9 is not supported any more.
