### ISSUE TITLE
Changed hero leads to reversion to the default language of python, irrecoverably.

### ISSUE THREAD

**Issue by tchalvak** [codecombat/codecombat#2459]
I swapped out the default male hero for the default female hero, and my previously javascript code became unusable, with a very user unfriendly error of:
"Expected an identifier and instead saw ':',"
Clicking on the "help" button leads to a blank help area.

Presumably, this is because it's trying to execute the javascript code as python code, but importantly, I cannot re-specify that the hero use javascript.  It doesn't appear to save correctly, so whenever I change heros, specify the language as javascript, and go back in to the "backwoods brawl" level, I get the same problem.
![screenshot from 2015-03-02 18 45 47](https://cloud.githubusercontent.com/assets/23353/6453656/55086b72-c10e-11e4-8ad9-8152364f980a.png)

**Comment by popey456963** [comment]
Your code appears to use both JS and Python.  Example:
```
";" is used to end some lines.  This is JS.
":" is used after if and else statements.  This is Python
```

**Comment by tchalvak** [comment]
How very weird.  I'm a web programmer, so I am of course familiar with the JS {} syntax.  However, while going through the game, I assumed that `loop:`  `if():` and `elif():` was a DSL specifically for the game, to make it easier for you guys to parse the generated code.  I swear the tutorials started me off with lots of `if(e):` stuff.
