### ISSUE TITLE
The Raised Sword bug

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2462]
When the level asks me to buy the Tarnished Bronze Breastplate, it also makes me equip it. Then, when the level reloads, I already have it equipped, but there appears a tip that tells me to equip it.

**Comment by nwinter** [comment]
Can anyone else reproduce this? It seems to go away properly for me when following the normal flow.

**Comment by Imperadeiro98** [comment]
Seems like it is fixed now.

**Comment by Imperadeiro98** [comment]
What happens is that the player is prompted to go to the store and buy the item. Then, it asks to equip and the page reloads. After this, the tip 'Equip the new breastplate to win the fight.' appears.

**Comment by nwinter** [comment]
I still can't reproduce. After the page reloads with the new breastplate equipped, the script is gone.

**Comment by Imperadeiro98** [comment]
Yeah, you are right
