### ISSUE TITLE
Auto complete of "do" to "distanceTo" makes Lua sad.

### ISSUE THREAD

**Issue by basicer** [codecombat/codecombat#2467]
When typing lua code into the spell editor, ace auto completes "do" to "self:distanceTo", and because do is the last thing that goes on a line for a block, pressing enter as you would do to end a line auto completes.

**Comment by nwinter** [comment]
I guess this is the same fuzziness issue that gets you when doing a range of other programming keywords that try to match autocompleted methods even when they are way too short and don't match that well.

**Comment by nwinter** [comment]
This is fixed.
