### ISSUE TITLE
World selector shows mountain locked after completing mountain levels

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2473]
Can still go to desert and navigate to mountain via purple arrow.

![screen shot 2015-03-05 at 11 13 12 am](https://cloud.githubusercontent.com/assets/2965172/6512421/c25e7e16-c328-11e4-9adc-fa425bd8c9f4.png)

**Comment by Vlevo** [comment]
Did you finish "Clash of Clones"?

because I see:

![mountain](https://cloud.githubusercontent.com/assets/11031492/6520467/41c762a8-c383-11e4-80b3-068eb89d8072.png)

**Comment by differentmatt** [comment]
Yes, I did finish Clash of Clones.

![screen shot 2015-03-18 at 10 13 24 am](https://cloud.githubusercontent.com/assets/2965172/6714795/8143a9f4-cd57-11e4-8564-3fb73fce4f1d.png)

**Comment by Vlevo** [comment]
I see the arrow.
Is it that you can't click on it (screen "too small" and they overlap or?) I have a hard time hitting the arrow from the forest to the desert, because it think I am hitting "Siege of Stonehold" instead.

**Comment by nwinter** [comment]
We found it. Workaround: `localStorage.clear()`. Affects only admins who might have edited the non-versioned Campaign in the campaign editor, because we still haven't done #2061.
