### ISSUE TITLE
Wrong graphic used in surface for Boom Ball

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2474]
Saw this on a leaderboard replay of clash of clones.

![screen shot 2015-03-05 at 3 26 26 pm](https://cloud.githubusercontent.com/assets/2965172/6517046/0b6d5f14-c34c-11e4-89a6-da5847d03126.png)

**Comment by nwinter** [comment]
I updated all the high-end ranger missiles to have the proper missile graphics, and also fixed an issue preventing all ranger charge explosion animations from firing.
