### ISSUE TITLE
moveXY

### ISSUE THREAD

**Issue by pemaolca** [codecombat/codecombat#2475]
Peasant Protection, in the Blackwoods Forest:

I'm having a little problem with getting the mission complete.

I'have seen post on how to do it but all involves the moveXY code...

And i'm unable to use that command, It says that, that book is restricted

Can anybody shed some light on this problem? Please...

Thanks

**Comment by popey456963** [comment]
the `moveXY` code is not given by a book, it is given by shoes.  By peasant protection, it is almost essential to have `moveXY`.  Thus, you should go buy the book.

If you don't have enough gems, you can go get more by simulating a few games.
