### ISSUE TITLE
Python else if doesn't give warning

### ISSUE THREAD

**Issue by txomon** [codecombat/codecombat#2478]
I have discovered that "if else" in an script isn't interpreted as a syntax error.

![Codecombat example](https://cloud.githubusercontent.com/assets/228250/6537864/52a0ed1e-c45b-11e4-9ab0-f31b0ff94195.png)
![iPython Notebook example](https://cloud.githubusercontent.com/assets/228250/6537865/52a1f970-c45b-11e4-8554-454d92df75a1.png)

**Comment by differentmatt** [comment]
Fixed in latest Filbert: https://github.com/differentmatt/filbert/commit/710be7a2faba8e7adff57e708ecb3b36f7af6fb3
