### ISSUE TITLE
Ariving /play/forest doesn't grant moveXY() for Peasant Protection

### ISSUE THREAD

**Issue by txomon** [codecombat/codecombat#2479]
In the level, you are required to stay close to the peasant, but there is no way to move next to it! 
![Peasant Protection](https://cloud.githubusercontent.com/assets/228250/6538187/558cd692-c45f-11e4-856e-8311cc2c0b16.png)

**Comment by txomon** [comment]
Just in case, the problem is that the boots are not adequate =)

**Comment by nwinter** [comment]
I've made it so that it requires the proper boots equipped to do this level.
