### ISSUE TITLE
Clojure and explicit do

### ISSUE THREAD

**Issue by Vlevo** [codecombat/codecombat#2480]
When I use an explicit "do" (instead of implicit ones such as "when true") nothing happens.

(using code from "endangered-burl" not because the level wants it but because it makes for a nice test bed)
```
(if (= (.type enemy) "ogre")
            (when true
                (.say this "Run Away!!")
                (.moveXY this 22 47)))
```
Works great, see the ogre, says "Run Away!!", then she does it...

But
```
(if (= (.type enemy) "ogre")
            (do
                (.say this "Run Away!!")
                (.moveXY this 22 47)))
```
Does nothing. My hero just stands there. The results of the two should be exactly the same.

**Comment by nwinter** [comment]
@vickychijwani this code should work in closer.js, right? I wonder what the difference between the generated code is.

**Comment by vickychijwani** [comment]
Yes it should work. The difference is that `do` creates a new function scope, `when` does not. Here's the Clojure => JS translation:

```clojure
(def enemy (clj->js {:type "ogre"}))
;; using when:
(if (= (.type enemy) "ogre")
    (when true
          (.log console "working!")))
;; using do:
(if (= (.type enemy) "ogre")
    (do (.log console "working!")))
```

```js
var enemy = closerCore.clj_$__$GT_js.call(__$this, closerCore.hash_$_map(closerCore.keyword('type'), 'ogre'));
// using when:
if (closerCore._$EQ_.call(__$this, typeof enemy['type'] === 'function' && enemy['type'].length === 0 ? enemy['type']() : enemy['type'], 'ogre'))
    if (true) {
        console['log']('working!');
    }
// using do:
closerCore._$EQ_.call(__$this, typeof enemy['type'] === 'function' && enemy['type'].length === 0 ? enemy['type']() : enemy['type'], 'ogre') ? function () {
    return console['log']('working!');
}.call(__$this) : null;
```

**Comment by Vlevo** [comment]
I am WAY out of my depth here, but...  (gotta love those buts)

It seems like the "do" should just make a { ... } block and not a function since the "when" doesn't create a function . . . or . . . when should also be a function.

"https://clojuredocs.org/clojure.core/when" says:
when
(when test & body)
Evaluates test. If logical true, evaluates body in an implicit do.

(clojure "expects" a return from the last expression of the when same as the "do", "when test & body" really is a "if test do body")

**Comment by vickychijwani** [comment]
@Vlevo you're right, `when` should ideally introduce a new function scope. But I didn't implement it that way because: (a) Aether used to have issues with nested functions in user code (and still does, as this issue suggests), and, (b) `when` is a frequently-used construct, unlike `do` (which I've personally never used when solving CodeCombat levels; I added it for the sake of completeness).

Also, I just realized, the original code can be written idiomatically as:

```clojure
(when (= (.type enemy) "ogre")
      (.say this "Run Away!!")
      (.moveXY this 22 47))
```

The whole point of `when` is that it's an `if` with a multi-line body.

**Comment by nwinter** [comment]
And with me writing the sample code while not knowing Clojure but just trying to imitate examples, I went and put `if` + `do` everywhere, hah!

@Vlevo Any interest in updating all the levels' sample code to use `when` when appropriate instead? At least we can work around the bug for a while and teach more idiomatic Clojure.

**Comment by Vlevo** [comment]
There appears to be no else for when in clojure.

So as long as the "if" getting replaced doesn't need an "else" then "when" makes a good replacement.

**Comment by Vlevo** [comment]
OK, I know I am changing the scope here (but, this is related to the fixing of (if ... (do )) sample code.

In the level Ogre encampment it seems to me that "if-let" would be the idiomatic clojure way to handle the problem (amazing what one can think one has learned in a couple of days...) :-)

So I treid it.
```
(dotimes [n 1000]
    (if-let [enemy (.findNearestEnemy this)]
        (.attack this enemy)
        (.attack this "Chest")
    ))
```
It looks like it "highlights" the "if-let" the same way it does "dotimes" (changes the color) but gives an error when I try to run it: "ReferenceError: if_$_let is not defined"
![if-let](https://cloud.githubusercontent.com/assets/11031492/6569577/7bef783a-c6b2-11e4-8fe2-7499c4d5da39.png)

So the first question is: Why does it recognize it ("highlight" if it is not defined)??
and the second is...: How "idiomatic" vs "same as the other languages" is codeCombat going for?
iow: should this be (let [enemy ...] (if enemy (then) (else)))" or the "(if-let [] (then) (else))"??

I haven't checked the other if-/when- forms yet. (-let, -not, -some)

**Comment by vickychijwani** [comment]
`if-let` isn't implemented in closer.js yet. Actually, the thing is, Clojure has Lisp macros, which makes it trivial to add constructs like `if-let`, `when-let`, etc. Closer.js doesn't have macros, so it requires significantly more effort to implement these constructs.

The reason `if-let` is still highlighted is because the syntax highlighter only knows that `if-let` is a valid *Clojure* construct; it's independent of closer.js.

**Comment by nwinter** [comment]
Closing for now since we can't currently support Clojure with the new interpreter.
