### ISSUE TITLE
Item shop doesn't expand function descriptions for Compound Boots

### ISSUE THREAD

**Issue by delve** [codecombat/codecombat#2484]
When selecting the Compound Boots in the Item Shop the list of functions in the description pane does not expand to show the function descriptions. Clicking on some other equipment (like Reinforced and Softened Leather Boots) exhibits similar behavior.
After clicking on Boots of Jumping the descriptions in the affected items will all expand.

**Comment by delve** [comment]
A picture is (sometimes) worth a thousand words. Maybe a video will be worth 54 in this case.
https://www.youtube.com/watch?v=gBuMjCNe9kA

**Comment by nwinter** [comment]
Bug is probably somewhere around [this code](https://github.com/codecombat/codecombat/blob/master/app/views/play/modal/ItemDetailsView.coffee#L32-L58).

**Comment by sirui-sun** [comment]
Looks like for the affected items, the call to docs.fetch is returning with an empty list, suggesting an issue with the underlying database?

**Comment by DBowlerHB** [comment]
Submitted thang patches to all the broken boots.  Fixed in dev.

**Comment by nwinter** [comment]
Wow, that took me a while to notice! Sorry for the late patch acceptance; got it in there now. Thanks!
