### ISSUE TITLE
Clojure Broken in Shield Rush and Patrol Buster

### ISSUE THREAD

**Issue by jllogan** [codecombat/codecombat#2487]
Please see http://discourse.codecombat.com/t/clojure-version-of-shield-rush-broken/3007 and http://discourse.codecombat.com/t/help-only-killing-1-ogre-in-patrol-buster-with-clojure/2817/13?u=jllogan for details.

**Comment by Vlevo** [comment]
There does seem to be a problem here (beyond the simple dotimes cycling into infinity) . . .  "shield" seems to take no time.

10,000 shield actions should take 4,000 seconds not ~8.4 (the "help" for" shield says "Takes: 0.4 s.")
![Uploading shield - no - takes.png . . .]()

I just switched to Tharin, who I believe has a shield animation . . . nothing, he just stands there, never even twitches. "(dotimes [n 10000] (.shield this))"

**Comment by nwinter** [comment]
`shield` will only take time if it is performed as an action; doesn't this mean that yielding is still not working properly, maybe not inside the `else` area? Does any other action in place of `shield` take time here, like the single-frame `move`?

**Comment by Vlevo** [comment]
OK, with moveXY & move() boots moving/oscillating  1 'x' he happily wiggles back and forth until they kill him.
```
;; moveXY
(dotimes [n 10000] (.moveXY this (+ (- (mod n 3) 1) 40) 35))
;;move()
(dotimes [n 10000] (.move this (clj->js { :x (+ (- (mod n 3) 1) 40), :y 35}) ))
```
also tested the "full" code:
```
(dotimes [n 10000] 
    (if (.isReady this "cleave")
        (.cleave this)
        (if (= 0 (mod n 1000))
            (.say this n)
            (.move this (clj->js { :x (+ (- (mod n 3) 1) 40), :y 35}))
    )))
```
![shieldbash](https://cloud.githubusercontent.com/assets/11031492/6568365/f3488d98-c69b-11e4-8102-0316db9cb38b.png)

My hero survives the onslaught (lost 168hp) until the second cleave by "wiggling".

**Comment by Vlevo** [comment]
I switched the shield into the "then clause" still does nothing. :(

**Comment by nwinter** [comment]
Oh man, I finally realized that the `shield` method was never made plannable this whole time. Oops! I think I have fixed it now.
