### ISSUE TITLE
Speed up initial MongoDB connection times

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2489]
It takes 33 seconds to connect to the MongoDB queue:

```
2015-03-09T16:04:24.911Z - info: Express SSL server listening on port 3000
2015-03-09T16:04:57.732Z - info: Successfully connected to MongoDB queue!
```

I don't know why it takes so long, but it probably doesn't help deployment times, and it definitely doesn't help local development times when using the production database. Maybe there's a way to make this faster? (What could possibly take 33 seconds in internet world?) @schmatz can you take a look?

**Comment by schmatz** [comment]
I'll take a look later, but I highly suspect it has something to do with local configuration. My connection reliably takes less than one second.

```
2015-03-09T16:27:31.625Z - info: Express SSL server listening on port 3000
2015-03-09T16:27:32.287Z - info: Successfully connected to MongoDB queue!
```

**Comment by schmatz** [comment]
Connecting to the replica set caused this issue, connecting directly to the primary speeds this up. Connect to the replica set if doing important things and need failover.
