### ISSUE TITLE
"It's" should be "its" in Thunder Hooves

### ISSUE THREAD

**Issue by robmuh** [codecombat/codecombat#2491]
cuz grammar

**Comment by J-F-B-M** [comment]
Hello robmuh.
You can use the level-editor to fix this yourself. Try it, using the editor can be fun. And maybe you soon build levels yourself.
The link to the level:
codecombat.com/editor/level/thunder-hooves

**Comment by robmuh** [comment]
Can the level editor be used to add simplier handling of list iterations as
well or is that a violation.

*Rob Muhlestein*
@SkilStak <http://twitter.com/skilstak>, Inc.
rob@skilstak.com
704-310-6778
@robmuh <http://twitter.com/robmuh>

**Comment by nwinter** [comment]
We probably wouldn't accept a patch for that, because we still think that extending `while` to cover list iteration before introducing `for-in` makes more sense for the campaign progression.
