### ISSUE TITLE
Improve method of finding next poll

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2494]
Currently we just [find the next one with the highest priority after the previous-most-recently-answered poll](https://github.com/codecombat/codecombat/blob/master/server/polls/poll_handler.coffee#L26-L40), but this doesn't let us insert polls in the middle or change priorities.

**Comment by nixel2007** [comment]
i didn't look in details but...
it's a sql dbms, right? you could add a trigger/proc for inserting values in the middle with re-index table.

**Comment by nixel2007** [comment]
or maybe add some view that will selects with sorting by priority (as separate field) AND uid (PK)

**Comment by nwinter** [comment]
I made it so that it actually finds the next unanswered poll, taking into account which have been answered.
