### ISSUE TITLE
Text-fit bug - /play - items

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2497]
![image](https://cloud.githubusercontent.com/assets/1132840/6581282/f4e9bade-c766-11e4-91db-f03b96988484.png)

So, "unlock" buttons don't fit. Full text is "Разблокировать"
ru-locale.

**Comment by Imperadeiro98** [comment]
This also happens with pt-PT.

**Comment by nixel2007** [comment]
closed via 599f18344e0738b8e81ec99fec0309e0df8b09f4
