### ISSUE TITLE
Mixed content warnings

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2505]
See [this forum post](http://discourse.codecombat.com/t/https-mixed-content-bugs/3035):

Analytics:

> Mixed Content: The page at 'https://codecombat.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://analytics.codecombat.com/analytics'. This request has been blocked; the content must be served over HTTPS.

At Game:

> Mixed Content: The page at 'https://codecombat.com/play/level/gold-rush?team=ogres&opponent=539c88756e1d923105078f04' was loaded over HTTPS, but requested an insecure resource 'http://ghbtns.com/github-btn.html?user=codecombat&repo=codecombat&type=watch&count=true'. This request has been blocked; the content must be served over HTTPS.

And:

> Mixed Content: The page at 'https://codecombat.com/play/ladder/gold-rush#my-matches' was loaded over HTTPS, but requested an insecure resource 'http://ghbtns.com/github-btn.html?user=codecombat&repo=codecombat&type=watch&count=true'. This request has been blocked; the content must be served over HTTPS.

**Comment by schmatz** [comment]
We should be able to fix the latter two by just replacing the http with https in the links. For the analytics server, I'll set up TLS.
