### ISSUE TITLE
Background in /i18n

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2508]
If you have a page with a lot of strings to translate, background fill (texture?) doen't cover all page.
If you scroll down you'll see this
![default](https://cloud.githubusercontent.com/assets/1132840/6606556/6cbed26e-c849-11e4-91bb-b15bb22857fd.PNG)

**Comment by nwinter** [comment]
Fixed by 5e80bb6.

**Comment by nixel2007** [comment]
Really? O_o
No new line crashes output css?
