### ISSUE TITLE
Next pay-date counts wrong

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2522]
So, my last paid was made march, 8
![2](https://cloud.githubusercontent.com/assets/1132840/6652455/8441e33e-ca80-11e4-8390-c525cbf0a763.PNG)

In "Subscription" windows system tells me that next charge will be today
![default](https://cloud.githubusercontent.com/assets/1132840/6652462/b18bea56-ca80-11e4-90f4-f294164eda85.PNG)

**Comment by nwinter** [comment]
@differentmatt can you check this out?

**Comment by Imperadeiro98** [comment]
I think this was fixes by [this](https://github.com/codecombat/codecombat/commit/b696c916c0eea96a0921af30cb6f76ad336eb913) commit.

**Comment by nixel2007** [comment]
Yeap, looks like you're right.
