### ISSUE TITLE
Clojure global "def" not global

### ISSUE THREAD

**Issue by Vlevo** [codecombat/codecombat#2541]
In clojure the "def" statement should be "global" but it isn't.

http://clojuredocs.org/clojure.core/def
"def: Creates and interns or locates a global var with the name of symbol and a
namespace of the value of the current namespace (*ns*)."

CodeCombat
```
(def bar 6)
(defn foo [a b] (def bar b) (* a b))
(.say this (str (foo 2 3) " " bar))
```
should say: 6 3
but says: 6 6

http://www.tryclj.com/
```
> (def bar 6)
#'sandbox21848/bar
> (defn foo [a b] (def bar b) (* a b))
#'sandbox21848/foo
> (print (str (foo 2 3) " " bar))
6 3nil
```

**Comment by Vlevo** [comment]
This one appears to be in Closer.js (as the demo site also outputs "6 6")
@vickychijwani

**Comment by nwinter** [comment]
Closing for now since we aren't currently supporting Clojure with new interpreter in Aether.
