### ISSUE TITLE
diplomat page - possible broken link

### ISSUE THREAD

**Issue by ChaosCat** [codecombat/codecombat#2544]
<h2>Result after the page is done loading (see image below):</h2>
![issue](https://cloud.githubusercontent.com/assets/10373239/6740773/640d1c1e-ce8b-11e4-92ee-2e06182390ff.png)
<br>
<h4>possible broken link <i>on firefox:</i></h4>
http://codecombat.com/contribute/diplomat
<br>
<h5><i>I have tried:</i></h5>
<b>1.</b> Loading page in different languages.
<b>2.</b> Refreshing page.
<b>3.</b> Disabling adblock.
<b>4.</b> Closing and re-opening browser,

**Comment by nwinter** [comment]
I fixed this in aae44c2, but I haven't gotten a working production deploy pushed yet, so it's not live yet. Soon!
