### ISSUE TITLE
Offline installation and some issues...

### ISSUE THREAD

**Issue by entrptaher** [codecombat/codecombat#2546]
CodeCombat seems really interesting.. :) , so I went ahead and tried to install into windows... When I failed, I tried to install it inside Ubuntu Studio...

Heres what I did and what happened on windows...
1. I followed all instructions and it couldn't download some files from npm registry despite of using both http and https connection...

Heres what happened on Linux...
1. I installed all dependencies and it stuck on node-gyp rebiuld...
2. In linux, there was no such error downloading from npm registry...

So basically, the problem lied on NodeJS... Its not CodeCombats fault.

Now what I wanted to say,
People are trying and succeeding but I'm not, So, I guess I'm at fault and its only me. Someday I'll succeed running CodeCombat from localhost...Maybe soon, maybe in distant future...

When I use Atom, Brackets, Netbeans, Aptana, Ruby/Mean/Lamp stacks, or thousand other automatic/portable solutions, they are painless to install, fast to run... but this is the first game in my life, Which downloaded some files over and over for whole night and still ran through errors...

I mean, there is no simple way, 
say, I want to learn Python by playing CodeCombat, I had to do a lot of other things "just to learn python basics"? Then it becomes just another irritating pain...

I am submitting this as an issue with the following problems on my hand,
- It downloads and rebuilds node (and some other packages), over and over again (on Linux).
- It stuck on http/https problem when downloading files from npm registry (on Windows).

# Suggestions:
- Create a virtualbox with everything set up inside. Maybe add some update script too to update the database dump. Maybe use port-forwarding and minimize the vbox size too. (ref: Bitnami Ruby Stack Virtual Machines...), or try vagrant/docker too?? 
- Create All-in-one setup file or Archive file with everything in it...So user can excute a single start script and navigate in the browser/use chrome-shell...
- Remove unnecessary file download codes, ask to install everything globally to remove basic problems.
- Maybe take advantage of Chocolatey...?

Why not I fork and do everything myself?
- Yeah, thats a clever idea, maybe I'll try it someday, and if I succeed, I'll not allow others to see it. I think some other person already has it installed in their virtualbox, they just don't feel to share it. You are super genius, ask them to help through your website... ;) ...

Sorry for my poor english, I guess you would understand what I'm saying if you are a genius.

**Comment by nixel2007** [comment]
Hello!
But there is all-in-one installers already for win and linux. do you try them?
there may be some problems for win like installing sass or not working SCOCODE.bat. but there are workarounds also.

**Comment by entrptaher** [comment]
See, I tried every possible way, ended up same and listed my problems exactly how it occurred. 
All in one installer means not a single script file, I meant a big archive with everything inside it...
I suggested some other things that would make it super easy as a noob could do.
Maybe you could do it and release a VBox tomorrow, it really could be done that fast.

**Comment by nixel2007** [comment]
but you need some configuration to pulling new code from gh, to make commits.
you could easily do a snapshot of working dev-enviroment. but if you want to contribute you must do some config-things.
but i agreed with you that ready-to-go snapshot with single config is better then setup script.

**Comment by entrptaher** [comment]
There are people who want to test things and not contribute first-hand, if they want to contribute, they would have to do something that an archmage does. You wouldn't make a nice game only for those who want to contribute...now, would you?

Note: Still unsolved. There's no way I would give it another try after trying for a whole day... Maybe I will try the online version and just wonder why it didn't work here...

Anyway, Maybe you can close the issue if you feel like it.

**Comment by nwinter** [comment]
What about #2106?

**Comment by popey456963** [comment]
Might it be easier just to fix the node-gyp problems and http problems you are facing?  Even a person with no computer skills is able to copy and paste six commands from the wiki into their command line (if it works).  Also, it's better to have one solution for everyone, so that we don't have to consistently update numerous auxiliary builds.  For example, the windows build isn't working for anyone, which will mean that it has to be updated, which takes time away from working on the core aspects of the website.

**Comment by entrptaher** [comment]
The most problems with installations were related to nodeJS mostly, like 'bower install' and stuff.
So no matter what strategy you try, if a small dependency didn't install, you get a lot of bug while running your CodeCombat.

Thats why I asked for if someone has any compiled/portable file/ISO/Virtualbox disks file. Because someone could have bad internet connection to wait for the installation to finish. I know its hard, but,
its like, building Ubuntu from Source vs Downloading ISO or Virtualbox disks, and using it right away and I could always update whatever I need and revert back if there is any problem.

This issue was dragged for a long time and it still remains open.

I wish CodeCombat releases some better solution so that we can recommend it better. ^_^

**Comment by popey456963** [comment]
Sorry for the lack of updates, I haven't been available due to personal reasons.  There is a virtual box currently being made, soon to be released.  I haven't had any updates, but we've already got it to have CoCo installed by default and are looking into networking, so that it can be accessed outside the box.

You can see the current version in this repo.

**Comment by entrptaher** [comment]
I think this issue will never be solved if no one builds a box and makes that public. Node repo can have problems all the time, but a box/iso file wouldn't hurt anyone. Linux distros does this all the time, they makes things easier, they don't tell people to build a distro from scratch.

Vagrant is useful but sometimes, building from base has huge downside. Running a vagrant is pretty much same as building codecombat from scratch. It takes hours and hours compared to just downloading and distributing the packed file among several person.

Sadly, I couldn't recommend codecombat to any of my friends who wanted to play it offline. They couldn't just get it right. If they have to be a master of programming and bug testing even before starting the game, then there are no point of them playing the game to learn programming.

**Comment by entrptaher** [comment]
:( No one shared a box/image even after all these months.
I'm very disappointed.

**Comment by xav2211** [comment]
Up, Sorry for the up, but I search for a virtualbox image of a CodeComat working server... do yu know one image somewhere ?

**Comment by okoklol1212** [comment]
Hey, I use Virtual Machine and run Ubuntu OS 
Then, I follow this [tutorial ](https://linuxhint.com/codecombat-multiplayer-game-linux/) https://linuxhint.com/codecombat-multiplayer-game-linux/ 
I stuck on the command line "$ npm run dev" 
I closed the terminal and proceed to the next line "$ npm run proxy" then it works!
