### ISSUE TITLE
i18n es-Es option-code-language

### ISSUE THREAD

**Issue by v0tka** [codecombat/codecombat#2550]
The translation should be "Sintaxis"
![2015-03-21-003304_1366x768_scrot](https://cloud.githubusercontent.com/assets/11511250/6763593/f33637dc-cf61-11e4-9b12-c9f6373739bd.png)

**Comment by Imperadeiro98** [comment]
You can try to fix it.

Just fork the project, go to [this](https://github.com/codecombat/codecombat/blob/master/app/locale/es-ES.coffee#L466) line (in your project) and correct it. You can also correct other translations, if you want. And then make a pull request.

**Comment by Imperadeiro98** [comment]
Fixed by #2551.
