### ISSUE TITLE
Ladder ranking

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2553]
I saw this bug in the ladder, where after the ... the places start repeating.

![sem titulo](https://cloud.githubusercontent.com/assets/6980488/6764966/b0eb0d20-cfc1-11e4-9c10-38bf9467b47c.png)

**Comment by nwinter** [comment]
I think this was just in Zero Sum? I was doing weird things for that ladder for the Singapore tournament, where I had unsubmitted the playtesters' sessions. I've resubmitted now, so it should be working again.

Let me know if it was another ladder you saw this on.

**Comment by Imperadeiro98** [comment]
Yeah, only Zero Sum.
