### ISSUE TITLE
Spectate improvements

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2556]
In spectate mode, we should show some more cool things:

- [x] Big player health bars
- [ ] Each hero's current action
- [x] Who won
- [x] Number (power?) of units alive, and maybe total units built

**Comment by nemoyatpeace** [comment]
Also, having the player name in bold above the player tends to block the action.  Better would be if there were a way to highlight the player in some simpler way (particles - red for human, blue for ogre).
