### ISSUE TITLE
Resizable/Fullscreen code editor

### ISSUE THREAD

**Issue by coder0xff** [codecombat/codecombat#2560]
Sometimes, when writing larger amounts of code, the provided editor is a bit small. I find myself copy/pasting to and from Notepad++ a lot.

**Comment by nixel2007** [comment]
Hello!
Do you try to play in fullscreen mode?

**Comment by coder0xff** [comment]
Definitely, but my "gaming rig" is a modestly sized laptop.

**Comment by nixel2007** [comment]
What screen resolution do you have? 

Отправлено с моего HTC

----- Ответное сообщение -----
От: "coder0xff" <notifications@github.com>
Кому: "codecombat/codecombat" <codecombat@noreply.github.com>
Копия: "Nikita Gryzlov" <nixel2007@gmail.com>
Тема: [codecombat] Resizable/Fullscreen code editor (#2560)
Дата: пн, марта 23, 2015 20:22

Definitely, but my "gaming rig" is a modestly sized laptop.

On Mar 23, 2015 9:31 AM, "Nikita Gryzlov" <notifications@github.com> wrote:



> Hello!

> Do you try to play in fullscreen mode?

>

> —

> Reply to this email directly or view it on GitHub

> <https://github.com/codecombat/codecombat/issues/2560#issuecomment-84998002>

> .

>



&mdash;

**Comment by coder0xff** [comment]
Not at home to check, but I think it's 1366x768. The in-editor API
reference doesn't fit on screen unless I scale down in my browser.

**Comment by nwinter** [comment]
@coder0xff any better now with the improvements I made for #1777?

We could do the work required to bring back the fullscreen code editor button, which is turned off for hero levels [here](https://github.com/codecombat/codecombat/blob/master/app/templates/play/level/tome/spell_list_tab_entry.jade#L21-L24) and has some logic [here](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/SpellListTabEntryView.coffee#L108-L113) and styling [here](https://github.com/codecombat/codecombat/blob/master/app/styles/play/level.sass#L254-L263) and maybe somewhere else.
