### ISSUE TITLE
Goldstorm doesn't stay in bounds

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2563]
When casting goldstorm, the cloud passes over walls and drops coins outside the bounds.

![image](https://cloud.githubusercontent.com/assets/6550021/6781587/c45248bc-d1a9-11e4-952f-267f48ce5378.png)

Thinking that the cloud should bounce off of walls, but not sure how to make that happen.  Might need a new component, maybe `movement.Bounces`

**Comment by nwinter** [comment]
Got it, thanks!
