### ISSUE TITLE
Counting Levels doesn't work on Mountain Stage

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#2565]
![](http://i.imgur.com/irNDHBf.png)

![](http://i.imgur.com/8ep4Yqh.png)

**Comment by Vlevo** [comment]
I think the "world" page is showing fully released and the "region" page is showing full & adventurer.

**Comment by popey456963** [comment]
I haven't finished any subscriber levels, those should be counted.  If we're following the same pattern as previous levels @Vlevo

**Comment by Vlevo** [comment]
Yes, no subscriber levels in yours would make the 5/5 make sense (mine is 8/8) I can make sense of those numbers (if you did it, it must exist). I think there is another problem here as well.
'cause mine should be 9/9 and 9/10 but it is 8/8 and 9/10. I can understand the 10 (future level started but not submitted, I guess I'll go submit and see what happens) but why have I completed 9 but only show 8. Seems like one of the adventurer levels from last week isn't getting counted... Is there one you haven't done?

**Comment by popey456963** [comment]
Also, (unfortunately I don't have an image) I was getting 3/3 and 4/4 as I was completing levels.  I don't think it's just not counting subscriber levels.

**Comment by nwinter** [comment]
Try doing a `localStorage.clear()` and seeing if the count updates.
