### ISSUE TITLE
Inventory freeze

### ISSUE THREAD

**Issue by matheod** [codecombat/codecombat#2574]
Hello,

This bug doesn't happend everytime : 
I start a level (the bug happend with different level, but I have only seen it on level with limited item), then I click on play -> the inventory panel open.

I try to click on an already equiped item and ... nothing hapend, the right panel doesn't show information about the item. In fact when cliking on already equiped item, nothing happend.
But not equiped item work perfectly (I can see information and equip them). Last information, if I equip an not equiped item, I still can't see information about it, but I can unequip it with double click (doesn't work with equiped item since the start).

Here the console log :

````
ThangType.coffee:459 Trying to determine whether Bronze Shield should be a silhouetted item, but it has no gem cost.
ThangType.coffee:459 Trying to determine whether Simple Sword should be a silhouetted item, but it has no gem cost.
ThangType.coffee:459 Trying to determine whether Sundial Wristwatch should be a silhouetted item, but it has no gem cost.
````

**Comment by nwinter** [comment]
Trying to figure this one out. Can anyone else reproduce this? @matheod which browser (or does this happen in all browsers)?

**Comment by matheod** [comment]
It was on google chrome (sorry to forgot to mention it). I tried to reproduce again on chrome but I couldn't. May have been fixed by something or may be a nasty bug requiring specials conditions.

Also : still got the error in the console log, so these errors are probably unrelated.

**Comment by nwinter** [comment]
Sounds like it might have been a temporary connectivity issue. Will reopen if we see it again and get more info on it.
