### ISSUE TITLE
Line 17: tmp17[tmp18] is not a function

### ISSUE THREAD

**Issue by matheod** [codecombat/codecombat#2575]
In this level : http://codecombat.com/play/level/copper-meadows

1) It should say function name, not tmpXX
2) I don't know if it's normal, but I have no free boots with moveXY for this level.

![image](https://cloud.githubusercontent.com/assets/339611/6837426/68690104-d34c-11e4-9888-42e87755c9bc.png)

No error in console, still happend after a reload.

**Comment by popey456963** [comment]
It's because you're using basic boots, which only have `moveRight(), moveLeft()...`.  If you don't have the moveXY boots available, try playing the level that unlocks them again:
    Level 1 - Defense of Plainwood

**Comment by popey456963** [comment]
I'll close this, but if you find that this is still an issue, post another comment and I'll reopen it.

**Comment by matheod** [comment]
Well the issues is that it show tmp[number] instead of showing a better error message (like this.moveXY is not defined).

**Comment by popey456963** [comment]
True true, that's a very good point.

**Comment by popey456963** [comment]
Linked #1189
