### ISSUE TITLE
Placeholder not escaped

### ISSUE THREAD

**Issue by matheod** [codecombat/codecombat#2579]
https://github.com/codecombat/codecombat/blob/7ebb2d0200b9f688bffab5a601e242f99ca04b80/app/views/core/SubscribeModal.coffee#L49

The translation is not escaped, so the ' make the placeholder bug;

**Comment by nixel2007** [comment]
In which language you see this bug? ' and " used to escape in locale-files with /' and /". also if i remember it right, propagination does some escaping to strings.

**Comment by matheod** [comment]
In french language.
