### ISSUE TITLE
Remove Apocalypse code

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2580]
Now that the Master Sword is no longer offered, [this](https://github.com/codecombat/codecombat/commit/3236abc5dad1ae7a2da19cc212ee0296e509d5b8) commit can be reverted.

**Comment by popey456963** [comment]
Shouldn't we keep it if we need some other item to show off?  It seems a waste just to get rid of it when it's likely we'll be offering another item at some point.

**Comment by nwinter** [comment]
I need to modify the code to keep around some of the logic for showing off items and highlighting levels, so let me figure it out.

**Comment by Imperadeiro98** [comment]
I say this, because the Apocalypse is highlighted with the particles and has the Master Sword in it's circle (it is a little bit misleading).
