### ISSUE TITLE
Submit button partially hidden after window resize

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2581]
I think, today's 7dff105cdf73bc5173376450be73cfe910734da1 commit broke some stuff.
My current ingame view is like this:
![default](https://cloud.githubusercontent.com/assets/1132840/6855337/411af4ba-d408-11e4-892b-931adf01621b.PNG)

And i can scroll it down to this:
![2](https://cloud.githubusercontent.com/assets/1132840/6855339/437317ba-d408-11e4-8227-2546738abc78.PNG)

Chrome 41.0.2272.101 m (64-bit)

**Comment by nwinter** [comment]
Can you help me out with steps to reproduce? I saw this once but then couldn't get it back. (Maybe it's really easy and I'm just wishfully thinking that this is a corner case.)

**Comment by Vlevo** [comment]
I can do that too. If my spell pallete doesn't fit (or is close). I can scroll down... (even when full screen)

**Comment by nixel2007** [comment]
I have 1650x1080 resolution and a lot of methods as you can see. I just load the page and see this. 
I didn't try to reload :/

**Comment by popey456963** [comment]
Could we turn this bug into a feature?

**Comment by nwinter** [comment]
I have been trying to reproduce this, but I can't. The bug is that the run/submit buttons sometimes get cut off, maybe just with specific screen sizes / ability configurations / amounts of code / phases of the moonn? If anyone can reliably reproduce, I'd love to know.

![screenshot 2015-04-13 15 29 42](https://cloud.githubusercontent.com/assets/99704/7126885/2a590882-e1f2-11e4-84df-c0913a9b5f7b.png)

**Comment by Vlevo** [comment]
I just did it, accidentally... 

![image](https://cloud.githubusercontent.com/assets/11031492/7175330/7840f476-e3d0-11e4-82f7-98a2a85b3648.png)

Now to see if I can do it on purpose . . . Yes he can.

Level with lots of code: I Click on level, Click Play, Click Play, once the loading screen resizes the background graphic, then I change my screen size:
- click {F11} to go/leave fullscreen
- click Restore Down / Maximize

![image](https://cloud.githubusercontent.com/assets/11031492/7175749/54a9e248-e3d5-11e4-84f1-af5344aef24e.png)

Changing the screen size, once in that state seems to fix it (I didn't test all possible permutations)
