### ISSUE TITLE
Bug: Under 9 Statements But Does Not Mark Complete

### ISSUE THREAD

**Issue by tjchan001** [codecombat/codecombat#2584]
http://codecombat.com/play/level/forgetful-gemsmith
![ccbug](https://cloud.githubusercontent.com/assets/4033083/6861201/3341d3c0-d400-11e4-9280-590ebc80ec84.PNG)

Thanks.
-Timothy

**Comment by Vlevo** [comment]
see https://github.com/codecombat/codecombat/issues/1808 and https://github.com/codecombat/codecombat/issues/1915

**Comment by nwinter** [comment]
Let's discuss in those issues.
