### ISSUE TITLE
Level - Tactical Strike - Sword will not equip.

### ISSUE THREAD

**Issue by tjchan001** [codecombat/codecombat#2591]
I see my sword is equipped.  I have tried unequip and reequip, but same result.

![sword not equipping](https://cloud.githubusercontent.com/assets/4033083/6879728/a56ac492-d4d3-11e4-807d-440c40d6102d.PNG)

I am not able to attack (self.attack commands are missing) because the sword somehow does not truly equip even though the previous screen says it is equipped.

![sword not equipping 2](https://cloud.githubusercontent.com/assets/4033083/6879731/bc9392a2-d4d3-11e4-86d6-7609afea0f1a.PNG)

**Comment by nwinter** [comment]
Can't reproduce; need to figure out a repro step so we can debug.
