### ISSUE TITLE
Sarven Savior [Desert] broken

### ISSUE THREAD

**Issue by coder0xff** [codecombat/codecombat#2593]
Something is causing the "infinite loop" error to pop up, even though the submitted code exits.

```python
# An ARRAY is a list of items.
# This array is a list of your friends' names.
friendNames = ['Joan', 'Ronan', 'Nikita', 'Augustus']

# Array indices start at 0, not 1!
friendIndex = 0

# Loop over each name in the array.
# The len() function gets the length of the list.
while friendIndex < len(friendNames):
    # Use square brackets to get a name from the array.
    friendName = friendNames[friendIndex]

    # Tell your friend to go home.
    # Use + to connect two strings.
    self.say(friendName + ', go home!')

    # Increment the index to get the next name from the array.
    friendIndex = friendIndex + 1

# Go back and build a fence to keep the ogres out.
self.moveXY(25, 30)
self.buildXY("fence", 29, 30)

self.say("All done")
```

**Comment by nwinter** [comment]
Can you check the JS console on this for any interesting messages about why it's showing the infinite loop error? I am not seeing it with your code, so it might be something that only happens on certain random seeds, or something else.

**Comment by coder0xff** [comment]
The last line shows up briefly after the error dialog appears. Maybe my laptop is just too slow.
```
ModuleLoader.coffee:84 lib
vendor/aether-clojure
vendor/aether-coffeescript
vendor/aether-io
vendor/aether-javascript
vendor/aether-lua
vendor/aether-python
vendor/coffeescript
vendor/d3
vendor/difflib
vendor/diffview
vendor/three
vendor/treema
views/account/AccountSettingsView
views/common/SearchView
views/editor
views/modal/ModelModal
views/modal/RevertModal
views/play
ModuleLoader.coffee:85 loaded 19 files, 1435 KB
CocoModel.coffee:90 Populated defaults for Level Sarven Savior in 92ms
VM716:198 Assigned power 700 to wave undefined with difficulty 0
VM716:198 Assigned power 600 to wave undefined with difficulty 0
LevelLoader.coffee:404 World has been initialized from level loader.
CocoModel.coffee:90 Populated defaults for User in 18ms
God.coffee:70 Umvelinqangi: Let there be light upon Sarven Savior! (preload: false)
Angel.coffee:47 |Umvelinqangi's Cyril| Worker initialized after 6239ms
Angel.coffee:47 |Umvelinqangi's Cyril| Generated random seed -672857334 of type submissionCount from sessionIDs 550fedc27552a97e0582c15f submissionCount 0
Angel.coffee:47 |Umvelinqangi's Cyril| Assigned power 700 to wave undefined with difficulty 0
Angel.coffee:47 |Umvelinqangi's Cyril| Assigned power 600 to wave undefined with difficulty 0
Angel.coffee:47 |Umvelinqangi's Ray| Worker initialized after 7142ms
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 95 of 1200 (+1072ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 196 of 1200 (+1133ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 249 of 1200 (+1042ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 318 of 1200 (+1025ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 362 of 1200 (+1198ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 392 of 1200 (+1116ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 421 of 1200 (+1061ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 447 of 1200 (+1051ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 480 of 1200 (+1126ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 510 of 1200 (+1001ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 551 of 1200 (+1092ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 591 of 1200 (+1082ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 629 of 1200 (+1088ms)
Angel.coffee:47 |Umvelinqangi's Cyril|   Loaded 668 of 1200 (+1035ms)
Angel.coffee:47 |Umvelinqangi's Cyril| Worker initialized after 1190ms
```

**Comment by 20alanning** [comment]
You can create a variable to make it stop:

# An ARRAY is a list of items.
# This array is a list of your friends' names.
friendNames = ['Joan', 'Ronan', 'Nikita', 'Augustus']
# Array indices start at 0, not 1!
friendIndex = 0
friendsCalled = 0;

# Loop over each name in the array.
# The len() function gets the length of the list.
while friendIndex < len(friendNames):
    # Use square brackets to get a name from the array.
    friendName = friendNames[friendIndex]

    # Tell your friend to go home.
    # Use + to connect two strings.
    self.say(friendName + ', go home!')

    # Increment the index to get the next name from the array.
    friendIndex = friendIndex + 1
    friendsCalled = friendsCalled + 1
    
# Go back and build a fence to keep the ogres out.
if friendsCalled == 4:
    self.moveXY(26, 30)
    self.buildXY("fence", 30, 30)

**Comment by 20alanning** [comment]
If, while friendIndex <len(friendNames), is not working you can try using a variable:

friendNames = ['Joan', 'Ronan', 'Nikita', 'Augustus']
friendIndex = 0
friendsCalled = 0;

while friendIndex < len(friendNames):
    friendName = friendNames[friendIndex]

    self.say(friendName + ', go home!')

    friendIndex = friendIndex + 1
    friendsCalled = friendsCalled + 1
    
if friendsCalled == 4:
    self.moveXY(26, 30)
    self.buildXY("fence", 30, 30)

**Comment by nwinter** [comment]
@coder0xff how fast is your laptop?

**Comment by coder0xff** [comment]
Qualitatively, not fast. It's good for word processing and Netflix. Lol

**Comment by kjdevocht** [comment]
Ran into the same problem.  The only thing I can think of is that the friends are have not reached their targets(their feet are still moving).  My while loop exits just fine.  I move back and build the fence and then it just hangs

**Comment by nwinter** [comment]
I think we probably fixed this by making the level less likely to trigger the case where a ton of ogres are all jostling each other and leading to a nigh-infinite collision solving loop in Box2D. If you still see it, try submitting to get a new seed and see if it still does it, then let me know.
