### ISSUE TITLE
Shift Click Location doesn't insert properly formatted position object in python.

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2594]
I love that if I want to add a specific point to my code I simply have to shift-click to get the position:

{x: 72, y: 40}

But for it to work, it should be:

{"x": 72, "y": 40}

Seems like this should be a simple fix, but I'm not sure where to go about making the change.  I'm also not sure if the formatting is different depending on the language.  I know this is what it needs to look like in python.

**Comment by Vlevo** [comment]
in clojure I get the same result {x: #, y: #}
even though it should be {:x # :y#}

**Comment by Vlevo** [comment]
Wasn't code submitted to fix this? (I still see the bug)

**Comment by nwinter** [comment]
Fixed in #2595. I just merged it and haven't deployed it yet.
