### ISSUE TITLE
Poll preview overlapping patch review

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2596]
In the poll editor, the poll preview covers the patch reviewing interface:

![0235550a-d5a3-11e4-99dc-e1b2325267e3](https://cloud.githubusercontent.com/assets/6980488/6883406/c2082b0a-d5a3-11e4-9acb-982a4786b851.png)

**Comment by nwinter** [comment]
This bug is probably a feature right now, because the poll patch reviewing is really janky and errorprone, so let me handle the poll patches–else we may lose votes or other translations.

**Comment by Imperadeiro98** [comment]
Ok. I didn't actually accept or reject patches. Just withdrew some I made for mistake.
