### ISSUE TITLE
.attack("target") method is unavailable

### ISSUE THREAD

**Issue by germ13** [codecombat/codecombat#2600]
I am unable to attack anymore, ie: the .attack method has become unavailable in my code.

I bought the builders hammer, and now this is the only primary weapon/tool that I am able to use.
There is no way that I can recover my old default sword.  When I unequipp the hammer, the "PLAY" button becomes ghosted out.

Being that I dont have enough gems to buy a sword, and I cant advance forward because I cant attack, I am stuck. Catch 22. :bug: ?

![codecombat-bug-01](https://cloud.githubusercontent.com/assets/146168/6884569/1d152296-d5ae-11e4-91d2-569b2daf0b2f.jpg)
![codecombat-bug-02](https://cloud.githubusercontent.com/assets/146168/6884568/1d152af2-d5ae-11e4-833c-d3f9e2c410f0.jpg)
![codecombat-bug-03](https://cloud.githubusercontent.com/assets/146168/6884570/1d1597ee-d5ae-11e4-9ada-56b620429242.jpg)

**Comment by Zerrien** [comment]
Can you try to play the: "Forgetful Gemsmith" level again, to see if it re-rewards you the sword?

**Comment by germ13** [comment]
@Zerrien Replaying "Forgetful Gemsmith" rewarded the sword again! Thanks! :smile: 

Immediate problem was fixed, but its still unclear as to why problem occurred in first place.

**Comment by popey456963** [comment]
I think I'll close this issue unless anyone else gets this problem.  It's somewhat linked to some other "not getting reward" issues.

**Comment by germ13** [comment]
Unsure as to the methodology of closing issues in this group...i would of kept it open @popey456963 .  Seems like a bug to me, that needs to be fixed. ill look into it, Thanks to @Zerrien though.

**Comment by popey456963** [comment]
We have a bunch of other issues where items don't get added when they should do.  I'm unsure whether another one would help or not.  This appears to add very little information, but, incase it does help, I'll reopen it.

**Comment by nwinter** [comment]
Oh my, I can't believe it took me this long to find it, but there were two versions of the fourth level (Forgetful Gemsmith versus Signs and Portents), and one of them didn't even give you the simple sword! So depending on which one you did, you would only fake-own the sword when it was required in some level, but you wouldn't always be able to equip it properly.

I've now added the sword to both versions. Thanks for keeping this one open until I could see the truth. ;)
