### ISSUE TITLE
World selector shows incomplete levels but they aren't available to play

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2607]
User reported seeing 32/35 levels completed in Dungeon, but no levels available when navigating to Dungeon.

I confirmed that they weren't seeing any available levels, but saw 33/35 in world selector.  Cavern Survival has particle effect visible, but that's it.

**Comment by nwinter** [comment]
I fixed this in https://github.com/codecombat/codecombat/commit/bf86b2f9cd2b5921cc21319e338326764937b7b5.
