### ISSUE TITLE
Broken Wall in Oasis

### ISSUE THREAD

**Issue by monotkate** [codecombat/codecombat#2608]
In the Oasis level in the desert you can move left as long as there is an enemy through the wall and hang out until they're all gone.  Fun, but probably not right. :D

![image](https://cloud.githubusercontent.com/assets/11742296/6926364/c3a0938c-d7b3-11e4-85dd-059ff9f29955.png)

**Comment by Imperadeiro98** [comment]
Duplicate of #2609.
