### ISSUE TITLE
Broken Wall in Oasis

### ISSUE THREAD

**Issue by monotkate** [codecombat/codecombat#2609]
In the Oasis level in the desert you can move left as long as there is an enemy through the wall and hang out until they're all gone.  Fun, but probably not right. :D

![image](https://cloud.githubusercontent.com/assets/11742296/6926375/dd323a80-d7b3-11e4-8b0b-019cbe01132a.png)

**Comment by popey456963** [comment]
Shouldn't we either:
 - Lower the amount of time that the player has to complete the level
 - Make the yaks come until the level ends
As well as fixing the wall?

**Comment by Zerrien** [comment]
Proposed a patch to Oasis map, and the Oasis Referee in an attempt to discourage 'hiding' behavior.

**Comment by nwinter** [comment]
Thanks, I accepted both patches–great solution!
