### ISSUE TITLE
The guantlet

### ISSUE THREAD

**Issue by chaoservices** [codecombat/codecombat#2612]
Hi Bonus reward on "The Guantlet" under Javascript does not award. I'd post the code but I redid it in python and I am exceedingly lazy. Simply do a line for line conversion from this:
loop:
    self.moveRight()
    enemies = self.findEnemies()
    self.attack(enemies[0])
    self.attack(enemies[0])

**Comment by tchalvak** [comment]
Recommend running the level again to try to re-trigger the reward.  Sometimes the levels don't fully trigger the first time.

**Comment by popey456963** [comment]
The reason the bonus does not work is that the code is longer than x statements.  Counting statements in JavaScript is broken.  Since this is in another issue, I will close this one.

**Comment by popey456963** [comment]
Other issues are - #1915 and #1808

**Comment by chaoservices** [comment]
Thanks popey, I queried for dupes but nothing for "guantlet" had come up.
