### ISSUE TITLE
sword of the frog, blowback

### ISSUE THREAD

**Issue by chaoservices** [codecombat/codecombat#2613]
Maybe a feature but IMO the blowback on this weapon rather weakens it.

Even from one hit kills the hero ends up chasing a body across the room.

I suggest killed enemy die before the fly, at minimum.

**Comment by nwinter** [comment]
Got it; thanks for the bug report! Now the Sword of the Forgotten is way more awesome.

**Comment by chaoservices** [comment]
Is that the name? Heh, funny place for the string to truncate on my display.
