### ISSUE TITLE
Colorize blocks contents in the code editor

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2618]
A player had a super great idea for helping other players understand when their code is and isn't within blocks (like if, else, loop, etc.):

> Maybe you could add a hint, such as line coloring, to group the statements with the "if" line together, and a different color for the "else" line and its statements?

We should be able to do some fun stuff with Ace overlays to make it really easy to see when your indentation or brackets are not right and when they are, so that it becomes much easier to understand how blocks work.

**Comment by popey456963** [comment]
How do we deal with if statements within if statements?

**Comment by nwinter** [comment]
If the background/border colors we use are sequential, partially transparent, or alternating based on scope depth, it should take care of itself. There are other ways, too, but we'll have to come up with a basic visual design before we know what we're going to do with overlapping blocks.
