### ISSUE TITLE
Highscore ties are sorted based on newest first.

### ISSUE THREAD

**Issue by Zerrien** [codecombat/codecombat#2621]
![blaoo2](https://cloud.githubusercontent.com/assets/9985594/6991219/cd59b31a-da3b-11e4-8c6b-8e9330cacdd4.jpg)

Scores should be sorted so the person who FIRST got the 'highest' or 'best' score are listed first.

Ref (when scores are sorted): https://github.com/codecombat/codecombat/blob/b4ea78e5cbb24f3beec3a1904e3b9f535f72209f/server/levels/level_handler.coffee#L433

**Comment by Vlevo** [comment]
Maybe to let the newbie, see their name on the score board, assuming it was "done on purpose". Several of the "scores" are like the one listed there, too easy to get and they are fixed. Take for example your image example: You can't get any better than "0" and as you can see lots of people get it so having the guy who played the level twenty years ago show up . . . what makes him more special than the guy who got it yesterday... (unless the guy is still active on site, I'd say there is less than nothing to make him/her more special.) I think the newest shows is a good way for an educational site to do the leader board. It gives incentive both to the newbie to try and if the "older" scorer wants back on the board well, then they need to do better.

Yes, other places do it the other way. That alone isn't good enough reason. :smile:

**Comment by Zerrien** [comment]
I understand that, but, I feel you should still reward earlier players over those who join later. There should be some competitiveness to drive players to reach that next level, even if they will be No. 34256 with a 'perfect' score. See also #2553.

For educational purposes, graphics like the competitive ladder screens should be implemented to assist players in understanding where they 'rank' with their highest score.

![percentile](https://cloud.githubusercontent.com/assets/9985594/6991506/580011b4-da4e-11e4-98ba-763a9b37e577.jpg)

**Comment by Vlevo** [comment]
The ladder style scoreboard would be great and would cover my comments about the newbie seeing his name in lights. :)

So would the graph kind of thing, but the other is already coded up so I can see that happening. :smile_cat:

**Comment by Zerrien** [comment]
We would need to add another index to allow for this sorting, but it doesn't make sense at this time.
