### ISSUE TITLE
updateI18NCoverage actually looks at what keys exist, not which ones have translated all properties

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2630]
@sderickson In https://github.com/codecombat/codecombat/commit/ffc33279b8ae34cf8945a9a443e7335434eb61d2 you made it so that `updateI18NCoverage` uses `TreemaUtils.walk` to do an intersection on which language codes have covered every property that needs to be translated. Except that in my test on [`effects.HasEffects`](http://localhost:3000/i18n/component/haseffects), `workingSchema` is always `{}`, and even if it was filled in, wouldn't it be `workingSchema.properties` instead of `workingSchema.props`?

[CocoModel updateI18NCoverage](https://github.com/codecombat/codecombat/blob/master/app/models/CocoModel.coffee#L400):

```coffeescript
        # use it to determine what properties actually need to be translated
        props = workingSchema.props or []
        props = (prop for prop in props when parentData[prop])
```

How are we supposed to get the proper working schema to look for properties?

I was going to add this so that if there are no properties to translate (because any properties we have are actually just empty strings and so don't need translations), we mark the language as covered:

```coffeescript
        unless props.length
          langCodeArrays.push _.without _.keys(locale), 'update'  # Every language has covered a path with no properties to be translated.
          return
```

Otherwise we get a lot of things marked as not covered when there are default `"'` values in schemas:

![screenshot 2015-04-06 08 54 48](https://cloud.githubusercontent.com/assets/99704/7007000/b52639d4-dc3a-11e4-9c35-2473e6bf1605.png)

**Comment by nwinter** [comment]
I guess `props` is what each `i18n` property calls its array of properties to translate. This is also failing on `programming.Programmable`'s `debug` property documentation:

![screenshot 2015-04-08 10 25 53](https://cloud.githubusercontent.com/assets/99704/7050960/a84e9b84-ddd9-11e4-86f8-fca1173f7eca.png)

Here `coverage` is actually reading from the `i18n` node's properties in one case:

![screenshot 2015-04-08 10 27 17](https://cloud.githubusercontent.com/assets/99704/7050998/ec681b9c-ddd9-11e4-8385-59e4a1d8a7aa.png)

**Comment by nwinter** [comment]
@sderickson can you advise?

**Comment by sderickson** [comment]
@nwinter I'm seeing "could not resolve reference metaschema" in the output. Could that have something to do with it? If it can't resolve a reference, that would explain why workingSchema isn't being what it ought to be.

I'd suggest having these examples in the client tests. There's already one in [here](https://github.com/codecombat/codecombat/blob/master/test/app/models/CocoModel.spec.coffee#L154-L176). Add more with the Programmable and HasEffects examples and that could make it easier to understand and debug the problem, and keep it from coming back. With that you could reduce the bug to its essence. It sounds like it's a tangled web right now that's dependent on what's in the db. Start by taking the raw `@attributes` and `@schema()` values and putting them into a test and then having the test identify what output you expect that you're not getting. Then reduce the values from there.

What are your tests, exactly?

**Comment by sderickson** [comment]
Fixed with a combination of that commit plus a [treema issue](https://github.com/codecombat/treema/commit/b325fa814af192151df100085b8b55ad25f2a92b) where `walk` wasn't properly passing `workingSchema` for array items.
