### ISSUE TITLE
Get blank on web after Dev Setup on ubuntu

### ISSUE THREAD

**Issue by valeera** [codecombat/codecombat#2642]
log on server:

GET / 200 3ms
GET /stylesheets/app.css 304 0ms
GET /lib/ace/ace.js 304 2ms
GET /javascripts/vendor.js 304 0ms
GET /javascripts/aether.js 304 0ms
GET /javascripts/app.js 304 0ms
GET /javascripts/app/locale/en-US.js 304 0ms
GET /images/pages/base/modal_background.png 304 1ms
GET /images/level/popover_background.png 304 1ms
GET /images/level/code_palette_wood_background.png 304 1ms
GET /images/level/code_editor_background_border.png 304 1ms
GET /javascripts/app/locale/en.js 304 0ms
GET /images/favicon.ico 304 0ms
GET /javascripts/app/views/HomeView.js 304 1ms
POST /db/analytics_log_event/-/log_event 200 1ms
GET /images/pages/base/logo.png 304 1ms
GET /images/pages/base/nav_background.png 304 1ms
GET /db/user/55255fb6eb583dd2764b4827/achievements?notified=false&_=1428514274122 200 2ms

**Comment by nwinter** [comment]
Is it white or brown? How big is app.css?

**Comment by valeera** [comment]
1.remove the node_modules,
2.update the npm to latest:
 >apt-get install python-software-properties
 apt-add-repository ppa:chris-lea/node.js
 apt-get update
npm install
sudo npm install -g brunch
sudo npm install -g bower
