### ISSUE TITLE
Implement paladin and new ogres

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2653]
- [x] Paladin art and stats
- [x] Paladin healing skill
- [x] Ogre Witch art and stats
- [x] Ogre Witch Spell 1 (poison-cloud?)
- [x] Ogre Witch Spell 2
- [x] Ogre Witch Spell 3
- [x] Ogre Warlock art and stats
- [x] Ogre Warlock raise-dead AI
- [x] Ogre Warlock summon-undead AI
- [x] Ogre Warlock Spell 3
- [x] Ogre Chieftain art and stats
- [x] Ogre Chieftain AOE attack skill
- [x] Catapult art and stats

![apr01-new sprites](https://cloud.githubusercontent.com/assets/99704/7094113/a2afedcc-df73-11e4-8b09-745e6eb8c261.jpg)

**Comment by Zerrien** [comment]
Worked on patching in Paladin Heal functionality to magic.CastsHeal.

This requires that the commanding unit (the player,) be given access to either the command: "perform_heal" or "heal" such as:
```
this.command(paladin, "heal", this);
//or
this.command(paladin, "perform_heal", this);
```

As well, I implemented basic AutoCasts functionality for it, finding the first injured friendly to heal.

**Comment by nwinter** [comment]
Cool; I hooked up that patch and adjusted it a bit to use the cast API instead of the heal method for the commandableMethod.
