### ISSUE TITLE
bower .json missing

### ISSUE THREAD

**Issue by dheerajdake** [codecombat/codecombat#2660]
While setting up the project, i came across this when i ran SCOCODE.bat. I tried executing bower install but it didn't help. I found this code 'bower init' which tells whether you have a bower in the directory. Try updating the things manually from git bash and it works !

**Comment by nwinter** [comment]
Can you be a bit more specific about what `bower init` did that made it work? `bower install` should have worked, not `bower init`.

**Comment by nwinter** [comment]
Let me know if you have more details on this one.
