### ISSUE TITLE
No play button when launched from local host

### ISSUE THREAD

**Issue by dheerajdake** [codecombat/codecombat#2661]
There is no play button available when launching from local host. I am able to login and logout. The levels are unavailable.

**Comment by nwinter** [comment]
Did you get the database dump restored properly? https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Windows#setting-up-mongodb

If the `mongorestore --drop <path-to-dump>` command works, then you should have the levels showing up.

**Comment by nwinter** [comment]
Let me know if the database download and restore doesn't fix it.
