### ISSUE TITLE
Can walk through doors in Cavern Survival

### ISSUE THREAD

**Issue by Vlevo** [codecombat/codecombat#2686]
Noticed by my daughter a couple of days ago, but I couldn't reproduce at the time.

Just reported by Danny Whittaker on HipChat:

@ nick http://direct.codecombat.com/play/spectate/cavern-survival?session-one=546021610e8fd63e1237f90a&session-two=5461b3fdee018e4105c62ff3 ... This match has some weirdness going on.  My human pender starts out by simply walking through the doors to the other side.  The only time I tell him to move to the other side is if self.isPathClear(self.pos,enemyHero.pos)  I'm wondering if possibly there is an issue with isPathClear when both are named the same thing?  Not sure but this is the only match I've found that has the issue.  It is almost as if there are no doors for the whole match as ogres just walk through the doors as well.  Can anyone confirm the issues I'm having?

<hr>

So, I checked again and now I can reproduce:

![image](https://cloud.githubusercontent.com/assets/11031492/7225838/d6450da0-e6ff-11e4-9572-db4351433807.png)

**Comment by nwinter** [comment]
Ah, I see. I just fixed the door rotation now that all static rotations are being actually recognized.
