### ISSUE TITLE
Non-Penders in Zero Sum

### ISSUE THREAD

**Issue by Vlevo** [codecombat/codecombat#2687]
![image](https://cloud.githubusercontent.com/assets/11031492/7234782/daa181e8-e746-11e4-89d0-c30e8d28ef6a.png)

![image](https://cloud.githubusercontent.com/assets/11031492/7234777/c7e4e0e0-e746-11e4-9ba5-31b128fa5ae3.png)

**Comment by popey456963** [comment]
Do any of the non-pendar heroes actually do anything?  That champion seems to just be bugged out.

**Comment by nwinter** [comment]
I made it so that their type is always `'sorcerer'` anyway.
