### ISSUE TITLE
Bad align of "Follow" at /play/ladder/

### ISSUE THREAD

**Issue by nixel2007** [codecombat/codecombat#2690]
If you open http://codecombat.com/play/ladder/cavern-survival#simulate (any locale) and look at the buttom of the page you can see this:
![default](https://cloud.githubusercontent.com/assets/1132840/7240901/591b2954-e7bd-11e4-98e5-e97aaba65ac4.PNG)

Also, "follow" button and "GitHub" button have common mouseOver event - it highlightes both buttons when you mouseover.

**Comment by Imperadeiro98** [comment]
Related to #2375.

**Comment by popey456963** [comment]
I think we should discuss a solution to this on that issue page.  There is a link to this page on that issue.
