### ISSUE TITLE
Clan page bug

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2693]
When I'm in the page of a clan that I own I can't neither edit the name of the clan nor its description. It gives me the error:

'Failed to load resource: the server responded with a status of 403 (Forbidden)'

Suggestion: Also, I think I should be prompted when clicking "Delete Clan", because it is very easy to click it without wanting.

**Comment by differentmatt** [comment]
Please open separate GitHub issues for separate issues.

https://github.com/codecombat/codecombat/issues/2696

**Comment by differentmatt** [comment]
Fixed by https://github.com/codecombat/codecombat/commit/559b9533c4a50d8eb7f0635aea358779b101b266

**Comment by Imperadeiro98** [comment]
Ok. Will open different issues next time.
