### ISSUE TITLE
Payment methods pop-up needs a close button

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2694]
The "Accepted Payment Methods" pop-up can't be closed without closing the whole subscribe window.

![sem titulo](https://cloud.githubusercontent.com/assets/6980488/7260662/909753e8-e863-11e4-9923-15d9bc754a87.png)

**Comment by differentmatt** [comment]
Clicking the payment methods link again closes the pop-up.

We should add a close X to the top right of the pop-up.
