### ISSUE TITLE
Updating email address causes loss of level progress

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2697]
User reports losing progress after updating their email address.  Details in Help Scout: https://secure.helpscout.net/conversation/85591362/6961/

**Comment by nwinter** [comment]
Unless we changed something recently with this, I'm guessing that the player actually had a different email address that has all the progress (different from the two we know about) and just signed up with this latest email, which created a new account. The account he is mentioning was created this morning, so I know it's not the right account. He would need to remember the email or username he used for the original account.
