### ISSUE TITLE
Character getting stuck inside a wall when trying to pick up an object

### ISSUE THREAD

**Issue by ancientgods** [codecombat/codecombat#2700]
This occured to me at level: The trials, when the third batch of mushrooms spawn, one particular mushroom is too close nearby a wall (the one at x:143, y:124). If I tell to MoveXY(143, 124), it will pick up the mushroom, but then stay stuck in a wall, not executing other commands.

Here is the code (javascript) I am using: http://pastebin.com/2ZrTjhTm

If you remove the code at lines 38 to 40, you will get stuck in the wall

**Comment by nwinter** [comment]
@sotonin did we fix this yet?

**Comment by sotonin** [comment]
I'm not certain. i don't recall ever experiencing it myself unfortunately.

**Comment by nwinter** [comment]
Ah, I see what happened–a mushroom was in a corner that looked like it was in a wall but wasn't, and if you got it, you would be in a place where you couldn't see the other mushrooms. I moved the mushroom out of the cubby and moved the visual walls to match the collision boxes.

**Comment by nwinter** [comment]
Ah, I see what happened–a mushroom was in a corner that looked like it was in a wall but wasn't, and if you got it, you would be in a place where you couldn't see the other mushrooms. I moved the mushroom out of the cubby and moved the visual walls to match the collision boxes.

**Comment by nwinter** [comment]
Ah, I see what happened–a mushroom was in a corner that looked like it was in a wall but wasn't, and if you got it, you would be in a place where you couldn't see the other mushrooms. I moved the mushroom out of the cubby and moved the visual walls to match the collision boxes.

**Comment by nwinter** [comment]
Ah, I see what happened–a mushroom was in a corner that looked like it was in a wall but wasn't, and if you got it, you would be in a place where you couldn't see the other mushrooms. I moved the mushroom out of the cubby and moved the visual walls to match the collision boxes.

**Comment by NP-Hardass** [comment]
I keep getting stuck at this part currently and it isn't even the same place that it gets stuck.  Sometimes it is getting stuck on the oasis tents, sometimes its stuck in the top right corner of the oasis, sometimes it is stuck in the top left corner of the oasis.

Please let me know what information I can provide to help you troubleshoot.
