### ISSUE TITLE
Summoned Peasants Don't Collect Gold

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2703]
I used my Boss Star 3 to summon a peasant, then sent her to the nearest coin.  Upon arrival, she stood there on top of the coin doing nothing.  This happened in both Cloudrip Brawl and Sarven Seige.  I assume that the peasant should be able to collect gold for me, but it isn't working.

**Comment by Vlevo** [comment]
I'd guess it is because they don't have inventory.Collects

**Comment by nwinter** [comment]
Now they do!
