### ISSUE TITLE
Can't get back to "All Thangs"

### ISSUE THREAD

**Issue by Vlevo** [codecombat/codecombat#2706]
I Thought there was an issue about this but I couldn't find it...

In the Level Editor - If I click on one of the Thang Components in the Components List, the screen is redrawn with the "'Back to all Thangs' button" having been shoved up permanently out of view.

![image](https://cloud.githubusercontent.com/assets/11031492/7334587/278b6156-eb55-11e4-9f94-88839137b73b.png)

**Comment by nwinter** [comment]
Found it–let's discuss on #2583.
