### ISSUE TITLE
No vertical scrollbar on main site pages

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2711]
Examples: homepage, teachers, clans.

**Comment by nwinter** [comment]
We usually use nanoscroller for this; maybe it's not hooked up here like it should be on some other pages?

**Comment by Imperadeiro98** [comment]
Fixed by 902c39f?

**Comment by UltCombo** [comment]
This seems fixed in `direct.codecombat.com`.
Perhaps worth noting that this fix did not propagate to the BR CDN yet.

**Comment by duybkict** [comment]
I haven't noticed this bug anywhere, should we close this issue?

**Comment by differentmatt** [comment]
Fixed somehow.
