### ISSUE TITLE
Sand World bug?

### ISSUE THREAD

**Issue by ItsDawson** [codecombat/codecombat#2712]
![screen shot 2015-04-27 at 11 53 36 am](https://cloud.githubusercontent.com/assets/12141926/7355105/9eac8406-ecd4-11e4-9036-5b433a4449cb.png)
So I finished the levels going on the right path, but I cant go to the next world for some reason, I don't know if it is a bug or I just need to go the other way haha. Just wanted to issue this and hope I could help if it was a bug.

**Comment by nwinter** [comment]
The map art isn't very clear. Yeah, you need to beat Mad Maxer and then Clash of Clones, which will appear in the upper left. The exit is in the upper left, not the upper right. Good luck with Mad Maxer!

**Comment by ItsDawson** [comment]
Okay, thank you. And Mad Maxer is very frustrating haha
