### ISSUE TITLE
Item details missing from glasses, pendants, flags, and boots

### ISSUE THREAD

**Issue by DBowlerHB** [codecombat/codecombat#2715]
When viewing an item in the store, or Item catalog, the granted method details are missing from ALL glasses, ALL necklaces/pendants, ALL flags, and all boots < Boots of Jumping. 

![image](https://cloud.githubusercontent.com/assets/12139059/7402919/5d015fd8-ee85-11e4-993f-c5a49714ac39.png) | ![image](https://cloud.githubusercontent.com/assets/12139059/7402902/36ca7cdc-ee85-11e4-82d2-5ec14733dc0a.png)

![image](https://cloud.githubusercontent.com/assets/12139059/7402838/d00057d8-ee84-11e4-817e-a147c920874a.png) | ![image](https://cloud.githubusercontent.com/assets/12139059/7402853/eece8518-ee84-11e4-952e-64792e494d05.png)

Update: Boots Fixed by adding missing Acts and Moves components to each.

**Comment by Vlevo** [comment]
see https://github.com/codecombat/codecombat/issues/2484

**Comment by DBowlerHB** [comment]
@nwinter @Vlevo 
 The db query returns nothing for each of these items.  The way the query is structured, it seems like it should return partial descriptions even if one of the method details was missing but I could be wrong.  I do know that method description exists for moveXY which the simplest boots have.  I grabbed the query for a broken item (Fine Wooden Glasses) here:
```
{
        "$or" : [
                {
                        "propertyDocumentation.name" : {
                                "$in" : [
                                        "distanceTo",
                                        "findItems",
                                        "findNearest",
                                        "findNearestEnemy",
                                        "findNearestItem"
                                ]
                        }
                },
                {
                        "propertyDocumentation.name" : {
                                "$regex" : /^cast.+/
                        }
                }
        ],
        "original" : {
                "$in" : [
                        ObjectId("53e12043b82921000051cdf9"),
                        ObjectId("524b4150ff92f1f4f8000024")
                ]
        },
        "slug" : {
                "$exists" : true
        }
}
```

And here is a working item (Simple Wristwatch) for comparison:
```
{
        "$or" : [
                {
                        "propertyDocumentation.name" : {
                                "$in" : [
                                        "isReady",
                                        "now"
                                ]
                        }
                },
                {
                        "propertyDocumentation.name" : {
                                "$regex" : /^cast.+/
                        }
                }
        ],
        "original" : {
                "$in" : [
                        ObjectId("53e12043b82921000051cdf9"),
                        ObjectId("524b4150ff92f1f4f8000024"),
                        ObjectId("524b85837fc0f6d519000020"),
                        ObjectId("52fe70f15cd2082e2422be16")
                ]
        },
        "slug" : {
                "$exists" : true
        }
}
```
Can you see anything that would cause the query to return zero results?  Advice on where to look next?

**Comment by DBowlerHB** [comment]
If you view an unaffected high level boot, the lower level boots will temporarily work as well, but I believe that the descriptions are cached from the working boot. When you return to the lower level boot the database is not queried at all.  So that doesn't help finding the root of the problem, which seems to be in the db query, or with the item data that causes it to be filtered out.

**Comment by Vlevo** [comment]
Yes, so long as you don't leave the store, the query results stay cached (velocity (from movement.Moves) on the sapphire sense stone is cached by the "working" boots.)
When I was poking at it I found lots of similarities between the ones that work and between the ones that don't work, but nothing that always held (for instance the movement.Moves stuff doesn't load on anything . . . then along come two boots where it does load . . . . So OK, all or nothing, but, then you look at the Unholy 3+ tomes and everything is fine except for findCorpses (which lives in alliance.Allied with the other find-Friends/Enemies type stuff which doesn't load anywhere)...

There are six component sections that I never got to work: alliance.Allied, combat.Attackables, effect.HasEffects, inventory.Collects, physics.Physical, targeting.Targets, ui.Selectable, vision.Sees, and ai.FindsPaths and then there is movement.Moves which works for two of the boots. I am thinking that there may be two(+) different things going on here, since there are six that seem to never work, and one that only works for two boots.

**Comment by DBowlerHB** [comment]
The simple boots have action.Acts and are broken.  The simple boots have all the components that the working boots have besides the 2 jump components.

**Comment by Vlevo** [comment]
Simple boots have move.<direction>, not move() or moveXY and I've never seen them not report their functions.

**Comment by DBowlerHB** [comment]
You're right, the simple boots are fine.  There was just lag or something when i went to look at them last, so the description didn't load right away.   All of the broken boots were missing Acts & Moves components and their dependencies.  I added them in my dev environment and it fixed all of them.  Just need to get the patches approved.  Will start looking at other broken categories next.

**Comment by nwinter** [comment]
Thanks for figuring all this out, guys! I finally had time to go through all the sense-stones, flags, glasses, and unholy tomes (in addition to the boots that @DBowlerHB did) and add all the missing Components to the items, so now all the docs get loaded properly. Phew! If you see any more where the docs don't load, check the item and submit a patch to add the Component that should provide the docs, or if there really are no docs, add them to the Component itself.
