### ISSUE TITLE
Can't Equip Rough Sense Stone (The Mighty Sand Yak)

### ISSUE THREAD

**Issue by extrajordanary** [codecombat/codecombat#2724]
No equip button, and double clicking isn't working. Have closed game and tried again several times. 

On inspecting element I saw it had class "locked", which, once removed, allowed me to equip the item and proceed.

![screenshot 2015-05-01 22 43 40](https://cloud.githubusercontent.com/assets/4017420/7440115/0bc71032-f055-11e4-9638-fda1576f97db.png)

![screenshot 2015-05-01 22 57 38](https://cloud.githubusercontent.com/assets/4017420/7440123/d8b0cdfe-f055-11e4-99dd-d9b46a1baca5.png)

**Comment by nwinter** [comment]
You are supposed to buy it with the unlock button after selecting it:

![screenshot 2015-05-03 15 30 59](https://cloud.githubusercontent.com/assets/99704/7447276/6a76d7c0-f1a9-11e4-9e5b-0a0e040f5cd0.png)
