### ISSUE TITLE
Recipe book

### ISSUE THREAD

**Issue by txomon** [codecombat/codecombat#2728]
After playing a many of the stages, I realized that it would be really nice for each player to be able to have a recipe book, where you could just call the functions you have created, to avoid having to copy paste from one to the next all your functionalities

**Comment by Vlevo** [comment]
Linked to https://github.com/codecombat/codecombat/issues/19, https://github.com/codecombat/codecombat/issues/2444, and https://github.com/codecombat/codecombat/issues/2561
