### ISSUE TITLE
Level List: highlighted levels

### ISSUE THREAD

**Issue by Catsync** [codecombat/codecombat#2732]
In the level list (http://direct.codecombat.com/editor/level). Some levels are highlighted and sorted to the top of the list.

The intended behavior (from Nick) is it should highlight the ones where you are the person who last saved the level. This doesn't seem to be the actual way it works (might be first person to save?).

However, it would be nice to have it also highlight levels you are watching in addition to levels you created.

**Comment by makertech81** [comment]
I will attempt to do this one...  It would be a good feature, I agree.
