### ISSUE TITLE
findNearestEnemy description bug

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2735]
User feedback:
>The findNearestEnemy() description says in python that it returns `null` when python uses `None`. That makes the Patron Buster exercise more complicated than it has to be.

**Comment by Vlevo** [comment]
Descriptions are programming-language agnostic. I submitted a patch that removes the box-highlighting from the "null" making it look less like it is the proper "variable" name for whatever your language is and more like an idea... (this is how findNearest's description is already.)
http://discourse.codecombat.com/t/none-over-null-in-python/3780

**Comment by nwinter** [comment]
We could make this description programming-language-specific, but I want to make it easier to translate for spoken languages, so let's leave it like this.
