### ISSUE TITLE
Problem with naming a variable throw in Backwoods Brawl

### ISSUE THREAD

**Issue by ChristianKleineidam** [codecombat/codecombat#2741]
The following code works in the variables are named as they are. If however the variable `throwo` get's instead called `throw` it breaks with the cryptic error message `Line 7: Unexpected token throw`. Given that the issue is not on line 7 that behavior is strange and feels buggy.

    # Stay alive for one minute.
    # If you win, it gets harder (and more rewarding).
    # If you lose, you must wait a day before you can resubmit.
    # Remember, each submission gets a new random seed.
    # Stay alive for two minutes.
    # If you win, it gets harder (and more rewarding).
    # Remember, each submission gets a new random seed.

    loop:
        if self.gold >= 25:
            self.summon("archer")
    
        enemy = self.findNearest(self.findEnemies())
        
        friends = self.findFriends()
        
        if enemy and self.distanceTo(enemy) < 40:
            for friend in friends:
                self.command(friend, "attack", enemy)
                throwers = self.findByType("thrower")
                throwo = self.findNearest(throwers)
            
            
                if throwo and self.distanceTo(throwo) <= 40:
                    self.command(friend, "attack", throwo)
                else:
                    self.command(friend, "attack", enemy)
            
            if self.distanceTo(enemy)<=10 and self.isReady("power-up"):
                self.powerUp()
                self.attack(enemy)
            elif self.distanceTo(enemy)<=3 and self.isReady("bash"):
                self.bash(enemy)
            else:
                self.attack(enemy)
            
        else:
            self.move({"x":86,"y":71})
            for friend in friends:
                self.command(friend, "move", {"x":self.pos.x + 2,"y":self.pos.y})

**Comment by Vlevo** [comment]
Python may not use the keyword "throw" but javascript does and all user code at codecombat passes through javascript. So anytime you make a variable with a name that has meaning in javascript you can get in trouble.

**Comment by ChristianKleineidam** [comment]
It would be possible to run a parser that renames "throw" before passing it to javascript. There might also be other variable names that produce similar errors.

**Comment by Vlevo** [comment]
OK, at the top of the window is the repository "codecombat / codecombat" click on the first "codecombat" and scroll down until you find "filbert.js". That is our python parser. Go into there and open an issue for teaching the parser to either complain about or rename variables/etc that are javascript keywords. :smile:

**Comment by ChristianKleineidam** [comment]
I opened a [ticket](https://github.com/differentmatt/filbert/issues/61) over there, so I close this one.
