### ISSUE TITLE
Mac and Vagrant Setup link points nowhere yet.

### ISSUE THREAD

**Issue by jacobakkerboom** [codecombat/codecombat#2744]
This is my first post in the issue tracker, so please bear with me.

The link labeled "Mac and Vagrant Setup" on 
https://github.com/codecombat/codecombat/wiki/Dev-Setup:-General-Information

does not really point anywhere. Perhaps we can remove this link for now and made a new link pointing to https://github.com/codecombat/codecombat/wiki/Dev-Setup%3A-Mac. 

The link labeled Mac on the main github page https://github.com/codecombat/codecombat points to the same place, i.e. nowhere.

Of course we could also just wait until somebody makes some content for the Vagrant + Mac setup if that is the preferred way to do this. But I feel that a dead link on the main github page is undesirable.

**Comment by nelsonam** [comment]
I agree, @jacobakkerboom. I can fix the link to go to https://github.com/codecombat/codecombat/wiki/Dev-Setup%3A-Mac, but there are dead links on that page too. For instance, the link "Vagrant tutorial" at the top is also a dead link. 

Are we planning to have a Vagrant description for OSX specifically? There's already https://github.com/codecombat/codecombat/wiki/Dev-Setup%3A-Vagrant and although that has some Windows-specific jargon, it should be able to be transferred to an OSX audience fairly easily. 

I can write up a Mac-specific Vagrant tutorial if that's what's needed, but it looks like we just need to clean up the links and better utilize the resources we do have.

**Comment by nwinter** [comment]
Yeah, maybe let's have just one Vagrant page, with subsections for any OS-specific differences if needed, and then we can organize the links–thanks for any help with this! @popey456963 feel free to advise if you know more about what we were going for here.
