### ISSUE TITLE
Steelclaw gap can't be started with CoffeeScript

### ISSUE THREAD

**Issue by ChristianKleineidam** [codecombat/codecombat#2748]
There seems to be a bug in Steelclaw gap that prevents starting the level with CoffeeScript and the default CoffeeScript code for the level. The error says something about a Infinite Loop.

**Comment by Vlevo** [comment]
I do not see this error...???... please try again and advise...

Did you enter this level for the very first time using coffeescript as your language or had you entered this level previously? Level code does not automatically get replaced if you choose a different language you have to "reload" the level from the editor.

I tried entering the level as coffescript with javascript, python and coffeescript default code preloaded, no infinite loop error, for any of the permutations I tried.
