### ISSUE TITLE
Heroes don't fit in choose hero dialog selector

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2753]
![screen shot 2015-05-12 at 5 10 13 pm](https://cloud.githubusercontent.com/assets/2965172/7601374/f730d3ec-f8c9-11e4-920b-4f893946e578.png)

**Comment by nwinter** [comment]
Sorry, I only barely had time to implement her. We need to implement a design that scrolls horizontally or something. I am unlikely to have time in the next day or so. Anyone want to take a crack at it, or temporarily hide Arryn so the layout doesn't break? (I guess we can set her to kind: "Unit" for now, but I'm on my phone now with a baby on me.)

**Comment by differentmatt** [comment]
No worries, a minor css width reduction will do for now.  We'll have to figure something out for additional heroes in the future.

**Comment by Vlevo** [comment]
Replace Pender with "..." so it is "obvious" that the list continues? There are already next/previous arrows...

**Comment by Vlevo** [comment]
This has returned.

![image](https://cloud.githubusercontent.com/assets/11031492/7825068/0eafb6b2-03c6-11e5-9c34-0797692a2ec8.png)

**Comment by Vlevo** [comment]
it seems to have to do with zoom%   (chrome)
33%, 67% 90% all have it messed up, but 25,50,75,100+ are all good

**Comment by differentmatt** [comment]
![screen shot 2015-06-11 at 5 05 04 pm](https://cloud.githubusercontent.com/assets/2965172/8121122/0c6a8c36-105c-11e5-8426-5a25af2656dc.png)
