### ISSUE TITLE
Firefox gets stuck sometimes while I play codecombat

### ISSUE THREAD

**Issue by motoko-11** [codecombat/codecombat#2759]
I use latest version of firefox and ubuntu. 4 GB ram, 64-bit .

**Comment by motoko-11** [comment]
Could we have a lighter version of codecombat for slow connections ?

**Comment by nwinter** [comment]
Can you describe how it gets stuck? Then we could see about improving the problem. We've already done a bunch of work on making it as light as we can, unfortunately, and it's still pretty heavy.

**Comment by motoko-11** [comment]
http://codecombat.com/play/level/hold-the-forest-pass 

This is the level I am currently playing right now, and It's unplayable to me due to the glitches ie getting stuck in every 2-3 seconds. It's not like page is not loading. The page loads but  The characters don't move smoothly . Also , as long as I keep running this level, my other work on firefox can't be done too, because whole thing gets damn slow.

Some other information that might help you,

Netspeed test results = {  Download : 15.75 Mb/s , Upload : 6.79 Mb/s }
OS: Windows 7 64-bit , 4 GB RAM , Intel core i5 , (lenovo laptop with not so good graphic card)
Firefox is latest version.

If the processing is happening at client end, and lots of characters have to be simulated, and that too in a interpreted language, such as javascript ( I haven't looked over the code, but I am assuming it that all this simulation happens on client end with javascript or some interpreted language) , it might result in slow rendering. Don't you think ? . But interactivity is required (such as putting flag during the play) , so might be compiling is not a option. But I think, firstly there should be some code to detect if the processing capacity of client system is optimum or not. What do you think about it ?

**Comment by nwinter** [comment]
Do you see any better performance now that we are using a new interpreter? It should make player code run faster. Let me know if you still have problems.
