### ISSUE TITLE
codefight,mathfight like two person battle(feature-request)

### ISSUE THREAD

**Issue by motoko-11** [codecombat/codecombat#2760]
It would be good if two people can fight in codecombat in a way similar to what codefights.com and mathfights.com apply to two person fights. Feature-request.

**Comment by nwinter** [comment]
We have asynchronous PVP already (see ladder levels like Dueling Grounds), and have a bunch of work done towards synchronous PVP, but it's on the backburner right now. Did you mean you wanted synchronous PVP? Have you tried the async?

**Comment by motoko-11** [comment]
Are you referring to the level where you get ranked for killing more number of ogres ? .  I played that level. Yes, I think I am talking about sync PVP. For like , two players get randomly matched and have to solve the some tasks of some random level during a specified amount of time.

**Comment by nwinter** [comment]
I think we will have to hold off on this feature for a while–doesn't fit too well in our roadmap.
