### ISSUE TITLE
Python generators don't work

### ISSUE THREAD

**Issue by dzhang314** [codecombat/codecombat#2764]
Currently, Python's `yield` and `yield from` statements appear to be unsupported. Use of either produces an "Unexpected token" error.

![2015-05-17 09_53_03-codecombat - learn how to code by playing a game](https://cloud.githubusercontent.com/assets/4504054/7670843/930aa1fe-fc7a-11e4-9677-7914571a524b.png)

These statements are used to define generators, which have many natural applications in CodeCombat. For example, the following code might be used to repeatedly summon triples of one archer and two soldiers:

```python
def unitTypes():
    while True:
        yield "archer"
        yield "soldier"
        yield "soldier"

def unitTypes2():
    while True:
        yield from ["archer", "soldier", "soldier"]

foo = unitTypes()
# foo = unitTypes2() would be equivalent
summonType = foo.next()

loop:
    if self.gold >= self.costOf(summmonType):
        self.summon(summonType)
        summonType = foo.next()
```

(Of course, the behavior described in this example could be simulated with `["archer", "soldier", "soldier"][len(self.built) % 3]`, but other use cases lack simple translations.)

**Comment by Vlevo** [comment]
These and other actual "python" problems belong in the repository for the python parser.

Under "codecombat/filbert".

(click the first codecombat in "codecombat/codecombat" near the top of the screen and then scroll down until you find "filbert" and place the issue in there.

Thanks.
