### ISSUE TITLE
Python comparisons don't chain correctly

### ISSUE THREAD

**Issue by dzhang314** [codecombat/codecombat#2765]
Python's chained comparison semantics differ considerably from most C-like languages. Whereas
```javascript
10 < 20 <= 4
```
usually parsed as
```javascript
(10 < 20) <= 4
// true < 4
// true
```
Python expands chained comparisons by implicitly `and`ing the individual comparisons together:
```python
(10 < 20) and (20 <= 4)
# False
```
CodeCombat does not perform this expansion correctly, so expressions of the form
```python
a < x < b
```
checking if a number `x` is contained in the interval (a,b) give spurious results. Note that this also applies to the `is`, `is not`, and `in` comparison operators, so
```python
3 in [1, 2, 3] is not False
```
should, somewhat unexpectedly, expand to
```python
(3 in [1, 2, 3]) and ([1, 2, 3] is not False)
```

**Comment by Vlevo** [comment]
These and other actual "python" problems belong in the repository for the python parser.

Under "codecombat/filbert".

(click the first codecombat in "codecombat/codecombat" near the top of the screen and then scroll down until you find "filbert" and place the issue in there.

Thanks.

**Comment by dzhang314** [comment]
I see. I'll go ahead and close my Python language issues, then.

On a related note, what would be the appropriate place to report language issues with Coffeescript/Clojure/Io/Lua?

**Comment by Vlevo** [comment]
Search here first, there are known issuses with them, that have been reported here.

the clojure parser lives at:  https://github.com/vickychijwani/closer.js

I'm not sure about the other ones... So I guess you'd have to report them here until we find out otherwise.

**Comment by nwinter** [comment]
Io: https://github.com/genko/iota but it doesn't have issues, so maybe at-mention genko here.
Lua: https://github.com/basicer/lua2js-dist/issues
CoffeeScript: this is just part of Aether, so try here: https://github.com/codecombat/aether/issues
