### ISSUE TITLE
Python extended iterable unpacking doesn't work

### ISSUE THREAD

**Issue by dzhang314** [codecombat/codecombat#2766]
Python allows the use of starred expressions in unpacking assignment statements to catch multiple values. For example,
```python
a, *b, c = range(5)
```
should set `a == 0`, `b == [1, 2, 3]`, and `c == 4`. (Note that `b` must be a list, not a tuple or `range` object. See [PEP 3132](https://www.python.org/dev/peps/pep-3132/) for details.) CodeCombat does not currently support this behavior. Attempting to use a starred expression in a Python assignment statement produces an "Unexpected token" error.

![2015-05-17 10_30_09-codecombat - learn how to code by playing a game](https://cloud.githubusercontent.com/assets/4504054/7670977/bbf40b46-fc7f-11e4-89a0-1ff4ca47a845.png)

**Comment by Vlevo** [comment]
These and other actual "python" problems belong in the repository for the python parser.

Under "codecombat/filbert".

(click the first codecombat in "codecombat/codecombat" near the top of the screen and then scroll down until you find "filbert" and place the issue in there.

Thanks.
