### ISSUE TITLE
Why does my code work

### ISSUE THREAD

**Issue by lyngaard** [codecombat/codecombat#2772]
Collect 25 gold, and then tell Naria the total.
Use break to stop collecting when totalGold >= 25.
totalGold = 0
loop:
    coin = self.findNearestItem()
    # Pick up the coin and add its value to the total.
    # Get its value with:  coin.value
    if coin:
        totalGold = totalGold + coin.value
        totalGold += coin.value
        pos = coin.pos
        x = pos.x
        y = pos.y
        self.moveXY(x, y)
    
    if totalGold >= 50:
        
        # >= means totalGold is greater than or equal to 25.
        # This breaks out of the loop to run code at the bottom.
        break

self.moveXY(58, 33)
self.say("Done collecting gold!")
self.say(self.gold)
Go to Naria and say how much gold you collected.

I don't get why my code works when i write  **if totalGold >=50:**
but not when i write **if totalGold >=25**

**Comment by Vlevo** [comment]
This should be in the forum not here in the repository.

You are counting each coin twice.

totalGold = totalGold + coin.value
totalGold += coin.value

Those two lines to the same thing and therefore do it twice . . . which is why you have to check for double the actual amouont...
