### ISSUE TITLE
Client tests broken

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2776]
http://codecombat.com/test
Travis CI:
`./node_modules/karma/bin/karma start --browsers Firefox --single-run`

Need to enable these tests in Travis CI after this is fixed:
https://github.com/codecombat/codecombat/blob/master/.travis.yml#L26

Last time these passed in Travis CI:
https://travis-ci.org/codecombat/codecombat/builds/56161768

**Comment by Vikasgupta09** [comment]
Ok please spare with me on my noobness. But i am not much into coffeescript , so for the start its difficult for me to track down the tests that are broken actually. The tests written inside server -> subscription.spec.coffee under 'TRAVIS' are broken ??? or other test ? when i try to run the 
./node_modules/karma/bin/karma start --browsers Firefox --single-run
it says ReferenceError: require is not defined
Is this what needs to be resolved ?
