### ISSUE TITLE
Reported subscription end date is incorrect

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2785]
User example:
> Hi, I unsubscribed after receiving my renewal notice, and thought that I would at least still have access for the remaining month. The renewal went through at 1:10 PM today and I unsubscribed at 3:30 PM. However, instead of saying that I would have access until June 24, my account says that I will have access until May 24... that seems wrong, given that I just paid $9.99.

**Comment by JordanLittell** [comment]
Would the PersonalSub class be a good place to look for this problem? I have just started digging into the code. My suspicion is that "sponsorInfo.subscription.current_period_end" may not be assigned correctly

**Comment by nwinter** [comment]
Yup, still happening, just says it's today. So the error should be somewhere around [this line](https://github.com/codecombat/codecombat/blob/master/app/views/account/SubscriptionView.coffee#L200).

**Comment by javatlacati** [comment]
I think its because users ahven't finished their trial when subscribed so... what about extending the trial period with the subscription period?
periodEnd = new Date((sub.trial_end + sub.current_period_end) * 1000)
