### ISSUE TITLE
Can't always find sponsorSubscriptionID when checking a sponsored subscription for updating

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2786]
See [stripe.coffee L164-L167](https://github.com/codecombat/codecombat/blob/master/server/routes/stripe.coffee#L164-L167). This was erroring out the server when the webhook fired until I added the handler to just log and return 500 instead.

**Comment by differentmatt** [comment]
Also related: https://github.com/codecombat/codecombat/commit/5c240d89cd79eb3069bfc227009083355e9b0945

Not a clear cause for this, and the code paths have changed a bit since this problem.  Will keep an eye out for new instances of this problem.
