### ISSUE TITLE
Lua logical operations bug

### ISSUE THREAD

**Issue by klm-1** [codecombat/codecombat#2788]
> Both *and* and *or* use short-cut evaluation, that is, they evaluate their second operand only **when necessary**.
> - http://www.lua.org/pil/3.3.html

It means that this code must work in any case. But it fails when there are no enemies
```lua
local enemy = findNearestEnemy()
if enemy and distanceTo(enemy)<10 then 
    attack(enemy)
end
```

**Comment by nwinter** [comment]
@basicer is this an Aether bug or a lua2js bug? I seem to remember a short-circuiting bug, but can't remember where it was.

**Comment by basicer** [comment]
I believe it's an aether bug that only manifests with yielding enables.
Short circuit or ands work in my lua2js unit teats.

**Comment by basicer** [comment]
This is (finally!) fixed in the newest build.
