### ISSUE TITLE
lodash chaining does not work

### ISSUE THREAD

**Issue by trotod** [codecombat/codecombat#2795]
In the spell editor:

```javascript
// taken from lodash docs

var characters = [
  { 'name': 'barney',  'age': 36 },
  { 'name': 'fred',    'age': 40 },
  { 'name': 'pebbles', 'age': 1 }
];

var youngest = _.chain(characters)
    .sortBy('age')
    .map(function(chr) { return chr.name + ' is ' + chr.age; })
    .first()
    .value();

this.say(youngest);
```

Expected: Hero says `'pebbles is 1'`

Actual: `undefined is not a function`

It's not too big of a deal, but I have a (not so optimal) use case something like

```js
var enemies = this.findEnemies();
var filtered = _.chain(enemies)
    .reject({ type: 'door' })
    .reject({ type: 'palisade' })
    .value();
```

And it would be great if this would work properly.

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter. The `map` line doesn't work currently due to a separate `Atempted to invoke bookmark for [Function]` error, but we have that bug elsewhere.
