### ISSUE TITLE
Enhancement in Teacher Survey page

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2806]
I think that if a user starts writing in the "Other:" box, the dot for it should be selected, and, consequently, unselect the others.
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/8013958/9bc12846-0bc4-11e5-964a-24efdb0badc8.png)

**Comment by nelsonam** [comment]
What if the teacher has students from varying grade levels? Since it's a radio button, it looks like you can only choose one at a time. I think it makes more sense to be check boxes.

**Comment by Imperadeiro98** [comment]
Maybe, but I was saying that in this particular situation, if I start typing in the box in front of "Other:", and if I had previously selected another box, that box remains selected and the "Other:" box is treated as not selected.
