### ISSUE TITLE
worldEndsAfter doesn't work as described

### ISSUE THREAD

**Issue by Vlevo** [codecombat/codecombat#2807]
For example:
"Hero Placeholder | Components | programming.Plans | worldEndsAfter" states "When not null, ends the world this many seconds after this Thang finishes its plans."

There is a drop down box with which to choose "null" or "number". If you choose "null", it works as expected. Choosing "number" and "1" works as one would expect. BUT, if you choose "number", and "0" the world does not end zero seconds after the plan finishes. This is one of those conceptual cases where "zero" is not "null".

This should either be changed so the code works as described or the description changed so that it reads "null or zero". Since the choice to choose "null or number" is given, it would seem that the intent was to have the world end zero seconds after Thang finished its plans (zero does not equal null) if zero was chosen. Having mentioned what would be the preferred/intended method, the question(s) becomes can the way the database was set up actually handle this distinction and how many levels were set up wrong (used zero when null was meant)....

**Comment by nwinter** [comment]
Let's just change the description, since people have set up a bunch of levels with the 0 value.

**Comment by Vlevo** [comment]
Submitted patch to Plans: Changed description of worldEndsAfter to match how it works (0===null)
