### ISSUE TITLE
Welcome sound occasionally plays when sound is turned off

### ISSUE THREAD

**Issue by anter69** [codecombat/codecombat#2819]
I have the sound turned off for CodeCombat (via the icon in the top-right corner) -- however, the welcome sound (*"[whistle] codecombat"*) is still played sometimes (even if just partially) when I open the browser with a tab including a level (http://codecombat.com/play/level/level-name). It also happens if I reopen a closed tab. Probably the page starts playing the sound before it checks the settings or there is a delay for some reason.

It happens both in Firefox (31.5 ESR) and Chrome (42 64bit), OS: Windows 7.

**Comment by Vikasgupta09** [comment]
As this has been marked for newbies, it will be better to let us know which file handles the sound play and which file first executes and handles the sound call on any level. I looked at Level.coffee but couldn't find any relevant code related to handling of sounds.
It's difficult to debug for newbies when they don't have insights of the code combat.

**Comment by nwinter** [comment]
This is where the sound is played: https://github.com/codecombat/codecombat/blob/master/app/lib/LevelLoader.coffee#L409-L416

[AudioPlayer](https://github.com/codecombat/codecombat/blob/master/app/lib/AudioPlayer.coffee) should be respecting volume, but maybe it isn't? We could just not play the jingle if we know the player's volume is 0.
