### ISSUE TITLE
Add Contact section to About page

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2822]
On this page: 
http://codecombat.com/about
https://github.com/codecombat/codecombat/blob/master/app/templates/about.jade

We need a new section under Blogger/Press called Contact, with this information:

```
CodeCombat, Inc.
188 King St #507
San Francisco, CA 94107
team@codecombat.com
```

**Comment by arthurnn** [comment]
Guess this can be closed now.
thanks all
