### ISSUE TITLE
Two rings of speed equipped

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2826]
From [the forum](http://discourse.codecombat.com/t/two-rings-of-speed/3847/2):

> In my inventory screen in Clash of Clones, I have two Rings of Speed on my hands. Why is this?

![b7ea7b550b944aa1](https://cloud.githubusercontent.com/assets/99704/8149981/a94fad60-128c-11e5-91ab-0a6a4a69df4f.png)

We need to make our ring equipping logic smarter. See also #2740.

**Comment by Vlevo** [comment]
I just fired up Haunted Kithmaze and my eyes were assaulted by (feasted on?) this
(also: Forgetful Gemsmith, Second Kithmaze, but not the other levels in the dungeon.)
![image](https://cloud.githubusercontent.com/assets/11031492/8323317/efa7eb40-19ff-11e5-8591-51bc699f03fd.png)

**Comment by nwinter** [comment]
I think someone made a nice patch so that this doesn't happen any more.
