### ISSUE TITLE
Write docs for modulo

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2829]
In the programming.UsesSnippets Component, we need to add to its config schema the modulo "concept", and also we need to add to its settings the documentation for that. If anyone's looking for an easy Scribe task that can be done just straight up in the level editor, they can get us started here!

http://direct.codecombat.com/editor/level/tiny

![screenshot 2015-06-14 14 14 10](https://cloud.githubusercontent.com/assets/99704/8150454/ac97d1c4-129f-11e5-9def-9e9083f7e96d.png)

**Comment by nelsonam** [comment]
I can do this. Can you provide a bit more detail on what you are looking for?

**Comment by nwinter** [comment]
I think the process described here is still mostly up to date: https://github.com/codecombat/codecombat/issues/399

**Comment by reesylou** [comment]
I know this is old, but was looking for an easy thing to close off.  I added a patch for this, but only samples for Javascript and LUA.  (Also didn't go into the difference between modulus and remainder)

**Comment by nwinter** [comment]
Thanks @reesylou!
