### ISSUE TITLE
Cavern survival bug

### ISSUE THREAD

**Issue by f0mster** [codecombat/codecombat#2836]
When i trying to defeat Glacian in Cavern survival - after 20-30 seconds my hero begins to act very strange eg. running into walls and doing not he must to do. did see this bug with other players.
Some time (if i change code) Glacian becomes untouchable - no orces or  my skeleton wants to attack him until timeout. it begins in 40 seconds and last till 120.

**Comment by nwinter** [comment]
Fixed; invisibility and hide, when stacked, weren't reverting to an unhidden state properly. Now each cancels the other correctly when first applied.
