### ISSUE TITLE
Code Combat dev setup error

### ISSUE THREAD

**Issue by tahmidshahriar** [codecombat/codecombat#2853]
If I try to set up dev in Linux, I would keep getting an enoent error (the error log is below). I would get this error if I tried the setup.py approach (the automatic linux one). I tried manually installing packages afterwards (sudo npm install) and got the same error. I tried as a root user as well but had same problem.

<b>  Error log  :</b>
8311 verbose about to build /usr/lib/node_modules/aether
8312 verbose unlock done using /home/tahmid/.npm/_locks/aether-f9d6d33a75785409.lock for /usr/lib/node_modules/aether
8313 verbose stack Error: ENOENT, chmod '/usr/lib/node_modules/aether/node_modules/esprima/bin/esparse.js'
8314 verbose cwd /home/tahmid/CC
8315 error Linux 3.13.0-55-generic
8316 error argv "node" "/usr/bin/npm" "install" "aether" "-g"
8317 error node v0.10.38
8318 error npm  v2.11.3
8319 error path /usr/lib/node_modules/aether/node_modules/esprima/bin/esparse.js
8320 error code ENOENT
8321 error errno 34
8322 error enoent ENOENT, chmod '/usr/lib/node_modules/aether/node_modules/esprima/bin/esparse.js'
8322 error enoent This is most likely not a problem with npm itself
8322 error enoent and is related to npm not being able to find a file.

I ended up temporarily solving it by removing aether from dependencies and manually install aether. I could not install aether through npm (gave a similar enoent error) and manually downloaded the repo. I attempted npm install on that and got the enoent issue again. The issue kept coming from the "esparse.js" in esprima. I looked at the package.json in aether and found esprima to be installed using "esprima": "https://github.com/ariya/esprima/tarball/harmony" (it would download the tar, and get stuck there). I replaced that with "esprima": "git://github.com/ariya/esprima" and was able to run it and finally install successfully (I installed everything and copy pasted aether (with its dependencies installed already) afterwards). I am not fully sure if this is an "issue" or not but I was wondering if there is any other fix for it or if the way I did it is likely to cause any issue for me in the future (if not, I would love to be able to contribute this as a temporary solution in installation docs in case someone else has a similar issue!).

<b> Finally ran : </b>
![image](https://cloud.githubusercontent.com/assets/8417980/8314317/9b527aea-199d-11e5-95a5-f59f83f87cd9.png)

**Comment by nwinter** [comment]
It seems like that should work fine; can you submit a pull request to Aether to replace the https:// with the git:// in that package.json?

**Comment by tahmidshahriar** [comment]
Okay! I will get that in by today :) Thank you very much for getting back to me so quickly!
