### ISSUE TITLE
Remove iPad support message

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2854]
Should say the generic mobile message if we're on iPad.

https://github.com/codecombat/codecombat/blob/master/app/templates/home-view.jade#L28

**Comment by Vikasgupta09** [comment]
Remove iPad support message. So you want to remove the message that says about good and bad news. like our native iPad app is awaiting Apple approval. ??
And show the generic mobile message in return of it ? 
Why not have a message that says
CodeCombat wasn't designed for ipad devices and may not work!
As ipad and mobile are not essentially same. 
Just need to have a better understanding of the problem statement. Thanks
its a very small change, will do it immediately after clarification.

**Comment by Vikasgupta09** [comment]
Also tell me one thing. When and where are these error messages actually appear . I tried to open codecombat.com/play on my android device, and it is working fine. I didn't even encounter any error message for mobile.
