### ISSUE TITLE
"Code never finished" error when using "while true do" to loop on The Mighty Sand Yak level

### ISSUE THREAD

**Issue by coldkey21** [codecombat/codecombat#2859]
The default lua code on the challenge uses the `while true do` to loop instead of the `loop` keyword that has been taught before this point. Using the `while true do` results in the following error message:
> **Fix Your Code**
> Code never finished. It's either really slow or has an infinite loop.

Simply replacing the `while true do` with `loop` will fix the issue and allow the code to run and be submitted without errors. This could be a major barrier to anyone new to programming.

**Comment by coldkey21** [comment]
I just found the Programmaticon III which is where the while loop skill is granted. The Programmaticon III is not unlocked until 3-5 where as the Mighty Sand Yak level is 3-1.

**Comment by Vlevo** [comment]
I don't see any error, when I load up the default lua code. But, I'll check why loop was changed to while.

**Comment by Vlevo** [comment]
Please close this topic, thanks!

**Comment by coldkey21** [comment]
Thanks for taking the time to look into it.
