### ISSUE TITLE
error message suggests using conditions before the user learned it.

### ISSUE THREAD

**Issue by ephigabay** [codecombat/codecombat#2864]
When you try to attack "null" reference the error says to try to use "if" statements' even though the user didn't learn conditions in the early stages.
Maybe it would be better to change the error message :)
@hibukki

**Comment by UltCombo** [comment]
In which levels does this happen? Some context would be nice to determine whether this is a common occurrence.

In the other hand, error messages which make no sense to reader at first glance are part of a coder's daily life. :smile:

**Comment by nwinter** [comment]
@Zerrien fixed this, right?
