### ISSUE TITLE
Ogrs dying from the spikes in the walls

### ISSUE THREAD

**Issue by ephigabay** [codecombat/codecombat#2865]
In the final kithmaze level, you can completely ignore the ogres and they die from the spikes on the walls..   
You can pass the level by using the following code:  
    loop:
        self.moveRight()
        self.moveUp()
        self.moveRight()    
        self.moveDown()
        self.moveDown()
        self.moveUp()

**Comment by Vlevo** [comment]
You must have a different seed then I do, as not all of my ogres spit themselves upon the spikes.

**Comment by nwinter** [comment]
Ah, mine did the same thing. Will have to do a tiny bit of hackery to stop this from happening. I will move the issue to the level editor checklist for that level.
