### ISSUE TITLE
Update i18n of the level save 'form'

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2867]
It is necessary to add i18n to some words of the level save "form", which can be accessed through the file https://github.com/codecombat/codecombat/blob/master/app/templates/editor/level/save.jade.
The lines are 4, 26 and 44.

**Comment by Vikasgupta09** [comment]
Hi ! I am new and doesn't know the insights much of how i18n work but i believe is this is how it should go:

1. h3= "Level: " + level.get('name') + " - " + (levelNeedsSave ? "Modified" : "Not Modified")
The above can yield two string
a) Level: Modified
b) Level: Not Modified
So, we want to convert this to have i18n. To do so, we must have the value of these in other languages in our locale files. So i think we will have to create its value in all locales files. (CONFUSING PART) 
How do we do this ? I mean, in English we can easily create
editor: 
level_modified : "Level : Modified"
But how do we go about adding them in all other subsequent languages ? Google and translate them and add ?? Or is there other quick way to do this ?? Or adding in one file , and after compiling it i18n translates it automatically to other language ?? Will be great to know about how it works. 
Once i understand the requirement clearly, these tasks are very very easy to be done in few minutes.
Thanks

**Comment by Vikasgupta09** [comment]
I have made the changes, but i need to test them. Can you tell me briefly the steps how to see this 'save' form ?

**Comment by Imperadeiro98** [comment]
You need to go to '/editor/level/(NameOfLevel)' and make changes to the level, a component and a system. The, you can click the save button in the upper right corner and there you will see all this strings.

**Comment by Vikasgupta09** [comment]
So,clicking save button shows 'Submit Patch' option 
hinzugefügt Thangs :: Ogre Commander :: Components :: Component :: Configuration :: Width

we need to change all of the possible words coming ?

**Comment by Imperadeiro98** [comment]
That is not the part that needs translation. They are these (the parts underlined):
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/8453847/588de1aa-1ff0-11e5-9eeb-88909044aaee.png)
![sem titulo1](https://cloud.githubusercontent.com/assets/6980488/8453849/5a972b3c-1ff0-11e5-8afe-7bd2e743e9f9.png)
![sem titulo2](https://cloud.githubusercontent.com/assets/6980488/8453850/5bb0e260-1ff0-11e5-8959-73b7a84d5ef6.png)

The strings can be found in the locale files. No need to add new ones.

**Comment by Vikasgupta09** [comment]
"Not Modified" does not exists in 'en-US.coffee' locale files. So, if that is to be included as part of translation , it needs to be added. may be inside delta as delta.modified exists.

Also, again sorry to ask you but when i click on 'save button' at top right corner it is not showing me what you had pasted. And i just wanted to see that option once before making any pull request for the same.
I tried to add new components by double clicking the components on the right side. Then i clicked on 'save button'

**Comment by Imperadeiro98** [comment]
Sorry, forgot to tell you that you need to be logged in and create a new level. To see all those, just put an object in the map, go to components and change one (the code for it), and the same with a system.
