### ISSUE TITLE
i18n not working in create new level

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2870]
As you can see, everything is internationalized except the 'Create New Level' part, in spite of being actually translated.
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/8395979/e6d44a7c-1d88-11e5-84cc-c807f5ea0572.png)
It also happens with 'Create New Achievement'.
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/8395997/27b78dbe-1d8a-11e5-91e5-8b51a0809782.png)

**Comment by Vikasgupta09** [comment]
Hi! I am new to code combat, and doesn't know the insights of the game. However, i desperately want to contribute by fixing some bugs. 
Can you help me by describing certain more things related to this issue. 
When do we get this option of 'Create New Level / Achievement' ? How can i see that in my browser this option ? 
I just want to debug it first and will then look over the code to see for the changes that are required.
Thanks
