### ISSUE TITLE
[Python] Reassigning a function parameter treats it as undefined until reassignment

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#2880]
Test case:

```
def f(x):
    self.say(x + '') # output: undefined, expected: 1
    x = 2
f(1)
```

**Comment by Vlevo** [comment]
[filbert](https://rawgit.com/differentmatt/filbert/master/test/interactive.html) turns:
```
def f(x):
    print(x + '')
    x = 2
f(1)
```
into
```
(function(__pythonRuntime){function f() {
    var __params0 = arguments.length === 1 && arguments[0].formals && arguments[0].keywords ? arguments[0] : null;
    var __formalsIndex0 = 0;
    var __args0 = arguments;
    function __getParam0(v, d) {
        var r = d;
        if (__params0) {
            if (__formalsIndex0 < __params0.formals.length) {
                r = __params0.formals[__formalsIndex0++];
            } else if (v in __params0.keywords) {
                r = __params0.keywords[v];
                delete __params0.keywords[v];
            }
        } else if (__formalsIndex0 < __args0.length) {
            r = __args0[__formalsIndex0++];
        }
        return r;
    }
    var x = __getParam0('x');
    return function () {
        __pythonRuntime.functions.print(__pythonRuntime.ops.add(x, ''));
        var x = 2;
    }.call(this);
}
f(__pythonRuntime.utils.createParamsObj(1));})(filbert.pythonRuntime);
```

**Comment by UltCombo** [comment]
Thanks.
Hm, that output is a bit more complex than I expected. My Python may be not sharp enough to figure out why all that is necessary, but I can see the problem: there's an "intermediate scope" where the parameters are defined and a child scope for the function body itself -- the function body scope's `var x` shadows the parameters scope's `x`, resulting in the error.

I believe the correct solution would be to not re-declare a variable when a formal parameter with the same name exists, but I may need to research a bit to be sure.

At least we know it is a bug with Filbert. :smile:

**Comment by UltCombo** [comment]
Reported in Filbert's issue tracker: https://github.com/differentmatt/filbert/issues/70

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
