### ISSUE TITLE
Servan Siege

### ISSUE THREAD

**Issue by CindyXinYou** [codecombat/codecombat#2883]
My operating system is "Windows 8.1", and my browser is "Google Chrome".

I don't know why my hero always goes to (84, 51) and staying on  it, she even didn't move to the coin.
Uhh... and I think the gold (this.gold)  started  did not enough to build any soldier.
The code didn't work before, and I tested someone's code which had been succeed, but it still not worked to me.
Here's my code (Javascript):

loop {
    var coin = this.findNearest(this.findItems());
    
    if (this.gold < 20 && coin) {
        this.moveXY(coin.pos.x, coin.pos.y);
    }
    else {
        if (this.pos.y > 65) {
            this.moveXY(84, 77);
        }
        else if (this.pos.y > 35 && this.pos.y <= 65) {
            this.moveXY(84, 51);
        }
        else {
            this.moveXY(84, 22);
            total = this.gold;
        }
    }
}

Sorry for my movie file's volume is too large, so I upload the pictures:

<img width="942" alt="01start" src="https://cloud.githubusercontent.com/assets/13193468/8515474/de593224-23d5-11e5-806e-efcc3babf87e.png">
<img width="944" alt="02" src="https://cloud.githubusercontent.com/assets/13193468/8515489/3091ede2-23d6-11e5-9f52-483310586b6d.png">
<img width="942" alt="03" src="https://cloud.githubusercontent.com/assets/13193468/8515491/3616eeca-23d6-11e5-8be9-90dae25b40d5.png">
<img width="942" alt="04" src="https://cloud.githubusercontent.com/assets/13193468/8515492/3a84b7c6-23d6-11e5-8487-819798a4e442.png">
<img width="944" alt="05" src="https://cloud.githubusercontent.com/assets/13193468/8515494/3f2ad1a2-23d6-11e5-859e-e8fe3f45f007.png">

**Comment by Vlevo** [comment]
Normally this kind of question is handled in the [forums](http://discourse.codecombat.com/) and faster also...

The code looks fine and I even copied and pasted and it runs fine for me . . . So, the only suggestion I can think of is that you empty your cache and reload the level.
