### ISSUE TITLE
Replayable level gems display cumulative total, not incremental award (confusing)

### ISSUE THREAD

**Issue by Sumeriano** [codecombat/codecombat#2889]
Hi, I have an issue.

what operating system,
Windows 7.

what browser(s),
Firefox and Google Chrome

exactly when it stops working and what you see,
I completed the map Backwoods Brawl in 3th lvl, I received more than 600 gems but they were not computed.

what programming language you're using,
Lua.

what level isn't working,
Backwoods Brawl.

and whether it worked before or has never worked.
I received gems from other lvls.

Thanks for your attention.

**Comment by nwinter** [comment]
It actually gives you the difference in gems between what level 3 was worth and what level 2 was worth, but shows the total gems awarded for the level. I should fix this to make it more clear that you get the difference each time.

**Comment by comason** [comment]
even if the gems shown when the level is complete is the difference in the value, they are not being awarded.  i completed "Backwoods Treasure" 3 times and the 3rd time it said "+437" gems, but i only received 110 gems.  so it doesn't matter whether its displaying the difference or what the level is worth, its not giving the correct amount of gems, and i just lost out on a whole lot of gems.

**Comment by comason** [comment]
as far as i can tell, its the same on all of the replayable levels.

**Comment by comason** [comment]
oh yeah, using ubuntu 14.04 lts, running mozilla firefox, programming in python, completed backwoods brawl 3 times and backwoods treasure 3 times only getting around 100 gems not the 400+ that the level says when completed.

**Comment by UltCombo** [comment]
I've just thought a bit about this and came up with (what I believe to be) a good solution. I've [posted it in the forum](https://discourse.codecombat.com/t/incorrect-gem-awarding-on-defeating-backwoods-brawl-multiple-times/2637/7?u=ultcombo), but I'll repost the UI suggestion here for commodity:

If the user has already beaten at least one round, display an "Already earned on previous rounds" section in the victory screen, which is shown as already unlocked (no unlock/counting animations) and contains the sum of all previous rounds' exp and gems. Then, below the "Already earned on previous rounds" section, show an achievement for the round that has just been beaten, containing the appropriate reward amounts and the unlock/counting up animations.

Does this sound good?

**Comment by nwinter** [comment]
That would be a better solution, but I think to keep things simple, I'll just keep it at what I just implemented: only showing the new gems, not the old ones you earned in previous rounds. Will deploy this fix later this week.
