### ISSUE TITLE
Backwoods Forest -> Hold for reinforcement: Only one wave of enemies has run.

### ISSUE THREAD

**Issue by adel77** [codecombat/codecombat#2901]
![01_forest_hold for reinforcements_only one wave of enemies](https://cloud.githubusercontent.com/assets/13463895/8845578/1efb525c-3129-11e5-9ca1-9462f4b93436.png)
Steps to reproduce:
1. Log in.
2. Go to Backwoods Forest location.
3. Start the 'Hold for Reinforcements' mission.
4. Choose the hero 
5. Run the default (original) code.

Expected result: Several waves of enemies should run, through all three passages.
Actual result: Only one wave of enemies has run, through the left passage.

Additional info:
JS, Chrome 43, Win7.
No errors in js console.

**Comment by Vlevo** [comment]
Fixed. Thanks for letting us know.
