### ISSUE TITLE
"How long have you been programming?" poll has 0 votes for first option

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2924]
![screenshot 2015-08-07 05 34 36](https://cloud.githubusercontent.com/assets/99704/9135803/066ae66e-3cc6-11e5-9770-8137db8b9960.png)

It should have a bunch of votes. The key for the first option is '0', which may be messing with something: '0' could get converted to a number and be falsy? I dunno. I haven't checked it out too much–I'm not sure if it's not displaying that option to players or not recording their votes when they pick it.

You can see it in the poll editor here: http://direct.codecombat.com/editor/poll/how-long-have-you-been-programming

Client-side code: [PollModal.coffee](https://github.com/codecombat/codecombat/blob/master/app/views/play/modal/PollModal.coffee)

Server-side code: [UserPollsRecord.coffee](https://github.com/codecombat/codecombat/blob/master/server/polls/UserPollsRecord.coffee)

The [friends who code poll](http://direct.codecombat.com/editor/poll/friends-who-code) also has zero votes for both first and second options, huh.

**Comment by trotod** [comment]
https://github.com/codecombat/codecombat/blob/master/app/views/play/modal/PollModal.coffee#L76

jQuery transform data values into a possible JavaScript value, so key values like `0` and `1` get turned into numbers, which fails the schema validation (apparently). Easy solution would be to stringify the value, though it's going to stay at 0 votes for a while...
