### ISSUE TITLE
'Specifically Covered' appears as 'Yes' when 'Overview' is not yet translated

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2925]
In the [i18n](https://codecombat.com/i18n) page, when a level is fully translated except for the Overview part, it shows 'Specifically Covered' as being 'Yes', when it shouldn't.

**Comment by sderickson** [comment]
Cannot repro.

**Comment by Imperadeiro98** [comment]
Can't reproduce it no longer.
