### ISSUE TITLE
Code Editor - UI layout error

### ISSUE THREAD

**Issue by bit-coursera** [codecombat/codecombat#2926]
After last update User Interface has additional scrollbar when Hero uses any of [Boss Star](https://codecombat.com/editor/thang/boss-star-i)  thang. Panel with used items (commands available to use) despairing in this case.

![bug](https://cloud.githubusercontent.com/assets/8536376/9150889/afbd6bd2-3dee-11e5-876d-0f3e277414d7.png)

**Comment by nwinter** [comment]
Hmm, I don't see the same thing. It looks like some JavaScript error has occurred when loading the page. Can you [check the JS console](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers/77337#77337) for red error messages that might give a clue?

**Comment by bit-coursera** [comment]
I found reason why you cant recreate this error. The problem is connected with i18n in Polish. When you change your language into Polish (Jezyk Polski) error is reproducible. On level loading lots of "red errors" appears:
```
Level.coffee:173 Samurai couldn't find lc for Object {original: "53178759a508f6e7b3464001", majorVersion: 0, config: Object}config: ObjectmajorVersion: 0original: "53178759a508f6e7b3464001"__proto__: Object of 
```

**Comment by bit-coursera** [comment]
After deeper testing I can assume that this bug happens when:
1. User works on other language then English
2. Hero uses thang which gives commands with i18n translation incomplete for particular programming language.  


Fixing:
- **Diplomat** : Change i18n [Components > Programming Commands > Settings > Property Documentation > Name = commandableMethods... >  i18n > Język polski] (http://codecombat.com/editor/level/tiny) bug is on version 0.19
  - make it translation programming language independent
or
  - make translations for all programming languages
- **Archmage** : correct code for situations when in components translations there is programming language dependent translation (_Language descriptions_) but for one programming language is missing - use English instead
