### ISSUE TITLE
Access Denied errors on Windows 10

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2930]
@Imperadeiro98 mentions that on both IE and Edge, on Windows 10, he gets a bunch of Access Denied errors from aether.js when on /play or when opening a settings menu. It does let him play a level, though. Weird. Need some more thorough fixings for Windows 10 than just what we did for #2917.

**Comment by themaka** [comment]
I cannot reproduce this in IE11, Edge 12, or Edge 13.
