### ISSUE TITLE
Facebook login non-functional

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2935]
From [the forum](http://discourse.codecombat.com/t/facebook-login-nonfunctional/4675):

> When I click "log in with Facebook", no little window pops up; neither does it log me in, even though I am already logged in to Facebook. The Google+ login window still pops up if clicked, but I don't use Google+. I am using Firefox 40.0. Update: Neither does it work in IE 11, a private window, Safe Mode, or Firefox 39.0.3.

Also:

> Confirmed. The `fb-login-button` is not initialized, it even looks like the FB JS API is not loaded at all as well.

@differentmatt did we change anything with this?

**Comment by UltCombo** [comment]
I did some testing, the FB JS API file is actually loaded when the login modal is opened. However, looks like it is throwing an error (which is silently ignored due to a try/catch in the FB JS API file), and thus it fails silently and `window.FB` is not defined.

**Comment by differentmatt** [comment]
@nwinter Not that I know of.
