### ISSUE TITLE
Possible problem loading game with Linux Chrome 43

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2937]
I'm seeing some error logs:

> Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://codecombat.com/javascripts/app/vendor/aether-python.js' failed to load.

They all happen in Linux Chrome 43. I haven't had a chance to spin one of these up to see what's going on and if it happens to everyone on that browser or just some people, or if it causes levels to not load. Can anyone on Linux test this out for me?

**Comment by trotod** [comment]
Always has worked fine for me in Chromium 43 and 44 on Linux...levels load fine without errors like the one above.
