### ISSUE TITLE
coffeescript - no success detection

### ISSUE THREAD

**Issue by bit-coursera** [codecombat/codecombat#2943]
On level [__Ogre Encampment__](http://codecombat.com/play/level/ogre-encampment) when using _CoffeeScript_ with code:
``` 
loop
    e = @findNearestEnemy()
    if e
        @attack e
    else
        @attack "Chest"
```
level does __NOT__ end and reports existence of infinite loop after opening `Chest`. The same level coded with _Python_ ends with full success:
```
loop:
    e = self.findNearestEnemy()
    if e:
        self.attack(e)
    else:
        self.attack("Chest")
```

**Comment by nwinter** [comment]
Ah, I guess we need #1570 for this to work, otherwise no blocking actions are taken in the loop after the chest dies and there are no other enemies and it becomes infinite.

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
