### ISSUE TITLE
Chrome audio only working in one channel

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2946]
From [the forum](http://discourse.codecombat.com/t/headset-not-working-sound-is-only-in-one-ear/4617):

> So I have a headset and I only hear sound out of one headphone. I can not find a setting to change it from mono or stereo. It's not my headset because it works just fine with other sites. Did I miss where to change my settings at or is this a bug?

and

> I had the same problem. My headphones are quality ones and 100% fine with every other program/music software. Only at codecombat the left channel was deaf completely, even at the "codecombat"-jingle. I guess i used Firefox, but since Firefox isn't really cared about and the sound was messed up before causing extreme performance issues...whatever. I didn't try with chrome i think.
> edit: ok surprise: it actually works with FF but not with chrome! lol

and

> In my case it happened after updating Chrome to Version 44.0.2403.155 m
> BTW, the hero's and enemies' voices (on click) and battle sounds are ok.
> PS. That new Chrome update not only corrupted the music and sounds in CodeCombat, but also added really bad performance issues frowning

but

> I've tried different headphones on Chrome for Windows and OS X, they are working fine for me.

When I tested it in Chrome 45, all the interface sounds and music played from the right, whereas the directional audio was working. So probably just something with our audio playback code is making sounds which don't have a direction specified just play from the right.

**Comment by nwinter** [comment]
This might be a bug in SoundJS.

> Even on demo page http://www.createjs.com/getting-started/soundjs in Chrome with headset only right side is playing, on Firefox both. So this issue is not in CC, but in SoundJS

Still, some sounds play from both channels, so we might be able to just call SoundJS in a different way to get it working.

**Comment by SoullessWaffle** [comment]
I am also on Chrome and I noticed CodeCombat's sounds only play through the right speaker of my headphones.
This does seem to be a SoundJS bug, since their demo page has the same issue.

Could it be a Windows 10 issue? I doubt something as big as this would have gone unnoticed for long, and I recently updated to Windows 10.

**Comment by SimonHung** [comment]
I think SoundJS  have fixed this problem, but should be released in the next version,
please visit this webpage: 
https://github.com/CreateJS/SoundJS/commit/70a812a564641e2f49b6edcb567efd75243b0e6c

**Comment by adel77** [comment]
Any news on that sound issue?
PS. Previous release of SoundJS was in December 2014. And before that it was May 2014.

**Comment by UltCombo** [comment]
It should be possible to build from the SoundJS's master branch, in case this issue is urgent enough that it can't wait for a new SoundJS release.

**Comment by SimonHung** [comment]
Accroding to: https://github.com/CreateJS/SoundJS/commit/70a812a564641e2f49b6edcb567efd75243b0e6c

It should be workable if add one statement to:
codecombat/vendor/scripts/soundjs-NEXT.combined.js

5965		this.panNode = s.context.createPanner();
5966		this.panNode.panningModel = s._panningModel;
5967		this.panNode.connect(this.gainNode);
	+		this._updatePan();
