### ISSUE TITLE
IE11: can't edit Gems or Death starter code

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2961]
> When I place the cursor on the number 3 to change it to a 4, the space turns red and will not accept input.

![image001](https://cloud.githubusercontent.com/assets/99704/9412548/2324c9de-47e1-11e5-93c6-7c7751b02c3a.jpg)

Haven't tested yet; anyone else see this in IE11?

**Comment by Imperadeiro98** [comment]
It is working for me.
