### ISSUE TITLE
Guide text overlapping wooden frame

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2963]
As you can see below, the Guide text and the Subscribe button are overlapping the wooden frame a little bit.

![sem titulo](https://cloud.githubusercontent.com/assets/6980488/9418175/0e9edf0e-484a-11e5-96bb-1546836a6c16.png)
![sem titulo1](https://cloud.githubusercontent.com/assets/6980488/9418176/0eb7bede-484a-11e5-88a1-6e5a83f9ced5.png)

**Comment by nwinter** [comment]
Ah, this is when scrolling down. I guess we just need to play around with the top padding so that it stays on the paper a bit better.

**Comment by Imperadeiro98** [comment]
What I got so far: I changed the class .game-menu-tab-content in [this sass file](https://github.com/codecombat/codecombat/blob/master/app/styles/play/menu/game-menu-modal.sass), making the top: 37px,  height: 490px, and padding: 10px 50px 10px 50px.

**Comment by viettruong2194** [comment]
Added some margin on the top and changed the height to offset the bottom overflow
<img width="836" alt="screen shot 2015-11-18 at 3 50 30 pm" src="https://cloud.githubusercontent.com/assets/7356884/11258220/42f99a7a-8e0c-11e5-959a-279ebe88c896.png">
<img width="815" alt="screen shot 2015-11-18 at 3 51 30 pm" src="https://cloud.githubusercontent.com/assets/7356884/11258221/4620c84a-8e0c-11e5-86d2-13f4310b048c.png">

**Comment by viettruong2194** [comment]
I think this issue can be closed out. Thanks!
