### ISSUE TITLE
Turn admin off by default on localhost

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2970]
The local development environment should default to non-admin when creating users.  This is a better for testing changes, since most of our users are not admins.

To make it easy to still create admin users, we should add an admin checkbox in the user creation dialog similar to the one in account settings.

See #566 for previous work in this area.

**Comment by nwinter** [comment]
I decided to skip the checkbox, as I see more people deploying their own shared CodeCombat servers, and that would be confusing.
