### ISSUE TITLE
Typing in restricted code area isn't obvious enough that it's restricted

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2982]
The dotted outlines are pretty faint. At one point I added a red flash to this, but either it's not working or it's not enough, because I've recently gotten several complaints of "it's not letting me type" where I confirmed the player didn't see any indication that it was a locked code area.

Code [here](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/tome/SpellView.coffee#L299-L300) and [here](https://github.com/codecombat/codecombat/blob/master/app/styles/play/level/tome/spell.sass#L166-L183).

Anyone want to take a crack at a better style or effect, or can test whether they see the red pulsate effect? You can test a locked sample code level by going to Haunted Kithmaze on a new anonymous account.

**Comment by Imperadeiro98** [comment]
Just a question: am I supposed to be able to write on the last line of the restricted code area?

**Comment by nwinter** [comment]
Hmm, it shouldn't let you write inside the dotted lines...

**Comment by Imperadeiro98** [comment]
It lets me write after the last character of the sample code.

**Comment by liljaminkev** [comment]
Maybe add a bar like this to the game so users understand its below the bar? #--------------------------------- 

I like separating functions like this for my code in my class assignments. 

I normally code in C++ so it looks like this:

//--------------------------------
//Move to the gem.
//Don't touch the walls!
//Type your code below.
//------------------------------------
sample code can be left open to user to modify. 

I just joined your development community and I am still getting used to the code. But upon playing the game I found that I didn't know where the code was supposed to be typed as well. and only figured it out after clicking around.

**Comment by liljaminkev** [comment]
This doesn't look that pretty but I think instead of locked it should say something along the lines of enter text below. Or completely separate the ability to click or enter code in that box. The locked message also flashes so briefly that I could barely catch it until I was messing with the code.

    .ace_marker-layer
      .ace_bracket
        // Override faint gray
        border-color: #BFF

      .locked-code
        border: 1px solid rgba(53, 45, 34, 0.5)
        background-color: beige
        @include transition(background-color 1.5s ease-in-out)  <---- sorry but I don't understand this line

        &:after
          content: "Enter your code below this box"
          opacity: 0
          color: white
          display: block
          text-align: center
          @include transition(opacity 4s ease-in-out)
          font-size: 18px

        &.pulsating
          background-color: #3d2b1f

          &:after
            opacity: 1


![screen shot 2015-09-01 at 11 09 08 pm](https://cloud.githubusercontent.com/assets/11880661/9624143/a0041862-50fe-11e5-8f40-5c8e4a416f5e.png)

**Comment by nwinter** [comment]
We are getting rid of locked default code ranges, so this isn't important any longer.
