### ISSUE TITLE
Extra word in view, which cannot be translated

### ISSUE THREAD

**Issue by Pena86** [codecombat/codecombat#2988]
While translating the game, I noticed a problem in play -> item info view (picture below).
There is additional 'Acton' -word there, which I cannot find in the translation file. Is it meant to be a header or ??

I would be interested to learn more about the development, so could someone point out, where the text is placed to the view and how it should be changed?

![codecombat_translation_problem_1](https://cloud.githubusercontent.com/assets/1288902/9651223/3d78c8be-5216-11e5-817e-f05520590ab1.png)

**Comment by nwinter** [comment]
Good eye! Should be good to translate now; I added the translation strings to the template [here](https://github.com/codecombat/codecombat/commit/02676dc59f07c7a9261b125d59a7e25287edc05d#diff-54b6c1b281df36b4b5506e2d2471d5a0R18).
