### ISSUE TITLE
Screen sometimes maximizes on Safari, then won't let player type

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#3017]
Because the game doesn't fit very well on very short screens, we auto-full-screen when going between inventory modal and playing a level if the screen is too small. We only do this once, so if the player doesn't like it, she just has to cancel out one time per session.

In Safari, though, most keyboard input stops working once in fullscreen, so we don't do this on Safari, using the much-maligned ancient technique of user-agent sniffing. [Here's the code](https://github.com/codecombat/codecombat/blob/master/app/views/play/menu/InventoryModal.coffee#L499):

```coffeescript
    ua = navigator.userAgent.toLowerCase()
    unless me.isAdmin() or hasGoneFullScreenOnce and (/safari/.test(ua) and not /chrome/.test(ua)) or $(window).height() >= 658  # Min vertical resolution needed at 1366px wide
      @toggleFullscreen()
      hasGoneFullScreenOnce = true
```

Surprise, surprise, it doesn't always work! Have had three bug reports of this in the past couple weeks. But why would people's Safari browsers not pass my `/safari/` test? Anyone able to reproduce by playing in Safari and making your screen less than 656px tall when starting to play a level?

**Comment by makertech81** [comment]
![screenshot 2015-10-08 07 59 37](https://cloud.githubusercontent.com/assets/5672443/10365607/a1971a48-6d92-11e5-8236-7337c6eb8718.png)
Well, I tried multiple times and never saw the problem.  More info would be helpful. Thanks.

**Comment by makertech81** [comment]
My resolution was not exactly 656 ppi, it was lower (640 api tall). Is that why?

**Comment by nwinter** [comment]
Okay, so it's working properly and not going full-screen on your machine, which is good. But then how is it happening for others? Hmm!

**Comment by makertech81** [comment]
Yes but I set it to that height, I don't actually have that resolution on my machine.  Do you think that is why?
