### ISSUE TITLE
Translate instructions in code comments

### ISSUE THREAD

**Issue by javatlacati** [codecombat/codecombat#3018]
Hello, I've seen that many leves haven't translated the instructions that is given by means of line coments.
I'd like to help with that technical translation.

**Comment by Imperadeiro98** [comment]
If you want to translate level related things, just go to http://codecombat.com/i18n, and then find the level you want to translate. By the way, thank you for doing it :+1:

**Comment by javatlacati** [comment]
Comment token remains unchanged without any minimal hint. Is it possible to get it dinamically?

**Comment by Imperadeiro98** [comment]
Which level is it?

**Comment by javatlacati** [comment]
I've tested change level and got it on first 3, and one from the second world. So... I think it's on all that the `--` down's change automatically to `#`. In coffe script it can make hints won't appear on first level, and on the next levels, It says that syntax is wrong without any hint at all.

**Comment by Imperadeiro98** [comment]
I don't think this is related to translations, is it?

**Comment by javatlacati** [comment]
Nope it seems language changing related

**Comment by nwinter** [comment]
I think I have another bug somewhere for changing code languages not necessarily reloading the code properly–that seems to be what's going on?
