### ISSUE TITLE
Triggers at doors needed

### ISSUE THREAD

**Issue by javatlacati** [codecombat/codecombat#3021]
level: signs-and-portents

![bug lua cc](https://cloud.githubusercontent.com/assets/1063901/9834560/f355692e-5984-11e5-8e36-890ef9f468e7.png)

I don't know if it's a lua bug, but it seems that runs an extra iteration even when the hero reached the end of the maze.

**Comment by nwinter** [comment]
You are supposed to just stand there on the X.
