### ISSUE TITLE
Campaigns appear as not translated in i18n page

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3030]
In [i18n page](https://codecombat.com/i18n), even though the campaigns are fully translated, they appear as if they are not.

**Comment by javatlacati** [comment]
Ho do they appear when translated? Just asking :blush:

**Comment by Imperadeiro98** [comment]
As of right now, in spite of being translated, they appear like
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/9917208/48c3935a-5cb8-11e5-8193-a475a588f6a6.png)
When they should appear like
![1](https://cloud.githubusercontent.com/assets/6980488/9917213/521452a0-5cb8-11e5-8a54-4e5344a7f62c.png)

**Comment by javatlacati** [comment]
Well I notticed that they work different when you click the :house: icon than when you go straight to the link... thought it was me :blush:
