### ISSUE TITLE
Arrows cause damage when colliding with a Thang after ricocheting.

### ISSUE THREAD

**Issue by Zerrien** [codecombat/codecombat#3042]
I lean either way on this, but wondered what the expected behavior for this is.

Included are two gifs, one 'frame-by-frame' one at full speed. Watch the arrows bounce and then collide with the player.

![ricochet_damage_full_speed](https://cloud.githubusercontent.com/assets/9985594/9974746/91eba46c-5e54-11e5-8843-5341bd7ce1bf.gif)
![ricochet_damage_frame_by_frame](https://cloud.githubusercontent.com/assets/9985594/9974748/92aa2f72-5e54-11e5-8d0d-b6c038e2c72c.gif)

**Comment by nwinter** [comment]
Yup, that's intentional. They should also do less damage if they collide at significantly slower speed. Logic in `combat.Arrow` Component.
