### ISSUE TITLE
[reluctantly with spoilers] Correcting maps that have errors after planned run and with Done/Submit

### ISSUE THREAD

**Issue by philandy** [codecombat/codecombat#3046]
The Done style maps are easiest to see this issue; I went back to ol Dungeons of Kithgard, let it complete the goals, and only then added `error;` (after error catching is turned off):

```
// Move to the gem.
// Don't touch the walls!
// Type your code below.

this.moveRight();
this.moveDown();
this.moveRight();
error;
```

Notice no errors. Click `DONE`. Now go back into the dungeon and _what?_ Error. Before suggesting a fix I want to detail the `SUBMIT` version of this issue.

Village Guard (Desert) seems to be the first level with `SUBMIT`. It's not that difficult of a level and is fairly quick to get to, but if you wish to see this and aren't at that point yet...sorry. You should be able to get there within a few minutes to a few hours. Let it complete and add the `error;` just after you deal with the rightEnemy:

```
// Patrol the village entrances.
// If you find an enemy, attack it.
loop {
    this.moveXY(35, 34);
    var leftEnemy = this.findNearestEnemy();
    if (leftEnemy) {
        this.attack(leftEnemy);
        this.attack(leftEnemy);
    }
    // Now move to the right entrance.
    // Use "if" to attack if there is an enemy.
    this.moveXY(60, 31);
    var rightEnemy = this.findNearestEnemy();
    if (rightEnemy) {
        this.attack(rightEnemy);
        this.attack(rightEnemy);
        error;
    }    
}
```

This acts differently because you have to `SUBMIT` the code which should catch most any of these situations? I mean surely even if you `SKIP` and add code later you still have to resubmit? No, non-infinite loops with errors after the map completes still cause issues with the `SUBMIT` system. Let's go to Lurkers (Desert) which could be considered a quick and simple example of this problem (sadly a bit into the game which is after a few skilled levels that could take days or longer to get there, however all you need is `break;` or `while()` if you can figure out how to get those commands). 

```
// findEnemies returns a list of all your enemies.
// Only attack shamans. Don't attack yaks!

var enemies = this.findEnemies();
var enemyIndex = 0;
while(enemyIndex<7){
    // Wrap this section in a while loop to iterate over all enemies.
    var enemy = enemies[enemyIndex];
    if(enemy){
        if (enemy.type == 'shaman') {
            while (enemy.health > 0) {
                this.attack(enemy);
            }
        }
    }
    enemyIndex++;
}
error;
//Try instead:
//while(true){}
```

There are 2 issues here.

The first issue being that you can add an `error;` before the planned run completes which will show you an error along with _GOALS: SUCCESS_. This entices the player to `SUBMIT` code with `errors;` they know about in them because the goals are complete; no further action necessary!

The second issue, how I caught this issue originally, is where the planned run/goals are complete with errors still in the code off screen, and then `SUBMIT`. A more complex `while(true){}` bounds breaking error (since you have this command available now) instead of a simply caught `error;` shows where this issue could go.

I liked how the first few levels had the Clean Code bonus and was a bit confused why that was removed in later levels, but worse is that I now see errors in the code that I cannot go back and fix until I reload the already loaded level.

Please let us close the Victory blurb out and continue with the current level so anything like this that may come up in the future can be a bit easier to deal with. Perhaps a grayed out `EDIT` or `CONTINUE EDITING` button to the left of the `VIEW LEADERBOARDS` or a better system that lets us edit any level code at any time which would be slightly more modular in approach to separating the IDE and game interfaces. I would suggest adding a quick button for now and then update the IDE later.

I hope these issues were presented clearly. Let me know if otherwise. Thanks!

**Comment by nwinter** [comment]
Fixed, thanks!
