### ISSUE TITLE
Ace of Coders - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MHeasell** [codecombat/codecombat#3049]
After messing around with Ace of Coders for a while I've hit the following issue a bunch of times. On compiling certain code, my hero stands motionless but the UI doesn't indicate any code errors, and no Ice Yaks spawn. I get the following message in the JavaScript console:

<pre>
ERROR in transforms.getUserFnMap RangeError: Maximum call stack size exceeded
    at Array.toString (native)
    at h (http://codecombat.com/javascripts/aether.js:2578:15)
    at h (http://codecombat.com/javascripts/aether.js:2580:27)
    at s (http://codecombat.com/javascripts/aether.js:2574:70)
    at s (http://codecombat.com/javascripts/aether.js:2575:103)
    at h (http://codecombat.com/javascripts/aether.js:2579:294)
    at s (http://codecombat.com/javascripts/aether.js:2574:70)
    at s (http://codecombat.com/javascripts/aether.js:2575:103)
    at h (http://codecombat.com/javascripts/aether.js:2579:294)
    at s (http://codecombat.com/javascripts/aether.js:2574:70)
</pre>

I don't have a minimal example for this, but it seems to happen reliably with certain versions of my code. I'm guessing it's a transpiler bug rather than a problem with my code, but I'm sure I could be proven wrong. I could share my code privately with a dev if this is helpful.

**Comment by nwinter** [comment]
Hey @MHeasell, sorry about that! Sounds like [this bug](https://github.com/codecombat/aether/issues/143) with [this code](https://github.com/codecombat/aether/blob/master/src/transforms.coffee#L51-L265). Can you find a minimal subset of your code that is triggering it? (It's probably just one or two function signatures.)

Will be excited when we fix this one!

**Comment by MHeasell** [comment]
Hi @nwinter, thanks for the link, I hadn't realised that there was an existing bug filed in aether for this.

I was just attempting to reduce my code down to a minimal example, however, half way through this process the behaviour of CodeCombat changed.

It now appears that declaring a named function results in a code error:

![codecombat-error](https://cloud.githubusercontent.com/assets/6900292/10047735/74bf5b8e-6207-11e5-9b03-18bf5e7c69af.png)

Since the code I was working with contained functions like this, I'm unable to continue.

Do I need to file this as a separate bug?

**Comment by MHeasell** [comment]
Oh my god I'm using the wrong language aren't I.

Disregard previous comment.

**Comment by MHeasell** [comment]
Okay, @nwinter, here is the smallest complete example I could come up with. When pasted into the editor for Ace of Coders, I get the mentioned error in the console.

```javascript
var v = new Vector(0, 0);

this.foo = function (units) {
    for (var i = 0; i < units.length; ++i) {
        var unit = units[i];
        var d = unit.pos.distance(v);
    }
};

this.bar = function (units) {
    for (var i = 0; i < units.length; ++i) {
        var unit = units[i];
        var d = unit.pos.distance(v);
    }
};
```

Some observations:

* Deleting either function makes the error go away
* Replacing either occurrence of `units[i]` with `units[0]` makes the error go away

Happy debugging!

**Comment by nwinter** [comment]
Thanks! Can you find a workaround (perhaps by changing argument/function names) that lets you get past it for now in your real code?

**Comment by MHeasell** [comment]
Hmm, I see now that renaming the `units` parameter in one of the functions to something else is also enough to avoid triggering the error.

I can probably work with this, assuming that this solves the problem in my competitive code. Isolating this bug has stolen all my motivation for the short-term though, so I'll have to wait for another time to see how things go.

**Comment by Driphter** [comment]
I've also been encountering this bug. I've been working around it by, like you, fiddling with the problematic functions. Usually it's changing `unitA.distanceTo(unitB)` to `unitA.pos.distance(unitB.pos)`.

**Comment by fisch0920** [comment]
:+1:

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
