### ISSUE TITLE
Artillery can accelerate to speeds beyond the intended maximum speed.

### ISSUE THREAD

**Issue by NoJuice4u** [codecombat/codecombat#3062]
I'm sure that many of us have seen the weird case where an artillery manages to accelerate to a speed beyond the maximum velocity set for an artillery.

After poking around, I produced a small code block that can produce the issue.  It seems to revolve around using the "attack" command to pick a target outside of the attack range, then switching to "attackPos" to attack the ground (somewhere within range), then issuing a few "move" commands in sequence to trigger.

Code Sample (Tested in the "Ace of Coders" level, against multiple opponents):
```javascript
this.summon("artillery");
var artillery = this.findByType("artillery", this.findFriends())[0];
var eGol = this.findByType("goliath", this.findEnemies())[0];
loop {
    this.command(artillery, "attack", eGol);
    this.move(new Vector(0, 0));
    this.command(artillery, "attackPos", new Vector(40, 40));
    this.move(new Vector(0, 0));
    // this.move(new Vector(0, 0)); // Uncomment to time it perfectly for the artillery to hit itself
    // this.move(new Vector(0, 0)); // Uncomment to time it perfectly for the artillery to hit itself
    this.command(artillery, "move", new Vector(0, 0));
    loop {
        this.command(artillery, "move", new Vector(0, 0));
        this.move(new Vector(0, 0));
    }
}
```

**Comment by Driphter** [comment]
Here's some more code that triggers the bug:

``` javascript
var timeAfterShotToMove = 3; // Bug occurs: 0.25 .. 3
var timeBetweenShots = 4; // Bug occurs: max(1, (cd + 0.25))
                          // Default Cooldown = 3.6 (effectively 3.75)
this.summon("artillery");
var shot;
loop {
    var arty = this.findFriends()[1];
    if (!arty) continue;
    if (shot && shot === this.now() - timeAfterShotToMove) {
        this.command(arty, "move", this.getControlPointsMap().farB.pos);
    } else if (!shot || shot === this.now() - timeBetweenShots) {
        this.command(arty, "attackPos", this.getControlPointsMap().center.pos);
        shot = this.now();
    }
}
```

Also tested in the level editor with various cooldowns. It seems that the bug revolves around some "ignored" momentum that is gained when using a move command within 3 seconds of artillery attacking. If the artillery attacks again on cooldown and moves again after attacking, the momentum seems to multiply.

**Comment by nwinter** [comment]
Finally got it, thanks for the debugging help! There was a piece of code that was letting accelerations from a previous successful move continue if the player commanded a move while attack was on cooldown.
