### ISSUE TITLE
sarven sum self.moveXY() seems broken with increased speed

### ISSUE THREAD

**Issue by mrnetops** [codecombat/codecombat#3063]
self.moveXY() seems to be including some kind of speed offset to the position requested, so your position ends up offset from what you requested.

```
whiteX = {'x':27, 'y':42}
redX = {'x':151 , 'y': 118}
min = 999999
max = 0
for trap in self.findByType("fire-trap"):
    if trap.value > max:
        max = trap.value
    if trap.value < min:
        min = trap.value
        
value = min + max
self.moveXY(28, 42)
self.say(value)
```

arryn + speed ring results in a large enough offset that the cat does not disable the traps on the say.

3 runs, one with anya, two with arryn, 3 with arryn + speed ring

![sarven sum 1](https://cloud.githubusercontent.com/assets/6243417/10116081/8c620916-63d9-11e5-9045-a65b7c2d814c.png)
![sarven sum 2](https://cloud.githubusercontent.com/assets/6243417/10116080/8c61d144-63d9-11e5-9672-19654dbd7c11.png)
![sarven sum 3](https://cloud.githubusercontent.com/assets/6243417/10116082/8c62cb3a-63d9-11e5-98f3-bd3c719700f7.png)

**Comment by nwinter** [comment]
Fixed, thanks!
