### ISSUE TITLE
Students course page bug

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3096]
This happens when I'm in the students view: when I click the arrow (shown bellow) to sort the students by name...
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/10405343/20e392f2-6ed0-11e5-91f8-d626332c3066.png)
... the tab is switched to the 'Levels' one, from the 'Class Progress'.

**Comment by nwinter** [comment]
The teachers view is already reimplemented, and we'll be replacing the student view soon enough, will make this obsolete.
