### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by YourMCGeek** [codecombat/codecombat#3107]
The code in the coding window is right. Multiple students have had the same code. The preview though for the program does not work though? Confirmed Bug?

**Comment by nwinter** [comment]
What is the code, for what level, and how does it not work?

**Comment by YourMCGeek** [comment]
It was some desert levels. But the code in the editor did not match what the hero placeholder was doing.

**Comment by nwinter** [comment]
Still not working? If I can get some more details, I can try to debug this.
