### ISSUE TITLE
mind the trap dead time

### ISSUE THREAD

**Issue by mrnetops** [codecombat/codecombat#3114]
"Mind the Trap" seems to have about 4.5 seconds worth of dead time at the end of the level (time between last enemy death and level completion) that artificially limits the best completion time to 24.07 seconds.  Ideally I'd like to be able to reach that sweet sweet 19.8 second completion time or thereabouts with efficient dispatching.

**Comment by Catsync** [comment]
I changed the way the win condition is calculated, so it should be possible to win faster now.

**Comment by mrnetops** [comment]
wow, changed it quite a bit I see.

On Thu, Oct 15, 2015 at 7:13 AM, Catsync <notifications@github.com> wrote:

> I changed the way the win condition is calculated, so it should be
> possible to win faster now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codecombat/codecombat/issues/3114#issuecomment-148398208>
> .
>



-- 
It turns out I'm secretly evil

**Comment by anter69** [comment]
I wonder how can you finish that level in 0.47 seconds...

![image](https://cloud.githubusercontent.com/assets/12795864/10639407/5f7ea9ea-7810-11e5-987f-c62f15faa127.png)

**Comment by nwinter** [comment]
f0mster let me know of a bug that can cause incorrect level completion times to be reported, so I'll try to fix that soon.

**Comment by anter69** [comment]
Oh, good. These impossible level times seem to appear everywhere... 15 minutes of fame for f0mster? :-)

**Comment by nwinter** [comment]
f0mster will have more than 15 minutes based on his non-buggy leaderboard performance on pretty much every other level ;)
