### ISSUE TITLE
Error when opening i18n page

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3126]
When opening the [i18n page](https://codecombat.com/i18n), this error appears:

Uncaught TypeError: Array.prototype.indexOf called on null or undefined --> I18NHomeView.coffee:93

t.exports.t.updateCoverageForModel	@	I18NHomeView.coffee:93
t.exports.t.updateCoverage     @	I18NHomeView.coffee:84
t.exports.t.getRenderData	@	I18NHomeView.coffee:68
t.exports.t.render	@	CocoView.coffee:111
t.exports.t.onCollectionSynced	@	I18NHomeView.coffee:60
h	@	backbone.js:207
t.Events.trigger	@	backbone.js:146
t.success	@	backbone.js:862
u	@	jquery.js:3099
c.fireWith	@	jquery.js:3211
i	@	jquery.js:8264
(anonymous function)	@	jquery.js:8605

**Comment by trotod** [comment]
Seems like the Dungeon Branching Test campaign is missing `i18nCoverage`...

**Comment by nwinter** [comment]
Right! I added it for now, and have also fixed the bug in 110ee58.
