### ISSUE TITLE
Text overlapping account drop-down

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3127]
If I navigate to the [contribute page](https://codecombat.com/contribute), and then open the account drop-down (while in russian language, in this example), the text of the contribute page overlaps the drop-down.
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/10637797/67dab202-77ff-11e5-87b1-4471ae66025e.png)

Note: I found out that if [this line]( https://github.com/codecombat/codecombat/blob/master/app/styles/contribute/contribute.sass#L16) is removed, this issue gets fixed (don't know if it affects anything else).

**Comment by viettruong2194** [comment]
I added 'z-index: 0' to the .class_tile class:

<img width="391" alt="screen shot 2015-11-19 at 11 58 43 pm" src="https://cloud.githubusercontent.com/assets/7356884/11294653/133ab800-8f1a-11e5-99cf-6eb2142c8c4c.png">

I actually just saw your note suggesting we remove the z-index for the text; if that approach is preferred let me know and I'll change it.

**Comment by Imperadeiro98** [comment]
It is probably simpler to just remove as I suggested, but I am not sure if it affects anything else.
