### ISSUE TITLE
Tell the author that this fails on your system: npm ERR!     node install.js

### ISSUE THREAD

**Issue by wenzhong999** [codecombat/codecombat#3135]
sudo python ./coco/scripts/devSetup/setup.py error!

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--python=python"
npm ERR! node v0.10.35
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/licanlong/Desktop/coco/npm-debug.log
Traceback (most recent call last):
  File "./coco/scripts/devSetup/setup.py", line 46, in <module>
    setup.setup()
  File "/Users/licanlong/Desktop/coco/scripts/devSetup/factories.py", line 82, in setup
    super(self.__class__, self).setup()
  File "/Users/licanlong/Desktop/coco/scripts/devSetup/factories.py", line 51, in setup
    self.repoCloner.install_node_packages()
  File "/Users/licanlong/Desktop/coco/scripts/devSetup/repositoryInstaller.py", line 77, in install_node_packages
    raise errors.CoCoError(u"Failed to install node packages")
errors.CoCoError: u'Failed to install node packages\n Please contact CodeCombat support, and include this error in your message.'

OS X EI Capitan 10.11 macbook air

**Comment by nwinter** [comment]
We have a new method of installing the dev environment now; check the wiki for the latest.
