### ISSUE TITLE
Stuck in the level A Mayhem of Munchkins.

### ISSUE THREAD

**Issue by jlsa** [codecombat/codecombat#3159]
Finishing this [level, A Mayhem of Munchkins](http://codecombat.com/play/level/a-mayhem-of-munchkins) results in a screen that stays still forever. 
![screen shot 2015-11-06 at 21 36 42](https://cloud.githubusercontent.com/assets/6825082/11008252/8cce6afe-84cf-11e5-9b66-e3856bc5bc51.png)

**Comment by nwinter** [comment]
Thanks for the heads up, @jlsa; I've fixed the bug and am deploying the fix now.

**Comment by jlsa** [comment]
You're welcome!
