### ISSUE TITLE
Lua self:findNearestEnemy without brackets

### ISSUE THREAD

**Issue by headspeak** [codecombat/codecombat#3166]
If findNearestEnemy is select in the proposal list, then the code ist with self:findNearestEnemy is completed - without brackets.

**Comment by ikeban** [comment]
I also write my solutions to problems in LUA and this lack of brackets in function findNearestEnemy got me crazy - so many times I had compilation error, because of this missing brackets.
I'm so angry, that I will try to fix it myself - I have no idea if it is hard or not - but at least I will TRY :)

**Comment by ikeban** [comment]
Hello,
I was able to built and run game from github on my local machine. I also read few articles on WIKI, how CodeCombat is organised.
Now I would like to change auto complete text for findNearestEnemy (from "self:findNearestEnemy" to "self:findNearestEnemy()").

For every level, user has to write a code. On right side of screen there is special editor, which is used to type code. This editor has auto complete feature - which behaviour I would like to modify for LUA. I guess that the editor is written in JavaScript, and code for this editor is executed on a client PC. If so, then I guess that it must be implemented somewhere in /app/ folder.

Could someone confirm that my above conclusions are correct? Could someone please give me a tip, where I should start my implementation (where I should look at - which files/folders)? Maybe the editor (and auto complete feature) are third party program? (if so where is it? which one is it?) Maybe auto complete feature uses database somehow to provide it's functionality? 
Is there any documentation related to this topic, which I should read?

Regards,
Ikeban

**Comment by nwinter** [comment]
Sorry for the slow response on this, guys. Actually, this one was lurking in a hard-to-find spot: in the snippets section of the findNearestEnemy documentation in the alliance.Allied Component of the Components tab of the level editor online! I've gone and fixed that one up now, so if you clear your cache, you should see the proper `self:findNearestEnemy()` inserted with snippets now.

Thanks for noting the bug!

**Comment by ikeban** [comment]
Thank you nwinter for fix - I see where you changed it and I will try to fix other things which I spotted during my LUA adventure in CodeCombat.
