### ISSUE TITLE
The Raised Sword requiring subscription in China

### ISSUE THREAD

**Issue by hinklefoxmail** [codecombat/codecombat#3169]
Running this with a class. For a small number of users (usually the ones using the Chinese Language) the level the Raised Sword is asking for a subscription making it impossible to advance. Creating new accounts does not help. Other users having no problems.

![raised sword](https://cloud.githubusercontent.com/assets/15206556/11056490/5142b5da-87bd-11e5-9581-f9ab783be8ca.jpg)

**Comment by nwinter** [comment]
Try the new Courses flow in China instead, which is the intended flow for classrooms: http://cn.codecombat.com/hoc
