### ISSUE TITLE
'Not Found' error in pending patches page

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3179]
In the pending patches [page](https://codecombat.com/admin/pending-patches), I'm getting these two errors in the console:

- POST http://direct.codecombat.com/db/thang_type/names 404 (Not Found)
- POST http://direct.codecombat.com/db/level_component/names 404 (Not Found)
- POST http://direct.codecombat.com/db/level_system/names 404 (Not Found)

**Comment by nwinter** [comment]
Ah, yeah, we did a big refactoring and now URLs with `_` in them instead of `.` (like `level.component`) don't work, so keep your eye out for any that are 404ing because they're formatted wrong.
