### ISSUE TITLE
Editor of Discourse WebSites - missing Button to mark a Code Block

### ISSUE THREAD

**Issue by headspeak** [codecombat/codecombat#3194]
I noticed by replaying to a question of lua code of a new programmer that I am missing a button for [code][/code] in the button bar of the editor. Manually inserting these tags works, but a new programmer does not know a Wiki language.

**Comment by nwinter** [comment]
I know it's not super intuitive, but you can do the preformatted-text button:

<img width="720" alt="screenshot 2015-11-21 16 03 40" src="https://cloud.githubusercontent.com/assets/99704/11321197/8e0b5cf6-9069-11e5-801d-059e8c33866e.png">

That indents things by 4 spaces, which is similar to using [code][/code] or \`\`\`triple backticks\`\`\`.
