### ISSUE TITLE
UsesSnippets translating into German

### ISSUE THREAD

**Issue by headspeak** [codecombat/codecombat#3197]
Maybe I don't understand how the translation website works:
1. chose text/chapter to translate
2. translate into the lines unter the small text/strings
3. submitting
4. translation website will be show the new state after reloading

It works for all texts except UsesSnippets to German. The translation seems sometimes to be submitted (look at the end of the translating page). Some parts were not submitted and were deleted.

PS: Where is the difference between "Specifically Covered" and "Generally Covered"? (Without a context I cannot translate into German).

**Comment by Imperadeiro98** [comment]
Hello, @headspeak
The way the translation flow works is that if you submit a change to something that was not previously translated, it is added right away to the game. But if it had a translation before, yours is submitted as a patch that someone needs to accept before appearing in the game.

'Specifically Covered' means that the property you are looking at is translated in the language you chose.
'Generally Covered' means that it is translated in one of the languages of the family of the one you chose (example: de-AT, de-CH, de-DE are all from the same family [de]).
