### ISSUE TITLE
Redundant Simple Sword reward 

### ISSUE THREAD

**Issue by mkronenfeld** [codecombat/codecombat#3198]
You can get the simple sword as reward for finishing one of these levels:
* Kithgard: Forgetful Gemsmith
* Kithgard: Signs and Portents

Since these levels are immediately consecutive and you don't need a sword to finish K:SaP, the reward in K:GS can be removed.

As far as I know K:SaP was implemented in a later update.

**Comment by nwinter** [comment]
Good point; we were originally considering Signs and Portents as an alternative to Forgetful Gemsmith, but then it was more difficult, so we use it as a side level now. I've removed the redundant unlocks.
