### ISSUE TITLE
China: wakka-mau doesn't load

### ISSUE THREAD

**Issue by hinklefoxmail** [codecombat/codecombat#3201]
The Wakka Mau doesn't load in China via the link in the courses page.

Brings up errors:
Error loading from server (Your Sessions) Not found.
Error loading from server (Level) Not found.

The level is still accessible via http://codecombat.com/play/level/wakka-maul
Works fine when using US server (via VPN).

Console Log:
unreachable code after return statement aether.js:22598:8
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create aether.js:272:9
unreachable code after return statement app.js:11739:6
unreachable code after return statement app.js:11752:6
unreachable code after return statement app.js:12585:4
unreachable code after return statement 56444a9c21342f3f056f7814:67:4
unreachable code after return statement 56444a9c21342f3f056f7814:4813:4
unreachable code after return statement 56444a9c21342f3f056f7814:9041:4
Unexpected value translate(NaN, NaN) parsing transform attribute. 56444a9c21342f3f056f7814:594:0
Unexpected value NaN parsing height attribute. 56444a9c21342f3f056f7814:594:0
Unexpected value translate(NaN, NaN) parsing transform attribute. 56444a9c21342f3f056f7814:594:0
Unexpected value NaN parsing height attribute.

**Comment by nwinter** [comment]
Fixed, thanks!
