### ISSUE TITLE
"Completed 10 Basic Syntax Levels" achievement is not unlocking

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3214]
The "Completed 10 Basic Syntax Levels" achievement is not getting unlocked for me:

![](http://i.imgur.com/7b8Vsxh.png)

I had already completed 10 basic syntax levels before this achievement was created, perhaps that is related to the issue. I've tried resubmitting a basic syntax level solution and the achievement still did not unlock.

**Comment by lepidopteralady** [comment]
I'm having the same issue, however my screenshot makes it look hilarious because I've just earned the 50 syntax levels achievement.
I'm learning Python, on Google Chrome, in Linux Mint 17.2 Rafaela.
![bug](https://cloud.githubusercontent.com/assets/15007314/11457173/a2986ab6-9667-11e5-8c91-647b4b2fdd2e.png)

**Comment by phyrenight** [comment]
I just got this achievement.I'm learning python, on Chrome,  in Windows 8.
![complete 10](https://cloud.githubusercontent.com/assets/14168678/11461704/7f537db0-96bd-11e5-8724-be2712eb5dcc.png)

**Comment by UltCombo** [comment]
So it seems this is a problem only for those that had already completed the given number of basic syntax levels before the achievement was added to the game.

**Comment by UltCombo** [comment]
Looks like @nwinter made a [migration script](https://github.com/codecombat/codecombat/commit/9d21f87345e20e07742ced8e9de09742276c4562), so I'm assuming this will be fixed in the next deploy.

**Comment by UltCombo** [comment]
The same problem now happens for "Completed 5 Arrays Levels", "Completed 5 Object Literals Levels", "Completed 2 Vectors Levels" and that whole class of achievements.

Seems like old accounts are missing a lot of XP and gems due to that.

**Comment by anter69** [comment]
Same here: I basically completed every level available (and even more) in CodeCombat, but I'm missing these basic achievements:

![image](https://cloud.githubusercontent.com/assets/12795864/13074910/e41ca2f8-d4a7-11e5-9ac2-786787f1a8ef.png)

---

But there is something wrong with the multiplayer achievements too, as I already [mentioned on slack](https://codecombat.slack.com/archives/general/p1454579097000325): beating an AI player does not unlock the relevant achievement.

Related to that, I copy - once again - my comment from #1957:
> I suggest that all players (no matter when they submitted their code) should be matched (at least 2-5 times) against all AI levels to have a chance for getting the achievements.

**Comment by UltCombo** [comment]
@anter69 As for the AI achievements, I believe the plan is to improve the UI to make it easier to select an AI opponent to fight against, and then improve the AI achievements system to unlock these achievements when synchronously fighting an AI (i.e. at the moment you play against an AI and submit winning code). You can see more of this discussion in #3241, though we should perhaps open a more focused thread.

**Comment by anter69** [comment]
This might be a good enhancement, but it seems to be a lot of work -- which could be avoided if the matching script would simply check any and all solutions against the AIs (unless the player already beat them):
```py
if player.achievement("Beat simple AI") == False and "simple AI" not in player.opponentsList:
   nextOpponent = "simple AI"
```
(I'm totally unfamiliar with the underlying code, obviously)

**Comment by UltCombo** [comment]
Yeah, I guess that would be an improvement to the simulations matching logic.

Also, I believe the achievement could be unlocked both ways—through sync and async simulations. It is a pretty bad user experience to beat an AI in the synchronous simulation and not get the achievement for it. Perhaps this is not so much work, as it seems the synchronous simulation already unlocks the achievement for the Simple AI, and Nick has stated that the team has been working on improving the multiplayer UI, so maybe they get to improve the opponent selection as well.

Again, though, it should be better to discuss this in #3241 or a new dedicated issue. We are only scattering this topic across several threads which makes it harder to track, and derailing this thread which should be about backfilling newly created achievements.

**Comment by UltCombo** [comment]
Hey people, any updates here? Any way I can help?

In any case, I have some suggestions for possible solutions:

- Run a script every 24 hours or so (like a cron job or a similar `setInterval` logic) that syncs up the achievements. In order to avoid overloading the server, this process should only run for "active" users (users that have logged in in the last 48 hours?) and be processed in batches (200~2,000 users at time?).

- Add a "Refresh" button to the Achievements modal that sends an API call to recalculate the achievements. This API should be rate-limited in order to avoid abuse/DoS, of course.

Let me know if any of these suggestions sound good, and I may start working on them if I have time. Note that these suggestions would not only fix this specific issue (#3214), but also any problems related to creating new achievements or adding concepts to existing levels (#3240).

**Comment by anter69** [comment]
I guess that achievements are currently checked and awarded when you successfully finish (submit) a level _for the first time_. So, why not remove the "first time only" restriction? That would require minimal changes, and would probably not need much extra resources either. Obviously, players would need to resubmit a few levels, but that's not much of an effort for the extra gems + xp...

**Comment by UltCombo** [comment]
@anter69 Seems like you are assuming that when you complete a level, the system queries the amount of completed levels that match the requirement (i.e. "basic syntax" levels) to unlock the achievement. As far as I can see, that is not how these achievements are handled currently.

When you beat a "basic syntax" level, it just increments your user's `stats.concepts.basic_syntax` counter. Removing the "first time only" restriction" means you would have to resubmit 50 levels in order to unlock the "Completed 50 Basic Syntax Levels" achievement. I believe we can agree that this would be rather unpleasant, right?

So, for your suggested approach to work correctly, we would first have to rewrite most of the achievements earning system, which completely kills your "minimal changes" motivation.

I'd suggest taking another look at my suggestions [above](https://github.com/codecombat/codecombat/issues/3214#issuecomment-202221319). Note that the "batched processing" I've suggesting can be replaced by MongoDB's built-in streaming fetch mode.

**Comment by anter69** [comment]
You're right, it wouldn't be pleasant to resubmit 50 levels... Thus, both your suggested solutions seem to be OK. Or they could be merged, so that you have a "request update" button on the achievements modal, and then all requests are processed in a batch once a day (or every few hours).

**Comment by UltCombo** [comment]
After giving this a bit more of thought, it may be possible to mix and match @anter69's suggestion into a third option, which would consist of the following steps:

1. Check for unlocked achievements on every victory submission, not just the first one;
1. For each programming concept associated with the level, recalculate the user's score in the given concept. More specifically, query the amount of levels that the user has beaten associated with the given concept, then save the new count in the user's `stats.concepts` object.
1. Finally, for each updated concept score, award the achievements for the given concept that require <= the user's score that have not been awarded yet.

I'd give special attention to the 3rd point above, as I've just been awarded the "Completed 5 recursion levels" but I have not received the "Completed 2 recursion levels" achievement yet! (Seriously, lol)

I know this approach may sound a bit complicated, but the other two suggestions I've posted are not very easy either. Well, perhaps a recalc button in the Achievements modal that would refresh the scores for all concepts would be easier to implement and reason about, but perhaps harder for users to find.

I'd like some feedback from the CodeCombat before I start dedicating time to implementing a fix.

**Comment by nwinter** [comment]
That sounds like the performance would be kind of slow, right?

I think the current approach should work to trigger the old achievements that should match the achievement query, since we know when a new level is beaten and successfully make a new achievement for the highest tier, but there must be some bug where it's not also making the ones for lower tiers. Maybe we can just fix the bug?

**Comment by UltCombo** [comment]
> That sounds like the performance would be kind of slow, right?

I'm not sure about performance. We are already hitting the server for every successful submission, right? I haven't checked the perf impact of the achievement unlocking logic yet, but I assume most people won't be repeatedly hitting the servers with successful submissions (except the most hardcore players trying for best seeds/high scores).

With your suggestion, one of the remaining problems is that people who have completed all available levels (reportedly [another user](https://discourse.codecombat.com/t/i-have-not-some-achievements/7264) experiencing the same issue and me) would have to wait until a new level that presents the specific concept is released, which would be a pretty bad experience IMO.

**Comment by nwinter** [comment]
My migration script should cover it, if we fix the just-in-time issue; just the migration script takes a long time to load all levels so we can index by concept.

**Comment by UltCombo** [comment]
Oh, nice!

**Comment by UltCombo** [comment]
So, I took a look on this. The issue is in the [`alreadyAchieved` logic](https://github.com/codecombat/codecombat/blob/9f3aac3313b9d1658b7ab11e3168c8551a44697f/server/plugins/achievements.coffee#L42). It considers an achievement as already achieved if the `unchangedCopy` (the user's data prior to this level session submission) would suffice to unlock it; it does not check whether a corresponding `earnedAchievement` actually exists in the db.

Under "normal" circumstances (i.e. the achievement already exists at the time the user reaches its unlock requirement), the current logic would suffice. The problem occurs when you create a new achievement and given users are already past its unlock requirement.

So there is the bug where unlocking a higher tier achievement is not also unlocking the lower ones. I believe this would not be a problem in practice if you run a migration script whenever new achievements are created.

Do you think we should still improve the achievement unlocking logic?

**Comment by UltCombo** [comment]
To be more clear, the migrations should not only set the players' stats but also unlock any achievements that these new stats would have earned. Then the current achievement unlocking logic would suffice without changes.

I could improve the achievement unlocking logic to ensure that lower-tiered achievements are properly unlocked, but this should not be necessary if the migrations properly unlock those achievements.

@nwinter WDYT?

**Comment by nwinter** [comment]
I did have [this script](https://github.com/codecombat/codecombat/blob/master/scripts/recreateEarnedAchievements.coffee) at one time; it should still work, right? Maybe we should run this. @sderickson see any obvious issues with this script, or shall we fire it up?

**Comment by sderickson** [comment]
We could, but I think the solution of iterating over users, even streamed, is now untenable. I'm partial to the earlier suggestion of having a 'refresh' button users can press to run something like that script (updated to use generators?) on just themselves.

**Comment by sderickson** [comment]
Updated and new achievements are now checked when you are on the site. Mainly set up in [this commit](https://github.com/codecombat/codecombat/commit/2fe28852b4a717c269ae4daf3e9157bb8029bf66).

**Comment by UltCombo** [comment]
Yay, thank you very much! 😄

I've gave it a test and it seems to be working properly now, awesome work @sderickson.

**Comment by anter69** [comment]
Wow, 20000 gems earned in a second! ;-)
