### ISSUE TITLE
dev server error: spawn nodemon ENOENT

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3219]
Whenever I try to start the dev server, it throws an ENOENT error. I tracked it down to Brunch not finding `nodemon`.

You guys that are running the dev server (`npm run dev`) on a Linux/Mac setup, do you have nodemon on your `$PATH` (check with `which nodemon`)? If not, then Brunch is working as expected and I'm facing a more specific issue (perhaps: [child_process.spawn ignores PATHEXT on Windows](https://github.com/nodejs/node-v0.x-archive/issues/2318)).

If you ***do*** have nodemon in your `$PATH`, then it should probably be documented in the Wiki and added to the vagrant setup's provisioner shell.

**Comment by nwinter** [comment]
I don't have nodemon in my path, no.

**Comment by UltCombo** [comment]
Thanks for testing. I've just tested on OS X and `npm run dev` is working even without nodemon in the `$PATH` as well.

So this is a Windows-specific issue. I should be able to submit a fix later tonight.
