### ISSUE TITLE
Dev Setup Linux Does Not Work

### ISSUE THREAD

**Issue by bitaxis** [codecombat/codecombat#3220]
Hi.  I walked through the [Dev Setup: Linux](https://github.com/codecombat/codecombat/wiki/Dev-Setup%3A-Linux) section on a VM running 64-bit Ubuntu Server 15.10, ran into issues below and worked through them:

1. Install mongodb instead of mongoldb-org
2. The version of NodeJS installed by OS is too old; resort to using [nvm](https://github.com/creationix/nvm) to install version 4.2.2 of NodeJS.
3. Run ```sudo service mongodb start``` (because of  item 1)

Then, after I executed ```nom run dev``` or ```nom start```, I was able to bring the the CodeCombat home page locally as well as creating a new account.

But when I click on "Play", all the lands are greyed out.  I am unable choose a hero nor play any level.

What went wrong?

![codecombat-local-1](https://cloud.githubusercontent.com/assets/95088/11464597/6defc6b4-96e5-11e5-8cc4-0d53a9df711a.png)
![codecombat-local-2](https://cloud.githubusercontent.com/assets/95088/11464607/9c64db6a-96e5-11e5-9290-7d932aa5aea4.png)

**Comment by nwinter** [comment]
The campaigns not showing up: this issue? https://github.com/codecombat/codecombat/issues/3216#issuecomment-160516623

The database dump restored without errors, right? Is there any content in http://localhost:3000/db/level/dungeons-of-kithgard ?
