### ISSUE TITLE
Massive memory leak \w python

### ISSUE THREAD

**Issue by Eximius** [codecombat/codecombat#3224]
The game leaks all the memory up to max possible (1GB) in chrome (46.0.2490.86 (Official Build) m (32-bit)) Win8 and then spontaneously crashes, when I write 
```
plan = [ (0,1), (1, 2), (2, 1), (1, 2), (0, 2), (1, 1), (3, 1), (0,1), (3,3), (4, 'Abracadabra')] 
def m(s, n):
    a = [self.moveRight, self.moveUp, self.moveLeft, self.moveDown]
    for i in range(n):
        a[s]()

def dispatch(event):
    code = event[0]
    if code < 4:
        m( # Complete this line with '*code)'  to get the crash
            
while True:
    for p in plan:
        enemy = self.findNearestEnemy()
        if enemy:
            self.attack(enemy)
        else:
            dispatch(p)
```

in "Kithgard Mastery".

Seems like the python autocomplete helper, or sanitizer, or the something is out of whack with python argument expansion.

**Comment by nwinter** [comment]
Is it just Kithgard Mastery? That level takes a lot of memory due to the way it constructs the level dynamically; needs some work. Do you see leaks like this with the same code in other levels?

**Comment by Eximius** [comment]
I didn't test that, and  I am only privy to the forest levels because I checked out the game for 10 mins or so :)

**Comment by Eximius** [comment]
Kithgard Mastery seemed to only take 340MB ~ in the chrome process. It spikes to 1GB when you do the aforementioned code writery, and then, of course, it dies.

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter, although note that the Python *spread operator isn't implemented in our Python parser yet.
