### ISSUE TITLE
Database import failed

### ISSUE THREAD

**Issue by lian1925** [codecombat/codecombat#3225]
I download the database dump from http://analytics.codecombat.com:8080/dump.tar.gz.
And then I unpack the archive and run: mongorestore --drop /root/data/dump  (/root/data is the path of database dump), but it failed.
Here is the error
2015-12-02T13:15:46.499+0800	restoring coco.media.files from file /root/data/dump/coco/media.files.bson
2015-12-02T13:15:46.507+0800	Failed: restore error: coco.media.chunks: error restoring from /root/data/dump/coco/media.chunks.bson: insertion error: EOF

Eviroment: debian7.5 Mongodb v3.0.7
Could you give the help ? Thanks

**Comment by nwinter** [comment]
What happens if you include the `--batchSize=100` option?

```
mongorestore --drop --batchSize=100 /root/data/dump
```

**Comment by lian1925** [comment]
That is ok. Thanks very much

**Comment by nwinter** [comment]
I updated [the wiki](https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Issues) to note this workaround for certain Mongo versions having this problem.
