### ISSUE TITLE
Playing free course levels unlock the corresponding subscriber levels in the campaign mode

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3229]
Steps to reproduce:

1. Log in with a free account;
1. Create a free course (Introduction to Computer Science) and complete all of the course's levels;
1. Go to the campaign mode's [dungeon world](http://codecombat.com/play/dungeon);
1. Some of the course levels that are subscriber-only in the campaign mode will be marked as complete. Thus, you will be able to replay and re-submit them, earning xp and gems :gem: in the process.

I'm not sure if this is intended behavior or not, so I'm reporting as a possible bug.

**Comment by nwinter** [comment]
Eh, I'm not too concerned about it.
