### ISSUE TITLE
"The Gauntlet" level: the "Done in fewer than 6 code statements" goal is not unlocking

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3230]
Although the "Under 6 statements" goal shows as completed in the top-left goals-checklist-thingy, it is not unlocked in the victory modal:

![Victory modal](http://i.imgur.com/EKYXx0O.png)

Here's the Python code:

```py
while True:
    self.moveRight()
    self.attack(self.findNearestEnemy())
```

**Comment by nwinter** [comment]
Fixed, will update soon. Thanks!

**Comment by UltCombo** [comment]
Woah that was fast, thanks. :smile:
