### ISSUE TITLE
Improve Teachers Page Design

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#3234]
At the moment, the [teacher page](https://codecombat.com/teachers) leaves some to be desired.

![](https://photos-1.dropbox.com/t/2/AACqp3JVH-T1LS8t_a5tGal6l8LFEaPRPMufLwxQ_Iu4Aw/12/96369584/png/32x32/3/1449244800/0/2/2015-12-04%2011_29_21-CodeCombat%20-%20Learn%20how%20to%20code%20by%20playing%20a%20game.png/ELDMxNIDGHcgASAHKAc/HZXE34DWInioTB9mCisvW7rMnV_C4FZ176-KgNzzyRQ?size_mode=3&size=1024x768)

It would be nice to improve this, perhaps with some styling or at least with actual arrows for "<-".

**Comment by Imperadeiro98** [comment]
Also, the line that says "Teachers, please see the free trial information above for further details." is referring to what 'free trial information above'?

**Comment by popey456963** [comment]
Also, something doesn't seem right with the code...

```jade
        .faq-question(data-i18n="teachers.who_for_title")
        p(data-i18n="teachers.who_for_1")
        p(data-i18n="teachers.who_for_2")

        .faq-question Does it cost anything to play Hour of Code?
        p No! The first hour of CodeCombat is completely free.
        p Teachers, please see the free trial information above for further details.

        .faq-question(data-i18n="teachers.more_info_title")
        p
          span.spr(data-i18n="teachers.more_info_1")
          a(href='http://discourse.codecombat.com/c/teachers', data-i18n="teachers.more_info_2")
          span.spl(data-i18n="teachers.more_info_3")
```

Does this mean we aren't i18n'ing the second bullet point?

**Comment by Imperadeiro98** [comment]
Yeah, but I am planning on adding i18n to the new code. Just waiting for the pages to stabilize.

**Comment by nwinter** [comment]
We totally reimplemented this whole area of the site.
