### ISSUE TITLE
 How can I add some courses in codecombat server?

### ISSUE THREAD

**Issue by lian1925** [codecombat/codecombat#3245]
After I have deployed the codecombat on the server , I found that it has no available course . How can I add some courses ? Could you give me some tip ? Thanks.

![error](https://cloud.githubusercontent.com/assets/10208302/11623170/ff2e3676-9d05-11e5-992e-609807a7190d.png)

**Comment by popey456963** [comment]
Hello @lian1925 , courses aren't in the database dump so of course the development version wouldn't have any courses available to it.  We've created another issue #3246 to try to fix this issue that I see you've commented on.  So as not to get everything split up between two different places, I'm going to close this issue.

**Comment by lian1925** [comment]
ok,thanks
