### ISSUE TITLE
Achievement translations not saving

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#3247]
Had a report yesterday for `pt-BR` and one also for `it` that Achievement translation edits/patches are silently failing.

**Comment by nwinter** [comment]
Now we have an error:

> Can't save Russian translation on https://codecombat.com/i18n/achievement/dungeons-of-kithgard-clean-code  – it reports: 
> Error saving Patch: 500 error {"message":"","property":"target.id"}

**Comment by Bryukh** [comment]
I tried to accept the translation patch for the achievement (https://codecombat.com/editor/achievement/hold-the-forest-pass-complete) and I got the error:
```
jquery.js:8630 PUT https://codecombat.com/db/patch/57018085f448484b00d9bb83/status 504 ()
send	@	jquery.js:8630
ajax	@	jquery.js:8166
t.exports.t.setStatus	@	Patch.coffee:12
t.exports.t.setStatus	@	Patch.coffee:9
t.exports.t.acceptPatch	@	PatchModal.coffee:69
r	@	lodash.js:729
dispatch	@	jquery.js:4435
v.handle	@	jquery.js:4121
```

I have admin permissions.

**Comment by Bryukh** [comment]
Additional:
When I tried to accept the patches [here](https://direct.codecombat.com/editor/achievement/bombing-run-complete), I got the same error (504), but texts were changed as it was in the patch. So it looks like patches were accepted and we got translations, but the patches are marked as "pending".

**Comment by sderickson** [comment]
This should be fixed with the recent [I18N changes](https://github.com/codecombat/codecombat/commit/7bab895dee010c780ff6f2458bdf4a9847bb71bb).
