### ISSUE TITLE
Getting errors after clicking play in campaign map

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3264]
When I click the 'Play' button to start a level...
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/11820285/9815095e-a35b-11e5-908a-671c43328071.png)
... I get some errors like:

- Trying to determine whether **item** should be a silhouetted item, but it has no gem cost.

**Comment by nwinter** [comment]
They are cosmetic logging errors; I have been ignoring them for a year, but yeah, gotta figure out what is going on there.
