### ISSUE TITLE
Error when accessing achievement without being logged in

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3266]
While trying to access an achievement in the achievement editor ([example](http://direct.codecombat.com/editor/achievement/deadly-pursuit-complete)) without having access to it (being logged out or logged in with a normal account), this error appears in the console:

- Uncaught TypeError: Cannot read property 'build' of null - VM84:1019

**Comment by popey456963** [comment]
Note, this is still occurring in `AchievementEditView.coffee` around lines 45 --> 52:

```
      supermodel: @supermodel
    @treema = @$el.find('#achievement-treema').treema(options)
    @treema.build()
    @treema.childrenTreemas.rewards?.open(3)
    @pushChangesToPreview()
```

Seems to be something to do with the @treema object being undefined, and so not having the property of .build...

**Comment by Maikdani** [comment]
Would like to give this a go, what would be the preferred action instead of showing the error and an empty page?

**Comment by nwinter** [comment]
I guess it would be best to show the Treema and the achievement editor interface, but make the Treema read-only, and hide any save controls. Second-best would be to leave the "admin-only" message and just not build the Treema so that error doesn't happen.
