### ISSUE TITLE
Repeated hero in play heroes modal

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3291]
In the play heroes modal, the hero Nalfar Cryptor is repeated, but in one of the versions it has no portrait and when clicking him his full image is not correctly sized.

![sem titulo](https://cloud.githubusercontent.com/assets/6980488/12051483/863c08c0-aefc-11e5-94d8-fc935901904e.png)

**Comment by nwinter** [comment]
I got rid of the extra hero fork.
