### ISSUE TITLE
How can I save a new level and include it in the main page

### ISSUE THREAD

**Issue by coollerjack** [codecombat/codecombat#3292]
I want to save  a new level in my local db and test it, but I don't know how to save it and include it in the main page

**Comment by nwinter** [comment]
If your local user is set to have admin permissions (in your account settings), then you will want to go to the campaign editor and add it to the campaign in order for it to show up, like http://localhost:3000/editor/campaign/dungeon and add it here.

<img width="697" alt="screenshot 2016-01-05 14 22 58" src="https://cloud.githubusercontent.com/assets/99704/12129346/dbe709d6-b3b7-11e5-8f17-1773323fb41e.png">

Then you would want to drag that dot to where you want it to go in the campaign map. You also need to make it unlocked by an achievement from some other level, so maybe in the achievement editor for the previous level you add it to the rewards section:

<img width="1167" alt="screenshot 2016-01-05 14 24 37" src="https://cloud.githubusercontent.com/assets/99704/12129378/1228dec0-b3b8-11e5-9fc2-90c4ebbb3fca.png">

Then after you did that you would want to load the campaign editor again and save it, and also maybe beat the level again that unlocks the new level.

But if you just want to test your level, and don't need it to be in the campaign, then you can do that with this button in upper right in the level editor:

<img width="329" alt="screenshot 2016-01-05 14 25 41" src="https://cloud.githubusercontent.com/assets/99704/12129398/38e189fe-b3b8-11e5-994b-44a920789409.png">

**Comment by coollerjack** [comment]
thank you for your answer and I will try my best to make a contribute to the game @nwinter
