### ISSUE TITLE
Console error when playing a level

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3299]
While playing a level, [this line](https://github.com/codecombat/codecombat/blob/master/app/models/Level.coffee#L168) gets fired several times at the beginning, just before the Goals/Intro modal appears.

**Comment by nwinter** [comment]
This is another cosmetic problem probably similar to https://github.com/codecombat/codecombat/issues/3264 except maybe something to do with loading projections that don't include components or something like that, I haven't looked into it. (It may also indicate a wasteful performance issue as well.) Maybe @taptapdan can save us!

**Comment by taptapdan** [comment]
I'm stepping through trying to understand what's going on here. If you load a level from the map (as opposed to loading it directly from url), it looks like the other heroes are getting pulled into [thangTypes](https://github.com/codecombat/codecombat/blob/master/app/models/Level.coffee#L31) that I'm guessing aren't supposed to be. I'll figure it out... :stuck_out_tongue_winking_eye:

The [serialize](https://github.com/codecombat/codecombat/blob/master/app/models/Level.coffee#L15) function is also running 2x on every level load, but I think that's a separate issue.

**Comment by nwinter** [comment]
Yeah, probably something with the projections of the heroes from the PlayHeroesView getting in there. Maybe we can load those separately or fix whatever that `notInLevel` part is supposed to be doing.

I wonder if we can get `serialize` to only run once; that takes a while, so could be hurting performance if we don't need to do it a second time.
