### ISSUE TITLE
/db/thang.type/529ffbf1cf1818f2be000001/version 404

### ISSUE THREAD

**Issue by fengbp** [codecombat/codecombat#3301]
I installed on the server codecombat, after running two 404 errors found,How can I solve:

GET /db/thang.type/529ec584c423d4e83b000014/version 404 177ms
GET /db/thang.type/529ffbf1cf1818f2be000001/version 404 179ms

**Comment by nwinter** [comment]
Do you have [the database dump](https://github.com/codecombat/codecombat/wiki/Dev-Setup:-General-Information#database)–are you seeing any other Thangs loading?
