### ISSUE TITLE
how to solve the problem of :"'ws://codecombat.com:9485/' failed"

### ISSUE THREAD

**Issue by coollerjack** [codecombat/codecombat#3302]
when I open "http://localhost:3000/editor/campaign/dungeon", it goes wrong and the console is below.
![2016-01-07 10 00 45 pm](https://cloud.githubusercontent.com/assets/16451569/12172225/96775f0c-b58a-11e5-906d-aa353ae68a76.png)

**Comment by nwinter** [comment]
That is a cosmetic error you can ignore if you want; it's basically saying it can't connect to the brunch autoreload server. If you run your server with `npm run dev`, then the brunch autoreload thing will be connected and it should be able to refresh automatically whenever you change the code.
