### ISSUE TITLE
CastsSoulLink - castSoulLink description - write error

### ISSUE THREAD

**Issue by headspeak** [codecombat/codecombat#3308]
In "#{spells.soul-link.range}m," is an 'm' a little too much.

**Comment by nwinter** [comment]
It is supposed to be there to indicate `meters` when interpolated:

<img width="528" alt="screenshot 2016-01-12 07 43 39" src="https://cloud.githubusercontent.com/assets/99704/12268118/407c877a-b900-11e5-9fb0-43e71aec6de3.png">
