### ISSUE TITLE
Facebook login does not work

### ISSUE THREAD

**Issue by vzverev78** [codecombat/codecombat#3310]
I click on "Sign In with Facebook", it opens Facebook login dialog, then I submit my credentials and nothing happens. In console I have:
could not get data, since no email provided
http://codecombat.com/javascripts/app/core/social-handlers/FacebookHandler.coffee line 46
Chrome 47.0.2526.106 m on Windows 8.1.

**Comment by nwinter** [comment]
Hmm, that's weird. Do you have any custom privacy settings on your Facebook account that would make Facebook not give us your email (which we need in order to make the authentication work)?

**Comment by vzverev78** [comment]
No, I don't think I have any special privacy settings.
Recently Facebook forced their apps to new API version. I had to upgrade v2.3 to v.2.5 Graph FB API on my project.
And in new version https://graph.facebook.com/me?access_token=... does not return email by default. You have to specify required user data explicitly:
https://graph.facebook.com/v2.5/me?fields=email,first_name,last_name&access_token=...
Maybe that helps.

**Comment by vzverev78** [comment]
See example here: https://developers.facebook.com/docs/javascript/reference/FB.api
It looks like you have to change line 42 in https://github.com/codecombat/codecombat/blob/master/app/core/social-handlers/FacebookHandler.coffee
```javascript
  fetchMeForLogin: ->
    FB.api('/me', @onReceiveMeInfo)
```
to
```javascript
  fetchMeForLogin: ->
    FB.api('/me', {fields: 'email,last_name,first_name,gender'}, @onReceiveMeInfo)
```

**Comment by nwinter** [comment]
Better now?

**Comment by vzverev78** [comment]
I see your changes but still the same error on line 46 :(
Maybe you can add debug info what we get in r after calling FB.api('/me')?

**Comment by nwinter** [comment]
One tester was able to log in with FB; haven't heard other bug reports of it. I wonder if there still might be something specific to your configuration. Anyone else having issues with this?

**Comment by Imperadeiro98** [comment]
I get the error "could not get data, since no email provided" too.

**Comment by nwinter** [comment]
@sderickson any ideas why FB wouldn't be giving us the email properly for a small subset of users?

**Comment by sderickson** [comment]
I think the best bet would be to console.debug the response, as @vzverev78 suggested, it might have an error attached to it that would explain what's going on.

I also wonder what would happen if you log in in incognito mode. Going through the whole authorization process again might help.

**Comment by vzverev78** [comment]
@nwinter, @sderickson, I think I found what's wrong.
My Facebook email address is not public (unlike Nick's one).
And your app does not request such permission. You can find more info in docs:
https://developers.facebook.com/docs/reference/javascript/FB.login/v2.5
To fix it, change line 38 in https://github.com/codecombat/codecombat/blob/master/app/core/social-handlers/FacebookHandler.coffee
from
```
      FB.login()
```
to
```
      FB.login(
            ->
            scope: 'email'
      )
```
or in JavaScript
```
FB.login(function() {}, { scope: 'email' });
```

**Comment by nwinter** [comment]
I think that fixed it; can you test again?

**Comment by Imperadeiro98** [comment]
It is working :+1:
