### ISSUE TITLE
Can't find Intro strings for translation for Sarven Desert levels

### ISSUE THREAD

**Issue by vzverev78** [codecombat/codecombat#3311]
Using http://codecombat.com/i18n tool I can't find Intro (Guide article name) and 'Intro' body strings for Russian translation for Sarven Desert levels. At least for the first three levels such as:
The Mighty Sand Yak
Oasis
Sarven Road

**Comment by nwinter** [comment]
Activated those and the other desert Intro translation keys. Thanks for the heads up!
