### ISSUE TITLE
Reaping Fire: "The Walking Dead"

### ISSUE THREAD

**Issue by ghost** [codecombat/codecombat#3328]
The `fangriders` enemies are still moving, even when they are already `dead`. This doesn't happen to everyone, only to those who were left with 0 `health`.

**Comment by nwinter** [comment]
Fangriders must not have their friction set properly (or something like this), so their death velocity when they hit the ground doesn't bring them to a halt. @Zerrien wanna check this out?

**Comment by Zerrien** [comment]
Looks like the Fangrider and Griffin Rider both didn't have any rolling resistance. Bumped it up a tad and they now stop after a bit of a slide.

Let me know if you see anything strange from this change!
