### ISSUE TITLE
Stillness-in-motion level showing ERB tags instead of actual comments

### ISSUE THREAD

**Issue by Narzerus** [codecombat/codecombat#3331]
This issue occurs in the level `Stillness-in-motion` when using `coffeescript` as the coding language, help comments are showing ERB tags as if they hadn't been parsed.

![screen shot 2016-01-17 at 2 36 59 pm](https://cloud.githubusercontent.com/assets/1808674/12378774/d2b0b186-bd27-11e5-8755-d1d3964cd8f8.png)

**Comment by Catsync** [comment]
Thanks! Fixed.
