### ISSUE TITLE
Python simulator slow, crashes often

### ISSUE THREAD

**Issue by Meerkov** [codecombat/codecombat#3334]
When running python code (e.g. to play Multiplayer Treasure Grove), the code can get heavy. Hitting the hard limit of 3 million executions error is easy.

But there are more problems: When you have a heavy simulation that does not hit the execution limit, the window will still crash in Chome or Firefox after several runs of simulations (e.g. change 1 line of code between each run so it re-simulates it).

Also, it can easily take more than a second to calculate a single frame of the simulation. I'm inclined to think there are improvements that can be made to the engine to make this faster, and leak less memory/crash less.

**Comment by nwinter** [comment]
Working on it now, my friend! We are adding an interpreter to [our transpiler](http://aetherjs.com/) which should give something like a 40x speedup on running player code, which you can try out here: http://basicer.com/esper/ – it isn't integrated into the transpiler yet, but when it is, it should fix a lot of bugs as well as increasing performance and letting us do a few cool things we haven't been able to do before.

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
