### ISSUE TITLE
}while(true) infinite-loops the parser

### ISSUE THREAD

**Issue by Dmitriy-Yusk** [codecombat/codecombat#3338]
Reproduced in FireFox 43.0.1 and Chrome 47.0.2526.111.
Browser cache clean up doesn't help.
Language: Javascript.

There was a crash on code check on the level. After the crash I can't proceed with the level due the freeze.
Login to codecombat is dmitriy.yuskevich@gmail.com.

Below is the screenshot with FF developer console.
![image](https://cloud.githubusercontent.com/assets/16769402/12408006/0b87a418-be65-11e5-9bfd-f6ae81744b73.png)

**Comment by nwinter** [comment]
Hmm, can you try switching your programming language to Python in order to load the level, then post what your JS code was that crashed the parser? Then we can try to debug what happened there.

**Comment by Dmitriy-Yusk** [comment]
Changed the language to Python and have the same issue.
Don't you store the problem code on your side? You can get it using my
login id which was provided on the issue description in Git.

2016-01-20 17:47 GMT+02:00 Nick Winter <notifications@github.com>:

**Comment by nwinter** [comment]
Hmm, weird that it errored in Python. I pulled the code out and recovered it, so you should be good to go. Updating the issue to cover a minimal example of the code that crashed the parser:

```javascript
}while(true)
```

**Comment by nwinter** [comment]
Now in Esper, it doesn't crash the parser, but we don't ever finish running or show a good error, either.
