### ISSUE TITLE
missing end of sentence in code comment of "Hoarding Gold"

### ISSUE THREAD

**Issue by headspeak** [codecombat/codecombat#3340]
In a code comment is written: "Get its value with"
I expect a function name/description to get the value of a coin to end the sentence.

**Comment by Catsync** [comment]
I see this:
`# Get its value with:  coin.value`

If you use the "Reload" button to reset to the default code, do you still not see it?

If it's still not there, please let us know what code language you're using, what browser, and what operating system? 

Thanks!

**Comment by headspeak** [comment]
I don't play this level. I translate it into German by the translation page.

**Comment by headspeak** [comment]
![zwischenablage01](https://cloud.githubusercontent.com/assets/912297/12475024/0ed14022-c020-11e5-9adf-58d80ed1b694.jpg)

**Comment by Catsync** [comment]
Ah! The end of the sentence is added inside the level, so this is ok.
