### ISSUE TITLE
The Score button is displayed for levels without a Scoring Type in the Campaign.

### ISSUE THREAD

**Issue by Zerrien** [codecombat/codecombat#3348]
Some levels don't have a scoreType so when pressing the button, an empty score modal displays.

<img width="426" alt="screen shot 2016-01-21 at 2 05 50 pm" src="https://cloud.githubusercontent.com/assets/9985594/12496054/29cfdc62-c048-11e5-96f2-f5ebc16c213b.png">
<img width="952" alt="screen shot 2016-01-21 at 2 05 53 pm" src="https://cloud.githubusercontent.com/assets/9985594/12496055/2af165de-c048-11e5-914b-24464c0a897c.png">

**Comment by binary-idiot** [comment]
Has this been fixed? it looks like Zerrien's commit fixed it but the issue is still open.
