### ISSUE TITLE
can not pass value into self defined function in Binary Deployment

### ISSUE THREAD

**Issue by zxcpoiu** [codecombat/codecombat#3354]
Can not pass value into self defined function in Binary Deployment
It always undefined if we `self.say(arg_number)` in the function.

It works if we execute `getBinaryArray` code in for loop directly instead call a function 

```python
def getBinaryArray(decNumber):
    # --- will return error: "Say What?"
    self.say(decNumber)

    # ... convert decimal number to binary array ...
    
    return binArray

paladins = self.findByType("paladin")

for g in paladins:
    # --- it will say the deployment value of paladin
    self.say(g.deployment)
    # --- But it did not pass the value into self defined function
    squadron = getBinaryArray(g.deployment)
    self.say(squadron) # --- Always empty
```

**Comment by nwinter** [comment]
Hmm, @nemoyatpeace did you run into this in your testing?

**Comment by UltCombo** [comment]
Do you ever re-assign the `decNumber` variable inside the `getBinaryArray` function? If so, it is the same problem as #2880 / differentmatt/filbert#70

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
