### ISSUE TITLE
repeatable level error

### ISSUE THREAD

**Issue by dre12345** [codecombat/codecombat#3355]
im on cloudrip brawl level 3 i just wrote a code that said that it was a success then when i submited it the coins changed direction and the enemies changed too i dont know why it did that but it did

**Comment by Meerkov** [comment]
Working as intended. Most levels after a certain point add randomness to the layout. When you are running your code whilte writing it, it's just an example layout. When you are ready to submit for real, then a new random layout is created.

**Comment by dre12345** [comment]
then wouldnt it be right if you submit your code into the level then the level stay the same until after the code is finished computing?

**Comment by nwinter** [comment]
Your code has to be able to deal with unknown randomness, otherwise it would be too easy to customize your code to the exact pattern of spawns that you are testing against.
