### ISSUE TITLE
Sand-yak is confused about its type

### ISSUE THREAD

**Issue by Meerkov** [codecombat/codecombat#3357]
In python, the following code will execute on Sarven Brawl 3:
```python
    nonyak = []
    for enemy in self.findEnemies():
        if enemy.type != "sank-yak":
            if enemy.type == "sand-yak":
                self.say('what')
            nonyak.append(enemy)
```

This means that my nonyak list is filled with yaks too, and my character stands there saying "what".

The player also stands there saying "what", but it's probably some funky operator overloading which has a flaw in it which allow both of these statements to be true at the same time.

**Comment by zxcpoiu** [comment]
Sorry but do you misspelled `sand-yak` to `sank-yak` ?
Or do you mean both `enemy.type != "sand-yak"` and `enemy.type == "sand-yak"`  are true?

**Comment by Meerkov** [comment]
: D Oh hey, would you look at that.
