### ISSUE TITLE
New homepage scrolls sideways

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3378]
In the new homepage (codecombat.com/home) it is possible to scroll to the right side of the screen.

**Comment by sderickson** [comment]
@Imperadeiro98 This might be due to [this commit](https://github.com/codecombat/codecombat/commit/902c39ffb19a5ab42e31a2038398d75ee3c27f22), if you have the HTML change but not the CSS change. Can you hard refresh to see? If it's still there, what browser/OS are you seeing this on?

**Comment by Imperadeiro98** [comment]
There are no bars in the page that I can use to scroll, but if I press the middle mouse wheel, I can move to the right side of the page. Using latest Chrome on Windows.

**Comment by Imperadeiro98** [comment]
It
