### ISSUE TITLE
Login and signup buttons visible when signed up

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3383]
In the new home page (codecombat.com/home), the Signup and Login buttons on the top of the page are visible even when the user is logged in, allowing them to login twice.

**Comment by popey456963** [comment]
This is something that I don't seem to be getting, [screenshot](http://puu.sh/nbTDw/08d704ac0f.jpg).  Again, can you reproduce it on alternative systems and browsers or is this a browser compatibility issue?

**Comment by Imperadeiro98** [comment]
It seems to be working fine now.
