### ISSUE TITLE
Error in the Bookkeeper level

### ISSUE THREAD

**Issue by DWand** [codecombat/codecombat#3385]
It looks like the Bookkepper level (http://codecombat.com/play/level/bookkeeper) has an error. Naria says that she was hoping me to say NaN.

Here is a screenshot:
http://data2.floomby.com/files/share/6_2_2016/11/hcoJnYNlMkm9ZFyXtDYsag.jpg

Here is my code:
```python
# Fight enemies for 15 seconds.
# Keep count whenever an enemy is defeated.
defeated = 0
while True:
    defeated += kill_enemy()
    if self.now() > 15:
        break

# Tell Naria how many enemies you defeated.
self.say(defeated)

# Collect coins until the clock reaches 30 seconds.
while True:
    coin = self.findNearest(self.findItems())
    if coin:
        self.move(coin.pos)
    if self.now() > 30:
        break

# Tell Naria how much gold you collected.
self.say(self.gold)

# Fight enemies until the clock reaches 45 seconds.
# Remember to reset the count of defeated enemies!
defeated = 0
while True:
    defeated += kill_enemy()
    if self.now() > 45:
        break

# Tell Naria how many enemies you defeated.
self.say(defeated)

def kill_enemy():
    enemy = self.findNearest(self.findEnemies())
    if enemy is not None:
        while enemy.health > 0:
            self.attack(enemy)
        return 1
    return 0
```

**Comment by Catsync** [comment]
This should be fixed now.

**Comment by rafagarces** [comment]
My collected doesn't work :/ 


defeated = 0
while True:
    enemy = hero.findNearestEnemy()
    if enemy:
        hero.attack(enemy)
        if enemy.health <= 0:
            defeated += 1
    if hero.now() > 15:
        break
hero.moveXY(59, 33)
hero.say(defeated)
# Collect coins until the clock reaches 30 seconds.

while True:
    item = hero.findNearest(hero.findItems())
    collected = 0
    if item:
        hero.move(item.pos)
        collected += 1
    if hero.now() > 30:
        break
hero.moveXY(59, 33)
hero.say(collected)

while True:
    enemy = hero.findNearestEnemy()
    if enemy:
        hero.attack(enemy)
        if enemy.health <= 0:
            defeated += 1
    if hero.now() > 15:
        break
hero.moveXY(59, 33)
hero.say(defeated)
