### ISSUE TITLE
Can't see functions needed to write the code

### ISSUE THREAD

**Issue by eric418** [codecombat/codecombat#3388]
the banner at the bottom of the screen blocks the functions in the lower right corner, and I can't scroll down or remove the banner.
![screen shot 2016-02-09 at 12 53 08 am](https://cloud.githubusercontent.com/assets/17136865/12908836/951c398c-cec8-11e5-81a0-a4e10db0d5a7.png)

**Comment by UltCombo** [comment]
There should be no "banner", it seems like a layout issue.

What browser and OS version are you using? It looks like Safari on OS X, but it would be nice if you can provide the exact OS X and Safari versions.

**Comment by nwinter** [comment]
@sderickson is this something that we broke with the recent removal of the nanoscroller stuff on the body somehow?

**Comment by sderickson** [comment]
Possibly. Will look into soon.

**Comment by ZufengW** [comment]
I have that issue too on Safari Version 6.1.6 (7537.78.2)
Fullscreen and resizing the window don't help much. Hovering the mouse below the cut-off line does not show any popups.
