### ISSUE TITLE
Infinite Redirect China site from China

### ISSUE THREAD

**Issue by hinklefoxmail** [codecombat/codecombat#3398]
China site (cn.codecombat.com) has an infinite redirect, but only when accessed in China.

Accessing From China:
![image](https://cloud.githubusercontent.com/assets/15206556/13031554/18a3c9a4-d30c-11e5-94fc-8c06f3133d6a.png)

Accessing with US IP:
![image](https://cloud.githubusercontent.com/assets/15206556/13031558/61f61a1c-d30c-11e5-80a0-9fe31534c683.png)

**Comment by UltCombo** [comment]
This seems fixed as per [this forum comment](https://discourse.codecombat.com/t/its-a-bug-or-not/6719/20?u=ultcombo).
