### ISSUE TITLE
Error in RequestQuoteView

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3404]
In the page https://codecombat.com/teachers/quote, if I click the 'Send' button, I get this error:

- Uncaught TypeError: Cannot read property 'style' of undefined

**Comment by popey456963** [comment]
Can you give us some more information about what you enter in to get said error?  I've tried with no input fields filled in (which gives me the "required fields not entered" error) and with sane inputs (which passed correctly).  Could it be browser/OS specific (if so, details of how you're running it would be great) and is it reproducible on multiple systems?

**Comment by Imperadeiro98** [comment]
To get the error, I just click 'Send' without filling any of the boxes (and then check the console).

I'm using the latest Chrome in windows.

**Comment by Imperadeiro98** [comment]
It is working now :+1:
Probably fixed in f1b046b
