### ISSUE TITLE
Teacher Guide ToC Interfering with Layout

### ISSUE THREAD

**Issue by popey456963** [codecombat/codecombat#3405]
On the [CodeCombat Teacher Course Guide](https://sites.google.com/a/codecombat.com/teacher-guides/course-guides/1-introduction-to-computer-science) it seems as if the table of contents takes up the left-half of the screen, resulting in the text being forced into the right-half, despite this looking absolutely shocking.  [Screenshot](http://puu.sh/nbUBi/799f826056.png).  Can we get it so that the top table of contents is a block element, forcing the text beneath it so that it takes up the full width?

**Comment by nwinter** [comment]
@ryang217 what do you think? Are we keeping this site around?

**Comment by ryang217** [comment]
Unfortunately the styling of the current Course Guide wiki is controlled by Google Sites, not a template we can easily modify. We'll be condensing the contents of this wiki plus additional resources into a more comprehensive Teacher Guide that lives on codecombat.com properly in the future.
