### ISSUE TITLE
Can't see all elements

### ISSUE THREAD

**Issue by FlashFMA** [codecombat/codecombat#3410]
Ubuntu  MATE 15.10, screen size 14, 1366x768.
![screenshot](https://cloud.githubusercontent.com/assets/10221153/13186421/d42cd422-d74e-11e5-95fa-118acdb6da17.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/10221153/13186432/df6eedac-d74e-11e5-8ee6-3da61c0373ca.png)
Tested: Firefox 44.0.2, Chrome 48.0.2564.116, Chromium 48.0.2564.82

**Comment by nwinter** [comment]
Same as in #3388, which I am guessing happened recently with some scrolling changes. Let's track it there.
