### ISSUE TITLE
Home page not HTTPS by default (insecure login form)

### ISSUE THREAD

**Issue by phoenixeliot** [codecombat/codecombat#3415]
If I navigate to http://codecombat.com, the `Log in` form is unsecured and would be sent over HTTP. 1Password pops up a big scary "This is not secure!" error if I try to use it to fill in my login.

We should probably have the homepage redirect to HTTPS by default to prevent it from ever having a page with a login form over HTTP.

Changing the URL to HTTPS manually fixes it for the current session and doesn't seem to cause problems.

<img width="562" alt="screen shot 2016-02-23 at 9 48 41 am" src="https://cloud.githubusercontent.com/assets/491376/13260928/a20402ec-da12-11e5-9dc9-87008f648eff.png">

**Comment by nwinter** [comment]
See also #2505. @sderickson know any reason why we wouldn't just HTTPS-by-default the whole site at this point?

**Comment by sderickson** [comment]
Not that I know of.

**Comment by basicer** [comment]
codecombat.com is now HTTPs all the time.
