### ISSUE TITLE
compoents missing?

### ISSUE THREAD

**Issue by xrfang** [codecombat/codecombat#3448]
I setup CC on my laptop following the Get Started guide, but it now get stuck on the 2nd task. Below is what I got from the console:

Failed to parse SourceMap: http://localhost:3000/stylesheets/treema.css.map
GET http://beacon.errorception.com/51a79585ee207206390002a2.js net::ERR_NAME_NOT_RESOLVED
lib
templates/courses/course-details
vendor/aether-clojure
vendor/aether-coffeescript
vendor/aether-io
vendor/aether-java
vendor/aether-javascript
vendor/aether-lua
vendor/aether-python
vendor/coffeescript
vendor/d3
vendor/difflib
vendor/diffview
vendor/three
vendor/treema
views/account/AccountSettingsView
views/common/SearchView
views/courses/ChangeCourseLanguageModal
views/courses/ChooseLanguageModal
views/courses/CourseDetailsView
views/courses/CoursesView
views/courses/StudentLogInModal
views/courses/StudentSignUpModal
views/editor
views/modal/ModelModal
views/modal/RevertModal
views/play
loaded 27 files, 2461 KB
SuperModel name property deprecated. Remove 'level' from code.
Populated defaults for Level Gems in the Deep in 51ms
SuperModel name property deprecated. Remove 'level_session' from code.
SuperModel name property deprecated. Remove 'thang' from code.
SuperModel name property deprecated. Remove 'thang_names' from code.
SuperModel name property deprecated. Remove 'component' from code.
SuperModel name property deprecated. Remove 'system' from code.
SuperModel name property deprecated. Remove 'level' from code.
GET http://localhost:3000/file/interface/victory.mp3 404 (Not Found)
SuperModel name property deprecated. Remove 'component' from code.
SuperModel name property deprecated. Remove 'thang' from code.
SuperModel name property deprecated. Remove 'thang' from code.
SuperModel name property deprecated. Remove 'component' from code.
GET http://localhost:3000/db/level/54174347844506ae0195a0b8/version/0 404 (Not Found)
GET http://localhost:3000/file/interface/ident_1.mp3 404 (Not Found)
Assigned power 50 to wave randomOgres with difficulty 0
World has been initialized from level loader.
SuperModel for Level loaded in 1648 ms
Hunab Ku: Let there be light upon Gems in the Deep! (preload: false)
GET http://localhost:3000/file/interface/ambient-dungeon.mp3 404 (Not Found)
|Hunab Ku's Archer| Worker initialized after 3465ms
|Hunab Ku's Archer| Generated random seed 5060436634 of type submissionCount from sessionIDs 56dd91f7f7a99ff71fed0ae2 submissionCount 0
|Hunab Ku's Woodhouse| Worker initialized after 3339ms
|Hunab Ku's Archer| Assigned power 50 to wave randomOgres with difficulty 0
|Hunab Ku's Archer| The world ended in lost on frame 71
|Hunab Ku's Archer| And it was so: (4.676ms per frame, 71 frames)
Simulation   : 332ms 
Serialization: 13ms
Delivery     : 6ms

I wonder if there are anything missing from the Guide or some file (e.g. mp3, maps ...) which are not in the Git repository?

**Comment by nwinter** [comment]
See #3281–the third level and later are not included in the public dump, so it 404s when it goes to preload it. Email me if you need more levels to work with–nick@codecombat.com

**Comment by xrfang** [comment]
hi, I think you may misunderstood. :-)  I am not playing the 3rd level, not even the 2nd level. I am playing the first level -- the dungeon, and it got stuck on the 2nd TASK.

**Comment by nwinter** [comment]
Hmm, I'm confused. The only thing that's an actual error in that log is this one:

> GET http://localhost:3000/db/level/54174347844506ae0195a0b8/version/0 404 (Not Found)

... which would mean you wouldn't be able to play the third level, which I imagine it was trying to preload. Also, I'm pretty sure you were playing the second level, since that is the one called "Gems in the Deep", which is reflected in the logs there, and that's the one that would preload the third level (which was missing).

But you say you got stuck there–can you send a screenshot of the screen where it stopped working? Did it just never load, or was there some other problem?
