### ISSUE TITLE
'Log In' misaligned in error page

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3456]
As you can see below, the 'Log In' sentence is not correctly centered in its place (it is a bit to the left).
![sem titulo](https://cloud.githubusercontent.com/assets/6980488/13649137/09cbe34a-e634-11e5-92ba-916b2e14198d.png)

**Comment by MaChengxin** [comment]
On which page did you meet this problem? Can you please put the link here?

**Comment by Imperadeiro98** [comment]
Sorry, I forgot.

For example accessing http://codecombat.com/admin/clas without being logged in.
