### ISSUE TITLE
tooltips don't show up sometimes at the "world navigation" screen

### ISSUE THREAD

**Issue by The-Alchemist** [codecombat/codecombat#3457]
https://www.youtube.com/watch?v=4O-YTZjKM3A

I'm referring to the "Boom and Bust" tooltip in the above video:

![codecombat-tooltip bug](https://cloud.githubusercontent.com/assets/812287/13649208/8720a710-e60a-11e5-8958-726cfe30fd77.png)

**Comment by UltCombo** [comment]
I can reproduce this as well.

It happens most often when you hover the level icon from above.

**Comment by duybkict** [comment]
this seems to be Bootstrap tooltip bug. When the cursor hovers the level icon from above, the tooltip is showned right where the cursor currently is -> the level icon loses hover (hover is now on the tooltip element) -> hide tooltip
a fix/workaround would be super unnecessary complicated, so I wouldn't recommend that we try to fix this
