### ISSUE TITLE
Some levels don't display keyboard shortcut on 'run' button

### ISSUE THREAD

**Issue by phoenixeliot** [codecombat/codecombat#3470]
On some levels, the `run` button does not have the keyboard shortcut displayed like normal. The keyboard shortcut works as expected.

Found on these levels (very incomplete list):
Dungeon/Signals and Portents
Dungeon/True Names
Dungeon/The Raised Sword

When it's missing:
<img width="565" alt="screen shot 2016-03-11 at 10 45 12 am" src="https://cloud.githubusercontent.com/assets/491376/13712035/5a296482-e776-11e5-98fe-c152be209c90.png">

Normally: 
<img width="558" alt="screen shot 2016-03-11 at 10 49 28 am" src="https://cloud.githubusercontent.com/assets/491376/13712160/f513b54c-e776-11e5-9ab3-d7bc5c5f035b.png">

**Comment by nwinter** [comment]
By design: we hide as many interface elements as we can at first to make the interface simpler for players just getting started. This is controlled by [the `hidesRunShortcut` option in the level/campaign](https://github.com/codecombat/codecombat/blob/master/app/schemas/models/level.coffee#L321).
