### ISSUE TITLE
start report error "SyntaxError: Unexpected token *"

### ISSUE THREAD

**Issue by lvkasi** [codecombat/codecombat#3495]
> [root@magt210 codecombat]# npm run dev

> codecombat@ dev /data/codecombat
> brunch watch --server

> Got 465 coffee files and 212 jade files (bundled 90 of them together).
> 17 Mar 14:10:44 - info: custom server started, initializing watcher
> 17 Mar 14:10:44 - [nodemon] v1.6.1
> 17 Mar 14:10:44 - [nodemon] reading config /data/codecombat/nodemon.json
> 17 Mar 14:10:44 - [nodemon] to restart at any time, enter `rs`
> 17 Mar 14:10:44 - [nodemon] ignoring: /data/codecombat/.git/**/* /data/codecombat/node_modules/**/* /data/codecombat/bower_components/**/* .sass-cache
> 17 Mar 14:10:44 - [nodemon] watching: server_config.js server_setup.coffee /data/codecombat/app/schemas/**/* /data/codecombat/server/**/*
> 17 Mar 14:10:44 - [nodemon] watching extensions: js,coffee
> 17 Mar 14:10:44 - [nodemon] starting `node .`
> 17 Mar 14:10:44 - [nodemon] child pid: 10761
> 17 Mar 14:10:44 - [nodemon] watching 175 files
> SENDWITHUS: Debug enabled
> 
> /data/codecombat/server/middleware/auth.coffee:56
>     loginByGPlus: wrap(function*(req, res) {
>                                ^
> SyntaxError: Unexpected token *
>   at Module._compile (module.js:439:25)
>   at Object.loadFile (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
>   at Module.load (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>   at Function.Module._load (module.js:312:12)
>   at Module.require (module.js:364:17)
>   at require (module.js:380:17)
>   at Object.<anonymous> (/data/codecombat/server/middleware/index.coffee:2:9)
>   at Object.<anonymous> (/data/codecombat/server/middleware/index.coffee:1:1)
>   at Module._compile (module.js:456:26)
>   at Object.loadFile (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
>   at Module.load (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>   at Function.Module._load (module.js:312:12)
>   at Module.require (module.js:364:17)
>   at require (module.js:380:17)
>   at Object.<anonymous> (/data/codecombat/server/routes/index.coffee:1:6)
>   at Object.<anonymous> (/data/codecombat/server/routes/index.coffee:1:1)
>   at Module._compile (module.js:456:26)
>   at Object.loadFile (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
>   at Module.load (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>   at Function.Module._load (module.js:312:12)
>   at Module.require (module.js:364:17)
>   at require (module.js:380:17)
>   at Object.<anonymous> (/data/codecombat/server_setup.coffee:17:10)
>   at Object.<anonymous> (/data/codecombat/server_setup.coffee:1:1)
>   at Module._compile (module.js:456:26)
>   at Object.loadFile (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
>   at Module.load (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>   at Function.Module._load (module.js:312:12)
>   at Module.require (module.js:364:17)
>   at require (module.js:380:17)
>   at Object.<anonymous> (/data/codecombat/server.coffee:11:15)
>   at Object.<anonymous> (/data/codecombat/server.coffee:1:1)
>   at Module._compile (module.js:456:26)
>   at Object.loadFile (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
>   at Module.load (/data/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>   at Function.Module._load (module.js:312:12)
>   at Module.require (module.js:364:17)
>   at require (module.js:380:17)
>   at Object.<anonymous> (/data/codecombat/index.js:3:14)
>   at Module._compile (module.js:456:26)
>   at Object.Module._extensions..js (module.js:474:10)
>   at Module.load (module.js:356:32)
>   at Function.Module._load (module.js:312:12)
>   at Function.Module.runMain (module.js:497:10)
>   at startup (node.js:119:16)
>   at node.js:935:3
> 
> 17 Mar 14:10:48 - [nodemon] app crashed - waiting for file changes before starting...
> 17 Mar 14:12:03 - info: compiled 952 files into 704 files, copied 423 in 80192ms

**Comment by nwinter** [comment]
You need a newer version of node in order to handle the generator functions; try node 5.x. @sderickson can we update our dev docs to point out this requirement and help people find the solution when they see this error? It's coming up a lot since the switch to generators.

**Comment by sderickson** [comment]
Updated wiki files. Also made it so that if the server is started with <4, it prints an error and exists.
