### ISSUE TITLE
Beautify button adds semicolon to loop keyword

### ISSUE THREAD

**Issue by PixelAl** [codecombat/codecombat#3510]
To see an example, I remarked on this bug first regarding a level in the forum: [https://discourse.codecombat.com/t/cant-find-the-bones-in-bonemender-forest/7105/3](https://discourse.codecombat.com/t/cant-find-the-bones-in-bonemender-forest/7105/3)

**Comment by UltCombo** [comment]
Seeing as the `loop` construct is a CodeCombat-specific addition, I speculate that the code beautifier only understands "standard" JavaScript code, and thus recognizes `loop {}` as just an identifier followed by a lone block.

Perhaps we could replace `loop` keywords with `while (true)` before passing the user's code into the beautifier? Something like `.replace /\bloop\b/g, 'while (true)'` should be enough, I think. If necessary, we could translate `while (true)` back to `loop` after the beautification.

**Comment by nwinter** [comment]
Good idea. We are also in the process of converting things to while (true) for campaign as well as classroom mode, but until then, the reversible regex fix sounds like a great workaround.

**Comment by UltCombo** [comment]
By the way, the "reversible" suggestion I have posted earlier wouldn't work very well if you use both `loop` and `while (true)` constructs in the same snippet. It would convert all of those to either `loop` or `while (true)` in the end.

If you agree that the beautifier should preserve the original construct, then we can use a more distinguishable valid syntax (e.g. `while (__COCO_LOOP_CONSTRUCT__)`) for the reversible substitutions.

**Comment by UltCombo** [comment]
I've submitted a patch here: #3513

*(sorry for the commit spam, I had some issues while crafting the commit message :sweat_smile:)*
