### ISSUE TITLE
No levels load using Safari Technology Preview 1

### ISSUE THREAD

**Issue by reedog117** [codecombat/codecombat#3519]
Using the new browser Safari Technology Preview (Version 9.1.1 (11601.6.10, 11602.1.25)) for Mac, no levels load.  It seems like the middle progress bar makes it about halfway across, then just stops.  The blue bar that progresses across the top of the frame goes all the way from left to right.

**Comment by nwinter** [comment]
Are there any JavaScript errors shown in this version, if you check the error console?

**Comment by reedog117** [comment]
Same problem in Safari Technology Preview 2 -- here are the errors I see in the Error Console:

In logs -> Errorception trial expired!
In errors -> Error: Access to that global property is forbidden. (No line numbers or file references)
In warnings -> A bunch of CSS warnings.

**Comment by nwinter** [comment]
Aha, I tracked it down. Should start working when we deploy again sometime in the next few days.
