### ISSUE TITLE
i18n Translation Editor drops content

### ISSUE THREAD

**Issue by KeldOelykke** [codecombat/codecombat#3523]
When I iterate with http://codecombat.com/i18n (over days) I can add translations (in danish) to the game, but when I reload the same translations later they are missing bits and pieces.

At first I was pretty sure it was a problem with multi-line entries, but now I am also missing a 1-liner.

Example: 
For language danish I have added all javascript entries in http://codecombat.com/i18n/component/usessnippets . 
Currently when I load the game I can see my danish translation of the Loop snippet: <img width="547" alt="screen shot 2016-04-02 at 10 50 28" src="https://cloud.githubusercontent.com/assets/6137135/14225401/3fb99b96-f8c2-11e5-8567-dbf91d651ce0.png">.
However, in Translation Editor the entry for 'loop description (javascript)' is an empty line:
<img width="1167" alt="screen shot 2016-04-02 at 11 01 08" src="https://cloud.githubusercontent.com/assets/6137135/14225409/78cfc0d6-f8c2-11e5-84db-8acb37d6d64c.png">
.

**Comment by nwinter** [comment]
Is it still sitting in the Pending Patches list for that Component?

**Comment by KeldOelykke** [comment]
I don't think I know where the Pending Patches list is :(

**Comment by KeldOelykke** [comment]
My translations are in the public game right now, but the Translation Editor can't load them, so I am pretty concerned whether they will be removed at next submit from the Translation Editor.

**Comment by KeldOelykke** [comment]
I found this Pending Patches list: https://codecombat.com/admin/pending-patches
Currently component UsesSnippet is only on that list for another language.

If I look at other languages like french and spanish none of them have translations for entries 'if/else description' and 'loop description', so I gather it might just be this component that has a bug.

**Comment by sderickson** [comment]
[I reworked the I18N diplomat submission system to be more transparent and reliable](https://github.com/codecombat/codecombat/commit/7bab895dee010c780ff6f2458bdf4a9847bb71bb). It should be deployed soon; you'll know you've got it if there's a list of patches on the right side of the screen.
