### ISSUE TITLE
Unclear subscription price

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3526]
When I open my account's [subscription section](http://br.codecombat.com/account/subscription) (in Brazilian Portuguese language) and click in the subscribe button, I get this screen:

![](http://i.imgur.com/68XqWqf.png)

It is not entirely clear to me whether the price is in USD or BRL.

I believe the "more than 60 free levels" and "3500 bonus gems" lines may also be inaccurate.

According to a [post](https://discourse.codecombat.com/t/level-6-subscription-bug/5453/35?u=ultcombo) by @nwinter, the price would be lowered to $3.99 and grant 1500 gems/month to Brazilian players.

Was the pricing model reverted at some point, or are these i18n bugs?

p.s. The buttons don't fit the i18n'd text, but I'd like to track that on a different issue.

**Comment by nwinter** [comment]
I think your account was created before the Brazil-specific pricing happened, so you are on the old model. I can update you to the new one if you like?

These lines need to be updated, or better yet, use interpolation so we can update the level/hero numbers outside of the locale files like we started doing with the gem counts and price: https://github.com/codecombat/codecombat/blob/master/app/locale/pt-BR.coffee#L510-L512

**Comment by UltCombo** [comment]
> I think your account was created before the Brazil-specific pricing happened, so you are on the old model. I can update you to the new one if you like?

Oh, I had almost forgotten that my account was still in the old model. That is actually fine for me, I don't mind paying a bit more given that I get a higher gems bonus. I haven't subscribed yet as I've had very little free time to play lately.

---

Should I open a new issue for the localization or would you like to use this thread to track it?

**Comment by nwinter** [comment]
This one. What do you think we should do about the buttons not fitting the text?

**Comment by UltCombo** [comment]
I'm not sure, maybe we can set a smaller font-size if the text doesn't fit the button (maybe using a plugin like [fit text](http://fittextjs.com/)), or we can switch the buttons to a flexbox layout where the first two buttons take as much space as needed the last one takes the remaining space (i.e. `flex-grow: 1`), but I'm not sure how well that would work with the background images.

**Comment by UltCombo** [comment]
Please see #3572.
