### ISSUE TITLE
CampaignView world background map is too low.

### ISSUE THREAD

**Issue by DerpfacePython** [codecombat/codecombat#3534]
![issue](https://cloud.githubusercontent.com/assets/14177193/14311177/64cf51b8-fc29-11e5-878b-e6b0d202fb26.PNG)
Shouldn't the map be higher, so that the buttons for character selection don't cover some of the levels?

**Comment by nwinter** [comment]
If the aspect ratio gets this out of whack (here due to a wide screen and the (currently-empty) ad container at the top), we could try moving those buttons off to side in a vertical layout.

**Comment by duybkict** [comment]
What OS/browser/screen you are having?
![untitled](https://cloud.githubusercontent.com/assets/3896985/15090108/c00eea8e-1443-11e6-9303-4c9d62b6955f.png)
I notice the same issue on my laptop with an unnecessary padding on top of play screen

**Comment by DerpfacePython** [comment]
I have Windows 7, with Google Chrome (resolution is 1440*900).

**Comment by nwinter** [comment]
How about now? We took out the ad bar placeholder we were going to test which was pushing everything down.

@DerpfacePython We have been introducing a ton of new stuff lately, and it's been pretty hard to keep up with all the bugs introduced by the changes. We are working on improving stability and quality now that the bulk of the teacher version and new interpreter engine are up.

**Comment by DerpfacePython** [comment]
@nwinter It still doesn't work, for some reason - the map is still too low.
![capture3](https://cloud.githubusercontent.com/assets/14177193/15350811/ccc02d54-1d1e-11e6-8741-c84d6f146c08.PNG)

**Comment by duybkict** [comment]
hmm, i check on my Windows laptop and it seems fine on both Firefox and Chrome

**Comment by DerpfacePython** [comment]
Well, that's weird.

**Comment by Imperadeiro98** [comment]
Fixed by 1e640fb?
