### ISSUE TITLE
Confusing create account page

### ISSUE THREAD

**Issue by kieranhogg** [codecombat/codecombat#3545]
I've just had a load of students (200ish) sign up and about 10% of them completed the form correctly then clicked 'sign in' rather than 'create account'. The sign in button should either be smaller or read e.g. 'Already have a account? Sign in' which would prevent confusion.

**Comment by nwinter** [comment]
Definitely–good point! We are redesigning those screens now and will take this into account.

**Comment by ryang217** [comment]
Yup, already being taken into account in the new designs. Thanks for bringing this to our attention!
