### ISSUE TITLE
Buttons not working in courses view

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3546]
When accessing one of my classes, as a teacher, through the link of the form "codecombat.com/courses/:classroomID", and then clicking either the ["Enroll Students in Paid Courses"](https://github.com/codecombat/codecombat/blob/master/app/templates/courses/classroom-view.jade#L57) or the ["Enroll {student name}"](https://github.com/codecombat/codecombat/blob/master/app/templates/courses/classroom-view.jade#L136) buttons, nothing happens and I get an error (repeated twice) for each of the button clicks.

Error:

- Uncaught TypeError: Cannot read property 'get' of undefined @ activate-licenses-modal.jade:48
- (anonymous function) @ activate-licenses-modal.jade:48
- r @ activate-licenses-modal.jade:74
- t.exports.t.render @ CocoView.coffee:115
- t.exports.t.onLoaded @ CocoView.coffee:157
- c @ backbone.js:204
- o.Events.trigger @ backbone.js:146
- t.exports.t.updateProgress @ SuperModel.coffee:237
- (anonymous function) @ SuperModel.coffee:1
- (anonymous function) @ lodash.js:5496

**Comment by Imperadeiro98** [comment]
Now the error is:

- Uncaught TypeError: Cannot read property 'models' of undefined @ ActivateLicensesModal.coffee:21
- s.exports.s.getInitialState @ ActivateLicensesModal.coffee:21
- s.exports.s.initialize @ ActivateLicensesModal.coffee:29
- o.View @ backbone.js:991
- t @ CocoView.coffee:56
- t @ ModalView.coffee:24
- s @ ActivateLicensesModal.coffee:11
- t.exports.t.onClickActivateLicensesButton @ ClassroomView.coffee:109
- r @ lodash.js:729
- d.event.dispatch @ jquery.js:4435
- v.handle @ jquery.js:4121

**Comment by nwinter** [comment]
I don't see any errors on this any more; assuming we fixed it in the last round of smashing. Let me know if you still see a problem?

**Comment by Imperadeiro98** [comment]
That page is no longer accessible to teachers, so it is fixed.
