### ISSUE TITLE
Level continue button not showing up/not working

### ISSUE THREAD

**Issue by smalllizard** [codecombat/codecombat#3553]
**Operating system:** Mac OS X 10.10.5
**Browsers:** Chrome and Safari
**When:** Happens right after I successfully complete and submit a level.
**Language:** Python
**Level:** Multiple levels
**New:** Was working fine up until the level "Back to Back" but now affects others too

When completing a level, the button to continue either does not show up or does not do anything when clicked. If the level gives a new item the buttons show up but clicking them doesn't work. If the level does not give a new item the buttons do not show up at all. I have tried disabling all my Chrome extensions and restarting the browser and using an alternate browser (Safari). 

 Here are the examples where the buttons are missing/inactive
![screen shot 2016-04-13 at 9 56 44 pm](https://cloud.githubusercontent.com/assets/18472106/14545078/53ba5d36-026a-11e6-8ade-1ec826a2bb2a.png)
![screen shot 2016-04-14 at 5 34 27 pm](https://cloud.githubusercontent.com/assets/18472106/14545193/0818574c-026b-11e6-8e46-cc425d1d2906.png)

Here is the error code that shows up in the console when clicking the inactive button. 
![screen shot 2016-04-14 at 6 02 37 pm](https://cloud.githubusercontent.com/assets/18472106/14545216/3914dfd2-026b-11e6-804b-92784ae31aec.png)

**Comment by nwinter** [comment]
We have this bug fixed soon; are you still seeing it? If so, let me know your username so I can update your account.

**Comment by smalllizard** [comment]
I ended up creating an account using an email instead of the "sign in with
google + option" to see if that would change anything and it got rid of the
issue. However now on the homepage something happened and instead of saying
"continue playing" it says "go to my classes" which will take me to the
teacher dashboard instead of to the level map. Now in order to access the
level map I have to go to my account settings, go to a recently played
level and then leave that level to access the map.

Is there something setting I can change so the "continue playing" button
comes back and I don't have to go through the extra steps?

**Comment by nwinter** [comment]
What are the two account usernames?

**Comment by smalllizard** [comment]
I had to delete the original as I only have one email and there was minimal
progress,  but the new one's username is soph222

**Comment by nwinter** [comment]
We'll fix this soon, but for now just go to http://codecombat.com/play to get to the individual game screen.
