### ISSUE TITLE
rich-forager level (Forest) hangs on completion

### ISSUE THREAD

**Issue by skeeve42** [codecombat/codecombat#3555]
I have successfully completed the level "[Rich Forager](www.codecombat.com/play/level/rich-forager)" a few times now in slightly different ways, but it continues to hang before awarding xp/crystals and the game won't move on.

Writing in Python and using (fully updated) Chrome on Windows 10.

Most recent code in game:
```
# Use "if" and "else if" to handle any situation.
# Put it all together to defeat enemies and pick up coins!
# Make sure you bought great armor from the item shop! 400 health recommended.

loop:
    flag = self.findFlag()
    enemy = self.findNearestEnemy()
    item = self.findNearestItem()

    if flag:
        # What happens when I find a flag?
        self.pickUpFlag(flag)
    elif enemy:
        # What happens when I find an enemy?
        self.attack(enemy)
    elif item:
        # What happens when I find an item?
        pos = item.pos
        x = pos.x
        y = pos.y
        self.moveXY(x, y)
```
Tried to post a screenshot, but it's not working for some reason.

**Comment by nwinter** [comment]
We have this bug fixed soon; are you still seeing it? If so, let me know your username so I can update your account.

**Comment by skeeve42** [comment]
Looks like it works now! Thanks. :)
