### ISSUE TITLE
Homepage: the regular campaign's "Play Now" button is not shown when the user is in a course

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3563]
It seems that when my user is in a course, the "Play Now" button (for the regular campaign) does not appear in the homepage. I'm talking about this button:

![](https://www.evernote.com/shard/s534/sh/6e35e53f-f60b-4370-afe9-73237f5adef9/303333a970171d1019eb8c630f937ec6/res/10eb28a7-29c4-4af1-8568-e9cf9fa7fcd8/skitch.jpg?resizeSmall&width=832)

I'm not sure whether this change was intended as to reduce the confusion and UI clutter for course students, but I find it unfortunate for players that may be playing both versions and suddenly can't find the link to the regular campaign play mode.

**Comment by Izsof** [comment]
I am teaching it in my ICT lessons... and when a student change to the class version he is not able to play the campaign and just some 18 levels of the game... which is for 1-2 hour... :(  the children said to me to not create classes because it's not worth it... I hope it is just a mistake... :(

**Comment by bdekk** [comment]
I guess this is more of a conceptual debate. Do you also want to let students play the same levels that they can also play within the course, by themselves without keeping track of their progress. It is an interesting question though.

**Comment by UltCombo** [comment]
I believe this is most troublesome when the user is already playing the campaign, and then signs up for a course and can no longer see the button to play the campaign.

**Comment by nwinter** [comment]
We are working on some designs to address this issue; will update soon when we have something to show.

**Comment by Izsof** [comment]
Thank you...
Dňa 18.5.2016 2:06 používateľ "Nick Winter" <notifications@github.com>
napísal:

**Comment by nwinter** [comment]
This isn't going to be supported for now; we're continuing to work on better separation of the classroom and individual game versions of CodeCombat.
