### ISSUE TITLE
Account navigation: missing subscription links

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3564]
Some links have vanished from the account navigation since the last update:
![](http://i.imgur.com/WFPyZeK.png)

Particularly, I can't seem to find the regular campaign's subscription page (`/account/subscription`), nor the prepaid coupons, and maybe there are more navigation items missing that I don't recall as well.

I'm not sure if this is related to my user being in a course or not.

**Comment by sderickson** [comment]
Yes, this is related to being marked a 'student'. Users who are part of a course are considered students, and so don't need easy access to these links.

https://github.com/codecombat/codecombat/blob/master/app/templates/base-flat.jade#L1-L16

These pages can be accessed through Settings -> [Account](http://codecombat.com/account), instead.

Closing this issue, since the changes were intentional.

**Comment by UltCombo** [comment]
Makes sense. I agree those navigation links as they stood could be more confusing than helpful to course students.

Though, I'll note that the `/account` page is extremely hard to get to, I've only found a link to it from the breadcrumbs.

In any case, campaign players can get to the subscription modal easily by clicking on a subscriber-only level, so that isn't really a problem. Though, now I wonder if a course student who is also subscribed to the campaign mode wants to cancel their subscription, that might be very hard (or nearly impossible) to do without the navigation link, right?

Would a patch to display the subscription page link when the student is subscribed to the campaign be welcome? Basically, I'm suggesting to add a `|| isSubscribed()`'ish to [this line](https://github.com/codecombat/codecombat/blob/f44f201548b7d2a84391ac3ce816c7a8c9819679/app/templates/base-flat.jade#L9).

**Comment by sderickson** [comment]
Sorry for the slow reply! It got lost in the shuffle discussing internally about solutions, and in the meanwhile Matt independently came to your same conclusion and fixed it: 92de821b76676727a56ada7aa90f4eacbfd908ca. So it's ended up covered, thanks for offering though!

**Comment by UltCombo** [comment]
Nice! Thanks guys for addressing it. 😄
