### ISSUE TITLE
Can't enter the level - Script: http://codecombat.com/javascripts/aether.js line 5756 > eval:2154

### ISSUE THREAD

**Issue by esova-ana** [codecombat/codecombat#3571]
Hey,

I click on the flag and try to enter Grim Determination level in Mountain world, but it just freezes. Tried other levels, everything works normal, tried to delete cache, to go to Firefox, but no success. It just freezes and doesn't want to open and in Firefox it throws some error...  It seems like it's an infinite loop in my Codecombat code for that level, but I can't even open it so I would reoad it...

**Here's the screencast https://drive.google.com/file/d/0B9vs9RxlIYARWmRBbXJRZ2FvaW8/view?usp=sharing (from Chrome)**

And this is the error message from Firefox
![And this is the error message from Firefox](https://cloud.githubusercontent.com/assets/16888832/14764045/b0e107bc-09a9-11e6-9480-2ec499fce2a9.png)

**Comment by esova-ana** [comment]
![screen shot 2016-04-24 at 05 42 51](https://cloud.githubusercontent.com/assets/16888832/14765378/7ec4693c-09df-11e6-9721-049b735ecdb9.png)

**Comment by Zerrien** [comment]
Hello,

Thanks for taking a video, but we are not seeing this problem at the moment.

What device are you using to play CodeCombat? Would it be possible to take a video of the console?
