### ISSUE TITLE
Pending patches page throws POST 404 error

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3577]
When accessing the pending patches [page](https://codecombat.com/admin/pending-patches), I get a 404 error:

**POST http://direct.codecombat.com/db/achievement/names 404 (Not Found) @ jquery.js:8630**
- send @ jquery.js:8630
- d.extend.ajax @ jquery.js:8166
- t.load @ SuperModel.coffee:313
- t.exports.t.loadCollectionModelNames @ PendingPatchesView.coffee:110
- t.exports.t.loadAllModelNames @ PendingPatchesView.coffee:85
- t.exports.t.onLoaded @ PendingPatchesView.coffee:22
- c @ backbone.js:204
- o.Events.trigger @ backbone.js:146
- t.exports.t.updateProgress @ SuperModel.coffee:237
- (anonymous function) @ SuperModel.coffee:1
- (anonymous function) @ lodash.js:5496

**Comment by sderickson** [comment]
Looks like I forgot to migrate this endpoint in b33620779da30924a87eaaad66a2484eb727b01d. Thanks for reporting this!
