### ISSUE TITLE
Log In screen gets a permanent 'Unauthorized' tooltip

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3587]
If I open the Log In modal (by clicking 'Log In' in https://codecombat.com, for example) and then click the Log In button without entering anything, I get an 'Unauthorized' error on top of the password field, and it doesn't go away.

Also, I get this error:
- undefined not found in [***] so couldn't show message: Undefined Unauthorized.

Btw, the 'X' that closes the modal disappears and reappears quickly when doing this.

**Comment by nwinter** [comment]
<img width="760" alt="screenshot 2016-05-17 16 56 48" src="https://cloud.githubusercontent.com/assets/99704/15343294/6155a982-1c50-11e6-8bfd-51e52420fcfb.png">
