### ISSUE TITLE
Kithgard enchanter stuck in move loop using correct value.

### ISSUE THREAD

**Issue by zimmah** [codecombat/codecombat#3595]
On the level "kithgard enchanter" (the level where you go back to one of the early levels and need to define your own functions for the first time) the default value of 12 for moveUp will cause the hero to walk into the wall and be stuck an in infinite loop.

Using any value between 9.83500000000001 and 11.99999999999999 will beat the level (any value higher than this will get stuck and any value lower will not pick up the top two gems.

this is the code i used:

'''
```
def moveRight():
    target = { "x": hero.pos.x + 12, "y": hero.pos.y }
    while hero.distanceTo(target) > 0:
        hero.move(target);

# Bepaal moveLeft
def moveLeft():
    target = { "x": hero.pos.x - 12, "y": hero.pos.y }
    while hero.distanceTo(target) > 0:
        hero.move(target);
# Bepaal moveUp
def moveUp():
    target = { "x": hero.pos.x, "y": hero.pos.y + 9.83500000000001 } #this value is supposed to be 12
    while hero.distanceTo(target) > 0:
        hero.move(target);
# Bepaal moveDown
def moveDown():
    target = { "x": hero.pos.x, "y": hero.pos.y - 12 }
    while hero.distanceTo(target) > 0:
        hero.move(target);
    
# Gebruik nu deze functies!
moveRight()
moveDown()
moveUp()
moveUp()
moveRight()
```
'''

**Comment by zimmah** [comment]
![kithgard madness](https://cloud.githubusercontent.com/assets/4273872/14972350/468476ea-10db-11e6-8536-26e00525054d.png)

**Comment by Catsync** [comment]
Thanks for the report! Seems like this happens if you don't have the Ring of Speed equipped. I think changing the distance check to something like `hero.distanceTo(target) > 0.1` is probably the simplest way to work around this issue.

**Comment by nwinter** [comment]
@Catsync can we also fix the level to normalize for speed a bit so that this code happens to work with a strict `0` check?

**Comment by Catsync** [comment]
Done!
