### ISSUE TITLE
Unintelligible translation (because of wrong context of homonyms) in reaping fire dutch ("in brand steken")

### ISSUE THREAD

**Issue by zimmah** [codecombat/codecombat#3597]
In the instructions in the comments of the dutch (nederlands) version of the level "reaping fire" ("in brand steken") it tells you to 'ga terug' a value

while 'ga terug' is a correct translation of the word 'return' (in the sense of return back to where you came from) it doesn't make any sense in this context. 

I propose changing it to 'geef terug (als argument)' which translates as return in the sense of returning a book.

**Comment by nwinter** [comment]
I accepted your patch for this–thanks!
