### ISSUE TITLE
Make items' coordinates hoverable

### ISSUE THREAD

**Issue by DerpfacePython** [codecombat/codecombat#3610]
Maybe the items' X-Y coordinates could be clearer, by making a hoverover box which tells the user what its X-Y coordinates are.

**Comment by nwinter** [comment]
Hmm, how would this be different from the default x-y coordinate hover that is always present after the forest?

**Comment by DerpfacePython** [comment]
The hover x-y coordinates are kinda arbitrary as to where the item (say, a gem) is.

**Comment by nwinter** [comment]
So it would snap to the item if you got close enough?

You can find the exact coordinates of a unit, gem, or coin by clicking on it and hovering over its info in the bottom left to pull up the position. Does that do it for you?

**Comment by DerpfacePython** [comment]
Wait, so is that feature in the game or not?

If it is already in the game, then sorry @nwinter. If not, then could you add it?

**Comment by nwinter** [comment]
Yeah: 
<img width="616" alt="screenshot 2016-05-26 09 46 29" src="https://cloud.githubusercontent.com/assets/99704/15582616/bf07220e-2326-11e6-8fb7-b6bd1deafc26.png">

**Comment by DerpfacePython** [comment]
Just asking, how do you link a .coffee file to your html file?
