### ISSUE TITLE
Repeated browser crashes on cubic minefield level

### ISSUE THREAD

**Issue by davosmith** [codecombat/codecombat#3634]
We've been unable to complete the cubic minefield level, as every attempt at it has resulted in frequent 'oops something went wrong' messages in Chrome.

**Comment by Zerrien** [comment]
Hello!

What devices, operating system, and programming language are you using?

**Comment by davosmith** [comment]
Windows 10 laptop (i7 processor, 8Gb RAM), python programming language.

**Comment by Zerrien** [comment]
Hm, those should be fine.

Are you still experiencing this problem as of today?

**Comment by davosmith** [comment]
I've sent through the email address of the account.

The level is loading very slowly at the moment - it eventually asked if I wanted to comment out the code to fix an infinite loop. I did that, then removed the added 'return' at the top of the code and it now seems to be running properly (but very, very slowly).

The browser hasn't crashed this time, but it did pop up to say 'Fix your code: code never finished. It's either really slow or has an infinite loop'. I could see it working, but the character was about 3/4 of the way across the minefield when it stopped.

**Comment by davosmith** [comment]
Problem solved via email - thanks.
