### ISSUE TITLE
Clicking Computer Science 2 link shows unrelated error

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3638]
After finishing the Introduction to Computer Science course, the page for my course shows me two options:
![endoflevel](https://cloud.githubusercontent.com/assets/6980488/15270607/8534946a-1a1d-11e6-8862-8106f810fac6.png)
If I click the Computer Science 2 option, it shows me this error (which is unrelated):
![endoflevel](https://cloud.githubusercontent.com/assets/6980488/15270621/ffbf12aa-1a1d-11e6-91a8-5d85cdc5f448.png)

**Comment by differentmatt** [comment]
If this is still a problem, can you reopen this issue and send me the username or login email so I can investigate further.

I was unable to reproduce this problem.

**Comment by Imperadeiro98** [comment]
Looks like it is working properly now (the Computer Science 2 button appears greyed out).
