### ISSUE TITLE
Simple CPUs are broken in multiplayer levels

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3642]
The Simple CPU character shows an error sign (red circle with big white X) and does not do anything in Dueling Grounds, Multiplayer Treasure Glove and Harrowland.

The Simple CPU seems to work fine in Cavern Survival, Zero Sum, Ace of Coders, Wakka Maul and Cross Bones.

**Comment by Zerrien** [comment]
Further information:

In Harrowland, happens when on Blue Team. The Red AI tries to access `this.attackRange` but it is protected.

```
|Teshub's Cyril| Hero Placeholder had new Programmable problem: plan Line 9: TypeError: Can't read protected property: attackRange 0.9666666666666667
```
