### ISSUE TITLE
Python list comprehensions not working a second time using the same identifier

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3643]
Test case:

```py
enemyHero = [a for a in self.findEnemies() if a.id == 'Hero Placeholder 1'][0]
enemies = [a for a in self.findEnemies() if a.type != 'sand-yak']
```

The second line throws:

> ReferenceError: a is not defined

The code above works with `?esper=false`. It is most likely an Esper issue, or the Filbert AST output has some incompatibility bug with Esper.

**Comment by nwinter** [comment]
See also https://github.com/codecombat/aether/issues/133

**Comment by UltCombo** [comment]
Yep, this looks like a duplicate (albeit my repro code is more minimalist).

**Comment by UltCombo** [comment]
Closing as per resolution in codecombat/aether#133 / https://github.com/codecombat/aether/commit/3f124071ad5b3e51564ec1a7368ad784e94e3145
