### ISSUE TITLE
Leave it to Cleaver level not loading

### ISSUE THREAD

**Issue by drew5252** [codecombat/codecombat#3669]
Hi, my level loads to max and then won't open :D I've tried rebooting but it doesn't work.  Please fix!! :D

**Comment by nwinter** [comment]
Which level is it? And which coding language? Please check [the JavaScript console in your browser](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers/77337#77337) to see what messages it's outputting.

**Comment by drew5252** [comment]
Leave it to cleaver.
Javascript.

The only error in "console" area of Developer Tools for Chromebook was as
follows:

esper.js:3496Uncaught ReferenceError: hero is not defined
CocoModel.coffee:100Populated defaults for User drew525252 in 20ms
https://analytics.codecombat.com/analytics Failed to load resource:
net::ERR_CONNECTION_TIMED_OUT
Tracker.coffee:173 Analytics post failed!

It had the hero is not defined listed twice.  Outside of the "console"
area, I didn't see any other red "X" or error.

**Comment by drew5252** [comment]
oh and analytics timed out before and I was still able to play, so I don't
think it is that.  but maybe that's something else to fix if you find the
time, LOL. @nick

**Comment by drew5252** [comment]
Any update??

**Comment by Catsync** [comment]
There's a bug preventing the level from loading because your code has an extra `}`. We're working on a fix, but you can work around the bug for now by switching your coding language for that level to something other than javascript, then changing or removing the code and switching it back to javascript.

**Comment by Catsync** [comment]
Fixed it so this level should load for you now.
