### ISSUE TITLE
Hero freezes on  'Medical Attention' 

### ISSUE THREAD

**Issue by rossdrew** [codecombat/codecombat#3675]
Hero just freezes on  'Medical Attention'  unless I have him `say()` something

i.e.
```
while True:
    currentHealth = hero.health
    healingThreshold = hero.maxHealth / 2
    #hero.say("Ready!")     <--- If this isn't here, he freezes after the first attack --|
    enemies = hero.findEnemies()
    if hero.health < healingThreshold:
        hero.moveXY(65, 46)
        hero.say("heal me")
    else:
        if enemies != None:
            enemy = hero.findNearest(enemies)
            if enemy != None:
                if len(enemies) > 2 and hero.canCast("chain-lightning"):
                    hero.cast("chain-lightning", enemy)
                else if hero.isReady("bash"):
                    hero.bash(enemy)
                else:
                    hero.attack(enemy)
```

**Comment by Zerrien** [comment]
Hi, can you take a screenshot of what gear you're using?

**Comment by themaka** [comment]
Hi. I copied your code into my level, removed your "Ready!" line and it works with no freezing. Are you still seeing it? You can also email team@codecombat.com and give us your CodeCombat username and I can log in as you and look at the level.

**Comment by rossdrew** [comment]
Still happening.

![gear_3675](https://cloud.githubusercontent.com/assets/1742406/15568200/83b8574e-2322-11e6-9ab6-09d77fc41ba1.png)
