### ISSUE TITLE
When /play/level/<level>?session=<id> doesn't find a session, no error shows

### ISSUE THREAD

**Issue by sderickson** [codecombat/codecombat#3678]
Try this: http://codecombat.com/play/level/sarven-outpost?session=573d6898746e452100edc7ce

There's a 404 because that session doesn't exist, but the loading screen is just blank; no error feedback.

Suggested solution:

1. Have LevelLoader emit an error when a resource fails to load
1. Have PlayLevelView listen for that event, and render the error on the screen when that happens.

**Comment by duybkict** [comment]
I would like to help on this issue, do you have any sample code for me to start with

**Comment by sderickson** [comment]
Well, the place to start is the [PlayLevelView](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/PlayLevelView.coffee). It [relies on LevelLoader](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/PlayLevelView.coffee#L142-L143) to load from the server, and the [LevelLoadingView](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/LevelLoadingView.coffee) is what is shown while everything is loaded. The [LevelLoader loads the level session](https://github.com/codecombat/codecombat/blob/master/app/lib/LevelLoader.coffee#L112-L146), among other things. In order to handle any resource errors, not just sessions, the LevelLoader could listen to its SuperModel's ['failed' event](https://github.com/codecombat/codecombat/blob/master/app/models/SuperModel.coffee#L226), then go from there, probably communicating to the LevelLoadingView through Backbone.Mediator, since that's what everything else in that area is doing (though not necessarily the best system in general).

**Comment by duybkict** [comment]
I hooked loadFailed event into PlayLevelView, how should I notice users about the error?

**Comment by sderickson** [comment]
The LevelLoadingView needs to display an error. Give it a function like [these ones](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/LevelLoadingView.coffee#L199-L205) and have the PlayLevelView call it when it receives the not found error.
