### ISSUE TITLE
Gem Counter

### ISSUE THREAD

**Issue by MunkeyShynes** [codecombat/codecombat#3684]
I'm not sure why but the gem counter doesn't seem to be accurately / properly adding gems that are earned.  I just beat the Kithgard Brawl for the fourth time and was awarded 318 gems.  Sweet.  The problem is that before starting, my gem counter read over 7100.  I don't remember the exact amount but I do recall it was over 7100.  After being awarded 318, it now reads 7279.  It's not that big a deal for me because I don't need more gems right now anyway but there could be a problem here.  I'm not asking for anything for myself but this type of error can be discouraging for someone working hard to save up for a piece of gear necessary to progress to a higher level and I thought you may want to look into it. 

Thanks.

**Comment by themaka** [comment]
The displayed gems is the total earned for that level, not the amount 
earned on the latest completion. So if a level awarded 50 each time you 
completed it, the second completion would show 100 gems earned.

Maka
