### ISSUE TITLE
Continuous Alchemy poison has the opposite effect

### ISSUE THREAD

**Issue by rossdrew** [codecombat/codecombat#3700]
In __Continuous Alchemy__, if I drink the poison, I loose health.  If an enemy drinks it, he becomes a headhunter and kills me (which he's only supposed to do if he drinks water).  So the level can't be won

**Comment by Zerrien** [comment]
Hello, I looked into this and have fixed it. The problem was Omarn was throwing out a second potion when you said "Poison!".

Try it again and let us know if it still doesn't work after a day (so the caching can catch up).

**Comment by rossdrew** [comment]
Yup, works for me :)
