### ISSUE TITLE
Getting console error for every simulation

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3701]
When accessing https://codecombat.com/play/ladder/wakka-maul (for example), before each simulation I get the error:

- Uncaught TypeError: Cannot set property 'plan' of undefined @ VM119:668
- t.exports.t.loadDependenciesForSession @ VM119:668
- (anonymous function) @ backbone.js:98
- (anonymous function) @ lodash.js:5605
- c @ backbone.js:207
- trigger @ backbone.js:146
- e.success @ backbone.js:434
- u @ jquery.js:3099
- fireWith @ jquery.js:3211
- E @ jquery.js:8264
- (anonymous function) @ jquery.js:8605

**Comment by popey456963** [comment]
Confirmed, Chrome, Win 7 and Firefox, Ubuntu.
