### ISSUE TITLE
IDE should catch '=+' and emit a warning instead of producing unexpected errors

### ISSUE THREAD

**Issue by alexholman** [codecombat/codecombat#3710]
Related to my initial issue report: https://github.com/codecombat/codecombat/issues/3709
I found my problem was typing =+ instead of += for an increment, resulting in an infinite loop condition. 

This is not a very informative error for this easy typo. The code should catch the use of =+ and warn, much like it catches capitalization issues in object names and missing ':' in loops.

**Comment by sderickson** [comment]
This is an [aether](https://github.com/codecombat/aether) bug. Moved issue there.
