### ISSUE TITLE
Commanding a paladin to shield uses up in-game time

### ISSUE THREAD

**Issue by coolbeans14** [codecombat/codecombat#3715]
This is what happens on "Grim Determination":

```
paladin = hero.findByType("paladin")[0]
while True:
    if len(hero.findEnemies()):
        time1 = hero.now()
        hero.command(paladin, "attack", hero.findNearest(hero.findEnemies()))
        time2 = hero.now()
        timeTaken = time2 - time1
        hero.say(timeTaken) # 0, good
```

and

```
paladin = hero.findByType("paladin")[0]
while True:
    if len(hero.findEnemies()):
        time1 = hero.now()
        hero.command(paladin, "move", hero.findNearest(hero.findEnemies()).pos)
        time2 = hero.now()
        timeTaken = time2 - time1
        hero.say(timeTaken) # 0, good
```

But for "shield", this happens:

```
paladin = hero.findByType("paladin")[0]
while True:
    time1 = hero.now()
    hero.command(paladin, "shield")
    time2 = hero.now()
    timeTaken = time2 - time1
    hero.say(timeTaken) # .266666, ???
```

Kind of screws up levels which involve shielding, since all your allies stop while your hero commands the paladin.

**Comment by popey456963** [comment]
(By the way, you are able to use triple backticks (```) in order to preserve indentation and keep it in <code> blocks.)

I also believe this is the desired behaviour.  All three use time, it's just that the shield time is taken immediately, whereas the movement/attack time are "thought" about before the player is moved, not blocking the code.

**Comment by nwinter** [comment]
Well, `shield` should take the paladin time, but it shouldn't take time for the hero, which is just doing a non-blocking `command` call. So it does sound like a fun new bug.

**Comment by coolbeans14** [comment]
Yes, nwinter is right. For example, if you run a for loop to shield all paladins, only one paladin will ever be shielded at a time (and you won't be able to command other troops while this paladin is being shielded, or command your hero). So hero time is being used up. Try it on Grim Determination to see what I mean.

**Comment by popey456963** [comment]
Ah, I see.  My apologies for not realising.

**Comment by Zerrien** [comment]
Hi, we implement a fix for this on Friday.

Give the level another try and let us know if it has improved.

**Comment by nwinter** [comment]
Closing unless it's still a problem.
