### ISSUE TITLE
Clicking 'Enter' while in create account modal opens Facebook login

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3729]
When the cursor is focused on any of the inputs of the create account modal and the key 'Enter' is pressed, the Facebook login modal opens up, even when the account creation is successful.

**Comment by popey456963** [comment]
I'm not seeing this behaviour on Chrome, Win 7.  What Operating System & Browser are you using?

**Comment by Imperadeiro98** [comment]
I'm using the latest Chrome version on Win 8.1.

**Comment by UltCombo** [comment]
I've pushed a fix for this here: #3762
