### ISSUE TITLE
No response from wizards in The Wizards Door level

### ISSUE THREAD

**Issue by skellitor301** [codecombat/codecombat#3749]
So I'm not sure what is going wrong with this level or if it's my coding, but I'm not getting any response or instruction from the wizards at all. The language is LUA and the code is pasted below:

> self:moveXY(30, 13)
> local s1 = self:findNearest(self:findFriends()).getSecret()
> self:moveXY(17, 26)
> local s2 = self:findNearest(self:findFriends()).getSecret()
> self:moveXY(30, 39)
> local s3 = self:findNearest(self:findFriends()).getSecret()
> self:moveXY(43, 26)
> local s4 = self:findNearest(self:findFriends()).getSecret()

**Comment by themaka** [comment]
Hello skelitor301!

Only the first wizard has a secret, then the wizards give you instructions on what to do with the secret.

**Comment by skellitor301** [comment]
But that's just it, there's no response at all aside from the player moving to the coords set.

**Comment by themaka** [comment]
I see now -- it looks like getSecret is not working correctly in Lua. I'll report it to the engineers.

**Comment by themaka** [comment]
One of them pointed out that the error is actually in your code above:

local s1 = self:findNearest(self:findFriends()).getSecret()
should be:
local s1 = self:findNearest(self:findFriends())**:**getSecret()

**Comment by skellitor301** [comment]
Ah, I'd recommend changing that in the commented out code then since that's what is said to use.

**Comment by themaka** [comment]
Yes. We have not yet had a chance to update that level to correctly reflect Lua needed code -- if you look at the default code all of it is commented out and the top line says 
-- TODO: translate code

We default code that was there was for another language.  We apologize for the confusion.

**Comment by skellitor301** [comment]
It's cool! I've noticed that before with string concatenation so I figured that was the case. Thanks for the help.
