### ISSUE TITLE
Teaching documents issue

### ISSUE THREAD

**Issue by shuwn** [codecombat/codecombat#3755]
I have found that teaching documents issue
e.q.
Dungeons of Kithgard level
Recommend code provided by the system is:
`hero.moveRight ()`

But Hints instructions are recommended to use
Python => `self`
javascript=> `this`

I think it would cause confusion and distress for beginners
**In many subsequent levels** have the same problem
Whether it is proposed to maintain consistency

**Comment by Catsync** [comment]
Hello! Can you post a screenshot of where in a level you're seeing "self" or "this" ?

Everything should be showing "hero" now, unless you previously played a level and you still had "self" or "this" in your code.

If you use the code with "hero" in it, then reload the level, it should not show self or this. If it is, we will certainly want to fix it!

**Comment by shuwn** [comment]
ok, I want to confirm one thing.
Now only need to enter the `hero`, not `self` or `this`, right?

If it is like this, I will help to make amendments Traditional Chinese translations.
But the English version and code still need your assistance confirmation.

Here is what I find out the **example**, there are many files have the same problem.

This is the English(US) version - Dungeons of Kithgard - Hints - Python
<img width="454" alt="2016-06-24 10 40 29" src="https://cloud.githubusercontent.com/assets/20023822/16326682/57f8d8dc-39fb-11e6-97ef-2a679d4d253c.png">

This the Traditional Chinese version - Dungeons of Kithgard - Hints - Python
<img width="462" alt="2016-06-24 10 37 49" src="https://cloud.githubusercontent.com/assets/20023822/16326707/8d84ab84-39fb-11e6-8a98-002d9a84b1ba.png">

**Comment by UltCombo** [comment]
Python's `self`, JavaScript's `this` and CoffeeScript's `@` are all "aliases" for `hero` (*most of the time*), `hero` being the most recently introduced and favored alternative.

**Comment by Catsync** [comment]
Ahh, this is the guide for "Gems in the Deep"!

I fixed the english version, so now it says `hero` instead of `self` or `this`.

Thank you for updating the Chinese guide! 谢谢！
