### ISSUE TITLE
Ladder pages aren't working properly

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3764]
For example, when I open https://codecombat.com/play/ladder/ace-of-coders without being logged in (otherwise, while logged in, it works properly), the layout doesn't look correct and I get this error twice in the console:

- Uncaught TypeError: Cannot read property 'models' of undefined @ SimulateTabView.coffee:140

**Comment by sderickson** [comment]
Probably an error caused by a4b5e92b06e6a5763aea5fce8af6bad12ba1d4c8

**Comment by Imperadeiro98** [comment]
Fixed in c3ed217.
