### ISSUE TITLE
All ladder opponents appear as Anonymous in my matches tab

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3765]
When I go to my matches tab, every opponent appear as 'Anonymous':
![opponents](https://cloud.githubusercontent.com/assets/6980488/16356767/f1ad6aa2-3adb-11e6-819f-f2350fe2c75a.png)
Edit: If in the meanwhile one of my matches is simulated, the opponents' names are replaced with the correct ones.

**Comment by sderickson** [comment]
Probably related to 0c0f075

**Comment by nwinter** [comment]
Probably some bug or race condition in [the `loadNames` logic](https://github.com/codecombat/codecombat/blob/master/app/views/ladder/MyMatchesTabView.coffee#L62-L102).

**Comment by nwinter** [comment]
Fixed in https://github.com/codecombat/codecombat/commit/4c5f119e705b379acfa733a3172f4da1ab296d1e
