### ISSUE TITLE
Message displaying oddly - Non subscriber trying to access subscriber level directly

### ISSUE THREAD

**Issue by Harry-the-Wanderer** [codecombat/codecombat#3776]
https://discourse.codecombat.com/t/list-of-items-and-levels/4209/9

The vertical centering seems off for the following message in Safari and Firefox on a MAC.

"You will need a subscription to play this level"
"Subscribe"
"Error loading from server"

**Comment by Imperadeiro98** [comment]
This also happens when trying to access levels belonging to a course when the user is not part of one.

**Comment by Imperadeiro98** [comment]
Fixed in 405c96e
