### ISSUE TITLE
Map animations doesn't show up in Firefox and Safari

### ISSUE THREAD

**Issue by anter69** [codecombat/codecombat#3777]
...but it works fine in Chrome. Please read this thread:
https://discourse.codecombat.com/t/recommendation-differentiate-the-multiplayer-levels-so-they-stand-out-on-the-game-board/8236/3

**Comment by UltCombo** [comment]
The particles are intentionally disabled in non-Chrome browsers, as you can see [here](https://github.com/codecombat/codecombat/blob/5dd4db7676b77fd660251563688b6d1938de86d5/app/views/play/CampaignView.coffee#L395).
This patch has been introduced [over a year ago](https://github.com/codecombat/codecombat/commit/77bca720023d3d859cdebf71b9e7fab2a86cb460) by @nwinter. I have no idea why it is like this. I've just removed the `and $.browser.chrome` part and the particles effect works nicely in Firefox/Win10, at least.

**Comment by anter69** [comment]
Well, if it's intentianally disabled, then there could be some other differentiation to clear the situation, e.g.:
* use a different design for those flags (e.g. with crossed swords, as suggested in the thread)
* or use a different color

**Comment by UltCombo** [comment]
It was intentionally disabled, but that was a long time ago and the reasoning is unclear. Perhaps it was due to a browser bug or third-party library compatibility issue that has already been fixed. I'd suggest to re-enable the particles effect and see if it is still an issue.

**Comment by nwinter** [comment]
Performance was really bad. Anyone tried in those browsers on older machines?

**Comment by UltCombo** [comment]
I have some ~5 years old PC/Mac, but their specs are still pretty decent, so I guess it doesn't count. I assume you meant low-end machines. 😛

**Comment by anter69** [comment]
So, if performance is an issue, how about some static differentiation, as mentioned above?

**Comment by nwinter** [comment]
We do have some new art ready to go for that, we just haven't implemented it yet. I could make it available if someone wants to take a crack at it.

**Comment by anter69** [comment]
New art was deployed sometime ago, things are more clear this way. Thanks!
