### ISSUE TITLE
Simulator breaks on sessions where multiplayer was turned off

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3778]
I started simulating games for 'Ace of Coders' and then, after 7 simulations, I got these errors:
- 403 (Forbidden) @ jquery.js:8630
- Uncaught TypeError: Cannot read property 'classMap' of undefined @ Simulator.coffee:231

After this, I reloaded the page and started simulating again. After only one simulation, I got the error:
- 403 (Forbidden) @ jquery.js:8630

Example URLs:
- http://direct.codecombat.com/db/level.session/560af4f753d6cae34c0dab8c?interpret=true&project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1470910833694
- http://direct.codecombat.com/db/level.session/563bc5de49d2698505c3096c?interpret=true&project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1470911087276
- http://direct.codecombat.com/db/level.session/5601decd47c9418605b9bad8?interpret=true&project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1470943859574
- http://direct.codecombat.com/db/level.session/5789bfa19895c321000745bd?interpret=true&project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1470945766704
- http://direct.codecombat.com/db/level.session/5604fad647c9418605bc679c?interpret=true&project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1471120273469
- http://direct.codecombat.com/db/level.session/5601decd47c9418605b9bad8?project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1471120639385

**Comment by sderickson** [comment]
A ladder session has been made private after it was public. Need to fix the simulation system to not attempt to rank private sessions (where `multiplayer` is false).

**Comment by nwinter** [comment]
The `multiplayer` flag shouldn't actually do anything; that was for synchronous multiplayer mode we were prototyping a while ago. `submitted` is the flag that controls whether a session should be ranked, and the player has no way to unsubmit...

**Comment by nwinter** [comment]
I think I fixed this in https://github.com/codecombat/codecombat/commit/bfa49cbbc6fc7eaa0d04fb56d19cab16232ded00 although it's not deployed yet, should be later today. The simulator will now add `submitted` to its projection, which checks the permission properly.
