### ISSUE TITLE
Getting 404 error from time to time

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3783]
While navigating through the site, from time to time, I'm getting the error:
- https://codecombat.com/javascripts/app/views/core/CreateAccountModal.js 404 (Not Found) @ preloadjs-NEXT.combined.js:3801

**Comment by sderickson** [comment]
This happened because the new CreateAccountModal is a folder with an index file, and our ModuleLoader didn't take that sort of module loading into account. Now it does. Thanks for the report!
