### ISSUE TITLE
Default code for Lua in One Wrong Step is JavaScript

### ISSUE THREAD

**Issue by stuartpb** [codecombat/codecombat#3789]
Not sure where to file bugs against individual levels, but One Wrong Step is missing an initial Lua version.

**Comment by stuartpb** [comment]
The same goes for Forest Evasion - I'm starting to suspect this forest is full of issues like this.

**Comment by themaka** [comment]
Hello Stuart,

Right now we're focusing on the Classroom version of the game, which uses JavaScript and Python only. 

We'll get to it adding the Lua and CoffeeScript eventually (unless someone in the community beats us to it), but I'm afraid our newest levels most likely will not have Lua instructions. We just don't have the resources available at this time.

This is the right place to report these issues, but please report each level separately.

Thank you!

**Comment by stuartpb** [comment]
If I wanted to patch in Lua versions, where in the source tree would I do that?

**Comment by themaka** [comment]
You'd have to do it in the Level Editor. One of our devs will give you more details.

**Comment by Catsync** [comment]
Default code is configured in the level editor on the Hero Placeholder, in the Programming component.

A lot more info about the editor and levels is in the wiki here: https://github.com/codecombat/codecombat/wiki/Artisan-Home

**Comment by Harry-the-Wanderer** [comment]
I just patched the level with a lua update if someone could add the patch to the level it would be working.  I can test it again once this is done.  All translations should also be updated for the lua code in the Intro and Overview.

**Comment by nwinter** [comment]
I accepted the patch. You can set yourself to Watching a level to get email updates from the first item in the dropdown arrow in the upper right in the level editor.
