### ISSUE TITLE
Not Found error in A Mayhem of Munchkins

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3800]
When playing the level A Mayhem of Munchkins, I get this 404 error:
- GET http://direct.codecombat.com/db/thang.type/grow 404 (Not Found) @ jquery.js:8630

**Comment by nwinter** [comment]
That's intentional; we automatically query the server to see if there are any animations for a Mark, and if there aren't, it's fine, just a 404.
