### ISSUE TITLE
Map seems to be stuck

### ISSUE THREAD

**Issue by KainsRache** [codecombat/codecombat#3804]
While playing the forest world, at some point advancement was not possible any more. The level is only half completed and a yellow arrow points to a subscription-only level. The desert world is not accessible, too.
![codewarriors](https://cloud.githubusercontent.com/assets/1352675/16991015/70b49f88-4e9a-11e6-96ec-4427400cd68e.PNG)

Windows 10 x64
Google Chrome
Python language
Last played level was "Leave it to Cleaver", "Agrippa Defense A" or "Backwoods Buddy", I don't really remember.

**Comment by Catsync** [comment]
Thanks for the report! Try re-submitting Leave it to Cleaver, and it should open up the next level correctly now.

**Comment by KainsRache** [comment]
Thank you for your support!
Did you reset something? I'm pretty sure that I already resubmitted it a couple of times before filing this report. :)
It works now!

**Comment by Catsync** [comment]
Yep, it looked like one of the unlocks got vanished somehow, so I put it back :)
