### ISSUE TITLE
Forest Evasion - Python - if statements not working

### ISSUE THREAD

**Issue by Trisped** [codecombat/codecombat#3821]
https://codecombat.com/play/level/forest-evasion

While I understand the goal is to avoid the headhunter, it is possible to use traps to kill him, so I wanted to take it one step further and not kill myself.
Please either add functionality or remove the ability to use if statements and the findNearestEnemy() method.

```
    hero.moveXY(56, 44)
    enemy = hero.findNearestEnemy() #skips line
    if enemy: #skips line
        hero.buildXY("fire-trap", 56, 44) #skips line
```

**JavaScript Console messages:**

>Gold.coffee:78 Ares: Let there be light upon Forest Evasion! (preload: false)
> PlayLevelView.coffee:474 Should we start simulating? Cores: 12 Heap limit: 793000000 Load duration: 3214
> PlayLevelView.coffee:501 Unwritten level type simulation heuristics; fill these in for new level type undefined?
> Angel.coffee:57 |Ares's Archer| Generated random seed -188869236 of type submissionCount from sessionIDs 57a60ecc628da845000dd64a submissionCount 0
> Angel.coffee:57 |Ares's Archer| And it was so: (3.150ms per frame, 240 frames)
> Simulation   : 756ms 
> Serialization: 14ms
> Delivery     : 10ms
> FPS          : 1190.5
> world.coffee:591 No frames were changed out of all 240

**Comment by Zerrien** [comment]
Hi, I'm not sure of the problem you're experiencing. If you're crafty, you should be able to build fire-traps to kill the headhunter.

Do you have your full code of what you wanted to do?

**Comment by Trisped** [comment]
Hi Zerrien,

It looks like I was wrong, if statements work, but the headhunter is not an enemy:

```
hero.buildXY("fire-trap", 56, 44)
hero.buildXY("fire-trap", 40, 56)
while True:
    enemy = hero.findNearestEnemy()
    if enemy:
        hero.say("Enemy")
    else:
        hero.say("No Enemy") #Always says this, even before the head hunter hits a trap.
    hero.moveXY(24, 44)
    hero.moveXY(24, 24)
    hero.moveXY(40, 12)
    hero.moveXY(56, 24)
    hero.moveXY(56, 44)
    hero.moveXY(40, 56)

```

Thanks for looking into this.

**Comment by Zerrien** [comment]
So, in CodeCombat, vision matters. Even though most heroes might look comically big, they can't see through a forest!

When I run your code, I use the time slider at the bottom to look when the hero first says anything. At that moment, the Headhunter is out of vision, so they say: "no enemy."

Try this code:

```
while True:
    enemy = hero.findNearestEnemy()
    if enemy:
        hero.say("I see you!")
    else:
        hero.say("No enemy...")
```

And you will see the hero say "No enemy..." until the Headhunter gets into 'vision' range.

**Comment by Trisped** [comment]
Thanks, that explains it.
