### ISSUE TITLE
403 error when simulating dueling grounds

### ISSUE THREAD

**Issue by Trisped** [codecombat/codecombat#3822]
Simulating crashes with 403 error after only a few simulations have been completed.

https://codecombat.com/db/level.session/54459c8ede0eb73e05ea28ff?interpret=…deLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1470506139230 Failed to load resource: the server responded with a status of 403 ()

I am using Chrome  52.0.2743.116 m

**Comment by nwinter** [comment]
Do you still see a 403 Forbidden response when visiting that link? Trying to figure out why that wouldn't load for you (no permissions), but it seems to be available to everyone.

Oh, perhaps it's because the link is truncated–the ... in the middle. Can you get the full URL next time you see this?

**Comment by Imperadeiro98** [comment]
Similar to #3778?

**Comment by Trisped** [comment]
Yes, Chrome was  truncating using the ...
The following are full links:

- https://codecombat.com/db/level.session/5782701bf6915221003a7f1d?interpret=true&project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1470870039814

- https://codecombat.com/db/level.session/5593ed691e1f7d8805ad7864?interpret=true&project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1470870262159

- https://codecombat.com/db/level.session/549781470ab92d5305ae175e?interpret=true&project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1470870317075

- https://codecombat.com/db/level.session/57880ff74239ef20009c8933?interpret=true&project=creator%2Cteam%2CheroConfig%2CcodeLanguage%2CsubmittedCodeLanguage%2Cstate%2CsubmittedCode&_=1470870386957


The error seems random, sometimes I get it in the first 2 or 3 simulations, sometimes I get it after 8 or 9.  Rarely do I ever get more then 10 simulations without refreshing or using multiple tabs.

I cannot tell if this is similar to #3778 since they did not include much in the way of debug info.  I can confirm that it is the same jquery file and line where the error is generated, but since this is probably the jquery code for handling AJAX requests and there are many other requests which succeed, the information is probably useless.

**Comment by nwinter** [comment]
I think I fixed this in bfa49cb although it's not deployed yet, should be later today. The simulator will now add submitted to its projection, which checks the permission properly.

**Comment by Trisped** [comment]
Fix confirmed.
I was able to run 100 simulations without issues.
