### ISSUE TITLE
 Bug level 17 Kithgard Dungeon Lua language 

### ISSUE THREAD

**Issue by NentoR** [codecombat/codecombat#3841]
I found bug in level 17 Kithgard Dungeon

This is my code:
local enemy1 = self:findNearestEnemy()
local enemy2 = self:findNearestEnemy()

self:attack(enemy1)
self:attack(enemy1)

self:attack(enemy2)
self:attack(enemy2)

And when my hero kill enemy1 trying to kill enemy2 but detecting enemy2 as enemy1 and saying "But it's dead"

**Comment by Kevitto** [comment]
As your code stands, your enemy1 and enemy2 values are the same object, self:findNearestEnemy().

You have to re-check findNearestEnemy() once enemy1 is dead to get enemy2, or just use self.attack(self.findNearestEnemy()) 4 times.
