### ISSUE TITLE
'Play as...' buttons disappear when coming from spectating

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3846]
If I go to the page of a ladder level (for example https://codecombat.com/play/ladder/ace-of-coders), press "Spectate" and then come back by clicking the "Ladder" button in the upper left corner, when the ladder page finishes loading, the image for that ladder and the "Play As..." buttons are not there.

**Comment by sderickson** [comment]
Can confirm

**Comment by Imperadeiro98** [comment]
Fixed by f57ec17.
