### ISSUE TITLE
"The Final Kithmaze" CodeCombat level 23 Glitch

### ISSUE THREAD

**Issue by HeyItsLex** [codecombat/codecombat#3847]
"The Final Kithmaze" level seems to be glitching for me. From what I have seen online, the level is 100% supposed to be completed using the hero.moveDirection commands, and not (X,Y), which had yet to even be introduced as a concept. The level requires a loop to complete (it must be done in under 10 moves) and therefore cannot be completed using X,Y. I'm learning JavaScript on an IOS computer in Crome.

![screen shot 2016-08-14 at 12 59 04 pm](https://cloud.githubusercontent.com/assets/21024872/17650621/ca50e202-621f-11e6-97d6-5c2c24e95304.png)
![screen shot 2016-08-14 at 12 59 53 pm](https://cloud.githubusercontent.com/assets/21024872/17650622/cb9c34e0-621f-11e6-9130-cbd632b6f78e.png)

**Comment by themaka** [comment]
You changed your boots, Lex.

Equipment controls which commands your hero had access to. Switch back to your moveDirection boots.
