### ISSUE TITLE
'Think Ahead' - CloudRip Mountain unit pathing issue [Python]

### ISSUE THREAD

**Issue by Kevitto** [codecombat/codecombat#3848]
The units on wave 4's pathing puts three (3) units within range of the explosion instead of two (2), leading to the third unit always dying.  

The code does not let me add a third target to the shielding mechanic, therefore always losing the battle.

![image](https://cloud.githubusercontent.com/assets/21039201/17666605/f2b9bd36-62ce-11e6-9e2e-5f216d534b55.png)

![image](https://cloud.githubusercontent.com/assets/21039201/17666592/dd5fa1bc-62ce-11e6-8a43-9986d74efadc.png)

**Comment by Bryukh** [comment]
@Kevitto, thank you for the report. Could you give your session id for this level? To get it - open the dev console in your browser and find a string sessionID. It can really help to reproduce the bug and fix it.

**Comment by Kevitto** [comment]
Sorry, I have no idea how to do any of that.  I play the free version on a browser.  I don't have a dev environment setup nor do I know how to set that up.

**Comment by Bryukh** [comment]
Ok. No problem, I think I'll find the problem. It's ok to post bugs here. Also you can write about problems with levels on the forum.

**Comment by Bryukh** [comment]
Fixed.
