### ISSUE TITLE
'Ritual of Rectangling' - CloudRip Mountain missing comment string values [Python]

### ISSUE THREAD

**Issue by Kevitto** [codecombat/codecombat#3849]
The comments in this one are showing the comment's name, not value:

![image](https://cloud.githubusercontent.com/assets/21039201/17670308/5f9fcfe8-62df-11e6-96e9-ecd3c10c4bfc.png)

**Comment by Bryukh** [comment]
Thanks! Fixed. You need to click "Reload" button in the top right corner of the editor.
