### ISSUE TITLE
Match Cord - Cloudrip Mountain fieldMap array is uneditable [Python]

### ISSUE THREAD

**Issue by Kevitto** [codecombat/codecombat#3898]
The array built at the beginning named fieldMap is uneditable, and even copying it to another array still locks it.  I'm trying to edit values within the array, and no error message pops up, but trying the exact same commands with a custom-made array of the same name confirms the fieldMap array is uneditable.

```
>>>>fieldMap[0][1] -> 'x' # value starts as x
fieldMap[0][1] = '.' # change value to .
>>>>fieldMap[0][1] -> 'x' # value is still x
map2 = fieldMap
>>>>map2[0][1] -> 'x'
map2[0][1] = '.'
>>>>map2[0][1] -> 'x'
```

**Comment by Bryukh** [comment]
Yes, because is a protected property.
`map2 = fieldMap` -- it's not a copy, it's a reference.
To make a copy you need use other methods.

**Comment by nwinter** [comment]
Shouldn't we have an error message when trying to write into a protected property, though? How is it protected?

**Comment by Bryukh** [comment]
@nwinter You are right - it's not a property. `fieldMap` is the result of the unit's custom method `getMap()`. So I'm not sure it's a referee bug or the interpreter.

**Comment by Bryukh** [comment]
Oh! Stupid me. @Kevitto you can't change lines of the array because they are strings and immutable. @nwinter should be an error in this case? If yes, then I think it's an editor/interpreter bug.
