### ISSUE TITLE
Add a tab for the default hero functions and abilities like Math or Vector

### ISSUE THREAD

**Issue by Harry-the-Wanderer** [codecombat/codecombat#3903]
The "Programmaticon V" adds tabs (Javascript?) to the function help descriptions under the code area.  When you click on a tab like Math or Vector it will load up the help section attached to those areas.  However there is no "Hero" tab for the original functions like hero.say() or hero.isReady() so the student then looses the quick reference to that part of their documentation.

Please expose or add an additional tab for "Hero" function help.  Or replace the current "empty" function tab with a tab called Hero.

https://discourse.codecombat.com/t/is-there-a-tab-for-the-default-hero-functions-and-abilities-like-math-or-vector/8828

**Comment by nwinter** [comment]
This works with new vertical code documentation design.
