### ISSUE TITLE
The Bane of Soldiers Level - Add requirement for glasses

### ISSUE THREAD

**Issue by judowalker** [codecombat/codecombat#3905]
I couldn't find any enemies on this level (https://codecombat.com/play/level/the-bane-of-soldiers) until I realized that the glasses I had equipped (Githgard Worker's glasses) didn't have enough range. I purchased and equipped the Twilight glasses which worked.

It would be nice if it required glasses with the minimum range necessary to complete the level the way it was intended.

**Comment by Zerrien** [comment]
I overrode the hero's sight range so they should be able to see all enemies and friends no matter what glasses they use. (As long as they have any glasses with the required methods.)
