### ISSUE TITLE
Wrong variable name on error

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3913]
If I type this line of code `loopCount = 1;` the following error appears:

![fix code](https://cloud.githubusercontent.com/assets/6980488/18313314/11c3cdd6-7506-11e6-9207-26daa6e9a72a.png)

As you can see, it thinks that my variable is `Count` instead of `loopCount`.

**Comment by nwinter** [comment]
There's probably some custom error message massaging that's happening somewhere to remove our old fake `loop` keyword that we need to find and take out.

**Comment by mmnishid** [comment]
Looking through the code I'm pretty sure that the custom error message is coming from the Aether as the output from castAether after trying to run the code returns the following output:

![image](https://user-images.githubusercontent.com/7968842/43803869-ecb0a878-9a4e-11e8-84bc-a22a52a38f02.png)

I'm going to try to build and run the Aether source code to try a trace this issue.

**Comment by Imperadeiro98** [comment]
Seems to be fixed. I can no longer reproduce it

**Comment by mmnishid** [comment]
I tracked this issue to the hint messages created by the jshint module used by aether. They must have fixed it on their end.
