### ISSUE TITLE
Game Dev Level Two - Red X does not appear

### ISSUE THREAD

**Issue by samerickson** [codecombat/codecombat#3917]
I was messing around, figuring out how the site works, I completed the first level of Campain Game dev in Python, then switched languages to Javascript and now level two does not work. The linter says incorrect first argument `game.spawnHeroXY(5, 8);` and that the first argument should be either `["spawn"],["hear"],["update"],["click"]` but as far as I can tell the code is correct. I did not change anything, and the instructions say that you don't have to, so everything should work.

**Comment by Catsync** [comment]
Sorry about that! We recently made some changes to prepare for future game dev levels that may be causing this error. Try clearing your browser cache to see if that clears things up?

If that doesn't work, try logging in to direct.codecombat.com, see if it works there?

**Comment by nwinter** [comment]
I think it's fixed–closing for now. Can re-open if it's still happening.
