### ISSUE TITLE
Does CodeCombat have an opinion on the future of Coffeescript?

### ISSUE THREAD

**Issue by greghuc** [codecombat/codecombat#3923]
Hi guys,

A quick heads up that there's a pretty active discussion going on over at [coffeescript6/discuss](https://github.com/coffeescript6/discuss) about possible next steps for Coffeescript.

Thought you might want to comment, given CodeCombat is a heavy Coffeescript user. Discussed issues are [here](https://github.com/coffeescript6/discuss/issues).

There's also a survey that's relevant to you: [Survey for devs/teams with maintained Coffescript codebases: happy with CS, or considering migrating?](https://github.com/coffeescript6/discuss/issues/32)

**Comment by nwinter** [comment]
Cool! I commented on the survey issue; hope this helps. Will leave this open in case others want to chime in or get informed.

**Comment by greghuc** [comment]
@nwinter thanks! Do you know of any other teams with big maintained Coffeescript codebases? I'd like to make them aware of the survey. CodeCombat was the first big team/project I thought of.

**Comment by nwinter** [comment]
Nah, I haven't really been following any.
