### ISSUE TITLE
Simulations stopped and threw an error

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3933]
I was simulation matches for the "Cavern Survival" ladder, and after some simulations, the simulator stopped. In the console I got the following error:
- GET http://direct.codecombat.com/javascripts/app/vendor/aether-clojure.js 404 (Not Found)

I also got a "SuperModel report", where the only resource with a false loaded property was "language_module".

**Comment by nwinter** [comment]
I just switched all the Clojure multiplayer sessions to JavaScript, so I think this should be fixed. Can you simulate some more on Cavern Survival and reopen this if you see it again?

**Comment by Imperadeiro98** [comment]
Seems to be fixed. Thanks!

**Comment by Imperadeiro98** [comment]
Happened again:

-  GET http://direct.codecombat.com/javascripts/app/vendor/aether-clojure.js 404 (Not Found) @ preloadjs-NEXT.combined.js:3801

**Comment by Imperadeiro98** [comment]
Another one:

-  GET http://direct.codecombat.com/javascripts/app/vendor/aether-io.js 404 (Not Found) @ preloadjs-NEXT.combined.js:3801

**Comment by nwinter** [comment]
Hmm, I found 34 more sessions with those languages set, so I unset them... not sure how more appeared. Reopen when you see it again and I'll see if they are still coming or if it was the last trickle.

**Comment by Imperadeiro98** [comment]
Saw another one:
- GET http://direct.codecombat.com/javascripts/app/vendor/aether-clojure.js 404 (Not Found) @ preloadjs-NEXT.combined.js:3801

**Comment by Imperadeiro98** [comment]
In 'Harrowland':
- GET http://direct.codecombat.com/javascripts/app/vendor/aether-clojure.js 404 (Not Found) @ preloadjs-NEXT.combined.js:3801

**Comment by Imperadeiro98** [comment]
In 'Dueling Grounds':

- GET http://direct.codecombat.com/javascripts/app/vendor/aether-clojure.js 404 (Not Found) @ preloadjs-NEXT.combined.js:3801
