### ISSUE TITLE
"Invisible" patches for levels

### ISSUE THREAD

**Issue by Bryukh** [codecombat/codecombat#3937]
@Harry-the-Wanderer created a patch for the level "Team Work"
![2016-09-19_07-29-16](https://cloud.githubusercontent.com/assets/343120/18622675/2600fa60-7e3b-11e6-8601-5ff13b0fc611.png)

But I haven't received an email about (I'm the author of this level and "watched" is "on").
Also I don't see that patch in the level, but I see a notification label only.

![2016-09-19_07-29-27](https://cloud.githubusercontent.com/assets/343120/18622688/5353d352-7e3b-11e6-894d-fa54f44e1789.png)

**Comment by nwinter** [comment]
Link to level: http://direct.codecombat.com/editor/level/team-work

**Comment by sderickson** [comment]
Fixed: https://github.com/codecombat/codecombat/commit/be1c1323ac86a378c0739d092f615293adb91d13
