### ISSUE TITLE
Unrelated error because of a not initialized variable

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3942]
In my code I have this line: `while (index < units.length)` and the variable `index` was not initialized. Because of that, this (apparently) unrelated error appears:

![error](https://cloud.githubusercontent.com/assets/6980488/18808507/676ccaf4-825c-11e6-894e-a2d0e5f504bc.png)

I think it would be better if the error message was something like "The variable `index` is not initialized".

**Comment by basicer** [comment]
Fixed here https://github.com/codecombat/esper.js/commit/8ddc42d25737c0466fe54984a3dddf0063abf6b5
