### ISSUE TITLE
Clicking 'Contact' when playing as a teacher does nothing

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3943]
If I play a level from https://codecombat.com/teachers/courses and click the contact button on the bottom of the page, nothing happens, and the following error appears in the console:

- Uncaught TypeError: Cannot read property 'compile' of undefined @ SpellView.coffee:653

**Comment by nwinter** [comment]
I think this might have been a temporary issue? I can't reproduce. Can you test again and let me know if you still see it?

**Comment by Imperadeiro98** [comment]
Still happening:
- Uncaught TypeError: Cannot read property 'compile' of undefined @ SpellView.coffee:656
- module.exports.SpellView.saveSpade @ SpellView.coffee:656
- (anonymous function) @ SpellView.coffee:1
- module.exports.SpellView.onContactButtonPressed @ SpellView.coffee:580
- publish @ backbone-mediator.js:128
- module.exports.PlayLevelView.onContactClicked @ PlayLevelView.coffee:608
- bound @ lodash.js:729
- dispatch @ jquery.js:4435
- elemData.handle @ jquery.js:4121
