### ISSUE TITLE
Hardened Steel Glasses do not have access to findNearestItem function

### ISSUE THREAD

**Issue by NP-Hardass** [codecombat/codecombat#3958]
Most likely related to  https://github.com/codecombat/codecombat/issues/2456.  This is mostly bothersome to me because a lot of the pregenerated code on levels uses this function and thus throws an error when I try to run it.

**Comment by Julix91** [comment]
I'm not familiar with those glasses, but I had the same problem with the best glasses in the game.

I can use `var items = hero.findItems();
    var item = hero.findNearest(items);` to get around that.


While I'm a fan of having better items make worse items irrelevant (so you can hide/sell them), I bought the glasses that let you see through walls very early on and had to figure out a way to deal with the lack of support for these glasses in many many levels. -- I saved a lot of crystals not buying any of the glasses in between, that was the price I paid for that.

Not sure if the stone glasses allow for this work around as well, but if you care for the convenience of using nearest item -- and more importantly nearest enemy (yes that one will go away too!) -- check which of the cheaper glasses still allow you to do that.

**Comment by nwinter** [comment]
I just added `findNearestEnemy` and `findNearestItem` to all the higher-level glasses that just had the array-based methods.
