### ISSUE TITLE
Cavern Survival simulator crashed

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3984]
While I was simulating some Cavern Survival games, the simulator crashed twice:

First time:
- ------------------- Destroying  Simulator and making a new one -----------------
-  Populated defaults for Level Cavern Survival in 24ms @ CocoModel.coffee:100
- |Hecate's Cheryl| Modern javascript detected, aw yeah! @ Angel.coffee:57
- |Hecate's Cheryl| Worker initialized after 4641ms @ Angel.coffee:57
- SuperModel report ------------------------ @ SuperModel.coffee:22
- 98 resources. @ SuperModel.coffee:23

All resources have the loaded property set to true, except a thang (I think it was "Health Potion Large").

Second time:
All resources have the loaded property set to true, except one 'thang_names'.

**Comment by nwinter** [comment]
I'm not getting any crashes, I think I fixed it. Let me know if you still see any.
