### ISSUE TITLE
Alejandro (hero) - hand icon misplaced on gear screen

### ISSUE THREAD

**Issue by Harry-the-Wanderer** [codecombat/codecombat#3985]
https://discourse.codecombat.com/t/alejandro-the-duelist-thumb-graphics-become-odd-hairdo/9319

When you equip the Emperor's Gloves and then remove them, Alejandro gets a new hairstyle!

Actually the hand graphic just displays over his head for some reason.  This doesn't happen with Tharin.

The easiest way to see this happen is to start with no equipment and then wear the gloves and then remove the gloves.

**Comment by nwinter** [comment]
Fixed it. The thumb was exported too large.
