### ISSUE TITLE
CSS property - background-color property documentation is wrong - patched

### ISSUE THREAD

**Issue by Harry-the-Wanderer** [codecombat/codecombat#3988]
https://discourse.codecombat.com/t/web-development-campaign-background-color-error-in-example-definition/8742

- CSS property is wrong
- the end style tag is missing a slash

I have created a patch for this component
https://discourse.codecombat.com/t/css-property-patch-for-background-color/9330

Please let me know if there is a better way to do this in future.  Should I just create an issue here and then submit the patch for it?

**Comment by Zerrien** [comment]
I accepted this patch on Friday. Thanks, Harry.
