### ISSUE TITLE
Stone Builder's Hammer

### ISSUE THREAD

**Issue by doudley** [codecombat/codecombat#3996]
In equipment screen, the hammer doesn't show on my hero's hand when equipped.
I've tried other heroes and other weapon/hammer (their OK, they appear) but with this hammer, it doesn't appear.

UPDATE:
It seems, I cannot build an Arrow Tower ("arrow-tower") and a Decoy ("decoy") with this hammer even if it should have. Please check.

![bug](https://cloud.githubusercontent.com/assets/22913280/19479962/b1322e22-957b-11e6-972a-a3dff269e0fa.PNG)

**Comment by Zerrien** [comment]
Hi, I can confirm I was able to build an arrow-tower and decoy with the hammer.

Do you have enough gold at the moment of building? It costs 75 gold to build an arrow-tower and 25 to build a decoy.

**Comment by doudley** [comment]
I didn't know that it need golds to build. My bad. Thank you again for confirming.

**Comment by doudley** [comment]
The hammer still doesn't show on my hero's hand in equipment screen. Can anyone confirm?
Also, I don't know if it would be helpful for other newbies like me but I would prefer some kind of hint that the equipment has requirement to use in-game before buying or when I use the build action without having gold, my hero will say "Insufficient gold" or something like that...

**Comment by sderickson** [comment]
The graphic bug is confirmed, and in our bug list. This is not the only hammer that has this issue.

**Comment by anter69** [comment]
same as #2891

**Comment by anter69** [comment]
If I could get any guidance about the requirements (size, etc) of the icons, I would happily create them. Otherwise I will copy and paste the existing hammer paper doll to the empty places, so there is at least something in the meantime :smile:
