### ISSUE TITLE
Error when accessing poll without being logged in

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#4006]
When I try to access a poll through the poll editor ([example](http://direct.codecombat.com/editor/poll/after-playing-codecombat-how-interested-are-you-in-programming)) without having access to it (like when I'm logged out or logged in with a normal account), I get this error in the console:
- Uncaught TypeError: Cannot read property 'build' of null @ PollEditView.coffee:58

Note: Similar to #3266.

**Comment by dfberry** [comment]
Currently in PR waiting for approval. Fix was to check me.isAdmin before building treema
