### ISSUE TITLE
Bug in 'The Raised Sword' when buying more armor

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#4031]
If I click the 'Open Item Shop' button in the level 'The Raised Sword' after I try to defeat the munchkins and I am prompted to buy more armor, the modal that opens breaks the game and I can't close it.

**Comment by sderickson** [comment]
Can you provide more details? I'm having trouble reproducing the broken modal.

**Comment by Imperadeiro98** [comment]
I can no longer reproduce it either. But when I saw the issue, I was playing with the hero 'Alejandro' in a brand new account using the CoffeeScript language.
