### ISSUE TITLE
New user, interface never finishes loading

### ISSUE THREAD

**Issue by olingern** [codecombat/codecombat#4033]
Hi, 

Was just poking around the production site and couldn't get things to work.

Precursors:
- Signed up as a new user ( individual )
- Navigated to: https://codecombat.com/play

<img width="1280" alt="screen shot 2016-11-07 at 11 41 08 pm" src="https://cloud.githubusercontent.com/assets/1470297/20087121/cdcf2b0c-a543-11e6-87ad-20dba8ddd468.png">

**Comment by leereilly** [comment]
Came here to report the exact same issue. For us, we're actually logged in already with my son's existing user account auth'd via my Facebook account. 

![pasted_image_11_7_16__8_57_pm](https://cloud.githubusercontent.com/assets/121322/20087367/b66726d4-a52c-11e6-8a1b-fd6c1ac935f5.png)


<img width="1440" alt="screen shot 2016-11-07 at 8 56 01 pm" src="https://cloud.githubusercontent.com/assets/121322/20087350/8df821bc-a52c-11e6-8b25-a6808f45a341.png">

**Comment by nwinter** [comment]
Should be fixed now; can you try again? (You might need to clear your browser cache.) Sorry about that!

**Comment by leereilly** [comment]
Thanks @nwinter!!! My kids's ready to slay some code again :crossed_swords: 

![](https://blog.codinghorror.com/content/images/uploads/2007/03/6a0120a85dcdae970b0128776ff992970c-pi.png)
