### ISSUE TITLE
Quiz for age does not have an option for < 13 

### ISSUE THREAD

**Issue by druttka** [codecombat/codecombat#4036]
Hi,

My kid started CodeCombat this weekend but is under 13. I created the account, and that seems to have worked fine. We love it. Thanks a lot for the work that has gone into it =)

The one bit of confusion was the daily quiz or bonus question that asked for an age, and we didn't see an option for < 13.

I did a quick search through the history, and I can see that the [change to require a minimum age of 13 on signup was intentional](https://github.com/codecombat/codecombat/commit/4183764b6136e47324cee621f597b193dfec44c9). I also see that the [ageRange enum was subsequently changed](https://github.com/codecombat/codecombat/commit/cdddc2469318add39b61e4cd196f26c7e0395d1f).

My questions are

1. Is there PG-13+ content that prompted the age restriction, or was this for other reasons (e.g., I think I saw a check for 18+ before what looked like an add-on / upsell prompt)? I played with my kid this weekend and haven't seen anything questionable yet, but just want to check before we get too far.
2. Should the age question consider the possibility of younger players who got an account through a parent, guardian, etc.?
3. This question may answer itself the next time we play, but is my kid "stuck" on this question unless or until we lie about the age? Or is there a way to skip this question that we're missing? Or does this feature cycle to a new question each day (as opposed to this being the first, and has to be answered before getting to the second)?

I'd be happy to help make any relevant changes here, but I didn't want to jump in too fast before confirming the goals and directions around age requirements.

Thanks!

**Comment by nwinter** [comment]
Hi @druttka, great questions. We did initially change the age range on the quiz when we didn't have the age check with parental consent on the signup form that we have now. There's no PG-13+ content in the game, but we just needed to be careful around compliance with COPPA and making sure we didn't store any personal identification of players under 13 in the US without parental consent.

Perhaps we will update the quiz option again in the future, but for now, just put your age in for the quiz, and then you and your kid will be able to get to the next quizzes to earn more gems.
