### ISSUE TITLE
Loader stuck on level 19/42 (Closing the Distance) on Kithgard Dungeon

### ISSUE THREAD

**Issue by maschasan** [codecombat/codecombat#4042]
Hello,

The level loader on level 19/42 (Closing the Distance) won't move over 25-30% for what reason ever.

Please find enclosed the output of the Java console.

Thank you in advance,
Benny and Michael

`opulated defaults for Level Closing the Distance in 42ms
Angel.coffee:86Stribog: Let there be light upon Closing the Distance! (preload: false)
Grid.coffee:42Uncaught SyntaxError: Unexpected identifier(…)(anonymous function) @ worker_world.js:9
Grid.coffee:42Uncaught SyntaxError: Unexpected identifier(…)(anonymous function) @ worker_world.js:9
aether_worker.js:1 Modern javascript detected, aw yeah!
concepts.coffee:32 SuperModel report ------------------------
concepts.coffee:32 178 resources.
concepts.coffee:32 	 level loaded true Level {cid: "c9", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}_changing: false_events: Object_listenId: "l11"_pending: false_previousAttributes: Objectattributes: ObjectattributesWithDefaults: Objectchanged: Objectcid: "c9"defaultComponentConfigurations: Objectheadless: falseid: "5823dff2c95c5d21005c6595"jqxhr: nulllastOriginal: "524b75ad7fc0f6d519000001"lastType: "component"loaded: trueloading: falsesaveBackup: ()saveBackups: falsesessionless: falseusesVersions: true__proto__: CocoModel
concepts.coffee:32 	 level_session loaded true LevelSession {cid: "c15", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}_changing: false_events: Object_listenId: "l17"_pending: false_previousAttributes: Object_revertAttributes: Objectattributes: Objectchanged: Objectcid: "c15"id: "581f16383b31021f009b9340"jqxhr: nullloaded: trueloading: falsesaveBackup: ()saveBackups: falseurl: ()usesVersions: false__proto__: CocoModel
concepts.coffee:32 	 thang loaded true ThangType {cid: "c18", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}_changing: false_events: Object_listenId: "l20"_pending: false_previousAttributes: Objectattributes: Objectbuilding: Objectchanged: Objectcid: "c18"id: "5821c9d4dba1473500d27113"jqxhr: nullloaded: trueloading: falseonFileUploaded: ()saveBackup: ()saveBackups: falsespriteSheets: Objecturl: ()usesVersions: true__proto__: CocoModel
concepts.coffee:32 	 thang loaded true ThangType {cid: "c21", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c24", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c27", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c30", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c33", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c36", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang_names loaded true ThangNamesCollection {ids: Array[11], length: 11, models: Array[11], _byId: Object, project: undefined…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c41", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c44", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c47", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c50", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c53", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c56", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c59", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c62", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c65", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c68", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c71", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c74", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c77", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c80", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c83", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c86", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c89", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c92", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c95", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c98", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c101", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c104", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c107", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c110", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c113", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c116", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 system loaded true LevelSystem {cid: "c119", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 level loaded true Level {cid: "c122", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c125", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c128", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c131", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c134", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c137", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c140", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c143", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c146", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c149", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c152", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c166", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c169", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c172", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c175", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c178", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c181", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c184", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c187", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c190", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c193", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c196", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c199", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c202", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c205", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c208", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c211", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c214", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c217", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c220", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c223", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 component loaded true LevelComponent {cid: "c226", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c229", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c232", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c235", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c238", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c241", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c244", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c247", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c250", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 thang loaded true ThangType {cid: "c253", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
concepts.coffee:32 	 1 loaded false null
dexecure-c167a5675c.js:1 Service Worker termination by a timeout timer was canceled because DevTools is attached.`

**Comment by sderickson** [comment]
Hi! I found Benny's account, but the level Closing the Distance isn't in your classroom list, so I'm not sure how he got to that level. How did he get there, and what's the url when you get there? Once we figure that out we should be able to better identify the problem.

Thanks for your patience!
