### ISSUE TITLE
Levels use 'self' instead of 'hero' in Lua

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#4044]
The levels "Gems in the Deep", "Kithgard Gates" and "Winding Trail" use the keyword 'self' instead of 'hero' when playing in the language Lua.

**Comment by nwinter** [comment]
Thought I got all these with the patches from Harry the Wanderer, but possibly something caused those patches to not apply properly in these levels.

**Comment by dfberry** [comment]
The fixes are in and waiting for approval - what is the flow after that?

**Comment by nwinter** [comment]
Merged 'em in!
