### ISSUE TITLE
Decrease number of ladder matches played against your own code

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#4051]
I don't know if it is intended to work like it does, but while playing the ladder levels and simulating them, I noticed that if I submit my code for both teams (Red and Blue), they end up fighting each other (several times in the first matches), and one of them falls behind. This makes it somewhat impossible to be the best of both teams' ladders.

My suggestion is to prevent players from fighting against themselves.

**Comment by anter69** [comment]
See similar suggestions here #3228

**Comment by nemoyatpeace** [comment]
This is directly connected to #4096.
Should be fixed at the same time.

**Comment by nwinter** [comment]
Fixed in https://github.com/codecombat/codecombat/commit/3067260b09c434d952d24cb7c1253efb0d4ccc06
