### ISSUE TITLE
Cannot play as teacher

### ISSUE THREAD

**Issue by Domiii** [codecombat/codecombat#4065]
After identifying as teacher, I cannot play or even view any of the levels. That puts me in quite a bad position since inability to view or work through the lessons makes adequate preparation close to impossibly (luckily, I am not using CC with my big class yet).

Details: Ever since I identified as teacher, when going to https://codecombat.com/play, I get immediately redirected to https://codecombat.com/teachers/classes. There seems to be no option for me to actually get into the game, view or try the levels. Any help would be greatly appreciated!

**Comment by themaka** [comment]
Hello Domiii,

Teachers can play all the levels by going to the [Course Guides page](https://codecombat.com/teachers/courses) of the Teacher Dashboard: https://codecombat.com/teachers/courses

Just select the correct language and level from the dropdown menus for each course.

Maka

**Comment by Domiii** [comment]
Thank you very much!

Maybe the `/play` URL path should redirect to that! :)

**Comment by themaka** [comment]
Uh, yes, we totally thought of that ourselves.
/frantically sends message to engineering team.

Thanks Domiii!
