### ISSUE TITLE
Vagrant setup fails

### ISSUE THREAD

**Issue by alexanderadam** [codecombat/codecombat#4076]
First of all: you guys are awesome!

I wanted to try the basic setup with Vagrant and it failed.
It ends with:

```
==> default: Setting up mongodb-org (2.6.12) ...
==> default: populating mongodb...
==> default: /tmp/vagrant-shell: line 65: /vagrant/scripts/vagrant/core/fillMongo.sh: Permission denied
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by dfberry** [comment]
Please edit the scripts/vagrant/core/provision.sh file with this to make the fillMongo.sh executable
chmod a+x /vagrant/scripts/vagrant/core/fillMongo.sh

You can see this fix in the PR 4070https://github.com/codecombat/codecombat/pull/4070/commits/17e5ae76ef97a588a7fdb5736dabd221cf0f5099#diff-58956def93611c9a3825b190a9a90a85

**Comment by alexanderadam** [comment]
awesome. thank you!
