### ISSUE TITLE
The Raised Sword requiring subscription

### ISSUE THREAD

**Issue by jway945** [codecombat/codecombat#4078]
After the 4 initial levels it gets stuck as "The Raised Sword" level keeps asking for subscription.
Tried different languages and creating different accounts, even though it keeps asking for subscription.

**Comment by nwinter** [comment]
Hey @jway945, see [this forum thread](https://discourse.codecombat.com/t/level-6-subscription-bug/5453/35?u=nick) – we are offering a cheaper subscription in Brazil to help with the currency issues, but it doesn't have as much free content.
