### ISSUE TITLE
Sometimes achievements don't show up as just earned in victory modal

### ISSUE THREAD

**Issue by MunkeyShynes** [codecombat/codecombat#4083]
When completing a level for the **FIRST** time, the gems and XP are not being reflected properly where indicated in the attached .jpg. The gems ARE being collected and I can only assume the XP points are being allocated as well. When I go to the main screen (https://codecombat.com/play), I can see that the number of gems listed in the lower left corner has gone up the correct amount. It's just immediately above the "continue" button where it does not register/indicate anything but zero. I would expect this if it was a re-submit of a previously completed level, but that is not the case - _this happens upon the first completion/submit_.

Last night I saw this happening on my daughter's account as well so I'm assuming that it's a bug. We're both using Chrome browser.

![codcom05](https://cloud.githubusercontent.com/assets/19597966/20969550/7b6b1058-bc57-11e6-91a2-266a63f0dd01.JPG)

Update:

It just did it again. I just submitted Clash of Clones for the first time and this is what I see.....

![codcom06](https://cloud.githubusercontent.com/assets/19597966/20969576/8fabd552-bc57-11e6-9472-23297b1163b3.JPG)

I don't care about the gems so much (I have plenty and don't really use them at the moment) but I'd really like to be sure that my XP are going up and there doesn't seem to be any way to check this.

**Comment by sderickson** [comment]
Thanks for the detailed report! Couple questions: 

* Is this happening every time or from time to time? If from time to time, 
* Do the icons animate when the xp and gems fail to increase? Normally the icons animate.

I'm thinking either the animation is breaking somehow, or (more likely) the game thinks you earned the achievements previously and so is skipping the animation. The XP and Gems and items are being earned either way. I also checked your account and already earned the achievement for Clash of Clones about five hours ago... so in line with when you submitted this issue.

**Comment by MunkeyShynes** [comment]
It appears to be happening a lot.  Not sure if every single time but I’m sure it’s happening a lot.  When my daughter submitted a level last night it happened again and she asked why she didn’t get any gems.  That’s when I decided to inquire about it.  There is no animation.  What you see in the screen shots I posted is all there is.

Thanks.

**Comment by sderickson** [comment]
@MunkeyShynes looks like this this issue has resolved?

**Comment by MunkeyShynes** [comment]
Yes, I closed it.  Apparently, the simulations were turned off on Friday to lighten the load on the server for the Hour Of Code.  I'm all for that and have no problem with it - I'm all for the Hour of Code thing.  I just would have liked someone to say something to inform me that it was the reason.  I wasted a lot of time making sure that there was no issue on my end.  :/

**Comment by MunkeyShynes** [comment]
just realized that I closed the wrong issue.  Sorry about that.  I'll reopen it if I see the no animations again.  The last few levels that I finished, the animations worked fine.
