### ISSUE TITLE
what is the "code: 'NO_BOWER_JSON'"

### ISSUE THREAD

**Issue by zorelu** [codecombat/codecombat#4095]
#i have build codecombat on ubuntu16.04,but want i run it ,it fail but i don't what the waring with it ,the fail log jiust like this
 `Got 542 coffee files and 262 jade files (bundled 125 of them together).
14 Dec 02:23:14 - error: { [Error: Component must have "/home/zorelu/codecombat/bower_components/jquery/bower.json"] code: 'NO_BOWER_JSON' }
14 Dec 02:23:15 - info: custom server started, initializing watcher
14 Dec 02:23:15 - [nodemon] v1.6.1
14 Dec 02:23:15 - [nodemon] reading config /home/zorelu/codecombat/nodemon.json
14 Dec 02:23:16 - [nodemon] to restart at any time, enter `rs`
14 Dec 02:23:16 - [nodemon] ignoring: /home/zorelu/codecombat/.git/**/* /home/zorelu/codecombat/node_modules/**/* bower_components .sass-cache
14 Dec 02:23:16 - [nodemon] watching: server_config.js server_setup.coffee /home/zorelu/codecombat/app/schemas/**/* /home/zorelu/codecombat/server/**/*
14 Dec 02:23:16 - [nodemon] watching extensions: js,coffee
14 Dec 02:23:16 - [nodemon] starting `node .`
'14 Dec 02:23:16 - [nodemon] child pid: 6365
WARNING: You are using Node v4. Please upgrade to Node v5. Your version: 4.2.6
14 Dec 02:23:16 - [nodemon] watching 207 files
module.js:328
    throw err;
Error: Cannot find module '../../bower_components/treema/treema-utils.js'
  at Function.Module._resolveFilename (module.js:326:15)
`
wnaht can i do ,pelase get me some help.

**Comment by nwinter** [comment]
Try using Node 6 instead of Node 4, then reinstall all your node modules (delete `node_modules` and then rerun `npm install`).
