### ISSUE TITLE
hazard.triggered property is protected (should be public)

### ISSUE THREAD

**Issue by vn971** [codecombat/codecombat#4107]
See subject.
The `hazard.triggered` property might be useful in real games, but currently it's "protected". Maybe make it public?

**Comment by liljaminkev** [comment]
Hello Where is this piece located at?

**Comment by vn971** [comment]
This goes to project developers (@nwinter ?). I only know where it can be seen on the website.

Then again, it might be relatively easy to find it in the source: https://github.com/codecombat/codecombat/search?utf8=%E2%9C%93&q=triggered I don't know.

**Comment by liljaminkev** [comment]
Thanks I'm currently exploring the code base.

**Comment by nwinter** [comment]
It would be in the level editor, in the Components tab, in the Components for Thangs that are Hazards (like `combat.Mine`). See this screenshot for where to look.

<img width="986" alt="screenshot 2017-01-13 12 41 14" src="https://cloud.githubusercontent.com/assets/99704/21944969/a25ff54a-d98d-11e6-8d09-1d6d43a6f18f.png">

**Comment by liljaminkev** [comment]
@nwinter So am I changing something in the source code is this within the level only?

**Comment by nwinter** [comment]
It will apply to every level that uses the `combat.Mine` Component.

**Comment by Bryukh** [comment]
Added as a property (get/set).

**Comment by vn971** [comment]
@Bryukh  Wait, what do you mean "get/set"? I shouldn't be able to call `set` on the "treggered" state of the hazard. Otherwise I can just disable them and stepping above them freely, or re-enabling a hazard so it activates twice.
?

**Comment by Bryukh** [comment]
@vn971 Don't worry about it. get/set means that I used getter and setter for the existed method to convert it to the property.

**Comment by vn971** [comment]
@Bryukh OK, that clarifies, thank you!

**Comment by vn971** [comment]
I'm trying to use `hazard.triggered` on "Multiplayer Treasure Grove" now, but it doesn't work. It says `TypeError: Can't read protected property: triggered`.
