### ISSUE TITLE
i run codecombat fail but where is the problem is？

### ISSUE THREAD

**Issue by zorelu** [codecombat/codecombat#4112]
i install codecombat in ubnutu 14.04 but when i step to run it ,it  warning the code just like this
 `npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! codecombat@ start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codecombat@ start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the codecombat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codecombat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls codecombat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/codecombat/npm-debug.log``

now i unkonw thewaring is in npm or codecombat  pack ，what can i run it 
please help。

**Comment by nwinter** [comment]
Does it work if you do it with node version 6?

**Comment by zorelu** [comment]
i do it with node 7,but if it  only work on version 6 what can i do.

**Comment by nwinter** [comment]
Uninstall node 7 and install node 6. Or use [nvm](https://github.com/creationix/nvm) to manage multiple node versions at once.
