### ISSUE TITLE
Stuck on 2º campain

### ISSUE THREAD

**Issue by zoiobnu** [codecombat/codecombat#4116]
I installed and use tutorial from wiki for linux .

I have Ubuntu 16.04 , using Node v5 .

But i have this error.

![image](https://cloud.githubusercontent.com/assets/4562546/21531982/337a0db6-cd33-11e6-87fa-01a241877bc3.png)

I'm using localhost

**Comment by nwinter** [comment]
The database dump just doesn't include those levels–it only has a handful for testing purposes. If you need more levels for a specific purpose, let's chat about it [in the Slack](https://coco-slack-invite.herokuapp.com/)?
