### ISSUE TITLE
hero.canCast Interrupts Actions for certain spells

### ISSUE THREAD

**Issue by taylerzy** [codecombat/codecombat#4119]
When hero.canCast("grow"); or hero.canCast("grow", target); is executed, it interrupts all other actions. I'm trying this on a warrior that obviously can't cast grow, so it should just ignore the command entirely. Same thing happens with shrink.

canCast doesn't seem to be working for sacrifice either, but in a different way. The following code gives the error "Unhandled error: TypeError: Cannot read property 'cooldown' of undefined'
`if(hero.canCast("sacrifice")) {
        var friend = hero.findNearest(hero.findFriends());
        if(friend) {
            hero.cast("sacrifice", friend);
        }
    }`

**Comment by Zerrien** [comment]
Hi, can you provide a minimized code-snippet of this, and what hero/gear you are using.

I wasn't able to reproduce.

**Comment by Zerrien** [comment]
Also, can you please split out the canCast + Sacrifice one into it's own issue?

**Comment by taylerzy** [comment]
I tried it again and found that my friend variable sometimes held objects that can't be grown/shrunk/sacrificed, such as the flowers in Cloudrip Siege. When sacrifice is cast on a flower, it interrupts the rest of the code, but that's not really a problem as it's not an intended action anyway.

**Comment by Zerrien** [comment]
If you want to create an issue for that, I think that is a good issue.

It should at least give you a verbal warning (hero saying something and cancelling the action) or a full blown error (cannot use sacrifice on units of type <x> or what have you.)

If you can create the smallest example of code and a specific level it occurs on, we can attempt to fix it in the future.
