### ISSUE TITLE
Automatic language selection not working

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#4121]
When I access the site without being logged in, my native language is no longer chosen by default and "English (US)" is the chosen one instead.

**Comment by nwinter** [comment]
Can you check your Accept-Language headers [at this site](http://www.reliply.org/tools/requestheaders.php) and let me know what they are? (Example: `en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4`)

**Comment by Imperadeiro98** [comment]
Mine are `pt-PT,pt;q=0.8,en-US;q=0.6,en;q=0.4`.

**Comment by nwinter** [comment]
Fixed in 049dc59, can't believe we didn't catch it earlier–thanks for noticing!
