### ISSUE TITLE
Code Interrupts w/ No Warning When Casting Spell on Immovable Allies

### ISSUE THREAD

**Issue by taylerzy** [codecombat/codecombat#4135]
When casting spells like sacrifice on immovable allies, such as an Arrow Tower or Flower West, the hero gets stuck trying to cast the spell and the rest of the code isn't ran.

Replay: https://codecombat.com/play/level/cloudrip-siege?session=5831d88217020f1f002e858b&observing=true

Code:
```var friend = hero.findNearest(hero.findFriends());
hero.say("Casting sacrifice on " + friend);
hero.cast("sacrifice", friend);

// code past this point won't run
hero.say("This should run, or a warning should be issued");
```

The exact same thing happens with seemingly any other ally spell, such as dispel, grow, regen, or shrink.

**Comment by Bryukh** [comment]
Fixed.
