### ISSUE TITLE
Some levels don't show i18nCoverage even when fully translated

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#4142]
See https://codecombat.com/i18n/level/backwoods-ambush for Russian. Every field is translated, but `i18nCoverage` is `[]` and the i18n page shows "Specifically Covered: No".

See also #3528 and #2925 for different bugs with i18n coverage reporting. *edit: and #3030*

**Comment by Bryukh** [comment]
The same for campaigns https://direct.codecombat.com/i18n/campaign/campaign-game-dev-1 (for example in Russian)

**Comment by Imperadeiro98** [comment]
@Bryukh, is your issue the same as [this one](https://github.com/codecombat/codecombat/issues/3030)?

**Comment by Bryukh** [comment]
@Imperadeiro98 Yep, thank you for the reference.
