### ISSUE TITLE
Error in 'If-stravaganza' for Lua language

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#4152]
Code:
![1](https://cloud.githubusercontent.com/assets/6980488/22174442/deff614e-dfd6-11e6-8524-33a87ce7cfab.png)

Error:
![2](https://cloud.githubusercontent.com/assets/6980488/22174443/e24e0300-dfd6-11e6-909d-bfc99e3acd9c.png)

**Comment by reesylou** [comment]
Patch sumbitted in level editor

**Comment by nwinter** [comment]
Accepted, thanks!
