### ISSUE TITLE
Tomb Ring required to Play Boss Star Levels (Wizards Only)

### ISSUE THREAD

**Issue by Shawnmm** [codecombat/codecombat#4157]
Hello,
# Issue
## Short Version
Requiring wizards both purchase and equip the Tomb Ring to play levels which only use the Boss Star.

## Long Version
When I went to start the mission called Mountain Mercenaries on Pender. The level highlighted and required I buy the Tomb Ring (which I did not own) and equip the Tomb Ring. Refusing to let me play the level if I did not. Despite having the Boss Star equipped.

After struggling with the level not working for a while, and wondering why I needed the Tomb Ring, I switched to a warrior who cannot equip the ring. This allowed me to play the level without the ring. 
However if I return to playing any mage, it requires the ring be re-equipped. This issue continues into the next level. I am not sure if it persists further, as I have not yet made it that far. 

I should also note that despite the level before called Cloudrip Commander, making use of the Boss Star. I was able to play it as a mage without the Tomb Ring. Thank you for your time.

## Language
Python

## Level it Began
Mountain Mercenaries

## Levels it Continues Into
Timber Guard
And possibly further

# Photos

### Without the Tomb Ring
![mage2](https://cloud.githubusercontent.com/assets/3301216/22282882/f55ac48c-e293-11e6-86d8-341e303fcab4.PNG)

### With the Tomb Ring
![mage1](https://cloud.githubusercontent.com/assets/3301216/22282889/01cd2d90-e294-11e6-9f93-8b3d702e4068.PNG)

### Without the Tomb Ring Requirement/ Warrior
![mage3](https://cloud.githubusercontent.com/assets/3301216/22282928/2c45f3cc-e294-11e6-9829-d468c1b7d539.PNG)

## Operating System
Windows 10 Home, Version 1607, OS Build 14393.693

## Browsers Effected
First encountered in Chrome Version Version 55.0.2883.87, but continues in Firefox Version 48.0.2 as well.

## Console Errors/ Warnings
I apologize for the long list. I could not figure out how to enclose segments inside of expandable sections that only show if one presses a button. Like one does with spoiler tags sometimes. Despite looking at the markdown page.

### Chrome Version Version 55.0.2883.87 m
https://codecombat.com/db/poll/586f48a15356e62100a108c6/next Failed to load resource: the server responded with a status of 404 ()

three.min.js:524 THREE.WebGLRenderer 71
114mountain:1 [.Offscreen-For-WebGL-04AA7868]RENDER WARNING: there is no texture bound to the unit 0

CocoModel.coffee:104 Populated defaults for Level Timber Guard in 16ms
dexecure-c167a5675c.js:1 Service Worker termination by a timeout timer was canceled because DevTools is attached.

#### Javascript:
unreachable code after return statement[Learn More]play:1226
unreachable code after return statement[Learn More]app.js:2266
unreachable code after return statement[Learn More]play:470
unreachable code after return statement[Learn More]play:1339
unreachable code after return statement[Learn More]app.js:1952
unreachable code after return statement[Learn More]app.js:1956
unreachable code after return statement[Learn More]play:1805
unreachable code after return statement[Learn More]play:3102
unreachable code after return statement[Learn More]play:3260
unreachable code after return statement[Learn More]play:2773

#### CSS
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:13930
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:14013
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:14504
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:14587
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:15110
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:15193
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:15631
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:15651
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:20688
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:20771
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:21259
Error in parsing value for 'background'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:21342
Unknown property 'user-select'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:23563
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:25341
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:25361
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:25830
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:25850
Error in parsing value for 'box-shadow'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:28487
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:37344
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:37364
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:40108
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:40403
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:41058
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:41078
Unknown property 'background-position-x'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:43088
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:44498
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:44518
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:47348
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:47368
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:50623
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:50643
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:50869
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:50889
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:54699
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:54960
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:55865
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:55885
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:56122
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:56142
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:58121
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:58222
Unknown property 'appearance'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:61008
Unknown pseudo-class or pseudo-element '-ms-expand'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:61083
Unknown property 'appearance'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:61620
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:70485
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:70665
Unknown pseudo-class or pseudo-element 'placeholder'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:70756
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:72835
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:72873
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:72911
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:73795
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:73833
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:73871
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:74452
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:74472
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:74763
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:74878
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:75328
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:75366
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:75404
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:76445
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:76465
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:76935
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:77341
Unknown pseudo-class or pseudo-element 'placeholder'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:77545
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:77830
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:78040
Unknown pseudo-class or pseudo-element 'placeholder'.  Ruleset ignored due to bad selector.inner-fa7364dfe29b344403620736e594009b.css:1:78146
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:78517
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:78555
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:78593
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:79352
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:79390
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:79428
Expected end of value but found 'transform'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:81891
Expected end of value but found 'transform'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:82535
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:82666
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:82686
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:91357
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:91395
Expected end of value but found 'opacity'.  Error in parsing value for 'transition-property'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:91433
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:92539
Error in parsing value for 'background-image'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:92628
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:93426
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:93446
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:93676
Error in parsing value for 'display'.  Declaration dropped.inner-fa7364dfe29b344403620736e594009b.css:1:93696
Expected media feature name but found '-webkit-min-device-pixel-ratio'.inner-fa7364dfe29b344403620736e594009b.css:1:95070
Expected media feature name but found 'min-device-pixel-ratio'.inner-fa7364dfe29b344403620736e594009b.css:1:95141

**Comment by Catsync** [comment]
Hello! I think this issue should be fixed. Let me know if you're still seeing it.

**Comment by Shawnmm** [comment]
Thank you very much. The error no longer occurs, impressive work.
