### ISSUE TITLE
JavaScript beautify button causes autocomplete to pop up

### ISSUE THREAD

**Issue by themaka** [codecombat/codecombat#4160]
Here's the bug report:
_Whenever I press the magnet icon to clean my code, it brings up a pop up menu hiding my code. I can't see the switch between the unclean and clean code. This gets in the way of learning what good formatting looks like. This is really annoying and the popup serves no purpose - its a bug._ 

<img width="1440" alt="screenshot 2017-01-24 23 33 44" src="https://cloud.githubusercontent.com/assets/3516905/22356021/4e4ad456-e3fc-11e6-8991-aee3098e98c4.png">

The user is using:
_MacOS 10.12.3 (16D32)
Chrome Version 55.0.2883.95 (64-bit)
The bug also shows up on Opera Version 42.0.2393.517_

**Comment by glassjoseph** [comment]
Confirmed, the autocomplete popup obscures the switch in code and makes it impossible to see the changes as they occur.

Confirmed on: 
_MacOS 10.12.5 (16F73)
Chome Version 59.0.3071.115 (Official Build) (64-bit)
Firefox Version 46.0.1_
