### ISSUE TITLE
Level 'Buddy's Name A' can’t  be started because user can’t choose pet 'Cougar' from inventory (Javascript)

### ISSUE THREAD

**Issue by Aleks386** [codecombat/codecombat#4183]
**Steps to reproduce**
1. Open codecombat as logged in user;
2. Choose JavaScript language;
3. Open level 58 (Buddy's Name A) in 'Backwoods Forest';
4. Buy 'Cougar' pet (if you by it before go to step 5.);
5. Try to choose pet 'Cougar'

**Actual result**
User can`t choose pet "Cougar"
Message 'restricted in this level' displyed in pet description
![screenshot](https://cloud.githubusercontent.com/assets/18620431/22891071/dc58864e-f216-11e6-8c3b-743dd700aa92.png)

**Expected Resut**
User can choose pet "Cougar" and level will start

**Additional information**
Browser : Chrome 56.0.2924.87 (64-bit)
Operation system: Windows 10

**Comment by Bryukh** [comment]
Thanks. Fixed.
