### ISSUE TITLE
Linux setup doesn't work

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#4226]
Reported user issue:

I follow the steps in
https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Linux and
dont works. I search some help on community forum, but dont help me...
I'm using a Ubuntu droplet in DigitalOcean.

   Can you update these steps? If need, i can send a IP/login/pass to
you try to install and update these steps during the process.

**Comment by nwinter** [comment]
More details: first error is:

```
when i run
sudo service mongod start

shows
failed to start mongod.service: unit mongod.service not found
```

**Comment by DeveloperAlan** [comment]
Try adding more memory to your Linux box

**Comment by duk3luk3** [comment]
@differentmatt What Ubuntu version? It worked without any troubles for me on Ubuntu 16.04 just following the official ubuntu setup instructions for mongo (https://docs.mongodb.com/master/tutorial/install-mongodb-on-ubuntu/) and node (https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).

**Comment by ogennadi** [comment]
See this article (https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04) for how to fix the "failed to start mongod.service" problem on Ubuntu 16.04.

> As of publication time, the official Ubuntu 16.04 MongoDB packages have not yet been updated to use the new systemd init system which is enabled by default on Ubuntu 16.04. Running MongoDB using those packages on a clean Ubuntu 16.04 server involves following an additional step to configure MongoDB as a systemd service that will automatically start on boot.
