### ISSUE TITLE
help! git not found

### ISSUE THREAD

**Issue by lRHyNol** [codecombat/codecombat#4238]
PS C:\Users\jon\Documents\Github\codecombat> npm install
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls
 graceful-fs' to find it in the tree.
npm WARN deprecated pug@0.1.0: Please update to the latest version of pug, at time of writing that is pug@2.0.0-alpha6
npm WARN deprecated node-force-domain@0.1.0: Use forcedomain instead.
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git://github.com/michaelficarra/CoffeeScriptRedux.git resetting remote C:\Users\jon\AppData\Roaming\npm-cache\_git-remotes\git-github-com-michaelficar
ra-CoffeeScriptRedux-git-2ca330a5 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git://github.com/codecombat/cashew.git resetting remote C:\Users\jon\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codecombat-cashew-git-1ad0d
587 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git://github.com/codecombat/skulpty.git resetting remote C:\Users\jon\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codecombat-skulpty-git-08a
8c545 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\jon\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/codecombat/cashew.git C:\Users\jon\AppData\Roaming\npm
-cache\_git-remotes\git-github-com-codecombat-cashew-git-1ad0d587: undefined
npm ERR! git clone --template=C:\Users\jon\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/codecombat/cashew.git C:\Users\jon\AppData\Roaming\npm
-cache\_git-remotes\git-github-com-codecombat-cashew-git-1ad0d587: undefined
npm ERR! git clone --template=C:\Users\jon\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/michaelficarra/CoffeeScriptRedux.git C:\Users\jon\AppD
ata\Roaming\npm-cache\_git-remotes\git-github-com-michaelficarra-CoffeeScriptRedux-git-2ca330a5: undefined
npm ERR! git clone --template=C:\Users\jon\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/michaelficarra/CoffeeScriptRedux.git C:\Users\jon\AppD
ata\Roaming\npm-cache\_git-remotes\git-github-com-michaelficarra-CoffeeScriptRedux-git-2ca330a5: undefined
npm ERR! git clone --template=C:\Users\jon\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/codecombat/skulpty.git C:\Users\jon\AppData\Roaming\np
m-cache\_git-remotes\git-github-com-codecombat-skulpty-git-08a8c545: undefined
npm ERR! git clone --template=C:\Users\jon\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/codecombat/skulpty.git C:\Users\jon\AppData\Roaming\np
m-cache\_git-remotes\git-github-com-codecombat-skulpty-git-08a8c545: undefined
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jon\Documents\Github\codecombat\npm-debug.log

**Comment by mattj256** [comment]
> npm ERR! Failed using git.
> npm ERR! This is most likely not a problem with npm itself.
> npm ERR! Please check if you have git installed and in your PATH.
It sounds like you either don't have git installed or NPM is having trouble finding git.

Are you able to run git locally?  (Type "git" at the command line.)  You might have to install git on your local machine.  I don't know much about NPM, maybe there's an easier way.
