### ISSUE TITLE
Campaigns are shown as non translated

### ISSUE THREAD

**Issue by Bryukh** [codecombat/codecombat#4260]
In the diplomat interface, I see some campaigns as not "Covered"
![image](https://cloud.githubusercontent.com/assets/343120/24289884/10230d96-1094-11e7-857c-3cb5c12342eb.png)

But they are translated and covered 
![image](https://cloud.githubusercontent.com/assets/343120/24289903/1dfceaa4-1094-11e7-8568-7b7f75d11563.png)

I tried to update translations, however, it didn't fix the coverage.

**Comment by Imperadeiro98** [comment]
Related: #3030

**Comment by sderickson** [comment]
Updated the translation data. Should be good, now!

<img width="754" alt="screenshot 2017-04-20 17 13 02" src="https://cloud.githubusercontent.com/assets/204723/25257400/a28e55ec-25ec-11e7-9aa2-7bc2f2d8039c.png">

**Comment by Bryukh** [comment]
@sderickson Looks like some of them has a problem still
https://direct.codecombat.com/i18n/campaign/auditions
The coverage is put correctly for that, but it's shown as non-covered in the diplomat interface.

**Comment by joca16** [comment]
The same seems to apply to some components, i. e. 
https://direct.codecombat.com/i18n/component/castswindstorm 
for de-DE.
