### ISSUE TITLE
Levels Freezing up.  Must refresh page to continue.

### ISSUE THREAD

**Issue by MunkeyShynes** [codecombat/codecombat#4264]
There is something seriously wrong with the levels.  I've noticed this problem on three different machines at two different locations.  My daughter (also a subscriber) has been having to refresh the screen when she tries to run a level after writing her code (daughter's username is phoreal).  I first thought that there was something wrong with the machine that we were using, but then noticed it on another machine at home.  Then we tried it on my login at a different location and it did the same thing.  What happens is that while writing the code, the screen with the characters/animations seems to get a foggy haze and then the movement is very jittery and slow when trying to run code.  After refreshing the tab everything runs fine for a few minutes and then it happens again - without exception and every time on every level.  I don't know exactly what's causing it but went through the first machine where this originally occurred and thoroughly cleaned the OS, shut down all unnecessary processes and updated browser, cleared cache, etc.  The machine is an i5 quad core with 8 gigs of RAM so power shouldn't be an issue. After the cleaning, it did it again and does it every time.  The second machine we did it on has an i7 processor with 16 gigs of RAM.  And then it did it again using my login with a Core 2 Duo and 4 gigs of RAM and a really good 2 gig DDR3 video card at a different location.  I believe that due to the number of machines we've seen this and the fact that it happens at two different locations that this is pointing back to  a problem at your end.  It isn't stopping us from using the site but it is very annoying to constantly have to refresh the page to run the code.  This is something that just started happening a few weeks ago.  It didn't used to happen.  I hope I've given you enough information to work with but if you have any further questions please let me know.  I know y'all are busy and hate to add this to your plate but we thought it would clear up eventually and it hasn't.  Thank you for all you guys do.

**Comment by themaka** [comment]
Hi Munkey,

Can you tell us a little more?

Which web browser and what version are you using? What OS and version?

It sounds like you're working on the level and suddenly the game window slows down. Does this happen on it's own, or when you click Run?

Can you give me a specific level that does this the most so I can do additional testing?

Maka

**Comment by MunkeyShynes** [comment]
Chrome browser on all machines.  Haven't tried a different one because Chrome seems to work the best for coco.  Browsers have been updated to latest version on all machines.  Daughter is currently in the Backwoods Forest domain and it has happened on every level she's done.  It happens on it's own after several minutes when writing code.  When the animated area gets a foggy haze look you can tell it's happened, even before the run button is clicked.  It doesn't affect typing in the code area but after the Run button is clicked, the animations occur albeit very, very slowly - like one movement every two seconds - and the haze doesn't go away until the page is refreshed.  After refreshing, everything runs fine until the haze returns.

I'm currently in Cloudrip Mountain but a new level appeared in backwoods forest on my profile and I went to do it and it happened to me as well on a third machine and that's when I suspected it was something on your end.  I believe the level was Return to Thornbush Farm B on my profile.  I haven't had much time to do levels on my profile lately so I've mostly seen it when working together on her profile but it's very consistent.  I'll do a level with her tonight and post a screen shot of the foggy haze when it occurs.

**Comment by nwinter** [comment]
Am I correct in guessing that 1) CPU/RAM usage doesn't go up substantially from normal (high) CodeCombat usage right as this problem occurs, and 2) the game is appearing to run at exactly either 1 or 2 frames per second?

Would love any sort of screencast or video recording of the problem to help confirm my suspicion on what this is.

**Comment by MunkeyShynes** [comment]
![saltedearth](https://cloud.githubusercontent.com/assets/19597966/24481186/adc9a5ca-14b6-11e7-90ac-d849f0b7d507.JPG)
 this just happened again a couple of minutes ago on daughter's profile.  The haze occurred while writing the code and then it ran at about 1 frame per second.

I don't have an application for a screencast but I'll work on that tonight when I get back from the gym.

**Comment by Bryukh** [comment]
@nwinter I have this problem too sometimes in play screen and in the level editor. Usually, it happens when I don't touch a page some time. Everything becomes grey (as in the end of the level) and then works weird. Reload page usually helps.

**Comment by nwinter** [comment]
If you open the JS console when it's in this state, does entering `application.idleTracker.isAway` result in `true` or `false`? Also, what about `currentView.surface.ended` and `createjs.Ticker.getFPS()` right after you hit play and it's rerunning the world? (So not when the level has finished and playback scrubber is at the end of the track, but when it's still going.)

**Comment by Bryukh** [comment]
Two days without this bug. I will try to check as you said if I meet it again.

**Comment by Bryukh** [comment]
```
> application.idleTracker.isAway
< true
```
"right after you hit play"
```
> currentView.surface.ended
< false
> createjs.Ticker.getFPS()
< 1
```
Looks it like this

![slow2](https://cloud.githubusercontent.com/assets/343120/24741562/235423b2-1aaf-11e7-8ca2-8096191ed38b.gif)

More data from the console:
```
Angel.coffee:58 |Perkele's Archer| Generated random seed 2913896600 of type submissionCount from sessionIDs 55fe596fb9c84c8605390206 submissionCount 0
Angel.coffee:58 |Perkele's Archer| And it was so: (2.009ms per frame, 225 frames)
Simulation   : 452ms 
Serialization: 6ms
Delivery     : 0ms
FPS          : 995.6
world.coffee:600 First changed frame is 30 with hash 1715908093.3271105 compared to 1715908089.104032
```

**Comment by Zerrien** [comment]
Putting in my vote on this, I'm experiencing this now.
