### ISSUE TITLE
[bug] Javascript Saven Road

### ISSUE THREAD

**Issue by eixan** [codecombat/codecombat#4273]
Error Message: Fix your code. Line 11:attack's agrument target should have type unit, but got function. Target a unit
Page in question:https://codecombat.com/play/level/sarven-road
My browser: Chrome  57.0.2987.133 (64-bit)
OS:windows 10 64bit
My code:
while(true) {
    // If there's an enemy, attack.
    var enemy = hero.findNearestEnemy;
    var x = hero.pos.x;
    var y = hero.pos.y;
    
    if(enemy) {
        hero.attack(enemy);
    }
    else {
        x=x+5;
        y=x+5;
        hero.moveXY(x, y);
    }
    // Else, keep moving up and to the right. 
    
}

**Comment by nwinter** [comment]
`var enemy = hero.findNearestEnemy;`
should be:
`var enemy = hero.findNearestEnemy();`

With `()` it doesn't call the function.

**Comment by eixan** [comment]
thanks
