### ISSUE TITLE
Interested in porting to JavaScript?

### ISSUE THREAD

**Issue by alangpierce** [codecombat/codecombat#4276]
Hi there, I'm the main person working on [decaffeinate](https://github.com/decaffeinate/decaffeinate) these days. It's a project that converts CoffeeScript to readable modern JavaScript to help people who want to migrate their codebase away from CoffeeScript. I've been using CodeCombat as a test case, and I recently got it to a point where all files convert and all tests pass. I have a JS fork of CodeCombat on GitHub that's automatically regenerated every day (a script pulls the latest code from this repo, then runs decaffeinate on all files, then patches the build system to use babel, then runs all tests):
https://github.com/decaffeinate-examples/codecombat

Obviously fine if you prefer CoffeeScript or would rather not go through a big codebase migration, but if you are interested in using decaffeinate to migrate to JS, I'd be happy to provide advice on configuration or strategy or anything else. Just calling that out in case you're interested.

P.S. Thanks for the awesome project, and for making it open source.

**Comment by sderickson** [comment]
Hi @alangpierce! Thank you for working on your tool with our project and offering to help. We've actually been floating around the idea of migrating from CS to JS for a variety of reasons. We're not completely set on the idea, but we're interested in trying out using your tool and working with you on making the switch to help with the decaf project.

We're thinking it would make the most sense to decaffeinate the project piecemeal, especially on pieces as we work on them, making sure they're well tested before switching. What are your thoughts on migration strategies?

**Comment by alangpierce** [comment]
Cool. Yeah, I understand it's a pretty big decision, and can be quite a bit of work for something that doesn't make users any happier (at least not directly). Also, while the decaffeinate output is generally much nicer-looking JS than the CoffeeScript output, it's still lacking in various places and usually requires at least a little human intervention to make the code look nice.

Generally, your strategy makes sense to me. I wrote up some thoughts on how to approach a codebase conversion a while back, which you may find useful.
https://github.com/decaffeinate/decaffeinate/blob/master/docs/conversion-guide.md#converting-a-whole-project

At my company, it has gone something like this:
* We got the tooling figured out and wrote up a style guide with examples of how CS idioms map JS idioms, etc.
* We set up tooling for a mixed JS/CS codebase and started writing new files in JS.
* When possible or when we were going to work with code quite a bit, we tried converting files to JS by hand. This ended up being very slow and error prone (e.g. one 500-line file took 4 engineer-days to convert and review and introduced two bugs). That was one of the reasons I got involved in the decaffeinate project in the first place.
* After fixing a bunch of decaffeinate issues, things are now in a state where we try to run decaffeinate on individual files or whole folders before we do significant work with them. Typically, we try to fix lint and any other style issues for every file we convert.
* Almost all active work is in JS now, and all tests are in JS, but there are still ~150k lines of production CoffeeScript left that would be nice to convert. Having to verify the conversion and fix lint issues in every file would take a very long time and leaves a lot of room for human error, so I've been working on making decaffeinate stable and high-quality enough that we can feel safe running it in large batches without needing to verify the results and without bothering to fix style issues (still maybe 10k lines at a time, spot-checking the output for glaring issues and carefully watching the error logs at each step). Basically I want it to be like babel where you can run it on a large codebase and expect zero bugs, which is why I've been working through decaffeinate bugs in various codebases including yours. At that point, style issues will be tech debt that we'll clean up when we can, although I'm also trying to automate as many style fixes as possible.

**Comment by sderickson** [comment]
* The tooling to compare CS and JS idioms sounds really useful, don't suppose that could be shared? Or know of any other, similar resources offhand?
* Ah, didn't notice that before, that it sets up code in ES6. That makes sense, though. The way it's set up now, how much work, if any, do you think there is left to modify the build to handle ES6?

Sounds like a very good system for gradually making the switch!

**Comment by alangpierce** [comment]
> The tooling to compare CS and JS idioms sounds really useful, don't suppose that could be shared?

By "We got the tooling figured out", I just mean that we set up babel, eslint, etc; the style guide with idioms was just an internal document. Most of it isn't super-useful in general, e.g. examples of using ES6 with React.

A few things it mentioned along the lines of "here's what to know about ES6 if you're used to CoffeeScript":
* `a?` becomes `a == null`.
* `a?.b` becomes `a && a.b`.
* Use `===` for equality.
* Use `.map` instead of `for` expressions.
* Remember to use `break` within `switch.

It also references some external resources on ES6 in general:
http://exploringjs.com/es6/
https://github.com/DrkSephy/es6-cheatsheet

> Ah, didn't notice that before, that it sets up code in ES6.

Yep! One of the nice things about decaffeinate is it converts destructuring to destructuring, arrow functions to arrow functions, classes to classes, etc. And in general it's focused on producing idiomatic ES6 code as much as it can. Some things (like `a?.b?.c?.d`) don't translate super-well, and some things (like default parameters) can't be used because they behave slightly differently, but generally it does a pretty good job of generating code like you'd write it in modern JavaScript.

> The way it's set up now, how much work, if any, do you think there is left to modify the build to handle ES6?

I already spent some time getting the codecombat build system working with ES6 so I could run tests. It's the "Add dependencies and config to prepare for decaffeinate" and "Modify the build to work with JavaScript" commits here:
https://github.com/decaffeinate-examples/codecombat/commits/decaffeinate

although it's a bit hacky and mostly focused on just getting the tests running. The main pain point was getting things to work with Brunch; it looks like you should upgrade Brunch so you can use the latest version of babel-brunch instead of having to pin to an old version. And I imagine you'd want to put more serious thought into the babel config, build system details, eslint config, etc.

**Comment by ankitprahladsoni** [comment]
Are there any plans for this migration?

**Comment by nwinter** [comment]
We did end up using decaffeinate to put everything into JavaScript!
