### ISSUE TITLE
thunderhooves bug

### ISSUE THREAD

**Issue by eixan** [codecombat/codecombat#4277]
OS:windows 10
browser: chrome Version 56.0.2924.87 (64-bit)

my code:while(true) {
    var yack = hero.findNearestEnemy();
    if (yack) {
        // A yak is above you if it's y is greater than your y.
        // If the yak is above you, build a fence 10m below it.
        
         if(enemy.pos.y > hero.pos.y){
            y = yack.pos.y - 10;
            x = yack.pos.x;
            hero.buildXY("fence", x, y);
        }
        
        else if(enemy.pos.y < hero.pos.y){
            var y = yack.pos.y + 10;
            var x = yack.pos.x;       
            hero.buildXY("fence", x, y);            
        
        }
       
        else {
        
            x = hero.pos.x + 10;
            y = hero.pos.y;
            hero.moveXY(x, y);
        
        }
    }
}

**Comment by Bryukh** [comment]
@eixan could you tell more about the bug? Which error did you get? What the problem with this level and code?

**Comment by eixan** [comment]
the character doesn't move. I opened the developer console and I don't see any error messages in red. The game doesn't give me any errors. The carrot is such on: var yack = hero.findNearestEnemy();


Here's my code again properly formatted as it is on my page:
```

while(true) {
    var yack = hero.findNearestEnemy();
    if (yack) {
        // A yak is above you if it's y is greater than your y.
        // If the yak is above you, build a fence 10m below it.
        
         if(enemy.pos.y > hero.pos.y){
            y = yack.pos.y - 10;
            x = yack.pos.x;
            hero.buildXY("fence", x, y);
        }
        
        else if(enemy.pos.y < hero.pos.y){
            var y = yack.pos.y + 10;
            var x = yack.pos.x;       
            hero.buildXY("fence", x, y);            
        
        }
       
        else {
        
            var x = hero.pos.x + 10;
            var y = hero.pos.y;
            hero.moveXY(x, y);
        
        }
    }
}

```

**Comment by Bryukh** [comment]
It's not a bug. It's a mistake in your code. Looks careful for the last 'else' and which "if" it closes.
