### ISSUE TITLE
[BR-Localization] Home-About page has multiple instances that need to be localized.

### ISSUE THREAD

**Issue by cwmaia** [codecombat/codecombat#4299]
When the user asceses the ABOUT on the BR version of the site, we see it has only been partially localized.
The following places need to be changed.

Under Press-Contact. It is not necessary on the BR version of the site do display direct links to downloadable content related to Code Combat.
Under Location. We should have a location in Brazil to server as our HQ placeholder, for sales purposes.

![homeaboutmission1](https://cloud.githubusercontent.com/assets/1056740/25247392/0ffe8bf8-25e1-11e7-8efb-bce2e15f08fa.png)
![homeaboutmission2](https://cloud.githubusercontent.com/assets/1056740/25247387/0fed6df0-25e1-11e7-9aef-9b38a1c3bec6.png)
![homeaboutcommunity](https://cloud.githubusercontent.com/assets/1056740/25247389/0fee2ee8-25e1-11e7-917d-6409abec1180.png)
![homeaboutstory](https://cloud.githubusercontent.com/assets/1056740/25247388/0fede230-25e1-11e7-9deb-61d5885e1bf4.png)
![homeaboutstory2](https://cloud.githubusercontent.com/assets/1056740/25247390/0ff2b026-25e1-11e7-8151-64e36b2003b0.png)
![homeaboutcareer](https://cloud.githubusercontent.com/assets/1056740/25247391/0ff611bc-25e1-11e7-90ba-7bae4322cbac.png)
![homeaboutcontact](https://cloud.githubusercontent.com/assets/1056740/25247393/100eb906-25e1-11e7-9387-a4bb7e97e3a9.png)
![homeaboutlocation](https://cloud.githubusercontent.com/assets/1056740/25247395/100f6a72-25e1-11e7-9859-39abe5839a8f.png)

**Comment by nwinter** [comment]
Here are the lines to translate: https://github.com/codecombat/codecombat/blob/master/app/locale/pt-BR.coffee#L847-L935

I will consider adding a Brazil office location for pt-BR users. What should the address be?

**Comment by cwmaia** [comment]
Here is the address for the Brazil office:

Avenida da Integração 2022
Candelária, Natal, RN, 59066-035

**Comment by fernandaagr** [comment]
Localization issues fixed.
