### ISSUE TITLE
Level "Loud Quietness" has a wrong flag color.

### ISSUE THREAD

**Issue by sake12** [codecombat/codecombat#4305]
The level has a red flag, so it means I can play it without subscription.
[Screenshot](https://www.dropbox.com/s/1y835t3st6p1ni5/Zrzut%20ekranu%202017-04-23%2008.55.32.png?dl=0)
But to play it I need a pet, so I can't really play it.
[Screenshot](https://www.dropbox.com/s/3934o1z32g6o84k/Zrzut%20ekranu%202017-04-23%2008.52.37.png?dl=0)

**Comment by Bryukh** [comment]
Thanks. Fixed.
