### ISSUE TITLE
[BR - Issue] Localization issues, spelling and page redirection on email verification page.

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4350]
The success message in the email verification page is not localized and both buttons, Continue Jogando and Visualizar Progresso, lead the user to the same page, Student dashboard witch is half localized.
Spelling erros in the email verification page, home, about and student dashboard. 
Word mispelled: Involva - se.
![1 - verify email](https://cloud.githubusercontent.com/assets/8160775/26644933/ce031560-460c-11e7-947f-aa6e94b6a0da.png)
![2 - redirect pages](https://cloud.githubusercontent.com/assets/8160775/26644949/da3187b8-460c-11e7-8fe9-5fc0ff831e75.png)

**Comment by nwinter** [comment]
Fixed in #4375
