### ISSUE TITLE
[BR - Issue] Browser cache

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4351]
If the user has played some level in anonymous mode and logged in for the first time after, the progress shown in the dashboard is different from 0%.

![2 - redirect pages](https://cloud.githubusercontent.com/assets/8160775/26645884/10c0590a-4610-11e7-9cf1-ece5a85b972f.png)

**Comment by nwinter** [comment]
This is intentional–students who create their account don't lose the progress they made while anonymous, and they keep the progress for any levels they did that are the same between the home version and the classroom version.

**Comment by fernandaagr** [comment]
Understood.
