### ISSUE TITLE
[BR - Localization] Request demo page partially localized and spelling error.

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4358]
The request demo page contains string that are still not localized and words mispelled: Solicite um Demonstração.

![9 - solicitar demonstracao](https://cloud.githubusercontent.com/assets/8160775/26728532/e7a1d702-4780-11e7-932d-e0d6d2d76ae2.png)
![9 1 - solicitar demonstracao](https://cloud.githubusercontent.com/assets/8160775/26728538/eb06ebbc-4780-11e7-965f-8d88c42ac8af.png)

**Comment by nwinter** [comment]
Fixed by #4375
