### ISSUE TITLE
[BR - Issue] When singing up as an individual account, its allowed enter with an invalid option of date of birth. 

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4359]
1: When a user is signing up as an individual account, it is allowed to enter with an invalid option of date of birth (Ex.: February/31/2000) and no warning or message is displayed saying that the date is invalid. After that the user can proceed to the next step and complete the process.

2: The message error when the user enter with an incomplete date of birth is still not localized.

3: Alignment issues with "Sign up for news" button and string not localized.

![13 2 - criar conta individual](https://cloud.githubusercontent.com/assets/8160775/26728655/5c965394-4781-11e7-8510-f6e5db4a7664.png)

![13 - criar conta individual](https://cloud.githubusercontent.com/assets/8160775/26728676/63bb4706-4781-11e7-9ade-7382d7de38e0.png)

![13 3 - criar conta individual](https://cloud.githubusercontent.com/assets/8160775/26728683/6a0edd98-4781-11e7-8bc0-f766aa91f40e.png)

**Comment by nwinter** [comment]
I don't really care about 1. Fixed 2. 3 is a duplicate from another issue.

**Comment by fernandaagr** [comment]
Understood!
