### ISSUE TITLE
[BR - Issue] Localization and space issues on the Items tab.

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4362]
Some strings not localized and the space intended for the item name is smaller than the item name.

![16 - jogador anonimo itens](https://cloud.githubusercontent.com/assets/8160775/26728882/1a843d1c-4782-11e7-936d-1bd2833bb40f.png)

**Comment by nwinter** [comment]
The item names are just going to have to truncate when they are too long. You can localize all the item names at https://direct.codecombat.com/i18n
