### ISSUE TITLE
[BR - Localization] Achievements tab partially localized.

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4363]
The Achievements tab contains strings that are still not localized and a better use of words is needed to full understanding.

![17 - conquistas](https://cloud.githubusercontent.com/assets/8160775/26728925/3a08b1e0-4782-11e7-83f1-b857e3e951fd.png)

**Comment by nwinter** [comment]
You can edit these and add new translations at https://direct.codecombat.com/i18n

**Comment by fernandaagr** [comment]
Fixed.
