### ISSUE TITLE
[BR - Localization] Localization issues on game levels.

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4364]
1: There are several levels that have localization issues on the Hint tab.

2: In the first levels the blue tab with hints says to click on "Finalizar" button which does not exist. The existing name of the button is "Pronto".

3: On the reload level button the warning should show “Você tem certeza que quer reiniciar a fase?” ou “Você tem certeza que quer reiniciar este nível?”.

![18 3 - fases](https://cloud.githubusercontent.com/assets/8160775/26728971/68f70092-4782-11e7-8947-f5a9f1eb36f7.png)

![18 - fases](https://cloud.githubusercontent.com/assets/8160775/26728978/6ea3e5be-4782-11e7-80d3-18f8cd4f4f7a.png)

![18 2 - fases](https://cloud.githubusercontent.com/assets/8160775/26728988/74d16fe2-4782-11e7-8f3f-a5222d2f513b.png)

**Comment by nwinter** [comment]
You can edit the translations for these at https://direct.codecombat.com/i18n

**Comment by fernandaagr** [comment]
2 e 3 fixed.
