### ISSUE TITLE
[BR - Issue] Code divergence on the Hint tab.

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4365]
At levels 2 and 20 the Hint tab says to use commands this.moveRight() and hero.moveRight(). And in the prompt is typed hero.moveRight().

![20 - fase 2 sugestoes](https://cloud.githubusercontent.com/assets/8160775/26729062/aeee5bcc-4782-11e7-8ad3-c87aab877ca3.png)

**Comment by nwinter** [comment]
I think these need to be updated to match the latest English hints, which you can also do at https://direct.codecombat.com/i18n/level/gems-in-the-deep

**Comment by fernandaagr** [comment]
Fixed.
