### ISSUE TITLE
[BR - Isue] Text overflow level 7.

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4366]
1: Text overflow on the goals tab.
2: On the Hint tab the text says to click on the "Avançar" button which does not exist. The right button to click is "Próximo".

![21 - fase 7](https://cloud.githubusercontent.com/assets/8160775/26729136/ec097a1e-4782-11e7-84ff-a4803d05c3d2.png)

**Comment by nwinter** [comment]
@fernandaagr I fixed 1. For 2, you can localize the level to change the name of the button in that text.

**Comment by fernandaagr** [comment]
Fixed.

**Comment by fernandaagr** [comment]
Fixed.
