### ISSUE TITLE
[BR - Localization] Strings on the Arena page are not Localized.

### ISSUE THREAD

**Issue by fernandaagr** [codecombat/codecombat#4368]
A few strings on the Arena page are not localized.

![25 - arena](https://cloud.githubusercontent.com/assets/8160775/26729206/3d39763c-4783-11e7-9572-38b3e761d2ab.png)

**Comment by nwinter** [comment]
I'll fix the "Levels" string. For the level description, edit that here: https://direct.codecombat.com/i18n/level/wakka-maul

**Comment by fernandaagr** [comment]
Fixed.
