### ISSUE TITLE
i18n - patches are shown as empty, translation lost

### ISSUE THREAD

**Issue by joca16** [codecombat/codecombat#4370]
Hi, I did a full translation de-DE on https://direct.codecombat.com/i18n/level/underground-business. Tested it and it was shown when playing the level.

Now all translation de-DE are missing. The patches are shown, but the first patch says:
```
Diplomat submission for lang de-DE: 8 change(s).
Keine Änderungen (No changes)
```
The second patch show further changes I made to my first patch, it's not accepted yet.

**Comment by joca16** [comment]
Found a somewhat related issue: The diffs in the patches section of i18n are not shown correctly:
At https://direct.codecombat.com/i18n/level/zoo-keeper
I did some small changes. This is the text after my edits (English section was not altered):
![bildschirmfoto 2017-06-05 um 00 19 47](https://cloud.githubusercontent.com/assets/26973584/26765888/e99fb91e-4985-11e7-8273-dcad82e02767.png)

However, the diffs in the patches section show some of the changed, new text (for example Feld was changed to Array) without green color, whereas the changes marked green show falsely one "," too much and "eineinen", instead of "einen". (see first picture for actual text in this patch).
![bildschirmfoto 2017-06-05 um 00 20 08](https://cloud.githubusercontent.com/assets/26973584/26765890/fbf60730-4985-11e7-8e7e-d4be634b1147.png)

**Comment by nwinter** [comment]
I'm checking in on the Underground Business translations; it's possible was a patch-acceptance mistake, will see; else a bug. I think @Bryukh might have accepted that one?

For the diff view thing, does the expert view show it correctly, if you click to expand that?

**Comment by joca16** [comment]
<b>Underground Business</b>: The two patches I made with the i18n interface show up in the level editor (as well as in the i18n interface). 
![bildschirmfoto 2017-06-05 um 23 36 51](https://cloud.githubusercontent.com/assets/26973584/26804415/2d5d00c2-4a48-11e7-8d4c-f99245a5aedd.png)

The first patch was made in the i18n interface and it was accepted automatically, as it was i18n only. It was also test-played and showed the translated level name on the map as well as the translated texts in the source and the Hints.

The second patch I edited in the level editor and changed an minor spelling mistake in the English text, too. This is the expanded view of the patch:
![bildschirmfoto 2017-06-05 um 23 46 10](https://cloud.githubusercontent.com/assets/26973584/26804699/39b6b6a0-4a49-11e7-8f8c-1e48e24d0288.png)
This patch was pending. I suppose @Bryukh has accepted this patch, as the correction of the English text is now applied.
The spelling correction of the German text, done in the same patch, is shown in the diff, but all i18n de-DE translations seem to be gone.


As far <b>as zoo-keeper</b> is concerned: I am sorry, I cannot remember wether the expert view showed the same. And I cannot re-check: Now the patch shows "No Change" , so I cannot  reproduce this faulty diff. The translations are still there and the patch was apparently applied correctly. I was only concerned about the false diff view which showed strange changes that did not happen.

**Comment by Bryukh** [comment]
@joca16 About "Underground Business". It was a problem because I was working on the level at the same time when you added the translation. So when I saved my changes, I "removed" your translation because they weren't in my cached version. Sorry, I restored (I hope all) your translations to this level.

**Comment by joca16** [comment]
@Bruyukh Thank you for the explanation and your effords in getting the texts back! Glad that there is no larger bug, just a race condition ;-) Thanks for resolving! Part <b>Underground Business</b>  can be closed imho.
As far <b>as zoo-keeper</b> is concerned: I will continue to watch whether similar strange diffs occur. I have noticed, that there are quite a few accepted patches, that show "No Change". Is this maybe the default behaviour for patches, that have been incorporated into the database?

**Comment by joca16** [comment]
I'm closing this issue, as the initial problem was solved. Thanks @nwinter & @Bryukh! I will open separate issues for two things that popped up in the discussion here later:

1. Implement a locking / mutex mechanism for editing levels, thangs, etc. This would prevent that changes might get lost if two persons work on the same object at the same time.

2. There seem to be some issues with showingpatches. As in the examples here, there seem to have been some editing conflicts before, it is not quite clear what was going on. I will try to look for reproducable errors an open a new issue then.
