### ISSUE TITLE
Strings i18n missing in item details view

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#4382]
![i18n missing](https://user-images.githubusercontent.com/6980488/26942810-5eae16a4-4c7b-11e7-8f78-3040c9964e97.png)

The strings "Ranger" and "Ranger Only" are missing.

**Comment by nwinter** [comment]
Code [here](https://github.com/codecombat/codecombat/blob/master/app/templates/play/modal/item-details-view.jade#L42):

```jade
    button.btn.big-font.disabled.unequippable #{item.get('heroClass')} Only
```

We have translations for the class names [here](https://github.com/codecombat/codecombat/blob/master/app/locale/en.coffee#L399-L401); need to use them, and also add a new translation string for the " Only" suffix.

**Comment by Imperadeiro98** [comment]
And [this line](https://github.com/codecombat/codecombat/blob/master/app/templates/play/modal/play-items-modal.jade#L65) too:
```jade
    span.big-font.unequippable= item.get('heroClass')
```

**Comment by oleksavr** [comment]
ONLY in Russian  is "ТОЛЬКО"
