### ISSUE TITLE
Setup dev environment. Database Import not working

### ISSUE THREAD

**Issue by pitetb** [codecombat/codecombat#4385]
Hello! 

On the instructions to setup dev environment on the wiki:
[https://github.com/codecombat/codecombat/wiki/Dev-Setup%3A-Linux](https://github.com/codecombat/codecombat/wiki/Dev-Setup%3A-Linux)
 it's mention to download last version of database on the URL: http://analytics.codecombat.com:8080/dump.tar.gz 
But this URL doesn't seems to work. 

Please update. Thank you.

**Comment by nwinter** [comment]
Thanks for the bug report! We've fixed up the database dump serving, so it should be accessible again.
