### ISSUE TITLE
无法使用google帐号登录，发生未知错误（unknown error）！！

### ISSUE THREAD

**Issue by KB5201314** [codecombat/codecombat#4387]
我无法使用google帐号来登录，我已经忙活了几个小时了，是的，我在中国，但我通过修改hosts连接上了google，并且在google上成功授权登录，但是codecombat页面上一直显示“正在登录”，一会儿后提示“unknown error”

希望能尽快解决这个问题

**Comment by KB5201314** [comment]
Ok，现在我发现这个问题的原因了，我的账号是在2年前注册的，那个时候只有codecombat.com，我在那里用google账号登陆并且玩了一段时间，现在我进入codecombat.com，想继续之前的账号，但是它自动跳转到了cn.codecombat.com，我知道这是在为中国用户提供便利，但是很显然codecombat.com和cn.codecombat.com没有使用同一个账号数据库，我自然无法在cn.codecombat.com里面找到我2年前的账号，因为它在codecombat.com里面......

现在，如果我访问codecombat.com，它还是自动跳转到cn.codecombat.com，这样我就不能在codecombat.com上玩我2年前的账号了，我希望codecombat能够像www.google.com那样添加“禁止国别跳转”（No Country Redirect），这样我在中国就能访问codecombat.com而不会跳转到cn.codecombat.com

谢谢

**Comment by nwinter** [comment]
You can use https://contributors.codecombat.com, that shouldn't trigger the redirect. Let me know if that doesn't work for you.
