### ISSUE TITLE
I cannot enter any level of the "Game Development 2"

### ISSUE THREAD

**Issue by px19911013** [codecombat/codecombat#4395]
Hi, could someone help me?? 

Win8.1
Internet Explorer 11
JavaScript

I cannot enter any level of the "Game Development 2". This dungeon has just been unlocked, but every chamber in this dungeon is locked. How could I start this dungeon? THX. 

![5c 80w 36u utm 32 r k](https://user-images.githubusercontent.com/29644102/27459960-0a4bf3c0-5805-11e7-9f82-2aeecc0cc332.png)
![b 709 kj gt jv9odiorx](https://user-images.githubusercontent.com/29644102/27459961-0a4cee56-5805-11e7-910f-922c47d9a77c.png)

**Comment by dantz15** [comment]
Oh no, this has been like this for 2 years. We just experience this recently.
We tried most of the browsers but still not showing any open levels.

**Comment by AndrewJakubowicz** [comment]
Thanks for reporting this. What account is this issue happening for?

**Comment by dantz15** [comment]
Thanks for getting back Andrew. I have a Lifetime Access. Is this what you need?

**Comment by AndrewJakubowicz** [comment]
I'm not able to replicate the issue myself. It would be helpful to know the username or email of the account that has the issue. Many thanks!

**Comment by dantz15** [comment]
Hi Andrew,DARK ZORC is the username.Thanks.Regards,Dante
-------- Original message --------From: Andrew Jakubowicz <notifications@github.com> Date: 8/10/20  11:53 am  (GMT+10:00) To: codecombat/codecombat <codecombat@noreply.github.com> Cc: "dante.ricafort" <dantericafort@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [codecombat/codecombat] I cannot enter any level of the "Game Development 2" (#4395) 
I'm not able to replicate the issue myself. It would be helpful to know the username or email of the account that has the issue. Many thanks!

**Comment by nwinter** [comment]
@dantz15 you should have access now.

**Comment by dantz15** [comment]
Thank you. I confirmed that I have access now.
