### ISSUE TITLE
i18n translations for user profile

### ISSUE THREAD

**Issue by joca16** [codecombat/codecombat#4407]
At https://codecombat.com/user/xxx (Menu Account -> Profile at website), some list entries are not translated according to the i18n System:

At **Singleplayer Levels**, list entries for "Level" and "Last Played" are not translated according to i18n. The levelnames are translated already in i18n.

At **Achievements**, list entries for "Achievement" and "Last Earned" are not translated according to i18n. (Achievements are translated in the i18n.coffee files. Not sure wether dates are in i18n at all).

**Comment by phoenixeliot** [comment]
Is this because of the language you have selected? Those values seem to be translated for Spanish and French, but not every language.

You can check the language you had enabled in the corresponding file here, at line 2058: https://github.com/codecombat/codecombat/tree/master/app/locale

If the line is commented out and in English, then we'd love a contribution to the translations there!

**Comment by joca16** [comment]
This seems not to be an issue of availability of i18n translations. I have added an image in order to show the problem:

![bildschirmfoto 2017-08-07 um 22 34 48](https://user-images.githubusercontent.com/26973584/29044695-e8718370-7bc0-11e7-97fb-2bedaeb1e638.png)
As you can see, the headers as "Nivel" or "Logro" are translated perfectly well according to the i18n.coffee file. However, the names of the levels are shown by their English title only, not by the translated title that has been translated in the i18n section.
So  "Signs and Portents" is already translated to "Signos y Presagios", but not shown in Espaniol (cf. https://codecombat.com/i18n/level/signs-and-portents)
So probably there is some i18n-lookup-command missing at the code generating this web page.

Regards!

**Comment by Imperadeiro98** [comment]
Same as #2327?

**Comment by joca16** [comment]
Yes, it is the same. In #2327, however, there is no mentioning of the Date-Translation of "Last Played" and "Last Earned". Should this issue be marked as duplicate and be closed?
