### ISSUE TITLE
Pets should not be purchasable in the free version

### ISSUE THREAD

**Issue by 0jrp0** [codecombat/codecombat#4421]
Steps to reproduce:

1. Create free account
2. Progress to point where pets are available
3. Acquire 1100 gems
4. Purchase brown rat

Actual:

- brown rat can be purchased
- it consumes 1100 gems
- brown rat moves from purchasable items to subscriber only
- this wastes over 1000 gems on something that's not available, not OK

Expected:

- all pets / animals appear under subscriber only and they cannot be purchased in anyway. 

Account: ```_jrp_```

**Comment by 0jrp0** [comment]
This shows Baby Griffin within the Locked section of a Free account. Purchasing it would waste gems and place the pet into the subscriber only section:

<img width="670" alt="screen shot 2017-08-08 at 4 43 27 pm" src="https://user-images.githubusercontent.com/4490960/29099222-d63dee94-7c58-11e7-9da4-72fef0414470.png">

**Comment by Catsync** [comment]
Fix for this should go live later today. Thanks for the report! 

If you need to get some gems reimbursed, send an email to team@codecombat.com with the details.

**Comment by 0jrp0** [comment]
Thanks. Although you've changed the button to show "Subscribe" instead of the number of gems to purchase the pet, I think the pet should also appear in the section where all the other pets are. I'm not sure why the Baby Griffin and Mimic do not appear in the SUBSCRIBER ONLY section. They currently appear in the LOCKED section. I would expect that the "Subscribe" button and the SUBSCRIBER ONLY section would share the same attribute across the object classes that represent pets. Instead it seems that there are two and they're being inconsistently set. Please check.
