### ISSUE TITLE
Create account back button doesn't work

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#4457]
When I open the Create Account modal and then click "Sign up as a Student" or "Sign up as an Individual" (for "Sign up as a Teacher" it works), if I want to go back by clicking the "Back" button, nothing happens.

**Comment by sderickson** [comment]
Can't repro. Can you confirm this is still happening in production?

**Comment by Imperadeiro98** [comment]
Yes, I can sill reproduce it in my computer (latest Chrome version on Windows 8.1).

**Comment by Imperadeiro98** [comment]
Can't reproduce it anymore.
