### ISSUE TITLE
No levels

### ISSUE THREAD

**Issue by gkua** [codecombat/codecombat#4476]
I have no levels in the cloned repo?
![image](https://user-images.githubusercontent.com/31951743/31175557-55efb604-a918-11e7-9101-2006afe5541c.png)

**Comment by sderickson** [comment]
Please see the Developer Setup in the Wiki, the section about loading the mongo dump to your local setup.

https://github.com/codecombat/codecombat/wiki/Dev-Setup:-General-Information#database
