### ISSUE TITLE
Node-gyp rebuild : Installation failed on debian / fedora

### ISSUE THREAD

**Issue by prysme01** [codecombat/codecombat#4551]
Hello, 

With using node 5 with nvm, I'm unable to complete the installation

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jeanjacques/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.11.0-1-amd64
gyp ERR! command "/home/jeanjacques/.nvm/versions/node/v5.12.0/bin/node" "/home/jeanjacques/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jeanjacques/source/codecombat
gyp ERR! node -v v5.12.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /brunch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm ERR! Linux 4.11.0-1-amd64
npm ERR! argv "/home/jeanjacques/.nvm/versions/node/v5.12.0/bin/node" "/home/jeanjacques/.nvm/versions/node/v5.12.0/bin/npm" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! codecombat@ install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codecombat@ install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the codecombat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codecombat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls codecombat
npm ERR! There is likely additional logging output above.

Could you help me ?

**Comment by nwinter** [comment]
Hmm, not sure, but possibly a problem with your `node-gyp` setup? Does anything from https://github.com/nodejs/node-gyp seem applicable?

**Comment by quant4s** [comment]
i had same mistake
node version: V 9.4.0
npm version: V5.6

**Comment by nwinter** [comment]
We are now on node 6 and have since made some changes to make this node-gyp less buggy, so give it a shot on node 6.

**Comment by quant4s** [comment]
RR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/bin/node-v6.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/usr/local/bin/node-v6.13.0-linux-x64/bin/node" "/usr/local/bin/node-v6.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/codecombat/node_modules/webworker-threads
gyp ERR! node -v v6.13.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN lifecycle codecombat@~postinstall: cannot run in wd %s %s (wd=%s) codecombat@ bower install && webpack /root/codecombat
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.6.4 (node_modules/webworker-threads):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.6.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

===========================================================
node version: V6.13.0
npm version: V3.10.10

**Comment by nwinter** [comment]
`webworker-threads` should be an optional dependency; is this a full build error or just indicating that you couldn't build that? (Anyway, you could remove it from `package.json` if you want.)
