### ISSUE TITLE
"Persistence Pays" in Python

### ISSUE THREAD

**Issue by malina-kirn** [codecombat/codecombat#4556]
I'm going through the CodeCombat exercises in prep for Hour of Code tomorrow (I'm a software engineer). I chose Python. There seems to be a bug in the "Persistence Pays" level. The individual goals are met when the level ends, but the level is marked as incomplete; it just keeps kicking me back into the code window. console log statements indicate that I am correctly storing a value into the DB with the specified key and that "the world ended in won on frame ...", but the goals are still marked as incomplete.

Here's my console log after clicking "Test Level":

```
|Huhetotl's Archer| ===== Profile: None collected =====
God.coffee:81 Huhetotl: Let there be light upon Persistence Pays! (preload: false)
CountdownScreen.coffee:78 should actually start in 1s
Surface.coffee:672 Force resize strategy
VM584:37 Generated random seed 16195641327 of type submissionCount from sessionIDs ["5a2749cb16fad7004071e453"] submissionCount 3
lodash.js:5496 [Violation] 'setTimeout' handler took 180ms
VM620:759 DB ADD
VM620:763 {"defeated":0,"plays":55}
Angel.coffee:355 [Violation] 'setTimeout' handler took 51ms
VM620:779 DB SET defeated 0
VM620:785 {"defeated":0,"plays":56}
PlayLevelView.coffee:573 Should we start simulating? Cores: 8 Heap limit: 2190000000 Load duration: 2995
world.coffee:393 The world ended in won on frame 122
world.coffee:393 The world ended in won on frame 167
world.coffee:393 The world ended in won on frame 167
Angel.coffee:355 [Violation] 'setTimeout' handler took 58ms
Angel.coffee:372 Construction: 174 ms. Simulation: 2723 ms -- 34.904 ms per frame, profiled.
esper.js:9009 ===== Profile: None collected =====
```

I can't seem to copy my game code, so here are the relevant lines I added:

```
// L17
      ui.track(db, "plays")
// L22-23
def onVictory(event):
  db.set("defeated", game.defeated)
```

I'm teaching Hour of Code tomorrow, so any rapid-turnaround suggestions would be helpful. Is this known to work in a different language? Is there a way I can have students skip the level?

**Comment by malina-kirn** [comment]
Le sigh, user error. Please ignore.

**Comment by nwinter** [comment]
@malina-kirn what was it? I'm actually working on that level right now, since it's proven to be very tricky in our Hour of Code activity. Trying to make it easier and more intuitive.

**Comment by malina-kirn** [comment]
Apologies for the delay -- HoC yesterday was exhausting but hugely successful, thanks to your hard work (thank you!). We used CodeCombat (build your own game) for 8th graders and 5th graders. Only one of my students had enough time to make it to "Persistence Pays" and she hit the same problem I did, which was meeting the second requirement (track the game's defeated property).

Specifically, the exercises up to that point have us accessing the game properties and methods with `.` operators (the hint tells you to use `db.set("defeated", game.defeated)`). And every call to `ui.track` that we've seen up to that point has always taken a `db` object. So it's not clear that `ui.track` will take *any* object and reference *any* property by string name. Specifically, there's no example which calls `ui.track(game, "propertyName")`, so it's not clear that this is possible to do. I eventually figured it out by reading the comment in the code more carefully.

I ended up calling `ui.track(db, game.defeated)`, my student ended up calling `ui.track(db, "defeated", game.defeated)`. Both are obviously wrong in retrospect, but both errors are due to neither of us understanding the type signature of the `ui.track` method. We both made incorrect assumptions about what arguments it could take, having only seen examples in which the UI displays properties on the db object. It wasn't clear to me that we were accessing properties by their name on the db object; I'd thought we were using string keys to get data out of app storage (not that my code did that either -- my student's code was actually closer to that type signature than my own code was).

I'd also consider reducing the default survival time to make it easier to test the level. 20 seconds is a while to wait to find out you failed. Of course I dropped it to 1 second and told my student to as well, but most instructors aren't going to know to suggest that.

Also, as generic feedback, I would suggest that when a level fails, the list of goals drops down in the upper left corner and the unmet condition is called out a little more explicitly, perhaps with a red x, or similar. As you can tell from my original ticket, I hadn't even realized this was the source of my error for a while (I thought it was the third condition, which I had actually met).

All these suggestions aside, I think CodeCombat is a great way to teach code; there's a reason I selected it for most of my students (didn't use for the 3rd graders). The 5th graders had a harder time following instructions, despite there only being a few sentences of instructions. But it was a good opportunity to encourage them to read the instructions. And they got to leverage their x/y coordinate skills; I think they enjoyed seeing a practical application for what they'd been learning.

**Comment by nwinter** [comment]
Thanks for the detailed feedback! We're going to add an example of `ui.track(game, "time")` here to help with the abstraction. Great suggestion to lower default survival time, too.

Were there other levels earlier that were taking lots of time? We're trying to reduce the activity time so that more students have time to get to the end. Interested to hear feedback for any other speed bump levels for your students.

**Comment by malina-kirn** [comment]
I'd say something like 90% of student pairs got stuck on and needed help with "Over the Garden Wall." Reading the instructions is critical for this level and students just didn't do it. This is the first level where students are editing the canvas instead of their hero and they just don't put together what they're supposed to do. It's also the first level dealing with x/y coordinate systems. I would not eliminate the level, because the teachers were obviously thrilled to see their students using x/y, and I could see how this was a fun learning opportunity for the students.

I'd consider making the level really emphasize that the students are now editing the canvas itself and remove everything that doesn't underscore that point. To that end, I'd get rid of all creatures on the canvas (monsters and villagers) and eliminate the villager survival requirement. I'd require them to build a single fence at a particular location, showing an example fence or two, and call it done as soon as they've edited the canvas. The issue I can see with this is there's not actually something to 'run', but I'm not sure how else to double-underscore that the point and purpose of the level is to edit the canvas.

Is there a different object that could be added to the canvas that they could perhaps move their hero to? They're comfortable with their hero object at this point. Just not with the canvas.

**Comment by nwinter** [comment]
When the students got stuck, what were they trying to do? Or were they just confused and not doing anything?

We previously had [Kithgard Gates](https://codecombat.com/play/level/kithgard-gates) to introduce x-y coordinates and building fences,  but from the hero's perspective, right before this. Took it out because we thought we could compress it a bit. Do you think that would be a good introduction? Or perhaps we could do [Defense of Plainswood](https://codecombat.com/play/level/defense-of-plainswood), or a version of it that uses `spawnXY` instead of `buildXY`...

**Comment by malina-kirn** [comment]
Most students did not make it to "Behavior Driven Development", but those who did got stuck. This is a great level, but also a big conceptual step. Even the students who read the instructions clearly didn't understand that `unit.behavior` was shorthand for `skeleton3.behavior, archer.behavior`, etc. For this one, I'd suggest reducing the number of units and boilerplate, so they can see the example code more clearly. With so many lines of code, they didn't really bother reading any of them, so didn't see the examples right in front of them. I'd also suggest modifying the help text to say `skeleton1.behavior` instead of `unit.behavior`.

**Comment by malina-kirn** [comment]
For "Over the Garden Wall", kids couldn't start; they didn't understand what they needed to do. They came to me for help before writing any code. I suspect that "Kithgard Gates" as an introduction with heavy hint comments in the code will help with the transition, since it independently introduces x/y coordinates. Ultimately though, I think "Over the Garden Wall" is difficult because it's the first level in which they edit the canvas (though combining with an introduction to x/y does make it more challenging). I'd suggest emphasizing in the transition notes that play in the bottom in "Over the Garden Wall" that we as the game developers are editing the game, instead of playing with our hero.

I'd also consider placing the "Forest Incursion" level before "Over the Garden Wall", since, in "Forest Incursion", you're editing the game by editing the hero's capabilities. That might also make the transition to "Over the Garden Wall" easier (now, we're editing the map, instead of editing the hero). Or perhaps even go so far as to change the ordering to Forest Incursion -> Behavior Driven Development -> Over the Garden Wall (first edit the hero's properties; then edit the enemy's properties; then edit the map).
