### ISSUE TITLE
Do you have a tutorial on whether you have a project deployment

### ISSUE THREAD

**Issue by cuiyimeng** [codecombat/codecombat#4574]
I'm a novice, but I'm trying to deploy this project locally, but I don't know how to do it. Do you have a detailed tutorial or document?

**Comment by nwinter** [comment]
The only documentation we have on this is here: https://github.com/codecombat/codecombat/wiki/Dev-Setup:-General-Information

Happy to help more if we can. Do you have a particular part of setup or deployment that you want help with?

**Comment by cuiyimeng** [comment]
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! codecombat@ start: `node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the codecombat@ start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the codecombat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codecombat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls codecombat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cym/codecombat/npm-debug.log

**Comment by cuiyimeng** [comment]
@nwinter I want to deploy this project locally for a test, but I deploy it after the document is deployed.

**Comment by nwinter** [comment]
```
npm ERR! node v6.9.5
```
This line shows you are on node 6. Try using node 5 (I recommend nvm to switch versions)  to do the install, and possibly reinstall node modules with `npm install` before doing `npm run dev`.
