### ISSUE TITLE
I tried to run this project. But it gave me the following mistakes

### ISSUE THREAD

**Issue by cuiyimeng** [codecombat/codecombat#4583]
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! codecombat@ start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codecombat@ start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the codecombat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codecombat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls codecombat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cym/codecombat/npm-debug.log

**Comment by nwinter** [comment]
Looks like you are using node 4. Try using node 5 (I recommend using nvm to switch node versions). Then you may need to `npm install` again to get the node modules installed with node 5.
