### ISSUE TITLE
Final Kismuth needs 10 stmts but instructions say less

### ISSUE THREAD

**Issue by kellerapps** [codecombat/codecombat#4596]
Maybe you meant in the loop body?

while True:
    hero.moveRight()
    hero.moveUp()
    e = hero.findNearestEnemy()
    hero.attack(e)
    hero.attack(e)
    hero.moveRight()
    hero.moveDown()
    hero.moveDown()
    hero.moveUp()

**Comment by Bryukh** [comment]
Do you mean "The Final Kithmaze"?
Your code can be shorter for one line. What about arguments?
