### ISSUE TITLE
Interception Unable to Remove Restricted Item

### ISSUE THREAD

**Issue by MrMork** [codecombat/codecombat#4617]
![image](https://user-images.githubusercontent.com/36214358/35892789-df609ecc-0b5f-11e8-88f0-efba6eb288b4.png)

In the Interception level. Unable to remove restricted item "Hardened Steel Glasses" to play.
Was able to circumvent by going to the URL directly.

https://codecombat.com/play/level/interception

**Comment by jasonpnnl** [comment]
Playing the level, it seems like the level would require glasses that can findNearestFriend but then won't allow any of them to be selected as it has marked them all as restricted.

**Comment by javajeff** [comment]
I have the same issue and can't remove the glasses.  I also tried to go to the URL directly but that didn't work for me.

**Comment by jay20162016** [comment]
then mark all glasses without findNearestFriend restricted

**Comment by Bryukh** [comment]
Thanks. I've removed 'findNearestFriend' from the required properties because it's "given" to the hero on this level.
