### ISSUE TITLE
Installation failed on Windows 10

### ISSUE THREAD

**Issue by olexandr-maltsev** [codecombat/codecombat#4621]
Hi, I have an issue during installing  dependancies:
(Node version 9.5.0, npm 5.6.0)

npm ERR! esper.js@0.3.0-dev preinstall: `node contrib/install-plugin-deps.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esper.js@0.3.0-dev preinstall script.

Could you please help me?

**Comment by nwinter** [comment]
Try using node 6, we aren't supporting 9.5 yet.
