### ISSUE TITLE
hero cannot move in epiphony3.8.2, raspbian stretch

### ISSUE THREAD

**Issue by quant4s** [codecombat/codecombat#4625]
os: raspbian stretch 
hardware: raspberry pi 3b
browser: epiphony3.8.2

from first level, some mistakes are raised
1. sound and music cannot be played
2. hero cannot move

**Comment by nwinter** [comment]
Are there any error messages displayed in the JS console? I would not expect a Raspberry Pi 3B to be able to run CodeCombat; usually we require 2GB of RAM and this only has 1GB, plus we rely on a lot of generally advanced browser and hardware acceleration features. Epiphany 3.8.2 is over 4 years old, too, so I'd be pretty surprised if it was capable of running CodeCombat.
