### ISSUE TITLE
Dump database results in 0 bytes file

### ISSUE THREAD

**Issue by amithrqb** [codecombat/codecombat#4661]
While setting up the project
The link to the database dump is: http://analytics.codecombat.com:8080/dump.tar.gz resultuing 0 bytes sized file.Please have a look

**Comment by yuanyuss** [comment]
http://www.codecombat.com:8080/dump.tar.gz

**Comment by mlordelo** [comment]
Same here.

**Comment by nwinter** [comment]
Try again–we fixed the server that had failed to generate the backup.
