### ISSUE TITLE
brunch build --env fast        

### ISSUE THREAD

**Issue by coffeecodegirl** [codecombat/codecombat#4666]
22:54:41 - error: The directory does not seem to be a Brunch project. Create brunch-config.js or run brunch from the correct directory. Cannot find module '/home/combat/codecombat_back/brunch-config'
22:54:41 - error: Here's a minimal brunch-config.js to get you started:

module.exports = {
  files: {
    javascripts: {
      joinTo: 'app.js'
    }
  }
};

**Comment by nwinter** [comment]
We use webpack now instead of brunch; where are you seeing directions to run `brunch build --env fast`?

**Comment by coffeecodegirl** [comment]
Hi,nwinter 

Thank you for your answer.

I had consulted  a url:  http://crokily.lofter.com/post/3d4cef_bb43475

npm install

sudo npm install -g bower --allow-root

sudo npm install -g brunch

sudo npm install -g node-gyp

sudo npm install -g node-sass

sudo bower --allow-root install

sudo bower --allow-root update

sudo brunch build --env fast

**Comment by nwinter** [comment]
Ah, that's an old post. See https://github.com/codecombat/codecombat/wiki/Dev-Setup:-General-Information for more up-to-date info on the new webpack process.
