### ISSUE TITLE
Yellow arrow covers parts of the text

### ISSUE THREAD

**Issue by petrblahos** [codecombat/codecombat#4671]
The yellow arrows marking where in the code changes should be made are too big, they cover parts of the code on the marked line, and also parts of the lines above and below. Really, both my kids who play CodeCombat find it annoying, and I can see their point. Perhaps making the arrow narrower and more to the left would help?

![codecombat-bug-01](https://user-images.githubusercontent.com/2546575/39479549-e57cc874-4d65-11e8-89eb-44385df833bb.png)

**Comment by nwinter** [comment]
Hmm, can you post a larger screenshot showing the whole window? Seems to be some other bug affecting the arrows (they're too far in and on the wrong line); should look like this:

<img width="763" alt="screenshot 2018-05-01 10 10 55" src="https://user-images.githubusercontent.com/99704/39483700-0f56eb04-4d28-11e8-8f5a-94c1e1ac8e1c.png">

**Comment by petrblahos** [comment]
Here you go: (firefox 59.0.2, 64bit ubuntu 16.04)

![screenshot from 2018-05-01 17-24-50](https://user-images.githubusercontent.com/2546575/39484263-7442ca2c-4d75-11e8-9c10-c5b5ad296b4c.png)

**Comment by nwinter** [comment]
@petrblahos thanks for the bug report–this is fixed and will go live with next deploy.

**Comment by petrblahos** [comment]
Thanks Nick, that was quick. When about can I expect it to go live? I want to know it I should switch kids to chrome...

**Comment by nwinter** [comment]
A little later today, most likely; if not, then tomorrow.
