### ISSUE TITLE
Reward and Ruination problem last loop not executed?

### ISSUE THREAD

**Issue by bennypr0fane** [codecombat/codecombat#4686]
In [reward and Ruination](https://codecombat.com/play/level/reward-and-ruination?), the last peon is not shot (or he is, but the level goals are still not completed).
There's a forum thread here: https://discourse.codecombat.com/t/reward-and-ruination-problem/7867 my code posted at the last answer:
```
while True:
    enemy = hero.findNearestEnemy()
    if enemy:
        enemyPos = enemy.pos.x + " " + enemy.pos.y
        hero.say("Enemy at " + enemyPos)
        pass
    # Now that you have sweet revenge,
    # why not have your cake and eat it, too?
    # Find the item's position and 
    # say it for your artillery to target.
    item = hero.findNearestItem()
    if item:
        hero.say("Gem is at " + item.pos.x + ", " + item.pos.y + "!")
    pass
```
Try running/submitting multiple times. It works _sometimes_, sometimes not!

**Comment by nwinter** [comment]
Hmm, I can't reproduce even with a dozen resubmissions. Can you email your CodeComat username to nick@codecombat.com and stop playing when you have submitted and seen one that doesn't work, so that I can investigate more closely?

**Comment by bennypr0fane** [comment]
Okay, I also tried re-submitting several times without the problem occurring again - it always passed the level. No idea what was wrong before, because the code was the same - sorry!

**Comment by daliz4rd** [comment]
![rewards-and-ruination](https://github.com/codecombat/codecombat/assets/55161334/66c40240-021e-4f8b-a79b-a58a6d075dc0)

I'm having this same issue in the javascript version, the hero says the last enemy position but the cannon doesn't fire at him
