### ISSUE TITLE
Windows dev steps are incomplete - please fix

### ISSUE THREAD

**Issue by iPzard** [codecombat/codecombat#4704]
Some steps like "Start mongoDB", just seem completely underdeveloped (what does that even mean?!). Then other instructions such as, 
"mongorestore --drop --noIndexRestore path/to/dump --db coco".. lack information such as which directory this action is performed in.

The steps were ultimately incomplete to the point of being unusable to successfully setup a dev environment. I ended up going here to get the additional steps:
https://gist.github.com/deepak1556/8319345

**Comment by nwinter** [comment]
I've added a little more detail here: https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Windows – hope this helps.
