### ISSUE TITLE
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`

### ISSUE THREAD

**Issue by ankitpachori** [codecombat/codecombat#4709]
Getting this error while i am doing an npm install
[2018-05-23T13_00_08_502Z-debug.log](https://github.com/codecombat/codecombat/files/2031210/2018-05-23T13_00_08_502Z-debug.log)

**Comment by nwinter** [comment]
Does this sequence of commands help?
```
npm install node-sass
npm install --ignore-scripts
bower install
npm install
```

Or this?
```
npm install node-sass@latest
```

**Comment by nightcrawler-** [comment]
`npm install node-sass@latest` resolves the issue

**Comment by singhrohan62** [comment]
> Does this sequence of commands help?
> 
> ```
> npm install node-sass
> npm install --ignore-scripts
> bower install
> npm install
> ```
> 
> Or this?
> 
> ```
> npm install node-sass@latest
> ```

not working for ubuntu 18.04 and node 10.12.0

**Comment by parkbroom** [comment]
the real issue is your node version change to version 6 and you're good

**Comment by jukuan** [comment]
Try to check and fix permissions on your `~.npm` directory

**Comment by FullTimeLinux** [comment]
For the most part @nwinter 's comment worked for me on Fedora 31. The only command I did not use was `npm bower install`
