### ISSUE TITLE
Error not showing up when deleting account

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#4721]
When deleting an account, through the form in https://codecombat.com/account/settings, if the given email/username is not valid, no error is displayed, and the following error appears in the console:
- email not found in ... so couldn't show message: Wrong Email

I think this happens because in [this line](https://github.com/codecombat/codecombat/blob/master/app/views/account/AccountSettingsView.coffee#L117) it is looking for the property "email", when it should be looking for "emailOrUsername". By the way, the error message should be updated to reflect this.

**Comment by nwinter** [comment]
Great catch @Imperadeiro98!
