### ISSUE TITLE
"mana-blast" ability has undocumented effect on units

### ISSUE THREAD

**Issue by vn971** [codecombat/codecombat#4738]
Mana blast is available in "zero-sum" tournament/ladder game, and it seem to have some effect on units (they show some graphical image above them after being attacked).

The problem is that this level does not allow you to list unit effects, so it's unclear how to understand whether a unit has this effect or not.

Same applies to `raise-dead`. How can I determine whether a unit is "raised-dead" or not?

Maybe answering these question in this issue might be good enough. Determined developers could find this in google / github issue search.
IDK if it makes sense to document it in-game, for those playing as Pender and not having improved hero.effects method.

**Comment by nwinter** [comment]
Good question. `mana-blast` sets the `confuse` effect. `raise-dead` sets the `undead` effect. These effect names happen to trigger the marks that appear over their head, which you can find in the Thang editor ([confuse](https://codecombat.com/editor/thang/confuse), [undead](https://codecombat.com/editor/thang/undead)). If you are every really curious as to how something works, you can also open up a level in [the level editor](https://codecombat.com/editor/level/zero-sum) and start reading the Component code (here `combat.ManaBlasts` and `magic.CastsRaiseDead`.

**Comment by vn971** [comment]
Thanks a lot! All clear.;)
