### ISSUE TITLE
new tournament?

### ISSUE THREAD

**Issue by vn971** [codecombat/codecombat#4739]
Are there any official or unofficial plans on making a tournament? Just managed to take my hero to 1-st position on ZeroSum, very eager to participate in something new!

**Comment by nwinter** [comment]
What would you like to see in such a tournament? Would you be willing to help out creating and balancing a new level?

**Comment by vn971** [comment]
> What would you like to see in such a tournament?

You mean technically?
That's indeed an interesting and valid question. Gold-gathering has basically being covered already, twice (I've independently invented the same algo as WizardDude did BTW).

Maybe try out some kind of resource war this time? Say, finite resources guarded by a neutral side. The most basic set-up:
```
you
--------
gold field
yak line
gold field
yak line
gold field
--------
enemy
```

The goal then would be to kill yaks as fast as possible, and fight in the center after that.

Or maybe have dead-end "slots/holes" which contain resources (gold) and which are guarded by a neutral side. You could then chose which target to attack, how to divide forces. This will also allow choosing between lucrative and hard-to-get targets and easy ones. Could as well try to trap the enemy , or try split army to get two bonus points at once.

The problem, however, would be somewhat separate map areas until final battle occurs. This may attract players, or it may not.

Thoughts?

Regarding "creation and balancing". To be realistic, balancing is the thing I'd be most interested to participate. Ensure there is no situation like archers being always better than soldiers (in a particular type of war), or certain goals being always more lucrative than some others.

**Comment by nwinter** [comment]
We may be doing some work on some new arenas soon; would love to have your help. Let's continue the discussion [in our Slack](https://coco-slack-invite.herokuapp.com/).

**Comment by vn971** [comment]
@nwinter oh, I don't have Slack (it's proprietary). I'm only available on IRC/Matrix/XMPP/Telegram for now.
