### ISSUE TITLE
Database restore failed

### ISSUE THREAD

**Issue by W1zb1t** [codecombat/codecombat#4740]
Hi; stumbled across your project and was taking a look... had an issue setting up the dev env though.
it seems similar to the [issue](https://github.com/codecombat/codecombat/issues/3225) raised by Iian1925:

I downloaded the database dump from http://analytics.codecombat.com:8080/dump.tar.gz.
Then I unpacked the archive and ran: mongorestore --drop --noIndexRestore dump 
It failed. Here is the error
`2018-06-03T12:44:54.779+0100    preparing collections to restore from
2018-06-03T12:44:54.792+0100    reading metadata for coco.thang.types from dump\coco\thang.types.metadata.json
...
2018-06-03T12:44:57.273+0100    restoring coco.media.files from dump\coco\media.files.bson
2018-06-03T12:44:57.733+0100    [########################]  coco.media.chunks  35.3MB/35.3MB  (100.0%)
2018-06-03T12:44:57.733+0100    Failed: coco.media.chunks: error restoring from dump\coco\media.chunks.bson: reading bson input: unexpected EOF`

I tried with the --db coco option as per the guide, but that didn't work at all. I also tried with the --batchSize=100 option; no difference to without it. Also tried without the --noIndexRestore but that failed on restoring an index... so guessed that was actually needed.

Seems slightly different to Iian1925's.
Note also that the dump seemed not to exist last night. So maybe there was an issue with the archive and this is indeed incomplete. Just incase the expected size differs I am seeing the dump file as 65,092kb. 
MD5 hash of file dump.tar.gz:
94 10 41 ac d4 1d c9 ad 0e ad 26 36 b3 3e c3 b7

Enviroment: windows8.1 
c:\Dev\data>"C:\Program Files\MongoDB\Server\3.6\bin\mongo.exe" --version
MongoDB shell version v3.6.5
git version: a20ecd3e3a174162052ff99913bc2ca9a839d618
OpenSSL version: OpenSSL 1.0.2o-fips  27 Mar 2018
allocator: tcmalloc
modules: none
build environment:
    distmod: 2008plus-ssl
    distarch: x86_64
    target_arch: x86_64

Thanks

**Comment by nwinter** [comment]
Try downloading the dump again–we fixed the server that had failed to generate the complete backup.

**Comment by W1zb1t** [comment]
Works... thanks. Now just need to work out how to get the node install to work against the Visual cpp compiler
