### ISSUE TITLE
npm install error - MSB3428: Could not load the Visual C++ component “VCBuild.exe”

### ISSUE THREAD

**Issue by mlordelo** [codecombat/codecombat#4744]
I tried to install the app and got this error:

![82p3a](https://user-images.githubusercontent.com/4330747/41010414-9eba15f4-690d-11e8-9871-d8e6b734e9f9.png)

To solve it just open CMD (Git Bash or PowerShell) as administrator and try:

`npm install --global --production windows-build-tools`

After this, I could install it.

**Comment by nwinter** [comment]
Thanks @mlordelo, I've added this to the [Dev Setup: Windows](https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Windows) instructions in the wiki.
