### ISSUE TITLE
Sprites not displaying properly

### ISSUE THREAD

**Issue by MunkeyShynes** [codecombat/codecombat#4789]
This has been reported by several users.  It's more obvious on the larger sprites such as sand-yaks, burls, and brawlers, but if you look closely, even the smaller sprites are chopped up looking.  Please see the screenshots in [this thread](https://discourse.codecombat.com/t/sprite-graphics-bug/15285) for more information.

**Comment by nwinter** [comment]
Thanks for the bug report! Please clear your cache and try again (possibly waiting up to one day). We investigated and contacted our CDN, who claims to have resolved a temporary issue causing this.
