### ISSUE TITLE
Background map offset for The Final Kithmaze

### ISSUE THREAD

**Issue by ronzilla** [codecombat/codecombat#4791]
The background map is getting drawn in the wrong spot for level The Final Kithmaze; I didn't see any errors in the console.

![the_final_kithmaze](https://user-images.githubusercontent.com/1984962/43051271-3310de4e-8dcc-11e8-8c3a-0f0a2ad40a00.png)

**Comment by nwinter** [comment]
Thanks for the bug report! Please clear your cache and try again (possibly waiting up to one day). We investigated and contacted our CDN, who claims to have resolved a temporary issue causing this. See also #4789.
