### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by fabriciosribeiro** [codecombat/codecombat#4792]
Hello, I'm a beginner in codecombat development. I'm very excited about it. But I'm having trouble in one of the steps of building (https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Windows). When I type 'npn install' an error appears that I still can not solve:
error https://goo.gl/Ev64zg

I am using Windows 7 and node v6.0.0. Please help me.

**Comment by nwinter** [comment]
As @basicer mentioned in Slack, seems like old D3 -> contextify dependencies are the problem here. Let's consolidate discussion in #4655.
