### ISSUE TITLE
manaBlast spell: "zero-sum" API breakage

### ISSUE THREAD

**Issue by vn971** [codecombat/codecombat#4812]
All of a sudden "manaBlast" disappeared from ZeroSum level.
![no-manablast2](https://user-images.githubusercontent.com/1547617/43689638-4a247696-9906-11e8-8553-4a12eb5bdb5d.png)

Really guys, there should be tests for API breakage IMO...

**Comment by Catsync** [comment]
Thanks for the report... this should be fixed now.

**Comment by vn971** [comment]
Thanks for the fix! Since this issue was about a very specific property (mana-blast), I'm closing the issue.

However, If any follow-up issues on API stability/tests/metrics will be raised in next days, feel free to link them here. Thanks.
