### ISSUE TITLE
Translation does not seem to work well.

### ISSUE THREAD

**Issue by zeen263** [codecombat/codecombat#4861]
Most of menus were previously shown in Korean but currently not. 
A month ago (approximately) there were Korean texts, but now... English everywhere.
Why this happened?

**Comment by Michael18811380328** [comment]
Maybe some menus were translated false and fix bug now. And if you have enough time, you can translate Korean texts from English with us. Come to join us!

**Comment by nwinter** [comment]
There was a translation that messed up the syntax of the Korean locale file, causing it to not register the translations. @chethana-sastry has fixed it and it will be deployed next week, probably on Tuesday.
