### ISSUE TITLE
Unable to load level Ingredient Identification 

### ISSUE THREAD

**Issue by erik-smit** [codecombat/codecombat#4885]
When I try to open the Ingredient Identification level I get the follow error:

![image](https://user-images.githubusercontent.com/1376121/45689621-c154b080-bb54-11e8-80a0-c5145462e24f.png)

I’ve tried all 3 buttons, no difference.
I’ve tried on Chrome and Edge, both the same result.

If I sign out, I can do the level, but as soon as I sign in again, it fails.
It also doesn’t remember my finishing the level, so I can’t progress.

Can I skip the level somehow?
Is it related to my account?

Discourse URL: https://discourse.codecombat.com/t/unable-to-load-level-ingredient-identification/15954

**Comment by Ads20000** [comment]
The answer on Discourse is that this level is probably not working with CoffeeScript syntax yet (so this Issue should remain open until that's fixed!), add `?codeLanguage=javascript` to the URL to fallback to JavaScript.
