### ISSUE TITLE
Decoy drill level issue while incrementing a variable

### ISSUE THREAD

**Issue by fistach** [codecombat/codecombat#4943]
On the decoy drill level this code works:

> totalGold = 0
> decoysBuilt = 0
> while True:
>     coin = hero.findNearestItem()
>     
>     if coin:
>         hero.moveXY(coin.pos.x, coin.pos.y)
>         totalGold = hero.gold
>     if totalGold >= 25:
>         hero.buildXY("decoy", hero.pos.x-5, hero.pos.y)
>         decoysBuilt += 1
>     if decoysBuilt >= 4:
>         break
> hero.say("Zakończono stawianie wabików!")
> hero.moveXY(14, 36)
> hero.say(decoysBuilt)

but if you change the line
        totalGold = hero.gold
to
        totalGold += coin.value

then the hero stucks after the first decoy is built. Also if you use totalGold = totalGold + coin.value.

**Comment by nwinter** [comment]
You would have to decrement `totalGold` by 25 whenever you build a decoy if you wanted to use your own `totalGold` counter here, otherwise you think you still have 25+ gold after you built the first decoy.
