### ISSUE TITLE
Level is broken: game dev 2 jailbreak

### ISSUE THREAD

**Issue by AwokeKnowing** [codecombat/codecombat#5077]
this level is broken:
https://codecombat.com/play/level/jailbreak?

gives this error:

The initial code to build the world never finished running. It's probably either really slow or has an infinite loop. Or there might be a bug. You can either try running this code again or reset the code to the default state. If that doesn't fix it, please let us know.

You can also open the developer console to see what might be going wrong.(instructions)

console says no property 'die'

**Comment by Bryukh** [comment]
Thanks. Fixed.

**Comment by AwokeKnowing** [comment]
for the record, it did load today, but there was a return statement as the first line.  I had to comment it out for the level to work.
