### ISSUE TITLE
Do geometry calculations

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#51]
Various parts of the game engine "rely" on being able to tell whether Thangs contain or intersect each other, or how far away their nearest edges are. Thangs are either ellipses or rectangles, and may be rotated.

I haven't actually finished the geometry calculations to determine most of the rectangle-rectangle, rectangle-ellipse, or ellipse-ellipse distances, intersections, or containment, especially with rotation.

So currently most of the calculations which would depend on those are hacked around--instead of Thangs being able to collect or melee attack each other if they're touching, instead they can do so if their center points are closer than their `attackRange` or `collectRange` or whatever silly nonsense property I have. This is fiddly and not good.

Since this is so CodeCombat-agnostic as to not require figuring out good test cases within the game engine itself, I've pulled out the relevant code into a Codepen so it'll be easy to play with:

![screenshot 2014-01-02 16 34 41](https://f.cloud.github.com/assets/99704/1836781/df19a1b2-740e-11e3-8199-fa490f9a3c58.png)

[http://codepen.io/nwinter/pen/itsgx](http://codepen.io/nwinter/pen/itsgx)

Update--Julia has made some progress here: [http://codepen.io/julenka/pen/DkEtb](http://codepen.io/julenka/pen/DkEtb)

Fork that, have fun, and do however much you want to do toward:

1. Getting my simple tests at the bottom to work by calculating distances from edges instead of centers
2. Adding more tests to make sure
3. Making it work with rotation
4. Filling in methods like Thang.intersects and Thang.contains in addition to Thang.distance.

It might be helpful to also add a simple graphics layer that draws the shapes you're working with in Thang's toString() method (before it returns the string).

Or if one prefers, they can hack on the [Vector](https://github.com/codecombat/codecombat/blob/master/app/lib/world/vector.coffee) and [Rectangle](https://github.com/codecombat/codecombat/blob/master/app/lib/world/rectangle.coffee) code in the repo itself, with some of it being in the `physics.Physical` Component in the level editor. Adding tests to our [testing system](https://github.com/codecombat/codecombat/wiki/Testing) would be pretty sweet, too.

**Comment by coder0xff** [comment]
After doing quite a bit of digging and maths, the few remaining methods might not be worth it to implement if the current approximations are "good enough." In specific, there's no practical analytic solution to those problems, so root finding or some other iterative approximation is necessary. While certainly doable, the cost of computation is high (at least in comparison to the other geometry tests). If there's enough desire for them still, I'll implement them and you can decide if/when to use them.

**Comment by nwinter** [comment]
Let's call it done, then! Nice work, everyone.

**Comment by bnosrat** [comment]
huzzah!

**Comment by coder0xff** [comment]
Seems I spoke to soon. I believe I've found an analytic solution.
