### ISSUE TITLE
Link to level-design video is broken

### ISSUE THREAD

**Issue by Frazer** [codecombat/codecombat#5136]
On https://github.com/codecombat/codecombat/wiki/Artisan-Home it links to a video about level design, but when you follow the link, youtube says 'this video is unavailable'.

**Comment by Chaboi45** [comment]
Removed the broken video. Thanks for reporting! @Bryukh is there an alternative video for the broken youtube video? Or should we just stick with the vimeo one?

**Comment by Bryukh** [comment]
We don't have an alternative video
