### ISSUE TITLE
Multiplayer bug?

### ISSUE THREAD

**Issue by IrusTheGreat** [codecombat/codecombat#5166]
Hello this is my first time writing on Github so I am sorry if any info is missing at first,
I don’t know if this is a bug or something but I always select in the menu the long sword (which is currently my best sword) which gives you the ability to cleave at enemies, well the thing is that sometimes when I want to fight someone and the level loads, the little duck says that there is no “cleave” method and that it doesn’t know what it means.
At first I thought I had made a mistake and selecting the wrong sword but then I checked that I had the right sword (and I did) I found it puzzling an even more so when this started happening with more frequency.
You will see in the first image that the ¨long sword¨ is selected so I should be able to ¨cleave¨ the next image shows my code and that I can cleave. But in the last one you will that my code has changed and if you look at the method there is another sword.
The images below:
![Uploading Captura de pantalla (5).png…]()
![Uploading Captura de pantalla (3).png…]()
![Uploading Captura de pantalla (4).png…]()

**Comment by Chaboi45** [comment]
@AndrewJakubowicz, this seems to be happening to all weapon's special abilities. Also reported here: https://discourse.codecombat.com/t/ritic-not-scattershooting/17855.

**Comment by Bryukh** [comment]
@IrusTheGreat could upload new screenshots, those are broken. Possible it's just something wrong with your code.

@Chaboi45 no, that is another case and there is just wrong code which can't work.

**Comment by Chaboi45** [comment]
The weird thing is, if it **was** wrong code, then why would it work before and not now?

**Comment by Bryukh** [comment]
It works now, just fix the code.

**Comment by IrusTheGreat** [comment]
@Chaboi45 @Bryukh it is not the wrong code. the code changes itself. Are the pics not working?

**Comment by Chaboi45** [comment]
In the first picture, you're playing Blue, in the second picture, you're playing Red, so the code should be different.

**Comment by IrusTheGreat** [comment]
@Chaboi45 I know but I have submitted both sides with the cleave method so I don't know why it changes to another one and besides the sword changes too, how does that happen?
