### ISSUE TITLE
hi! it's "i18n " not fix yet?? 

### ISSUE THREAD

**Issue by Jacksonluang** [codecombat/codecombat#5178]
![image](https://user-images.githubusercontent.com/22166503/54977234-a6696a00-4fd7-11e9-80c7-aa4e4e92485f.png)
![image](https://user-images.githubusercontent.com/22166503/54978544-a1a6b500-4fdb-11e9-8a77-4707c56b21ba.png)

expect to fix ,thx

**Comment by AndrewJakubowicz** [comment]
Hi! Thanks for sharing this. We can't reproduce this.

Are you able to provide more details? (Browser, repro steps, etc...)
Here's a good [template](https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md).

**Comment by Jacksonluang** [comment]
sorry! thx!
