### ISSUE TITLE
Self-created levels inaccessible?

### ISSUE THREAD

**Issue by Chaboi45** [codecombat/codecombat#5186]
Created several levels in the direct servers(direct.codecombat.com) and trying to access them on the normal server(codecombat.com), it prevents me from accessing the level that I made

**Comment by AndrewJakubowicz** [comment]
Thanks for reporting this.
That's very strange as the direct.codecombat.com and codecombat.com use the same database.
The only difference is that codecombat.com has some caching.

Would you be able to provide more details like your level name.
Could you also try using private browsing mode with codecombat.com

**Comment by Chaboi45** [comment]
Seems to be fixed the second time I tried it. Strange.
