### ISSUE TITLE
Pixie Release

### ISSUE THREAD

**Issue by Chaboi45** [codecombat/codecombat#5231]
Tasks:

- [x] Animations
- [x] Spritesheets
- [x] Price
- [x] Sounds
Abilities:
- [x] Flap(Wind Gust)
- [x] Flap animations
- [x] Pacify(Weakens enemy)
- [x] Pacify animations
- [x] Paralyze(Paralyzes the enemy)
- [x] Paralyze animations

@nwinter. is this ok?

**Comment by Chaboi45** [comment]
I will update this and add a public testing link once I'm finished configuring them.

**Comment by Chaboi45** [comment]
More details for abilities:

- [x] Flap
Like Windstorm, it shoots a gust of wind around the user, pushing/blocking projectiles/mobile-thangs with a wind mass of ≈5 kg. (Might change). The user will say, "<FLAP>" during the usage of this movement. 

Stats:
```
|   Mass   | Cooldown    |   Duration   |
|   5 kg.  |     0.1s.   |     Nan s.   |
```
- [x] Paralyze
Paralyzes **both** heroes and thangs for around 3 seconds. The paralyzed thang/hero will say "I...can't...move" after being paralyzed. My current setting for the range is 7m, but might be shifted later after the first ability testing has started. 

Stats:
```
|   Damage   | Cooldown    |   Duration   |
|       0    |      15s.   |       3s.    |
```

- [x] Pacify
Temporarily lowers their health during the 7 seconds of this ability. Reduces damage and speed, and makes them weaker and more vulnerable. 

Stats:
```
|      Damage          |Cooldown|Duration|
|Proportional to health|   15s. |   7s.  |

```

Plus...
Envenom, which is poisonous missiles. Use Naria(Forest Archer), to see the effect. 

We're almost there! I'll comment on this "Issue" when there are new updates on Zana's release. 

![b9a6ff7ee9d4b328a85ed6993f4955e2743229f1](https://user-images.githubusercontent.com/29741391/56494948-fda71f80-652e-11e9-8268-fe72b6dd1c10.jpg)

**Comment by Chaboi45** [comment]
Milestone A:
- [x] Paralyze Alpha Stage

Now Paralyze() will be moved to Beta for testing. Links will be shared out privately in a few business days. 

- [x] Flap 

Flap is almost ready! A few more configurations and adjustments and we're done. 

- [ ] Pacify

I noticed a few bugs when using this ability. I will have to work on this again and fix whatever it's causing Pacify to malfunction.

**Comment by Chaboi45** [comment]
Code snippets:
Pacify:
`hero.pacify(target)`

Flap:
`hero.flap()`

Paralyze:
`hero.paralyze(target)`

**Comment by Chaboi45** [comment]
Task B:
- [ ] Add KB to Pacify.
- [ ] Add a small ring around hero during Paralyze. 
- [ ] Balance the broken Pacify

**Comment by Chaboi45** [comment]
Milestone B:
I finished Pacify and Paralyze. A few more configurations and I'll start Beta Test!

**Comment by Chaboi45** [comment]
Milestone C:
Beta Test Has Started!

**Comment by Chaboi45** [comment]
Right now, it's only available to codecombat team members. I'll give it out publicly soon!

**Comment by codeluggage** [comment]
This is excellent, wow! 🎉

**Comment by Chaboi45** [comment]
Full checklist:
- [ ] Price
- [ ] Sounds
- [ ] Animations
- [ ] Ability Narraration
- [ ] Alpha Stage
- [ ] Beta Stage
- [ ] Release
- [ ] Private Team Testing
- [ ] Selected Public Testing
- [ ] Public Testing 
- [ ] Pacify 
- [ ] Pacify Moveset
- [ ] Paralyze Sounds
- [ ] Paralyze
- [ ] Paralyze Moveset
- [ ] Paralyze Sounds
- [ ] Flap
- [ ] Flap Animations
- [ ] Flap Sounds
- [ ] Flap Moveset
- [ ] Spritesheets
- [ ] Damage Multiplier
- [ ] Health Multiplier
- [ ] Speed
- [ ] Choose Tier
- [ ] Choose Location in Hero Shop

**Comment by Chaboi45** [comment]
I usually hate giving spoilers, but I guess this time, I'm willing to do so. 
Stats:
Health: 160%
Damage: 83.34%
Speed: 11m/s

**Comment by Chaboi45** [comment]
Here's the animation that I made for paralyze:
![output_qdl4MK](https://user-images.githubusercontent.com/29741391/56845419-d15b1c80-68fb-11e9-9cb5-b99ba44342fc.gif)

**Comment by Chaboi45** [comment]
Pacify animation:
https://media.giphy.com/media/YqcrMWouKuXP5IZB9L/source.gif

**Comment by Chaboi45** [comment]
Released
