### ISSUE TITLE
error codecombat@1.0.0 proxy: `COCO_PROXY='true' nodemon`

### ISSUE THREAD

**Issue by aabababb** [codecombat/codecombat#5620]
npm run proxy

then get the error
```
error codecombat@1.0.0 proxy: `COCO_PROXY='true' nodemon`
```

**Comment by codeluggage** [comment]
Hi @aabababb - that's unfortunate. Were you able to fix this? 

We've just updated the onboarding guide to include a [docker guide](https://github.com/codecombat/codecombat/wiki/Docker-guide) which is much easier to get started with, and includes all the dependencies you need. That may be helpful!

**Comment by Sketti385** [comment]
How do I fix this? COCO_PROXY is not a command no matter what i do.
