### ISSUE TITLE
Interface broken and cannot play

### ISSUE THREAD

**Issue by aagrossman** [codecombat/codecombat#5664]
When opening the entire site the layout is off then when entering the game there is a PICOCTF watermark in the top left and icons aren't clickable. Login doesn't work from the board selector. Was able to login from the homepage though once breaking through that the game interface is also broken. Attempted on Chrome (regular and incognito) and Safari. Also attempted to clear site cache.

![Screen Shot 2019-11-06 at 3 47 15 PM](https://user-images.githubusercontent.com/14900421/68336631-cce29e00-00ac-11ea-9697-548a0f76ab17.png)

![Screen Shot 2019-11-06 at 3 48 17 PM](https://user-images.githubusercontent.com/14900421/68336716-f4d20180-00ac-11ea-977d-bd8e5710e4b2.png)

**Comment by AndrewJakubowicz** [comment]
We had a brief outage. Everything should be resolved now.
Is the site working correctly after a refresh @aagrossman  ?
Thanks for opening an issue.

**Comment by AndrewJakubowicz** [comment]
Closing as we believe it's resolved.
