### ISSUE TITLE
Site is not operational

### ISSUE THREAD

**Issue by shoddy89** [codecombat/codecombat#5665]
just got done subscribing to the website and now everything is broken. icons don't work and home page is out of wack. I really hope my subscription went through and I didn't lose my $10 to the void.

**Comment by AndrewJakubowicz** [comment]
We had a brief outage. Everything should be resolved now.
Is the site working correctly after a refresh?

**Comment by AndrewJakubowicz** [comment]
Thanks @shoddy89 , closing as I believe it's resolved.
