### ISSUE TITLE
is it full open source or just part of open source

### ISSUE THREAD

**Issue by gaoyuqi** [codecombat/codecombat#5672]
as shown above, if full open source, I'd like to join as contributor.

**Comment by nwinter** [comment]
Hi @gaoyuqi, our client-side codebase (most of it) is open source; the server side is now closed source. This was in part to make it easier to contribute to (use our servers in proxy mode to contribute to the client), partially to help us maintain control over our server deployments in China. Happy to welcome your contributions to the project!
