### ISSUE TITLE
is this bound with www.163.com in China?

### ISSUE THREAD

**Issue by gaoyuqi** [codecombat/codecombat#5675]
as shown in the title,  once we deploy this site locally, and run the start page, it navigates to https://codecombat.163.com/play/level/dungeons-of-kithgard?
so, is this open source from 163 company in china? 
any advice is warmly welcome

**Comment by nwinter** [comment]
What commands are you running to run the server? Proxy mode development shouldn't redirect to the China server, maybe there is some bug there.
