### ISSUE TITLE
Proposal: Attendance event

### ISSUE THREAD

**Issue by JaewonLee0217** [codecombat/codecombat#5692]
Proposal
In this game, we can collect gems for playing games or purchasing , and we can buy equipments for each characters. Game Event is important to increase participation for game, so i think the attendance event is effective to increase more participation and interest of this game.

**Comment by nwinter** [comment]
Thanks for the suggestion! We have done live events in the past as an experiment, but our focus is elsewhere at the moment, so until we have a dedicated "live ops" game team, we won't be able to support these.
