### ISSUE TITLE
Can't play web development leve's

### ISSUE THREAD

**Issue by AldairReis** [codecombat/codecombat#5758]
I can't play those levels, I've tried it with a lot of browsers. That the error I get:

![image](https://user-images.githubusercontent.com/28535314/74087278-65e8d280-4a69-11ea-8931-2e7d4a93a5e4.png)

**Comment by codeluggage** [comment]
Hi @AldairReis, this is a really frustrating issue, and I have been looking into it. This screenshot is really useful for finding the issue! 

It is specifically for connections from Brazil. Until this has been resolved, you can get around it by using a VPN. You can use a VPN to set your country to a different country than Brazil, and then the connection would work. 

We are working on a fix so using a VPN is not necessary. I'll report back here once the issue has been fixed 👍

**Comment by nwinter** [comment]
I've made some code changes in our various repositories that should fix this. It's not live yet, but it will be deployed sometime later this week (probably sometime on Tuesday). After that goes up, there should be no more issues for web development in Brazil.
