### ISSUE TITLE
[Log In Bug] Broken Facebook Button

### ISSUE THREAD

**Issue by LWFlouisa** [codecombat/codecombat#5773]
Was there any plans to outmode the Facebook log in? As it is, I can only log in on Mobile version rather than through the desktop, which is where I do the majority of my programming.

I just woke up today, and found I couldn't log in with the Facebook button. Which means having to create an account through google and starting over.

**Comment by codeluggage** [comment]
Hi @LWFlouisa, thank you for reporting this. We have had some trouble with this in the past. A known issue right now is that browser with more privacy protection like Firefox and Safari, especially when using privacy plugins, block social logins such as this. 

I was able to start the process in Chrome. Which browser are you experiencing this on? Have you tried other browsers?

**Comment by LWFlouisa** [comment]
I've most frequently had the trouble in Firefox. I might try to see how it works in Nativefier as a stand alone app.
