### ISSUE TITLE
Random Paths should lead somewhere

### ISSUE THREAD

**Issue by LWFlouisa** [codecombat/codecombat#5801]
[Untraversible Path](https://cdn.glitch.com/f9022043-9c1a-424e-88f8-d54d190fcaf6%2Fcodecombat.png?v=1584810877086)

Random is good, as long as you find a way to make sure whatever is generated actually leads to some place. This goes back to the generate a small room problem in roguelikes.

This explains why I could have perfectly working code, and it would still say I have "fault logic".

it's not my logic, this is lazy programming.

**Comment by Bryukh** [comment]
So line 20 you are trying to move directly to the next points avoiding the choice top or bottom way. You need to choose between (32, 33) and (32, 13) (the same X coordinate). On line 16 you are trying to move the top path always without checking conditions.
There is always a path.
