### ISSUE TITLE
Official Docker images at Docker Hub

### ISSUE THREAD

**Issue by alexanderadam** [codecombat/codecombat#5825]
Hi folks, thank you so much for your work! :pray: 

Currently there are a lot of [outdated images at Docker Hub](https://hub.docker.com/search?q=codecombat&type=image&sort=updated_at&order=desc).
So i guess it would be great to have an official image, which is automatically build with every Release (i.e. [with GitHub actions](https://help.github.com/en/actions/building-actions/creating-a-docker-container-action)). Otherwise people might think that CodeCombat is not such a good experience although they are just using old code which has been fixed in recent releases.

There are also [a few Dockerfiles on GitHub](https://github.com/search?l=&q=codecombat+language%3ADockerfile&type=Code) (in case you need some inspiration).
Also the folks at [OPE (Open Prison Education)](https://github.com/operepo) made [an image](https://github.com/operepo/ope_documentation/blob/0d02bd7575896d3ce0fef6780313f7431f83909b/README.md#codecombat) and published the [build files](https://github.com/operepo/ope/tree/master/docker_build_files/ope-codecombat). Naturally they can't access anything from the internet, once the image is delivered.

Also an official image could follow some of the best practices like [not running as `root`](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user) and having a small footprint.

**Comment by codeluggage** [comment]
This is a great request @alexanderadam and we're about to do a big overhaul to make it easier to get started with CodeCombat using Docker. Github Actions is on our radar, and it's a great idea to include the image as part of an automatic build so the latest version is always available. I've surfaced this to the team so we can prioritize it. 

I'll comment on this issue once a new image has been posted, and with more details on what's happening with automatic builds.

**Comment by alexanderadam** [comment]
That's awesome news @codeluggage, but could you please leave this issue open then until it is solved?
This way people could see it and track its progress.

**Comment by codeluggage** [comment]
Yep no problem!

**Comment by codeluggage** [comment]
@alexanderadam I'm excited to share that the docker image is now up on [Docker Hub](https://hub.docker.com/r/codeluggage/codecombat-proxy)! 

There's also a [brand new guide](https://github.com/codecombat/codecombat/wiki/Docker-guide) for getting set up with `docker-compose` locally, which I warmly recommend. 

We are getting set up with Github Actions, and will start including builds with the merges we do too, so the image will always be up to date 👍 

Hope this solves everything for you!

**Comment by alexanderadam** [comment]
> @alexanderadam I'm excited to share that the docker image is now up on [Docker Hub](https://hub.docker.com/r/codeluggage/codecombat-proxy)!

Thank you for your work, @codeluggage.

I have some further questions, though:

1. Your links in the comment and in the wiki, go to `codeluggage/codecombat-proxy`. So I guess this is just temporary and it will be `codecombat/app` later on (or at least something else in the namespace of the `codecombat` organization)?
2. There are no image tags in your link. Not even a valid `latest` tag.
3. Your image is called `-proxy`. Why "proxy"? Does this mean, that this isn't an offline-ready image?
4. Would it be possible to add the used `Dockerfile`.
