### ISSUE TITLE
it seems that mongodb dump link is broken!

### ISSUE THREAD

**Issue by robmlee** [codecombat/codecombat#5827]
Hi there,

Today when I try the command below:
(cd $(mktemp -d /tmp/coco.XXXXXXXX) && curl http://analytics.codecombat.com:8080/dump.tar.gz | tar xzf - && mongorestore --drop --host 127.0.0.1)

I got an error as follow:
> 
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.12.0</center>
</body>
</html>

<br>
I don't know whether is URL broken or something is wrong with the server. Does anyone has same issue?

**Comment by codeluggage** [comment]
Hello @robmlee! The mongodb dump is no longer available. 

We recommend that you use the new [docker guide](https://github.com/codecombat/codecombat/wiki/Docker-guide) to get set up with the local environment. That will let you read data directly from codecombat.com, so you can get all the levels and content directly. 

If you do need to run a local server, we have some new details up on [the FAQ](https://github.com/codecombat/codecombat/wiki/Archmage-Home#how-can-i-run-the-codecombat-server) about this.
