### ISSUE TITLE
dump.tar.gz NOT found

### ISSUE THREAD

**Issue by goldseek** [codecombat/codecombat#5830]
hi,  
http://analytics.codecombat.com:8080/dump.tar.gz  404 not found.  

can you help give a new link?

thanks very much!

**Comment by codeluggage** [comment]
Hi @goldseek ! We are no longer providing this download, as we are focused on running the local environment as a proxy directly to codecombat.com. That way you get all the levels and all the content. 

The guide to get set up that way has been updated here: [docker guide](https://github.com/codecombat/codecombat/wiki/Docker-guide)

If you really do need to run a local server, there are some more details about that [here in the FAQ](https://github.com/codecombat/codecombat/wiki/Archmage-Home#how-can-i-run-the-codecombat-server).

**Comment by YihaoPeng** [comment]
You can find it from web archive:
https://web.archive.org/web/20150813174038if_/http://analytics.codecombat.com:8080/dump.tar.gz

Thank this project to help us fight against time.

**Comment by SwimmingTiger** [comment]
A version that upload to Baidu Disk on 2018-11-04:
https://pan.baidu.com/s/1cBqOWv6QEr-zB5j7aHtvSw

https://drive.google.com/drive/folders/1ZvqDVHYYHZ20al_k_m6PYksG-VZUzw9l?usp=sharing

**Comment by SwimmingTiger** [comment]
The Lua code works extremely well. My friend will be very happy with this version.
![image](https://user-images.githubusercontent.com/4986069/87235352-d4153500-c40d-11ea-9f30-2a3cfa62dcc3.png)

So I think it is never a good idea to delete the old version. Especially when the old version has features that the new version does not.

**Comment by YihaoPeng** [comment]
The last commit with server code is https://github.com/codecombat/codecombat/tree/f278c9ca202d087f67c409fe53e3922b5a6e4b8a

The next commit https://github.com/codecombat/codecombat/tree/17c793547be604b81ece2de7603e4a3d23340d0d deleted the server directory

**Comment by velcrine** [comment]
@YihaoPeng So does this last commit with server code works well with the database u have sent?? What commit u are using?? Pls tell, very important for me

**Comment by YihaoPeng** [comment]
> @YihaoPeng So does this last commit with server code works well with the database u have sent?? What commit u are using?? Pls tell, very important for me

I use my fork:

https://github.com/SwimmingTiger/codecombat/commits/deploy

**Comment by velcrine** [comment]
@YihaoPeng  Just one last question, what are credentials of admin user.

**Comment by velcrine** [comment]
```Error: Loading chunk 6 failed.
    onScriptComplete app.js:101
    requireEnsure app.js:93
    AccountSettingsRootView dynamicRequire.js:5
    routeDirectly Router.coffee:272
    go Router.coffee:4
    Backbone 2
    some Lodash
    Backbone 2
    init initialize.coffee:45
    <anonymous> initialize.coffee:206
    jQuery 8
    <anonymous> app.js:160
    __webpack_require__ app.js:52
    <anonymous> 397:61
    <anonymous> app.js:2108
    __webpack_require__ app.js:52
    <anonymous> npm.js:2
    <anonymous> app.js:2102
    __webpack_require__ app.js:52
    <anonymous> app.js:1
    <anonymous> 395:20
    <anonymous> app.js:2096
    __webpack_require__ app.js:52
    <anonymous> app.js:147
    <anonymous> app.js:150
Router.coffee:289:14

​```

**Comment by velcrine** [comment]
docker run -p 5000:5000 -itv /fullpath/to/an/empty/directory:/var/lib/mongo velcrine/jaishreeradhe
loginCreds=>
username: shreekrishn
password: vrindavan

enjoy the godMode account and an admin too. Only thing that doesn't works is sending email, hence new subscribed users can't be made, as they require an email to be sent.

**Comment by hsiangko** [comment]
In velcrine/jaishreeradhe docker images ,teacher can not assign course to students ,and student do not have any  courses,help me, thanks

**Comment by hsiangko** [comment]
> docker run -p 3000:3000 -itv /fullpath/to/an/empty/directory:/var/lib/mongo velcrine/jaishreeradhe
> loginCreds=>
> username: shreekrishn
> password: vrindavan
> 
> enjoy the godMode account and an admin too. Only thing that doesn't works is sending email, hence new subscribed users can't be made, as they require an email to be sent.

In velcrine/jaishreeradhe docker images ,teacher can not assign course to students ,and student do not have any courses,help me, thanks

**Comment by velcrine** [comment]
it is supposed to be used in a way that any one has access to all the stages. I was not interested in teacher mode. 
There needs to be some tweaking in source code for teacher mode.
As @YihaoPeng  said, few stages are broken, hence,  god mode is the only way to cover all.

**Comment by hsiangko** [comment]
> it is supposed to be used in a way that any one has access to all the stages. I was not interested in teacher mode.
> There needs to be some tweaking in source code for teacher mode.
> As @YihaoPeng said, few stages are broken, hence, god mode is the only way to cover all.

thanks

**Comment by hsiangko** [comment]
> it is supposed to be used in a way that any one has access to all the stages. I was not interested in teacher mode.
> There needs to be some tweaking in source code for teacher mode.
> As @YihaoPeng said, few stages are broken, hence, god mode is the only way to cover all.

can you tell me how can i change new register people to gold mode/admin mode in your dock
when i use username: shreekrishn login system
i can not set new registered pople to gold mode/admin mode
 I must use the database command method to change admin mode??
thank you.

**Comment by velcrine** [comment]
I can share with you the steps, how I did what much I did.

First, take the commit provided by YihaoPeng in above messages.
Try building in ubuntu 16.04 with the npm and node version described in Readme.md in that commit.

I can share my history file for that time:
```
    8  sudo apt install npm
   10  sudo npm install -g n
   12  sudo n 6.12.2
   13  cp -R ../m/codecombat-d85c7cec8aa975f4b3f63d99456f7b98597e1c81/ codecombat
   14  cd codecombat/
   17  node --version
   18  npm --version
   20  sudo npm install -g npm@3.10.10
   22  . ~/.bashrc 
   23  npm --version
   24  npm install #this will take hack lot of time
   25  cd ..
   26  cp -R codecombat/ ../m/codecombatworking
   27  cd codecombat/
   28  npm run
   29  npm run nodemon
# and proceed further only if it runs.
```
then in the dockerfile:
```
from ubuntu:xenial
workdir oval
run echo $PATH
run apt-get update
run apt-get install -y libcurl3 openssl npm curl
run npm install -g n
run n 6.12.2
add ./mongo/*  /usr/local/bin/mongo/

add codecombat.tar.gz ./
copy ./dump2 ./dump2
add ./entrypoint.sh ./
run chmod -R a+rwx ./entrypoint.sh

entrypoint [  "bash" ]
cmd ["entrypoint.sh"]


```

in entrypoint.sh
```
/usr/local/bin/mongo/mongod --dbpath /var/lib/mongo & 
sleep 2
echo waiting for mongo server
sleep 15

/usr/local/bin/mongo/mongo --eval 'db.getMongo().getDBNames()' | tail -1
set +e
/usr/local/bin/mongo/mongo --eval 'db.getMongo().getDBNames()' | tail -1 | grep '"coco"'


if [[ $? == 1 ]]; then 
set -e
/usr/local/bin/mongo/mongorestore --drop --noIndexRestore --host 127.0.0.1 ./dump2 ; 
 fi
 set -e
cd ./codecombat/
node ./index.js
```

**Comment by velcrine** [comment]
So these steps, only for running your own codecombat.
Now you can experiment with your code&db on your own.

the mongo version is also very old. U might want to download that too, in a weird way.

**Comment by hsiangko** [comment]
> So these steps, only for running your own codecombat.
> Now you can experiment with your code&db on your own.
> 
> the mongo version is also very old. U might want to download that too, in a weird way.

thanks ,I will try it

**Comment by velcrine** [comment]
arigatoguzaimasta

**Comment by hsiangko** [comment]
> arigatoguzaimasta

Hello, how do I connect to the MongoDB database through the MongoDB Compass software? I have changed the bind_ip to 0.0.0.0, but it was unsuccessful, and I cannot find the mongo.conf file because I want to use the MongoDB Compass software to read Get information,thanks.

**Comment by velcrine** [comment]
it seems you are not ready to this task, it would prove super complex to you are stuck at that point. Because that commit is way too old.

**Comment by haobohuiying** [comment]
> it seems you are not ready to this task, it would prove super complex to you are stuck at that point. Because that commit is way too old.

![image](https://github.com/user-attachments/assets/5a7477c7-c9fa-4f1c-bc49-b3014530f627)
learning html module, show "localhost access deny", how to fix it

**Comment by supershopping** [comment]
Can anyone share a newer dump.tar.gz file please? Thanks.
