### ISSUE TITLE
Open source this abandoned project?

### ISSUE THREAD

**Issue by PatrickMassot** [codecombat/codecombat#5845]
One month ago I wasted a couple of days with CodeCombat (especially writing translations) because I didn't realize it was abandoned in favor of Ozaria. Given that it received many community contributions since its beginning, wouldn't it make sense to fully open-source it, including levels? This move would allow this project to continue to live around the world (and not only for English speaking children). This is a pretty common workflow for abandoned proprietary software, and makes even more sense for partially open-source project like CodeCombat.

**Comment by regeter** [comment]
+1
I think it could be really great, I think it's not fully abandoned, but mostly volunteers are creating new levels etc.

**Comment by alexanderadam** [comment]
> wouldn't it make sense to fully open-source it, including levels?

Could you please elaborate on this? Does this mean a local build won't have all levels by default? :thinking:

**Comment by PatrickMassot** [comment]
See https://github.com/codecombat/codecombat#license: "Note: the levels on codecombat.com are not open source." and more details at "https://github.com/codecombat/codecombat/blob/master/LICENSE-LEVELS.md".

**Comment by alexanderadam** [comment]
I've used some codecombat Docker images that I found on Docker Hub before and they obviously contained levels (see also [the request for an official image](https://github.com/codecombat/codecombat/issues/5825)).
Does the Docker images have _fewer_ levels or simply the same used with a different license?

**Comment by Dranaxel** [comment]
Hi @PatrickMassot I think it would be a great idea to re-use the code of the game and make it all open source by creating new levels. Same as adding translations so it could be  use widely around the world

**Comment by MaikNog** [comment]
+1 
I also started completing the existing German translation, that was one month ago.

I do respect the volunteers time and their initial effort, but I don't see myself investing more time at the moment.

Even responses here are slow.

Open Source the main part and give active contributor more permissions here to merge PRs or such.

**Comment by Dranaxel** [comment]
So first part of the work would be to delete all the non open source content then redefine contributing guidelines to finally create a new story, does it looks good or am i forgotting something ?

**Comment by PatrickMassot** [comment]
@Dranaxel what you want is already possible, without deleting anything. I think everything that is publicly available is open source. But creating a nice set of levels from scratch is a huge amount of work. 

What I think is really bad here is that many people contributed to those closed source levels, especially by providing translations, and they can't use this work anymore. In the beginning it was fair since the deal was clear and translations efforts were reflected in the game. But now all those outdated translations become unusable (there is no point telling children to play a half translated game) and the translation work is locked in, so we can't take over the maintenance work.

At the very least, the codecombat company should put huge banners on the translation pages saying clearly that contributions are no longer welcome, or that people should expect to wait several months before seeing the result of their translation work.

Look at the number of employees listed at https://codecombat.com/about. Isn't it striking that nobody there is listed as taking care of translations (except for Chinese)? 
And look at #5816: not a single answer since April 1st. Here we get neither the professionalism that is expected from a company selling a product nor the possibilities of open source.

**Comment by Dranaxel** [comment]
Patrick, I totally agree with you. This is a pretty bad sign sent to the
community which worked and cared the project at the beginning.

However my idea was to fork the project and allow only open source levels
in order to make the whole game open source and usable all over the world.
As I agree creating levels would be a huge amount of time we first only
need to launch the movement and see what happens, I personally plan to use
this game with an non-profit training kids with programmation so it can
help us to get material on a regular basis

Le dim. 24 mai 2020 à 14:04, Patrick Massot <notifications@github.com> a
écrit :

**Comment by Chaboi45** [comment]
Ozaria is the main priority **at the moment**, it still lacks enough content for the classroom, and due to Covid-19, the demand for online classroom content spiked. I assure you more attention will be brought back to CoCo once everything settles down and Ozaria is stable.

**Comment by alexanderadam** [comment]
> Ozaria is the main priority **at the moment**

Well, in that case it would make sense to open up more — _especially_ in this case. Because external contributors can help you out on codecombat if everything is open while you're focused on ozaria , right?

**PS:** Is someone able to answer [my question from above](https://github.com/codecombat/codecombat/issues/5845#issuecomment-629983764)?

**Comment by codeluggage** [comment]
Thank you for bringing this up @PatrickMassot, and thank all of you for your thoughts and suggestions in this thread.

We hear you, and we're excited to finally get to the point where we can dedicate more engineering resources to this! To begin with, here's what we're going to do: 

* Overhaul the onboarding experience, including an official Docker image and a step by step guide to get started
* Clean up the wiki and guides, bringing everything up to date
* Start up the translation work again, going through the open PR's to merge them and include them in the codecombat.com builds
* Start up work on the backlog of issues and PR's again, with regular triaging and communication

Expect to hear more in the coming days and weeks as we ramp this up. We'd love to hear your thoughts.
