### ISSUE TITLE
Level code is not moving the character to the right place.

### ISSUE THREAD

**Issue by yowshee** [codecombat/codecombat#5855]
In the level One Wrong Step, moving the character to (40, 56) actually moves them to (43, 56). When you go anywhere close to the gem, it just hits some sort of invisible barrier. I don't get what is going on at all. 

Thanks

**Comment by nwinter** [comment]
@yowshee which character? What's the rest of the code? Trying to figure out the problem here.

**Comment by yowshee** [comment]
The Character is: Ritic The Cold
The Code is:
# The hero is all confused!
# Correct their path so they don't walk on the mines.

hero.moveXY(11,36)
hero.moveXY(35,25)
hero.moveXY(77,58)
hero.moveXY(40,56)

**Comment by nwinter** [comment]
I see; you got to the exit gem first, then tried to back for third gem, but level ended a moment too soon. I tweaked it so you can get those gems in either order.
