### ISSUE TITLE
Character tries to move beyond wall in Sesame Path

### ISSUE THREAD

**Issue by themadpsychologist** [codecombat/codecombat#5916]
I'm running into some very strange behavior with positions in Sesame Path. Tharin says the passcode, the door to his right opens, and he moves (in an odd arc) to (34, 10) as he ought. But then he wobbles forever against the wall between (34, 10) and (34, 9), trying to reach (34, 8).

It may be worth noting that, after the door is opened, `hero.isPathClear(hero.pos, {"x": hero.pos.x + distance, "y": hero.pos.y}) = False`, whereas `hero.isPathClear({"x": hero.pos.x + distance, "y": hero.pos.y}, hero.pos) = True`.

My code:

```
sesame = "Open Sesame"
distance = 24
previous = ""

positions = [{"x": hero.pos.x, "y": hero.pos.y + distance}, {"x": hero.pos.x + distance, "y": hero.pos.y}, {"x": hero.pos.x, "y": hero.pos.y - distance}, {"x": hero.pos.x - distance, "y": hero.pos.y}]

hero.moveXY(10, 10) # to remove ambiguity; has the same result

while True:
    hero.say(sesame)
    for i in positions:
        if hero.isPathClear(i, hero.pos): # because that's the order that works, as stated
            if i != previous:
                previous = hero.pos
                hero.moveXY(i.x, i.y)
```

Screenshot of Tharin's useless flailing: https://www.dropbox.com/s/d6zm0dho20cfr4y/Sesame%20Path.PNG?dl=0

**Comment by themadpsychologist** [comment]
Sorry. Closing it was accidental.

**Comment by nwinter** [comment]
I can see two problems:
1. You need to define `positions` inside the loop, so it updates them from where your hero is at
2. The `previous` variable isn't going to be exactly equal like that. You might check that the distance between the new target position and where you were before, to see if it'd be the same as going backwards.

**Comment by themadpsychologist** [comment]
> I can see two problems:
> 1. You need to define `positions` inside the loop, so it updates them from where your hero is at
> 2. The `previous` variable isn't going to be exactly equal like that. You might check that the distance between the new target position and where you were before, to see if it'd be the same as going backwards.

Whoa. I thought I had finally found an actual bug; instead, I learned a bit about how Python works that I must have forgotten. Many thanks, Nick!
