### ISSUE TITLE
Level "zero sum" allows decoys, which breaks the game

### ISSUE THREAD

**Issue by vn971** [codecombat/codecombat#5955]
"Zero sum" seems to be broken in the last months. Players like "OLEASA" (top-1), "fatDecoy" are commanding peasants to build decoys on this map. Building decoys causes all allies to attack the decoys in a loop, even if instructed to do `while (true) { hero.say("test"); }`

This is obviously OP on this map as enemy hero stops gathering gold and has no control over its actions. I would suggest disabling decoys for this map entirely, or setting decoy HP to 1, or allowing to not attack decoys with main hero and allies.

Previously and originally, decoys were not "magnets" for allied attack, and you could instruct your hero and allies to ignore decoys.

**Comment by nwinter** [comment]
Thanks; I nerfed the decoys to only have 40 health and 15 meter lure range on this map after [discussion on the forum](https://discourse.codecombat.com/t/are-decoys-too-annoying-in-multiplayer/25091).

**Comment by vn971** [comment]
Oh nice, thanks for the answer and the fix!
