### ISSUE TITLE
docker ERR in the end

### ISSUE THREAD

**Issue by wjinyao** [codecombat/codecombat#5963]
=======================================================================
Starting coco_proxy_1 ...  done   
Attaching to coco_proxy_1
proxy_1  |
proxy_1  | > webworker-threads@0.6.4 install /coco/node_modules/webworker-threads
proxy_1  | > node-gyp rebuild
proxy_1  |
proxy_1  | make: Entering directory '/coco/node_modules/webworker-threads/build'
proxy_1  |   CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
proxy_1  | In file included from ../node_modules/nan/nan.h:194:0,
proxy_1  |                  from ../src/WebWorkerThreads.cc:12:
proxy_1  | ../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)':
proxy_1  | ../node_modules/nan/nan_maybe_43_inl.h:221:58: warning: 'v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3566): Cloning is not supported. [-Wdeprecated-declarations]
proxy_1  |    return array->CloneElementAt(GetCurrentContext(), index);
proxy_1  |                                                           ^
proxy_1  | In file included from ../node_modules/nan/nan_new.h:189:0,
proxy_1  |                  from ../node_modules/nan/nan.h:200,
proxy_1  |                  from ../src/WebWorkerThreads.cc:12:
proxy_1  | ../node_modules/nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)':
proxy_1  | ../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: 'static v8::Local<v8::Value> v8::BooleanObject::New(bool)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:4895): Pass an isolate [-Wdeprecated-declarations]
proxy_1  |    return v8::BooleanObject::New(value).As<v8::BooleanObject>();
proxy_1  |                                       ^
proxy_1  | In file included from ../src/WebWorkerThreads.cc:12:0:
proxy_1  | ../node_modules/nan/nan.h: At global scope:
proxy_1  | ../node_modules/nan/nan.h:602:20: error: variable or field 'AddGCEpilogueCallback' declared void
proxy_1  |        v8::Isolate::GCEpilogueCallback callback
proxy_1  |                     ^
proxy_1  | ../node_modules/nan/nan.h:602:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
proxy_1  |        v8::Isolate::GCEpilogueCallback callback
proxy_1  |        ^
proxy_1  | ../node_modules/nan/nan.h:603:18: error: expected primary-expression before 'gc_type_filter'
proxy_1  |      , v8::GCType gc_type_filter = v8::kGCTypeAll) {
proxy_1  |                   ^
proxy_1  | ../node_modules/nan/nan.h:608:20: error: variable or field 'RemoveGCEpilogueCallback' declared void
proxy_1  |        v8::Isolate::GCEpilogueCallback callback) {
proxy_1  |                     ^
proxy_1  | ../node_modules/nan/nan.h:608:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
proxy_1  |        v8::Isolate::GCEpilogueCallback callback) {
proxy_1  |        ^
proxy_1  | ../node_modules/nan/nan.h:613:20: error: variable or field 'AddGCPrologueCallback' declared void
proxy_1  |        v8::Isolate::GCPrologueCallback callback
proxy_1  |                     ^
proxy_1  | ../node_modules/nan/nan.h:613:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
proxy_1  |        v8::Isolate::GCPrologueCallback callback
proxy_1  |        ^
proxy_1  | ../node_modules/nan/nan.h:614:18: error: expected primary-expression before 'gc_type_filter'
proxy_1  |      , v8::GCType gc_type_filter = v8::kGCTypeAll) {
proxy_1  |                   ^
proxy_1  | ../node_modules/nan/nan.h:619:20: error: variable or field 'RemoveGCPrologueCallback' declared void
proxy_1  |        v8::Isolate::GCPrologueCallback callback) {
proxy_1  |                     ^
proxy_1  | ../node_modules/nan/nan.h:619:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
proxy_1  |        v8::Isolate::GCPrologueCallback callback) {
proxy_1  |        ^
proxy_1  | ../node_modules/nan/nan.h: In function 'bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)':
proxy_1  | ../node_modules/nan/nan.h:1961:16: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3236): Use maybe version [-Wdeprecated-declarations]
proxy_1  |      , attribute);
proxy_1  |                 ^
proxy_1  | In file included from ../src/WebWorkerThreads.cc:17:0:
proxy_1  | ../src/bson.cc: In member function 'v8::Local<v8::Value> BSONDeserializer::DeserializeDocumentInternal(bool)':
proxy_1  | ../src/bson.cc:428:37: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |    returnObject->ForceSet(name, value);
proxy_1  |                                      ^
proxy_1  | In file included from ../src/WebWorkerThreads.cc:17:0:
proxy_1  | ../src/bson.cc:437:69: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3896): Use maybe version [-Wdeprecated-declarations]
proxy_1  |          return Nan::New(bson->dbrefConstructor)->NewInstance(3, argv);
proxy_1  |                                                                      ^
proxy_1  | ../src/bson.cc: In member function 'v8::Local<v8::Value> BSONDeserializer::DeserializeValue(BsonType, bool)':
proxy_1  | ../src/bson.cc:494:77: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3896): Use maybe version [-Wdeprecated-declarations]
proxy_1  |              return Nan::New(bson->timestampConstructor)->NewInstance(2, argv);
proxy_1  |                                                                              ^
proxy_1  | ../src/bson.cc:513:72: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3896): Use maybe version [-Wdeprecated-declarations]
proxy_1  |              return Nan::New(bson->codeConstructor)->NewInstance(2, argv);
proxy_1  |                                                                         ^
proxy_1  | ../src/bson.cc:522:72: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3896): Use maybe version [-Wdeprecated-declarations]
proxy_1  |              return Nan::New(bson->codeConstructor)->NewInstance(2, argv);
proxy_1  |                                                                         ^
proxy_1  | ../src/bson.cc:528:76: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3896): Use maybe version [-Wdeprecated-declarations]
proxy_1  |              return Nan::New(bson->objectIDConstructor)->NewInstance(1, argv);
proxy_1  |                                                                             ^
proxy_1  | ../src/bson.cc:543:74: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3896): Use maybe version [-Wdeprecated-declarations]
proxy_1  |              return Nan::New(bson->binaryConstructor)->NewInstance(2, argv);
proxy_1  |                                                                           ^
proxy_1  | ../src/bson.cc:566:72: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3896): Use maybe version [-Wdeprecated-declarations]
proxy_1  |              return Nan::New(bson->longConstructor)->NewInstance(2, argv);
proxy_1  |                                                                         ^
proxy_1  | ../src/bson.cc:582:74: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3896): Use maybe version [-Wdeprecated-declarations]
proxy_1  |              return Nan::New(bson->symbolConstructor)->NewInstance(1, argv);
proxy_1  |                                                                           ^
proxy_1  | ../src/bson.cc:586:63: warning: 'v8::Local<v8::Object> v8::Function::NewInstance() const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3901): Use maybe version [-Wdeprecated-declarations]
proxy_1  |          return Nan::New(bson->minKeyConstructor)->NewInstance();
proxy_1  |                                                                ^
proxy_1  | ../src/bson.cc:589:63: warning: 'v8::Local<v8::Object> v8::Function::NewInstance() const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3901): Use maybe version [-Wdeprecated-declarations]
proxy_1  |          return Nan::New(bson->maxKeyConstructor)->NewInstance();
proxy_1  |                                                                ^
proxy_1  | ../src/bson.cc: In static member function 'static void BSON::Initialize(v8::Local<v8::Object>)':
proxy_1  | ../src/bson.cc:652:81: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      target->ForceSet(Nan::New<String>("BSON").ToLocalChecked(), t->GetFunction());
proxy_1  |                                                                                  ^
proxy_1  | ../src/bson.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE BSON::BSONDeserialize(Nan::NAN_METHOD_ARGS_TYPE)':
proxy_1  | ../src/bson.cc:796:51: warning: 'ssize_t node::DecodeBytes(v8::Local<v8::Value>, node::encoding)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/node.h:403): Use DecodeBytes(isolate, ...) [-Wdeprecated-declarations]
proxy_1  |          intptr_t len = DecodeBytes(info[0], BINARY);
proxy_1  |                                                    ^
proxy_1  | ../src/bson.cc:803:47: warning: 'ssize_t node::DecodeWrite(char*, size_t, v8::Local<v8::Value>, node::encoding)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/node.h:416): Use DecodeWrite(isolate, ...) [-Wdeprecated-declarations]
proxy_1  |          DecodeWrite(data, len, info[0], BINARY);
proxy_1  |                                                ^
proxy_1  | In file included from ../src/WebWorkerThreads.cc:17:0:
proxy_1  | ../src/bson.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE BSON::BSONSerialize(Nan::NAN_METHOD_ARGS_TYPE)':
proxy_1  | ../src/bson.cc:897:73: warning: 'v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/node.h:384): Use Encode(isolate, ...) [-Wdeprecated-declarations]
proxy_1  |    Local<Value> bin_value = Encode(serialized_object, object_size, BINARY)->ToString();
proxy_1  |                                                                          ^
proxy_1  | In file included from ../src/WebWorkerThreads.cc:18:0:
proxy_1  | ../src/jslib.cc: In function 'void ReportException(v8::TryCatch*)':
proxy_1  | ../src/jslib.cc:58:35: warning: 'int v8::Message::GetEndColumn() const' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:1637): Use maybe version [-Wdeprecated-declarations]
proxy_1  |    int end = message->GetEndColumn();
proxy_1  |                                    ^
proxy_1  | ../src/jslib.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE console_log(Nan::NAN_METHOD_ARGS_TYPE)':
proxy_1  | ../src/jslib.cc:159:11: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:8371): Use isolate version [-Wdeprecated-declarations]
proxy_1  |   TryCatch trycatch;
proxy_1  |            ^
proxy_1  | ../src/jslib.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE console_error(Nan::NAN_METHOD_ARGS_TYPE)':
proxy_1  | ../src/jslib.cc:175:11: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:8371): Use isolate version [-Wdeprecated-declarations]
proxy_1  |   TryCatch trycatch;
proxy_1  |            ^
proxy_1  | In file included from ../src/WebWorkerThreads.cc:18:0:
proxy_1  | ../src/WebWorkerThreads.cc: In function 'void eventLoop(typeThread*)':
proxy_1  | ../src/jslib.cc:25:126: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      obj->ForceSet(Nan::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), attribute_ro_dd);
proxy_1  |                                                                                                                               ^
proxy_1  | ../src/WebWorkerThreads.cc:263:5: note: in expansion of macro 'JSObjFn'
proxy_1  |      JSObjFn(fs_obj, "readFileSync", readFileSync_);
proxy_1  |      ^
proxy_1  | ../src/WebWorkerThreads.cc:264:94: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      global->ForceSet(Nan::New<String>("native_fs_").ToLocalChecked(), fs_obj, attribute_ro_dd);
proxy_1  |                                                                                               ^
proxy_1  | In file included from ../src/WebWorkerThreads.cc:18:0:
proxy_1  | ../src/jslib.cc:25:126: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      obj->ForceSet(Nan::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), attribute_ro_dd);
proxy_1  |                                                                                                                               ^
proxy_1  | ../src/WebWorkerThreads.cc:267:5: note: in expansion of macro 'JSObjFn'
proxy_1  |      JSObjFn(console_obj, "log", console_log);
proxy_1  |      ^
proxy_1  | ../src/jslib.cc:25:126: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      obj->ForceSet(Nan::New<String>(name).ToLocalChecked(), Nan::New<FunctionTemplate>(fnname)->GetFunction(), attribute_ro_dd);
proxy_1  |                                                                                                                               ^
proxy_1  | ../src/WebWorkerThreads.cc:268:5: note: in expansion of macro 'JSObjFn'
proxy_1  |      JSObjFn(console_obj, "error", console_error);
proxy_1  |      ^
proxy_1  | ../src/WebWorkerThreads.cc:269:96: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      global->ForceSet(Nan::New<String>("console").ToLocalChecked(), console_obj, attribute_ro_dd);
proxy_1  |                                                                                                 ^
proxy_1  | ../src/WebWorkerThreads.cc:271:71: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      global->ForceSet(Nan::New<String>("self").ToLocalChecked(), global);
proxy_1  |                                                                        ^
proxy_1  | ../src/WebWorkerThreads.cc:272:73: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      global->ForceSet(Nan::New<String>("global").ToLocalChecked(), global);
proxy_1  |                                                                          ^
proxy_1  | ../src/WebWorkerThreads.cc:274:112: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      global->ForceSet(Nan::New<String>("puts").ToLocalChecked(), Nan::New<FunctionTemplate>(Puts)->GetFunction());
proxy_1  |                                                                                                                 ^
proxy_1  | ../src/WebWorkerThreads.cc:275:114: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      global->ForceSet(Nan::New<String>("print").ToLocalChecked(), Nan::New<FunctionTemplate>(Print)->GetFunction());
proxy_1  |                                                                                                                   ^
proxy_1  | ../src/WebWorkerThreads.cc:277:126: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      global->ForceSet(Nan::New<String>("postMessage").ToLocalChecked(), Nan::New<FunctionTemplate>(postMessage)->GetFunction());
proxy_1  |                                                                                                                               ^
proxy_1  | ../src/WebWorkerThreads.cc:278:124: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      global->ForceSet(Nan::New<String>("__postError").ToLocalChecked(), Nan::New<FunctionTemplate>(postError)->GetFunction());
proxy_1  |                                                                                                                             ^
proxy_1  | ../src/WebWorkerThreads.cc:281:79: warning: 'bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3164): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
proxy_1  |      global->ForceSet(Nan::New<String>("thread").ToLocalChecked(), threadObject);
proxy_1  |                                                                                ^
proxy_1  | ../src/WebWorkerThreads.cc:285:154: warning: 'v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3518): Use maybe version [-Wdeprecated-declarations]
proxy_1  |      Local<Object> dispatchEvents= Script::Compile(Nan::New<String>(kEvents_js).ToLocalChecked())->Run()->ToObject()->CallAsFunction(threadObject, 0, NULL)->ToObject();
proxy_1  |                                                                                                                                                           ^
proxy_1  | ../src/WebWorkerThreads.cc:301:18: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:8371): Use isolate version [-Wdeprecated-declarations]
proxy_1  |          TryCatch onError;
proxy_1  |                   ^
proxy_1  | ../src/WebWorkerThreads.cc:371:59: warning: 'v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3518): Use maybe version [-Wdeprecated-declarations]
proxy_1  |              dispatchEvents->CallAsFunction(global, 2, info);
proxy_1  |                                                            ^
proxy_1  | ../src/WebWorkerThreads.cc:394:59: warning: 'v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3518): Use maybe version [-Wdeprecated-declarations]
proxy_1  |              dispatchEvents->CallAsFunction(global, 2, info);
proxy_1  |                                                            ^
proxy_1  | ../src/WebWorkerThreads.cc:405:71: warning: 'v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3518): Use maybe version [-Wdeprecated-declarations]
proxy_1  |            resultado= dispatchNextTicks->CallAsFunction(global, 0, NULL);
proxy_1  |                                                                        ^
proxy_1  | ../src/WebWorkerThreads.cc: In function 'void Callback(uv_async_t*, int)':
proxy_1  | ../src/WebWorkerThreads.cc:479:12: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:8371): Use isolate version [-Wdeprecated-declarations]
proxy_1  |    TryCatch onError;
proxy_1  |             ^
proxy_1  | ../src/WebWorkerThreads.cc:495:78: warning: 'v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3518): Use maybe version [-Wdeprecated-declarations]
proxy_1  |          Nan::New(job->cb)->CallAsFunction(Nan::New(thread->JSObject), 2, argv);
proxy_1  |                                                                               ^
proxy_1  | ../src/WebWorkerThreads.cc:540:91: warning: 'v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3518): Use maybe version [-Wdeprecated-declarations]
proxy_1  |        Nan::New(thread->dispatchEvents)->CallAsFunction(Nan::New(thread->JSObject), 2, info);
proxy_1  |                                                                                            ^
proxy_1  | ../src/WebWorkerThreads.cc:564:91: warning: 'v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3518): Use maybe version [-Wdeprecated-declarations]
proxy_1  |        Nan::New(thread->dispatchEvents)->CallAsFunction(Nan::New(thread->JSObject), 2, info);
proxy_1  |                                                                                            ^
proxy_1  | ../src/WebWorkerThreads.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE Create(Nan::NAN_METHOD_ARGS_TYPE)':
proxy_1  | ../src/WebWorkerThreads.cc:874:155: warning: 'v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3518): Use maybe version [-Wdeprecated-declarations]
proxy_1  |      Local<Value> dispatchEvents= Script::Compile(Nan::New<String>(kEvents_js).ToLocalChecked())->Run()->ToObject()->CallAsFunction(local_JSObject, 0, NULL);
proxy_1  |                                                                                                                                                            ^
proxy_1  | ../src/WebWorkerThreads.cc: In function 'void Init(v8::Handle<v8::Object>, v8::Handle<v8::Value>, void*)':
proxy_1  | ../src/WebWorkerThreads.cc:916:173: warning: 'v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:3518): Use maybe version [-Wdeprecated-declarations]
proxy_1  |    target->Set(Nan::New<String>("Worker").ToLocalChecked(), Script::Compile(Nan::New<String>(kWorker_js).ToLocalChecked())->Run()->ToObject()->CallAsFunction(target, 0, NULL)->ToObject());
proxy_1  |                                                                                                                                                                              ^
proxy_1  | ../src/WebWorkerThreads.cc:920:68: warning: 'static v8::Local<v8::ObjectTemplate> v8::ObjectTemplate::New()' is deprecated (declared at /root/.node-gyp/8.15.1/include/node/v8.h:5756): Use isolate version [-Wdeprecated-declarations]
proxy_1  |    Local<ObjectTemplate> local_threadTemplate = ObjectTemplate::New();
proxy_1  |                                                                     ^
proxy_1  | WebWorkerThreads.target.mk:99: recipe for target 'Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o' failed
proxy_1  | make: Leaving directory '/coco/node_modules/webworker-threads/build'
proxy_1  | make: *** [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
proxy_1  | gyp ERR! build error
proxy_1  | gyp ERR! stack Error: `make` failed with exit code: 2
proxy_1  | gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
proxy_1  | gyp ERR! stack     at emitTwo (events.js:126:13)
proxy_1  | gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
proxy_1  | gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
proxy_1  | gyp ERR! System Linux 4.19.76-linuxkit
proxy_1  | gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
proxy_1  | gyp ERR! cwd /coco/node_modules/webworker-threads
proxy_1  | gyp ERR! node -v v8.15.1
proxy_1  | gyp ERR! node-gyp -v v3.8.0
proxy_1  | gyp ERR! not ok
proxy_1  | npm WARN lifecycle codecombat@1.0.0~postinstall: cannot run in wd codecombat@1.0.0 bower install && npm run build-aether && node ./runWebpack.js (wd=/coco)
proxy_1  | npm WARN terser-webpack-plugin@1.2.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
proxy_1  | npm WARN vue-loader@15.7.0 requires a peer of webpack@^4.1.0 || ^5.0.0-0 but none is installed. You must install peer dependencies yourself.
proxy_1  | npm WARN vuex-router-sync@5.0.0 requires a peer of vuex@^3.0.0 but none is installed. You must install peer dependencies yourself.
proxy_1  | npm WARN webpack-dev-middleware@3.6.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
proxy_1  | npm WARN The package webpack is included as both a dev and production dependency.
proxy_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
proxy_1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
proxy_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.6.4 (node_modules/webworker-threads):
proxy_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.6.4 install: `node-gyp rebuild`
proxy_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
proxy_1  |
proxy_1  | audited 2496 packages in 15.424s
proxy_1  | found 1757 vulnerabilities (1018 low, 37 moderate, 687 high, 15 critical)
proxy_1  |   run `npm audit fix` to fix them, or `npm audit` for details
proxy_1  |
proxy_1  | > codecombat@1.0.0 proxy /coco
proxy_1  | > COCO_PROXY='true' nodemon
proxy_1  |
proxy_1  | 3 Sep 11:34:07 - [nodemon] v1.6.1
proxy_1  | 3 Sep 11:34:07 - [nodemon] reading config /coco/nodemon.json
proxy_1  | 3 Sep 11:34:07 - [nodemon] to restart at any time, enter `rs`
proxy_1  | 3 Sep 11:34:07 - [nodemon] ignoring: .git /coco/node_modules/**/* bower_components .sass-cache
proxy_1  | 3 Sep 11:34:07 - [nodemon] watching: server_config.js server_setup.coffee /coco/app/schemas/**/* ./server app/assets/main.html
proxy_1  | 3 Sep 11:34:07 - [nodemon] watching extensions: js,coffee
proxy_1  | 3 Sep 11:34:07 - [nodemon] starting `node index.js`
proxy_1  | 3 Sep 11:34:07 - [nodemon] child pid: 78
proxy_1  | 3 Sep 11:34:07 - [nodemon] watching 171 files
proxy_1  | info: Using dev proxy server
proxy_1  | fs.js:948
proxy_1  |   binding.stat(pathModule._makeLong(path));
proxy_1  |           ^
proxy_1  |
proxy_1  | Error: ENOENT: no such file or directory, stat '/coco/public/images/favicon.ico'
proxy_1  |     at Object.fs.statSync (fs.js:948:11)
proxy_1  |     at resolveSync (/coco/node_modules/serve-favicon/index.js:187:17)
proxy_1  |     at favicon (/coco/node_modules/serve-favicon/index.js:61:12)
proxy_1  |     at setupExpressMiddleware (/coco/server_setup.coffee:91:11)
proxy_1  |     at Object.exports.setupMiddleware (/coco/server_setup.coffee:227:3)
proxy_1  |     at module.exports.createAndConfigureApp (/coco/server.coffee:27:15)
proxy_1  |     at Object.module.exports.startServer (/coco/server.coffee:15:9)
proxy_1  |     at Object.<anonymous> (/coco/index.js:12:8)
proxy_1  |     at Module._compile (module.js:653:30)
proxy_1  |     at Object.Module._extensions..js (module.js:664:10)
proxy_1  |     at Module.load (module.js:566:32)
proxy_1  |     at tryModuleLoad (module.js:506:12)
proxy_1  |     at Function.Module._load (module.js:498:3)
proxy_1  |     at Function.Module.runMain (module.js:694:10)
proxy_1  |     at startup (bootstrap_node.js:204:16)
proxy_1  |     at bootstrap_node.js:625:3
proxy_1  |
proxy_1  | 3 Sep 11:34:08 - [nodemon] app crashed - waiting for file changes before starting...
======================================================================
help me to solve this. thank you.

**Comment by ZJUSTKIDDING** [comment]
just create a "public" directory in your codecombat dir

**Comment by ZJUSTKIDDING** [comment]
Run `npm install bower` and rerun the container.

**Comment by Sketti385** [comment]
> Run `npm install bower` and rerun the container.

Even that fails...
