### ISSUE TITLE
Calling bash() on a dead enemy freezes the hero (unlike attack())

### ISSUE THREAD

**Issue by pbodnar** [codecombat/codecombat#6033]
Hi,

this problem I'd like to report has been already discussed in here: https://discourse.codecombat.com/t/bypass-but-its-dead-hero-freezing-while-using-bash-in-javascript/16751.

It's basically about this, to quote myself from the forum:

> This is an example code **where `bash()` on a *dead* enemy does cause the freeze, while `attack()` doesn’t** :
> 
> ```python
> ...
> enemy = self.findNearestEnemy()
> ...
> self.say("Attacking nearest enemy: " + enemy.type)
> if self.isReady("bash"):
>     self.bash(enemy)
> else:
>     self.attack(enemy)
> ```
>

The following line is crucial in the example for successful reproduction of the issue. It is just for debugging (and there are no alternatives according to [Access console.log in game?](https://discourse.codecombat.com/t/access-console-log-in-game/2465/4) so far), yet it is considered as just another hero's action, so enemy's state may change between `findNearestEnemy()` and the attack:

> ```python
> self.say("Attacking nearest enemy: " + enemy.type)
> ```

So what I suggest is to make the behavior of attacks *consistent*, so that it doesn't confuse (new) players. So either to fail-fast, or to continue *after both types of attacks*. If doing this would be too complicated, what about to give at least an appropriate warning for example to the in-game documentation of the `bash()` method?

**Comment by nwinter** [comment]
Thanks for the bug report. It's tricky to get this one working correctly, but I'll put it on the list to see if we can't make it more robust.

**Comment by Bryukh** [comment]
Fixed
