### ISSUE TITLE
Using isPathClear on level Almost Perfect Minefield doesn't work to detect mines

### ISSUE THREAD

**Issue by Anthony-Gaudino** [codecombat/codecombat#6111]
On level `Almost Perfect Minefield` trying to use the `hero.isPathClear` method to detect mines doesn't work. It always says the path is clear even though it's not.

The item that gives the `hero.isPathClear` method is the **Twilight Glasses**.
In the item  description it says:

> Returns whether there are any obstacles (walls, cliffs, etc.) or hazards (traps, pits, etc.) in the straight line between start and end positions.

Since it detects **traps** this seems to be a bug.

Example code:
```python
hero.say(hero.isPathClear({'x': 10, 'y': 10}, {'x': 72, 'y': 10}))
```

**Comment by Bryukh** [comment]
There was something weird with traps, default settings didn't work for them
