### ISSUE TITLE
Negative numbers not accepted

### ISSUE THREAD

**Issue by xR3l4Xx** [codecombat/codecombat#6177]
On the level **Ingredient Identification** (Kithgard Dungeon 17/43) the solution is **INCOMPLETE** when I assign a **negative number** (both integer and float) to a variable.
The problem occurs in **python** and **javascript** too.  Coffeescript did not work at all (only the first variable is set) but that's another issue. I could not test c++ as a free member.

**Comment by Chaboi45** [comment]
The goal of the level is to label and "fill" the bottles, so it doesn't make sense if the number was a negative value. (Negative liters of water in a bottle doesn't really make sense). I'll change the player comments so it's less misleading.

**Comment by Chaboi45** [comment]
Actually, nevermind. There's a lot of i18n translations done in the hero placeholder comments, so I just pushed a fix to the level so it supports negative values!

**Comment by Chaboi45** [comment]
Should be fixed now 👍 Thank you for the report!
