### ISSUE TITLE
Hebrew translation contrib.

### ISSUE THREAD

**Issue by schapira** [codecombat/codecombat#6197]
Hi I would like to contribute string translation and fixing to the Hebrew language (many non Hebrew word in hebrew letters etc. ) before starting, is here someone that is also working on it? it will be nice to work together.

**Comment by mloskot** [comment]
I think there is no need to ask, but you just submit PRs and they are peer-reviewed what essentially means "to work together"

**Comment by nwinter** [comment]
Yup, feel free to submit translations and raise issues for incorrectly localized strings. Would love some help getting the Hebrew experience more polished!
