### ISSUE TITLE
Running clone behind reverse proxy error 400 using google sign in

### ISSUE THREAD

**Issue by xbromy** [codecombat/codecombat#6268]
Hello,
I started a clone on an https://codecombat.companyxyz.com behind a reverse proxy for ssl offload.
When I try to login by google I get this error in popup:
Fehler 400: redirect_uri_mismatch
The JavaScript origin in the request, https://codecombat.companyxyz.com, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/800329290710-j9sivplv2gpcdgkrsis9rff3o417mlfa.apps.googleusercontent.com?project=800329290710 to update the authorized JavaScript origins.

Do I need to change some value for running behind a reverse proxy?

**Comment by nwinter** [comment]
I am guessing that Google OAuth won't work behind the reverse proxy. What is your use case for this SSL offloading approach–something we can help with?
