### ISSUE TITLE
I can't buy the equipment I need for Pender’s Trial　(solved)

### ISSUE THREAD

**Issue by kozv** [codecombat/codecombat#6335]
I bought Mahogany Glasses, Boots Of Jumping, and Twilight Glasses by following the arrows, but I can't challenge the level.
Which equipment do I need?
Thank you!

![Screenshot (142)](https://user-images.githubusercontent.com/86694578/123883685-77938880-d984-11eb-8173-2424dac8518e.png)
![Screenshot (143)](https://user-images.githubusercontent.com/86694578/123884030-3354b800-d985-11eb-8fde-74993637fd40.png)

OS: windows10
Browser:chrome (Even in Edge It became the same state)
Language: python
Level: Cloudrip Mountain - Pender's Trial

Some time ago, something similar happened. If my memory is correct. sorry. I don't remember well.

**Comment by Chaboi45** [comment]
You need to equip Boss Star II or above.

**Comment by kozv** [comment]
Yesterday, Boss Star was on the list of items that couldn't be equipped. But when I tried today, it was already equipped.
Thank you!!!!
