### ISSUE TITLE
Blazing Battle not loading

### ISSUE THREAD

**Issue by joshkordek3** [codecombat/codecombat#6357]
Screen Recording:
https://user-images.githubusercontent.com/79750252/126849842-bd01ae97-d280-475c-bd49-16c4fbf50c77.mp4

**Comment by nwinter** [comment]
This should be fixed, but let me know if it's still happening, along with [any JS errors](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers) you see.
