### ISSUE TITLE
Stored battle message

### ISSUE THREAD

**Issue by carl689** [codecombat/codecombat#643]
I keep finding myself wondering which "strategy" my scripts ran against an opponent while viewing the results of the matches.

Do you think it would be useful if we could see a SHORT custom message in the MyMatches table?  Perhaps it could be the last home this.say or a new method? this.inscribe... etc

This would also be nicer on the server as it would lesson the amount of battles I need to open just to see what strategy is failing.

**Comment by nwinter** [comment]
After pondering this for a while, I think that we probably want to save space in those match histories, which get kind of long, instead of storing it for each match result.
