### ISSUE TITLE
DEV: Godmode not working

### ISSUE THREAD

**Issue by ZJUSTKIDDING** [codecombat/codecombat#6508]
I suspect this is because if `npm run proxy` is used, most db calls are forwarded to your servers. In earlier versions there was a bin folder with mongo. But now there isn't. Any ideas how to fix?

**Comment by nwinter** [comment]
Right, we simplified the dev setup experience to just use our backends a few years ago, so now you can't give yourself godmode when developing locally (since that would be real godmode on the production server as well).
