### ISSUE TITLE
Dungeon Raider - Unbeatable, 404 Glitch?

### ISSUE THREAD

**Issue by davidallanturner** [codecombat/codecombat#6524]
I have explored every inch of this dungeon, and cannot seem to "beat" it. I do find something at the bottom right screen, but when my character goes over it, my character becomes significantly larger, and then the game continues on.

When I encounter the areas where my character grows, my browser shows the following error: 
GET https://codecombat.com/db/thang.type/foo 404

This appears to be my environment variables:
Generated random seed 1182786421 of type playerSession from sessionIDs 6202d64381d5cf002380f788 submissionCount 0

Is this correct?

**Comment by Chaboi45** [comment]
@davidallanturner thank you for reporting. Could you share your in-game username so I can investigate this issue? Thank you!

**Comment by davidallanturner** [comment]
DavidAllanTurner

**Comment by Chaboi45** [comment]
It should be fixed!
