### ISSUE TITLE
Unable to even get running

### ISSUE THREAD

**Issue by Sketti385** [codecombat/codecombat#6553]
Container codecombat-proxy-1  Created
Attaching to codecombat-proxy-1
codecombat-proxy-1  | npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN ajv-formats@2.1.1 requires a peer of ajv@^8.0.0 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN sass-loader@12.6.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN sass-loader@12.6.0 requires a peer of node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN sass-loader@12.6.0 requires a peer of sass-embedded@* but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN vue-pug-plugin@1.0.16 requires a peer of pug@^3.0.1 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN ws@7.4.6 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN ws@7.4.6 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
codecombat-proxy-1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
codecombat-proxy-1  |
codecombat-proxy-1  | + bower@1.8.14
codecombat-proxy-1  | updated 1 package and audited 1320 packages in 7.999s
codecombat-proxy-1  | found 58 vulnerabilities (5 low, 30 moderate, 22 high, 1 critical)
codecombat-proxy-1  |   run `npm audit fix` to fix them, or `npm audit` for details
codecombat-proxy-1  | npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN ajv-formats@2.1.1 requires a peer of ajv@^8.0.0 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN sass-loader@12.6.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN sass-loader@12.6.0 requires a peer of node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN sass-loader@12.6.0 requires a peer of sass-embedded@* but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN vue-pug-plugin@1.0.16 requires a peer of pug@^3.0.1 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN ws@7.4.6 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN ws@7.4.6 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
codecombat-proxy-1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
codecombat-proxy-1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
codecombat-proxy-1  |
codecombat-proxy-1  | audited 1320 packages in 6.351s
codecombat-proxy-1  | found 58 vulnerabilities (5 low, 30 moderate, 22 high, 1 critical)
codecombat-proxy-1  |   run `npm audit fix` to fix them, or `npm audit` for details
codecombat-proxy-1  |
codecombat-proxy-1  | > codecombat@1.0.0 proxy /coco
codecombat-proxy-1  | > COCO_PROXY='true' nodemon
codecombat-proxy-1  |
codecombat-proxy-1  | /coco/node_modules/update-notifier/index.js:58
codecombat-proxy-1  |                   } catch {
codecombat-proxy-1  |                           ^
codecombat-proxy-1  |
codecombat-proxy-1  | SyntaxError: Unexpected token {
codecombat-proxy-1  |     at createScript (vm.js:80:10)
codecombat-proxy-1  |     at Object.runInThisContext (vm.js:139:10)
codecombat-proxy-1  |     at Module._compile (module.js:617:28)
codecombat-proxy-1  |     at Object.Module._extensions..js (module.js:664:10)
codecombat-proxy-1  |     at Module.load (module.js:566:32)
codecombat-proxy-1  |     at tryModuleLoad (module.js:506:12)
codecombat-proxy-1  |     at Function.Module._load (module.js:498:3)
codecombat-proxy-1  |     at Module.require (module.js:597:17)
codecombat-proxy-1  |     at require (internal/module.js:11:18)
codecombat-proxy-1  |     at Object.<anonymous> (/coco/node_modules/nodemon/bin/nodemon.js:15:3)
codecombat-proxy-1  | npm ERR! code ELIFECYCLE
codecombat-proxy-1  | npm ERR! errno 1
codecombat-proxy-1  | npm ERR! codecombat@1.0.0 proxy: `COCO_PROXY='true' nodemon`
codecombat-proxy-1  | npm ERR! Exit status 1
codecombat-proxy-1  | npm ERR!
codecombat-proxy-1  | npm ERR! Failed at the codecombat@1.0.0 proxy script.
codecombat-proxy-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
codecombat-proxy-1  |
codecombat-proxy-1  | npm ERR! A complete log of this run can be found in:
codecombat-proxy-1  | npm ERR!     /root/.npm/_logs/2022-03-16T17_37_48_033Z-debug.log
codecombat-proxy-1 exited with code 1

**Comment by Sketti385** [comment]
I used windows 10 and installed everything, but every attempt on "npm installl" fails.

**Comment by nwinter** [comment]
What version of node and npm did you have? We just updated to node 14, but might not have done that everywhere?

**Comment by Sketti385** [comment]
Node as in 14, or 14.18.3? Also I can't tell what version of npm i get, i don't know how to access it.

**Comment by foxracle** [comment]
> I figured out how to get the proxy running, but I can't access the site due to "unhandled promise rejections"

I had same problem with you, I followed the docker guide on Mac.

Could you share me how to get the proxy running?
