### ISSUE TITLE
**Desert Duel** "Unhandled error: Error: You can't use Hero Placeholder's summon method here."

### ISSUE THREAD

**Issue by n1mr0dIX** [codecombat/codecombat#6683]
When calling a function that is defined ousite of the _while True:_ loop, which uses the _hero.summon_ method from **Desert Duel**, an error is thrown.
_Unhandled error: Error: You can't use Hero Placeholder's summon method here._
![cc_bug2](https://user-images.githubusercontent.com/99561176/176539304-0427e2de-b5e9-42aa-b528-921cd210b198.png)
![cc_bug1](https://user-images.githubusercontent.com/99561176/176539310-6cbe0cca-6a70-44f2-92db-3ef360122a02.png)

**Comment by Bryukh** [comment]
Your code has an error. Check arguments more carefully.
However, the thrown error is wrong here too. The real error that you can see in the console is 
`ArgumentError: Wrong player type 1. Check the docs to find available player types. 0`
