### ISSUE TITLE
Game Development 1 Java auto-complete

### ISSUE THREAD

**Issue by Roshi-Codes** [codecombat/codecombat#6721]
When typing out code in the game development levels the spawnPlayer auto-complete uses single quotes and the highlighted text includes the single quotes. If the student just leaves it to default to captain with single quotes the player will not spawn and the level will not run.

This is different behaviour to when spawning items such as fences where the object name will be highlighted inside of double quotes.

Unsure if this is a deliberate learning point or a bug. 

`game.spawnPlayerXY('captain', 36, 30);
`

**Comment by Chaboi45** [comment]
Hi there! Sorry about this issue,  and the slow response. In Java, single quotes are restricted to `char`, and double quotes for `String`. The autocomplete snippet incorrectly used single quotes. This is fixed now. 👍
