### ISSUE TITLE
Google login not working

### ISSUE THREAD

**Issue by ZJUSTKIDDING** [codecombat/codecombat#6784]
Google login does not do anything, no traceback or error in console, nothing.
Because of this I am unable to sign the CLA, so somebody else needs to fix this.

**Comment by mrfinch** [comment]
Hi @ZJUSTKIDDING, I'm not able to reproduce it. I was able to log in using Gmail. Can you give more details about the browser or steps to reproduce it?

You can't log in to CodeCombat using Google at all? CLA is hosted on CodeCombat too.

**Comment by ZJUSTKIDDING** [comment]
Okay, I managed to login manually.
Browser details:
Firefox 104.0.2 64-bit (as Snap) on Ubuntu 22.04
Add-ons: Wappalyzer, Windscribe
Tried this on a local dev server too, same thing.
I suspect that Windscribe is blocking some crucial code, happened earlier, I will try to disable it.

**Comment by ZJUSTKIDDING** [comment]
Nevermind, that was Windscribe. Sorry for the disturbance.
