### ISSUE TITLE
[Wiki] Old link to loading tips in wiki.

### ISSUE THREAD

**Issue by xtreemtm** [codecombat/codecombat#6785]
Wiki page for Archmages, section Starting off, loading tips link points to an old issue, which points to an old level loading template file.

New link: https://github.com/codecombat/codecombat/blob/ab6cef931ab77aa05fcfa6769d63af0a4e93afbe/app/templates/play/level/level-loading-view.coco.pug

**Comment by nwinter** [comment]
Fixed, thanks!
