### ISSUE TITLE
Getting started with Docker FAILED.

### ISSUE THREAD

**Issue by SuperJe** [codecombat/codecombat#6907]
I have downloaded the docker desktop, which includes docker-compose. After cloning the repository, the execution of docker-compose fails, and the same error occurs on both windows and mac:

```
W: GPG error: http://deb.debian.org jessie Release: The following signatures were invalid: KEYEXPIRED 1668891673
```

So I added the --force-yes option to the apt-install command in Dockfile, and this time I got a new error:

```
 > [4/6] RUN rbenv install 2.6.1 && rbenv global 2.6.1:
#0 0.259 To follow progress, use 'tail -f /tmp/ruby-build.20230211125129.19.log' or pass --verbose
#0 0.272 Downloading ruby-2.6.1.tar.bz2...
#0 0.272 -> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.1.tar.bz2
#0 165.1 error: failed to download ruby-2.6.1.tar.bz2
#0 165.1
#0 165.1 BUILD FAILED (Debian GNU/Linux 8 using ruby-build 20230208.1-2-g4d2e1cc)
#0 165.1
```

Apparently https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.1.tar.bz2 is an incorrect URL.

Please help to solve this problem, thanks.

**Comment by SuperJe** [comment]
Please take a look if you have time, thank you very much! @Bryukh

**Comment by SuperJe** [comment]
Please take a look if you have time, thank you very much! @Bryukh

**Comment by prasy-loyola** [comment]
@SuperJe 

Updating the base docker image to `node18-bookworm` made it build in my machine. 

You can find the change here.
https://github.com/prasy-loyola/codecombat/blob/update-base-docker-image/development/docker/Dockerfile

I am new to CodeCombat , so I am not sure if all the functionalities are working fine, but I was able to build and open it locally in  the browser.

**Comment by SuperJe** [comment]
> @SuperJe
> 
> Updating the base docker image to `node:18-bookworm` made it build in my machine.
> 
> You can find the change here. https://github.com/prasy-loyola/codecombat/blob/update-base-docker-image/development/docker/Dockerfile
> 
> I am new to CodeCombat , so I am not sure if all the functionalities are working fine, but I was able to build and open it locally in the browser.

thank you very much, tried what you said and it works successfully in my local browser.
