### ISSUE TITLE
An error appears when content is translated into Japanese and sent.

### ISSUE THREAD

**Issue by tsubame-kamome** [codecombat/codecombat#6964]
I have translated it into Japanese at the link below.
[Student Quick Start Guide](https://direct.codecombat.com/i18n/resource_hub_resource/student-quick-start-guide)
However, an error message appears when I click submit.
Could you please tell me how to make it work without error?

There are many other pages besides the Student Quick Starg Guide that give errors.

Below are the error messages that appeared.
`403 error {"errorName":"Forbidden","code":403,"message":"You do not have permissions necessary.","name":"Error"}`

**Comment by nwinter** [comment]
I see the problem and will post a fix this week–thanks for raising that one!

**Comment by tsubame-kamome** [comment]
@nwinter You're welcome!

**Comment by nwinter** [comment]
Fixed on the server side, will go live with next deploy (possibly tomorrow, else next week).

**Comment by tsubame-kamome** [comment]
Thank you very much!
