### ISSUE TITLE
Sweep: fix comment whitespace issues in translate-utils.coffee

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#7024]
In `app/lib/translate-utils.coffee`, some of the comments aren't indented correctly, instead just starting at the beginning of the line. We should fix the comment whitespace on all the improperly indented comments in this file.

**Comment by wwzeng1** [comment]
Hi @nwinter! Sweep timed out due to your repository size. We're increasing our timeouts, expect this to be fixed shortly!

**Comment by wwzeng1** [comment]
sweep: retry

**Comment by wwzeng1** [comment]
sweep: retry
