### ISSUE TITLE
Unable to send translated text.

### ISSUE THREAD

**Issue by kamome-run** [codecombat/codecombat#7047]
I want to send the translated text from the page at the URL below. I cannot send it and an error appears.

[Student Quick Start Guide](https://direct.codecombat.com/i18n/resource_hub_resource/student-quick-start-guide)

![image](https://github.com/codecombat/codecombat/assets/40795169/da19d8bd-c6ca-426e-a2e1-b7f5a0c2a22a)

Please fix the bug.

**Comment by smallst** [comment]
did you login your account to save the translation?

**Comment by nwinter** [comment]
This should be fixed now.
