### ISSUE TITLE
Hi everyone ！ i can't copy a new level from a  existing level

### ISSUE THREAD

**Issue by China-Frank** [codecombat/codecombat#7049]
I tried using a derived method to copy a new level, but it was constantly being read and could not generate a new level

i need your help ！

**Comment by nwinter** [comment]
Did you use the `Fork` action in the top right of the [level editor](https://codecombat.com/editor/level/dungeons-of-kithgard)? If so, what error did you get?

<img width="259" alt="Screenshot 2023-07-20 at 07 01 48" src="https://github.com/codecombat/codecombat/assets/99704/c60ee622-f688-480b-aeeb-88bc62a9cacc">
<img width="669" alt="Screenshot 2023-07-20 at 07 02 00" src="https://github.com/codecombat/codecombat/assets/99704/ff3b8c14-94bb-4b53-b097-621257a01ce9">
