### ISSUE TITLE
Seek-and-Hide Collision failure when hero is Okar

### ISSUE THREAD

**Issue by AlejandroGarcia95** [codecombat/codecombat#7064]
Hi all, we have seen this today while playing the level with one of my students.

In Computer Science 2 Level 30 (Seek-and-Hide) there is an undesired failure when the hero is Okar (Goliath). This happens because the hero is quite big, resulting in a collision with one of the walls. Please check the picture attached.

![Screenshot from 2023-07-29 11-20-04](https://github.com/codecombat/codecombat/assets/13912744/2a02e23b-80dc-455a-9fe0-03485036eb70)

The code is the expected one for the level (equal to the solution), but due to this problem the level outcome is a failure with this hero. Workaround is to use a different (smaller) hero.

**Comment by nwinter** [comment]
This is fixed now; thanks for the bug report!
