### ISSUE TITLE
Google+ login sometimes just closes without doing anything

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#741]
From [SpedsT on the forum](http://discourse.codecombat.com/t/login-in-problem/593):

```
Sometimes, when you access the front page of codecombat.com the Google+ "log in" button won't work (It shows the "Connecting" pop-up window and then closes without actually logging in )
I'm using Google Chrome 33.0.1750.154 m. I haven't tried any other browsers.
```

No JavaScript errors were detected.

**Comment by simon2768** [comment]
Hi there, we are having this exact same problem, any ideas what we are doing wrong? ta

**Comment by AndrewJakubowicz** [comment]
Hi @simon2768, thanks for the message.

Would you be able to share more information regarding when it happens?

What browser, and operating system are you using?

Steps to reproduce with screenshots if possible.

Finally could you also copy paste any error messages or logs in the developer console. Let me know if you have any other questions!

Thanks!
