### ISSUE TITLE
Add sound sprites from SoundJS

### ISSUE THREAD

**Issue by sderickson** [codecombat/codecombat#750]
http://blog.createjs.com/audio-sprite-support-in-soundjs/

The most useful version of this would be to allow caching and downloading of all sounds needed for a given level or for a given sprite. Probably the simplest way would be to set up the server to dynamically stitch together a given set of files and serve them, with CloudFlare handling the caching. Sounds from Levels and ThangTypes would be the best groupings for sounds. According to the blog post, this would help by decreasing network calls and overall size. Although, this may not be worth it, given the drawbacks listed in the blog post as well.

**Comment by nwinter** [comment]
With HTTP/2, it will no longer pay to introduce complexity to reduce the number of network requests like this, so New Internet Technology will do this for us.
