### ISSUE TITLE
Seeking Advice: Students Struggling in CodeCombat CS4 due to equipment

### ISSUE THREAD

**Issue by edmangog** [codecombat/codecombat#7869]
Hello everyone, I’m a teacher who recently assigned CodeCombat CS4 to my students, who are experienced in Python programming. While I believe that the difficulty level of CS4 is appropriate for their learning, many of them struggle to defeat enemies, even though they have written the correct code.

One significant challenge is that, as new users, they cannot upgrade their equipment, which adds to the difficulty of defeating tougher enemies.I’m looking for strategies, tips, or resources that could help my students overcome this challenge and succeed in CS4.

Any advice from those who have faced similar situations would be greatly appreciated!

**Comment by mrfinch** [comment]
Hi @edmangog , you should out to support@codecombat.com for these issues.

As an easy hack, you could disable equipment/gems for your classroom. Regarding student specific issues with equipment, the support team can help you.

**Comment by edmangog** [comment]
Thanks a lot. It works!
