### ISSUE TITLE
No email validation

### ISSUE THREAD

**Issue by schmatz** [codecombat/codecombat#914]
I can enter a string, such as "asdfasdfasdfasdf" for email and register an account. We need some email validation.

**Comment by tahmidshahriar** [comment]
How strict do you want the email validity check? A simple aa@bb.cc requirement, or something more strict? Currently aa@bb passes but the '@' is required since type is email.

Additionally, what would you want to happen on the server-side if the email is not valid?

**Comment by nwinter** [comment]
Let's use the built-in HTML5 validation stuff on the client, and the simple regex on the server, and throw some sort of error if they somehow submit an invalid email to the server anyway. Hopefully we can test and make sure that it makes sense on the front-end if they somehow do that.

**Comment by tahmidshahriar** [comment]
If signup button is pressed with an email that isn't aa@bb.cc (checks on server side, shows the error message if it fails the regex and doesn't continue with signup): 

![image](https://cloud.githubusercontent.com/assets/8417980/8420747/fcb84d28-1e7a-11e5-8fef-d4694d4a3dac.png)

Is this similar to what you wanted?

**Comment by nwinter** [comment]
Ya

**Comment by nwinter** [comment]
Well, this covers the client side of it, but not the server side yet.

**Comment by tahmidshahriar** [comment]
Ah, I apologize, I did not fully understand the server side part then. For server side, it should pass the client side, successfully go through the sign up process and get logged in. Meanwhile, a second check will be done and if it fails, display an error to user (or do something else)?

**Comment by Imperadeiro98** [comment]
I think there was already a validation of the email, that still appears if you enter something random without the '@' symbol. Shouldn't it be removed now, or is it to be kept?

**Comment by nwinter** [comment]
That's built into (some) browsers and isn't as restrictive as we wanted–lots of "soandso@gmail" (without the .com) emails being signed up, for example. So we added another layer that would be a little more aggressive.

We should use the same regex on the server, too.

**Comment by Imperadeiro98** [comment]
Ok, thought it was CodeCombat specific.

**Comment by tahmidshahriar** [comment]
I can remove that though (the browser  @ symbol one) since just the type needs to be changed for that to go away

**Comment by nwinter** [comment]
Nah, let's keep that one in as the first line of defense–that one is more standardized and visible.

**Comment by duybkict** [comment]
Hi guys, is this issue fully resolved yet? I want to work on email validation on server side, where could I get started?
I also notice this line `email: c.shortString({title: 'Email', format: 'email'})` from `\app\schemas\models\user.coffee`, isn't it enough already?

**Comment by sderickson** [comment]
We do not have our JSON-schema validator, tv4, set up to enforce an email format. We do, however, reject signups now that don't fit a simple regex.

https://github.com/codecombat/codecombat/blob/master/app/views/core/CreateAccountModal.coffee#L86-L87

So this issue is resolved.
