### ISSUE TITLE
API protection breaks use of non-standard methods

### ISSUE THREAD

**Issue by gosnat** [codecombat/codecombat#957]
Example:  codecombat.com/play/level/mod-squad-supplies-party

Basically, I added the pickMushroom(), buySmallPotion(), buyMediumPotion(), buyLargePotion() methods, but if the user tries to call them, they get the error:

TypeError: Cannot read property 'pickMushroom' of undefined

![image](https://cloud.githubusercontent.com/assets/6819822/2870758/9745c9a4-d2de-11e3-882b-d6e85873d0b1.png)

It works with http://codecombat.com/play/level/mod-squad-supplies-party?skip_protect_api=true

**Comment by nwinter** [comment]
We've been just putting these methods in the programmableProperties list and assigning them from the Referee or a custom Component, and it works fine.
